### ISSUE TITLE
Not working on Win10 / Docker with current version? (1.0.44)

### ISSUE THREAD

**Issue by TLoxxx** [zoffline/zwift-offline#10]
followed instructions exactly as described (for Windows)
-zoffline is running in docker. --> how to test if it is working properly?
"docker ps" Shows zwift-offline

-certificates are installed
When running zwift installer I receive error message --> cannot connect to the Internet...

When commenting out hosts-line Version 1.0.44 is downloaded. After starting this Version with zoffline running: error message --> cannot connect to zwift Server

is there some change on zwift Server, or am I missing an Installation step?
Curious, because during installation of zoffline I didn't use any file downloaded here.

Besides : where is the docker container stored on my PC?

**Comment by oldnapalm** [comment]
What does “docker ps” show under status? I had a similar problem (issue #3) where apache would not start (status was “exited” instead of “running”).

After editing the hosts file try to open https://secure.zwift.com in your browser.

**Comment by TLoxxx** [comment]
```
$ docker ps
CONTAINER ID        IMAGE               COMMAND              CREATED             STATUS              PORTS                                      NAMES
fe3242c8379d        zoffline/zoffline   "httpd-foreground"   9 hours ago         Up 8 hours          0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   zwift-offline
sh: __git_ps1: command not found
```

https://secure.zwift.com delivers "Can't reach site"

**Comment by oldnapalm** [comment]
Which network driver are you using in docker container? I’m not using docker but I believe you must use host networking, and documentation says default driver is bridge, so I guess you have to change that.

https://docs.docker.com/network/

If you use bridge networking you have to specify the container IP in hosts file, instead of 127.0.0.1

**Comment by TLoxxx** [comment]
I deleted the container and created a new one using `docker create --name zwift-offline --network host -e TZ=Europe/Berlin zoffline/zoffline`

because it told me, that port-forwarding will be discarded anyways when using host -mode.

docker ps Shows `aad3e44d4abc        zoffline/zoffline   "httpd-foreground"   3 minutes ago       Up 3 minutes                            zwift-offline`

still when Opening https://secure.zwift.com/ I get "can't reach" (what should be there?)
Other Question: I do own a QNAP NAS. Would it be easier to have z-offline running there?

**Comment by oldnapalm** [comment]
Opening secure.zwift.com should access the httpd server on docker.

I also had problem with docker so I installed Ubuntu server in VirtualBox.

Sorry, no other idea about what your problem is, lets wait for a reply from the project developer.

**Comment by TLoxxx** [comment]
Ok, thanks anyways ;-)

**Comment by TLoxxx** [comment]
@ oldnapalm Could you give a short wrap-up which ubuntu VB-Image you are using? I tried ubuntu 10.04 and can't get Internet Connection at all.

**Comment by oldnapalm** [comment]
I installed Ubuntu 18.04.1 ISO under latest VirtualBox. After installing the requirements in zoffline ReadMe I needed to install some extra apache modules (can’t remember them all, one is WSGI) but you can figure out looking at apache error logs.

**Comment by oldnapalm** [comment]
Forget about the host networking thing, looks like it doesn’t work under Windows, it should work with the -p arguments in instructions. Maybe you have a problem with (or missing) virtual network interface. Try to take a look in Hyper V settings.

**Comment by TLoxxx** [comment]
I believe i figured why it is not working for me with docker. My CPU does not support SLAT which unfortunately is a prerequisite for Hyper-V. Although I can start Hyper-V Administration, I cannot start any virtual machine.

**Comment by TLoxxx** [comment]
I tried around a bit more and found that docker Toolbox should do the Job.

Installed z-offline, everything running like a charm, (starting docker terminal as admin!)

Now I figured that the issue is related to the ip-adress Definition.
`docker is configured to use the default machine with IP 192.168.99.100
For help getting started, check out the docs at https://docs.docker.com

TLo-PC@TLo-PC MINGW64 /c/Program Files/Docker Toolbox
$ docker start zwift-offline
zwift-offline

TLo-PC@TLo-PC MINGW64 /c/Program Files/Docker Toolbox
$ docker ps
CONTAINER ID        IMAGE               COMMAND              CREATED             STATUS              PORTS                                      NAMES
a1f5905f9f21        zoffline/zoffline   "httpd-foreground"   45 minutes ago      Up 4 seconds        0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   zwift-offline

TLo-PC@TLo-PC MINGW64 /c/Program Files/Docker Toolbox
$ docker inspect --format '{{ .NetworkSettings.IPAddress }}' zwift-offline
172.17.0.2


Ping wird ausgeführt für 192.168.99.100 mit 32 Bytes Daten:
Antwort von 192.168.99.100: Bytes=32 Zeit<1ms TTL=64
Antwort von 192.168.99.100: Bytes=32 Zeit<1ms TTL=64
Antwort von 192.168.99.100: Bytes=32 Zeit<1ms TTL=64
Antwort von 192.168.99.100: Bytes=32 Zeit<1ms TTL=64

Ping-Statistik für 192.168.99.100:
    Pakete: Gesendet = 4, Empfangen = 4, Verloren = 0
    (0% Verlust),
Ca. Zeitangaben in Millisek.:
    Minimum = 0ms, Maximum = 0ms, Mittelwert = 0ms

Ping-Statistik für 192.168.99.100:
    Pakete: Gesendet = 4, Empfangen = 4, Verloren = 0
    (0% Verlust),
Ca. Zeitangaben in Millisek.:
    Minimum = 0ms, Maximum = 0ms, Mittelwert = 0ms

C:\Users\TLo-PC>ping 172.17.0.2

Ping wird ausgeführt für 172.17.0.2 mit 32 Bytes Daten:
Zeitüberschreitung der Anforderung.

Ping-Statistik für 172.17.0.2:
    Pakete: Gesendet = 4, Empfangen = 0, Verloren = 4
    (100% Verlust),`
That means I can ping the "Default" docker VM but the container itself cannot be reached.

**Comment by oldnapalm** [comment]
What IP address did you insert into hosts file? If I remember correctly when I used docker I had to set as 127.0.0.1 and not the IP assigned to the container.

**Comment by TLoxxx** [comment]
Tried both, neither will work. Right now i am experimenting with port forwarding 80 and 443 in NAT definition in virtualbox. So far no success.

**Comment by TLoxxx** [comment]
I think the problem is Windows 10:
https://github.com/docker/for-win/issues/204

but unfortunately neither of the suggested  solutions works. I tried machine-ip:80, container ip:80
still no luck.

**Comment by TLoxxx** [comment]
WTF I don'T know what I have changed, but now it seems to work.
I adjusted hosts to 
192.168.99.100 us-or-rly101.zwift.com secure.zwift.com cdn.zwift.com
which is machine-ip from docker.
Pretty sure this has not been working before but I noticed that using EDGE browser does NOT work for me. Using Chrome I was able to see the published port. (I tested if ist working using the ginx example from here: https://docs.docker.com/docker-for-windows/#explore-the-application

**Comment by zoffline** [comment]
Glad it's working for you now. Your issues made me realize there's no reason for all this additional complication of using Apache for most users. I've just pushed a pure-python standalone version that can run natively on the major platforms without the heaviness of a VM/Docker on Win. With it are some probable breaking changes for those currently running zoffline for which I apologize.
