### ISSUE TITLE
Instruction clarifications

### ISSUE THREAD

**Issue by sjstein** [zoffline/zwift-offline#100]
In Readme.md, Strava import section,
  Clarify the line `Get CLIENT_ID and CLIENT_SECRET from https://www.strava.com/settings/api` as [OPTIONAL]: (For Strava App Developers)

**Comment by oldnapalm** [comment]
Addressed in https://github.com/oldnapalm/zwift-offline/commit/f4a50f775572073db19a9dadbd3c6c7eb76529f2
