### ISSUE TITLE
get_profile.py hangs under mingw64 bash

### ISSUE THREAD

**Issue by sjstein** [zoffline/zwift-offline#101]
No password prompt after entering "python get_profile.py <uname>" on bash shell in windows.

Unable to interrupt (ctrl-c)

Works fine from windows command shell

**Comment by sjstein** [comment]
This comes down to the use of `getpass()` to query the user for their password without echoing text to the screen. Apparently this function does not play well with windows bash.

A workaround is to detect the shell running and either exit upon non-conforming shell, or possibly warn user of visible text being used for capturing password.

See, for example, this [post](https://stackoverflow.com/questions/24544353/python-getpass-getpass-function-call-hangs#:~:text=getpass()%20will%20freeze%20if,...%20if%20not%20sys.).

**Comment by zoffline** [comment]
Resolved with #102 - Thank you.
