### ISSUE TITLE
Could not create SSL/TLS secure channel

### ISSUE THREAD

**Issue by 6Xkljk8Vj7Tk1k4** [zoffline/zwift-offline#103]
Hi,

I follow the instructions provided to execute offline server on linux and I cannot connect with zwift:
![image](https://user-images.githubusercontent.com/754027/101181335-0c334380-364d-11eb-921d-73ed546e85f2.png)

All ports are opened and reachable as expected.

I tried mp branch and source for latest release as well even in both pyton2 and python3 - same results. 
However when I download exe and execute it on windows it works fine. 

Please support.
Thanks!

**Comment by oldnapalm** [comment]
Try changing MinProtocol in /etc/ssl/openssl.cnf to TLSv1.0

If it's not there, try adding this to the end of the file
```
[system_default_sect]
MinProtocol = TLSv1.0
CipherString = DEFAULT@SECLEVEL=1
```

We had a similar problem setting up a server on Linux, the error message was no exactly the same but may be related.

**Comment by 6Xkljk8Vj7Tk1k4** [comment]
That worked! Thanks!

For centos it is:
[root@minecraft zwift-offline]# cat /etc/crypto-policies/back-ends/opensslcnf.config
CipherString = @SECLEVEL=1:kEECDH:kRSA:kEDH:kPSK:kDHEPSK:kECDHEPSK:-aDSS:-3DES:!DES:!RC4:!RC2:!IDEA:-SEED:!eNULL:!aNULL:!MD5:-SHA384:-CAMELLIA:-ARIA:-AESCCM8
Ciphersuites = TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256:TLS_AES_128_CCM_SHA256
MinProtocol = TLSv1.0
MaxProtocol = TLSv1.3

**Comment by oldnapalm** [comment]
Just to register it, posted by **javamilk** on Discord

> I can make it accept tls1 with text "TLSv1" instead of "TLSv1.0"
> Or just remark the MinProtocol line, it will fallback to default seclevel=1
> my env: openssl 1.1.1f (Ubuntu 20.04)

**Comment by oldnapalm** [comment]
### Method posted by Sinistar on Discord

Create a file `ssl/openssl.cnf` with the contents:

```
openssl_conf = openssl_init

[openssl_init]
ssl_conf = ssl_sect

[ssl_sect]
system_default = system_default_sect

[system_default_sect]
MinProtocol = TLSv1
CipherString = DEFAULT@SECLEVEL=1

```

Invoke the server from the install directory as follows:

`sudo OPENSSL_CONF=ssl/openssl.cnf python3 standalone.py`
