### ISSUE TITLE
ghost/strava upload

### ISSUE THREAD

**Issue by 6Xkljk8Vj7Tk1k4** [zoffline/zwift-offline#104]
Hi,

In previous issues I found that ghosts and strava uploads work for >5km. 
Is there a possibility to implement lower value for running ex. 400m ?

Thanks,

**Comment by zoffline** [comment]
I believe runs only have to be over .8km to be uploaded and the new minimum for cycling rides is only 2.6km (based on https://support.zwift.com/my-activity-didn%27t-upload-H1Zv962fS). The minimums are controlled by the Zwift game so I'm not sure there'd be a way around them aside from manually uploading the locally saved .fit file.
