### ISSUE TITLE
Message to Companion App - Question not issue 

### ISSUE THREAD

**Issue by jameshindle1972** [zoffline/zwift-offline#110]
Hi, 
I'm sure I read somewhere that you were looking into capturing the messages send from the Zwift App to the Companion App, did you ever find a way as I've been trying for weeks and getting nowhere, I'm after the workout messages and changes to trigger other events ?
Thanks for any help
James

**Comment by zoffline** [comment]
I'm not sure if anyone is actively looking into the companion app right now. To capture the messages sent/received by the app something like mitmproxy (https://mitmproxy.org) or Fiddler (https://www.telerik.com/fiddler) could be used. There's also HttpCanary (https://play.google.com/store/apps/details?id=com.guoshi.httpcanary), but I've never used that myself. Wireshark may also be useful if the app is communicating via more than HTTP.

zwift-mobile-api (https://github.com/Ogadai/zwift-mobile-api) includes some details of the messages used by the Companion App. It's also possible to obtain details on the messages via the APK with something like pbtk (https://github.com/marin-m/pbtk).

It's probably worth noting that if you've agreed to the Zwift EULA, all of the above sniffing/reversing would be in violation of it should you reside in a country where that's enforceable.

**Comment by zoffline** [comment]
Closing to consolidate Companion App request in issue #99
