### ISSUE TITLE
Method for uploading ride data to Zwift server

### ISSUE THREAD

**Issue by rdvAndroid** [zoffline/zwift-offline#113]
I enjoy ghost riding as a way to add a RGT feature to Zwift. What I miss is getting Zwift credit for my sweat equity. As Zwift doesn't support fit file imports I'd like to be able to "Save and exit" a Zoffline ride to Zwift as that is an easy way to keep track of my efforts. 
I've tried hitting ESC and seeing the "Save and exit" pop-up and then behind the scenes return the host entry back to the normal Zwift values before clicking the "Save and Exit" button but that didn't work. 
Of course being greedy I'd like the ride data saved to Zwift but the ghost ride details saved as well. I may as well dream for the most flexible solution.
Obviously this is an enhancement but I'm fairly sure others would like it as well.

**Comment by oldnapalm** [comment]
This is a quick test I did which seems to work:
- In zwift_offline.py add this before the final return of `api_profiles_activities_id` (it will save the activity to a binary file)
```
    with open('%s/%s/%s.bin' % (STORAGE_DIR, player_id, activity_id), 'wb') as f:
        f.write(activity.SerializeToString())
```
- After saving an activity, edit the hosts file to use Zwift online and run (put the script in zoffline folder)
`python upload_activity.py -p <your online Zwift ID> -a <activity file>`

https://gist.github.com/oldnapalm/5563849ce609d10226ae1d8e0481722b

**Comment by oldnapalm** [comment]
Added binary releases in my fork if someone wants to test
https://github.com/oldnapalm/zwift-offline/releases/tag/zoffline_1.0.61590

**Comment by rdvAndroid** [comment]
Thank you very much. I've successfully uploaded an activity file to Zwift proper. I noticed that if you try to upload the same activity file twice that second attempt replaces the first one as I had added the specific route name and that vanished. GREAT! accidents do happen and I don't want to double count. 
I also noticed that Zwift flags the activity with "Activity details could not be loaded" although the virtual world name, distance, elapsed time, and elevation are all correct. It also is unresolvable for the Zwift Activity Feed web site when you click on an uploaded entry. Neither of these slight limitations bother me at all.

As far as I'm concerned this enhancement has been fully implemented. 

Thankyou so much for such a speedy response. As I find Zwift Pace Partners so unsatisfactory/limited your ghost rider enhancements to Zwift has enhanced my indoor training experience.

**Comment by oldnapalm** [comment]
The "activity details could not be loaded" issue was because we were uploading the activity without creating it first, which was fixed later, but currently (since the free trial account changes I guess) we get "this activity is missing the fit data".

**Comment by oldnapalm** [comment]
Improved the script a bit so you don't need to enter your Zwift ID, it will be obtained from the server.

**Comment by oldnapalm** [comment]
The feature was merged into zoffline.

An executable release of [upload_activity](https://github.com/zoffline/zwift-offline/blob/master/scripts/upload_activity.py) was included in [zoffline_helper](https://github.com/zoffline/zwift-offline/releases/tag/zoffline_helper).

**Comment by jaduncan** [comment]
Can one upload arbitrary .fit files like this that are not generated in Zwift? It would enable credit for real world ridiing.
