### ISSUE TITLE
Docker image not updated

### ISSUE THREAD

**Issue by lee-staples** [zoffline/zwift-offline#115]
Just found your project, love it.
Found docker hub images is outdated, not updated with git changes to files
- zwift-offline/cdn/gameassets/Zwift_Updates_Root/

Is it possible to get docker images to follow and update based on git updates

Also suggest updating docker instruction to expose the folder
- /usr/src/app/zwift-offline/cdn/gameassets/Zwift_Updates_Root/
and or how to update docker container locally
- docker cp <somefolder>/Zwift_ver_cur.xml zwift-offline:/usr/src/app/zwift-offline/cdn/gameassets/Zwift_Updates_Root/

**Comment by zoffline** [comment]
An optional dependency, cryptography, used by zoffline and included in the Docker image started requiring Rust recently breaking an absurd amount of docker images including the last couple of zoffline image builds. That dependency has been removed and the Docker images should be updating again.
