### ISSUE TITLE
Zwift Launcher is out of date

### ISSUE THREAD

**Issue by geoced** [zoffline/zwift-offline#119]
Hello,

I've updated both Zwift and Zoffline to their latest version but I cannot get it to work. 

I get a popup saying that Zwift Launcher is out of date and must be updated, but it already is.

I also get a Python error (ssl.SSLEOFError: EOF occurred in violation of protocol), not sure if this is related.

![screenshot](https://user-images.githubusercontent.com/40609578/112336197-2a38b880-8cbd-11eb-91da-b305a6705540.png)

Anyone having the same issue ? It used to work in the past, so I guess a recent update broke things...

**Comment by oldnapalm** [comment]
Hi,

which version is your launcher?

I just tested and it's working for me (launcher 1.0.50)

![2021-03-24 12_51_21-](https://user-images.githubusercontent.com/38410858/112341285-0b77f900-8ca0-11eb-8255-2f459e93ea1f.png)

**Comment by geoced** [comment]
I have v1.0.51!

**Comment by oldnapalm** [comment]
Just updated to 1.0.52 and it's working.

![2021-03-24 17_38_09-](https://user-images.githubusercontent.com/38410858/112380266-f4e59800-8cc7-11eb-82d8-9edbd829864a.png)

Maybe it's an issue with the specific version you are using? Try to update, just download from https://www.zwift.com/ca/download and run the installer again.

**Comment by oldnapalm** [comment]
As of 1.0.67624 Zwift forces an update to launcher 1.0.52

**Comment by geoced** [comment]
Yep, I finally got the update !
