### ISSUE TITLE
Batch file to launch windows launcher

### ISSUE THREAD

**Issue by Gentatsu** [zoffline/zwift-offline#121]
I tried to upload this as a bat, but git doesn't like it, so I've uploaded it as a text file.

This is a batch file which moves the original hosts file to a temp location, opens the zwift launcher, and then when the user presses a key, moves the old one back. This prevents needing edit the host file in the `configure_client.bat`. Ip address is stored in `ip_address.txt` file. Seems to work a charm. 

I wasn't sure how to add this to the repo, as the helper isn't there. 

[launch.txt](https://github.com/zoffline/zwift-offline/files/6214503/launch.txt)

[ip_address.txt](https://github.com/zoffline/zwift-offline/files/6214499/ip_address.txt)

**Comment by zoffline** [comment]
Thanks!
