### ISSUE TITLE
Add support for Meet Up

### ISSUE THREAD

**Issue by Dv8ers** [zoffline/zwift-offline#123]

**Comment by zoffline** [comment]
Adding enhancement label, but this would be very ambitious to support since it currently requires the companion app. A more basic app or web UI created just for zoffline meet up support could probably be used instead though.

**Comment by oldnapalm** [comment]
Meetup support was added in https://github.com/zoffline/zwift-offline/tree/zca (thanks @ursoft), still a work in progress but it's functional.
