### ISSUE TITLE
how do I add a large number of bots to the map?

### ISSUE THREAD

**Issue by flix56** [zoffline/zwift-offline#146]
I have 9 bots on the vatopia map, is it possible to increase their number to 1000 or 3000?

**Comment by oldnapalm** [comment]
It's possible, but the bots are not procedurally generated, they are activities recorded using a power simulator (like ghosts). You would need to do that, or use ghost files from your previous activities (saved in storage/profile_id/ghosts).

**Comment by flix56** [comment]
that is, the more I ride, the more bots there will be?

**Comment by oldnapalm** [comment]
Yes, but ghosts are loaded automatically when you ride the same route again, they are not like pace partners and bots, which keep riding their routes independently of where you ride.

If you want to have other bots (always riding around) you need to create them from ghost files.

I used this script to create the bots included in zoffline
https://github.com/zoffline/zwift-offline/blob/master/scripts/bot_editor.py

**Comment by flix56** [comment]
tell me where to enter this script

**Comment by oldnapalm** [comment]
Run it from the bot folder, which must contain a profile.bin (any profile file) and a route.bin (any ghost file). See comment about folder name in script header.

The script only changes the bot name and trims the route to make a perfect loop. If the route is not a loop (doesn't start and finish in the same place) you can use it anyway, but when the bot finishes, it will teleport to the beginning and start again.

**Comment by flix56** [comment]
well, how can I cancel this script if something happens

**Comment by oldnapalm** [comment]
I do not understand.

**Comment by flix56** [comment]
how can I cancel this script if anything

**Comment by oldnapalm** [comment]
I don't understand what you mean with "cancel this script", it doesn't make sense.

**Comment by flix56** [comment]
how can I cancel this script
