### ISSUE TITLE
Profile data missing

### ISSUE THREAD

**Issue by oldnapalm** [zoffline/zwift-offline#15]
With current zoffline version the "this ride/your best" info in the menu is zeroed out. I tried to create a new profile and the info is there after the first ride, but it's lost after the client is closed/reopened. No matter if using standalone or Apache.

Using previous zoffline version (before the standalone changes) the information is persistent.

I also noticed a bug in rider customization (missing helmet) with current zoffline version.

All tests with latest client version (1.0.31087).

**Comment by zoffline** [comment]
Fixed now. tyvm for testing prior version. Probably saved me from wasting a lot of time down the wrong path.
