### ISSUE TITLE
Updates to the Docker image?

### ISSUE THREAD

**Issue by dazzag24** [zoffline/zwift-offline#150]
Hi,

I use the docker-compose mode of installation. I notice that the installer receives regular updates that follow official updates.
However the docker image appears as if it has not been updated for 3 months?

https://hub.docker.com/r/zoffline/zoffline/tags?page=1&ordering=-name

or is this just an artifact of re-using the latest tag?

It would be good to include tagged versions of the docker images to make it clearer when updates are being provided.

Also, would it be possible to to include some notes on how to update for people who are using the docker-compose setup?
I think it will be something like this:

```
docker-compose stop
docker-compose pull
docker-compose up -d
docker-compose logs -t -f
```

Many thanks

**Comment by oldnapalm** [comment]
If the server has files `*_ver_cur.xml` older than the client, when you start the client it will try to downgrade and fail (unless you have cdn proxy configured and the old version files are still available on Zwift server).

Issues with multiplayer are most likely not related to this (the downgrade error should occur regardless of multiplayer support).

**Comment by dazzag24** [comment]
Would it be a good idea to update the instructions for the Docker users to state that they should use their own built images rather than the out of date on hosted on Docker hub.

e.g if you change this line in the compose file:

```
-         image: zoffline/zoffline:latest
+         image: <username>zoffline:latest
```

then when you do "docker-compose up -d" it will build a local image rather than download one.
