### ISSUE TITLE
Version 1.0.100133 doesn't log into account 

### ISSUE THREAD

**Issue by pdn-ussr** [zoffline/zwift-offline#151]
After entering the password, it does not log into the account

**Comment by oldnapalm** [comment]
cacert.pem was updated, you need to re-add the certificate (or just run configure_client.bat again).

**Comment by oldnapalm** [comment]
@zoffline #62 is no more, you may want to edit the instructions.

**Comment by pdn-ussr** [comment]
Thank you!

**Comment by oldnapalm** [comment]
No problem.

If you update manually, make sure to update [TCPHandler](https://github.com/zoffline/zwift-offline/blob/9d6808fa8cb692e276f1ce47585615401da2e83c/standalone.py#L252) (the hello packet was modified) or else the ghosts, pace partners, bots and multiplayer won't work. There were also changes in the [variant](https://github.com/zoffline/zwift-offline/blob/9d6808fa8cb692e276f1ce47585615401da2e83c/zwift_offline.py#L2017) response (not sure if it depends on platform or other variable, I tested only on Windows).

**Comment by ursoft** [comment]
> the hello packet was modified
Hi! 
Please look into last commits in my fork https://github.com/ursoft/zwift-offline :
1. TcpHello packet recognition bug fixed
2. Zwift Companion App partially supported (first approximation)
3. Some others bugs fixed (or added - not sure :-)

What version of protoc.exe are you using? Latest 3.19.1 - but I often see "Connection Disconnected" banner with it.

**Comment by oldnapalm** [comment]
> 2. Zwift Companion App partially supported (first approximation)
Hi.
Nice! This has been requested a few times (#99).
A new certificate is really needed?

**Comment by ursoft** [comment]
> A new certificate is really needed?
No, just regenerated for myself

**Comment by ursoft** [comment]
> I often see "Connection Disconnected"

It's a bug in 1.0.100133 (all platforms). The memory allocated for the TelemetryService class is not initialized with nulls.
Patch for ZwiftApp.exe:
![image](https://user-images.githubusercontent.com/3672801/143140252-aefede12-22d8-4a71-864f-c7908167313d.png)

**Comment by oldnapalm** [comment]
> I often see "Connection Disconnected"

I saw this alert once, then never again.

> The memory allocated for the TelemetryService class is not initialized with nulls.

Maybe related to `/api/telemetry/config` response?

zoffline currently returns `{"isEnabled":false}` while retail server returns
```
{
    "analyticsEvents": false,
    "batchInterval": 120,
    "endpointUsage": false,
    "innermostCullingRadius": 1500,
    "isEnabled": true,
    "key": "aXBSdlpza3p1aVlNOENrMTBQSzZEZ004Z2pwRm8zZUE6",
    "remoteLogLevel": 3,
    "sampleInterval": 60,
    "url": "https://api.segment.io/v1/track",
    "urlBatch": "https://us-or-rly101.zwift.com/hvc-ingestion-service/batch"
}
```
then `/hvc-ingestion-service/batch` returns `{"success": true}`

Have you tried removing `game_1_19_system_alerts` from `/experimentation/v1/variant`?

**Comment by ursoft** [comment]
> I saw this alert once, then never again.

Need dirty heap at application start - hard to reproduce. Application Verifier could help, but ZwiftApp.exe too bad to work with AppV enabled.

> Maybe related to `/api/telemetry/config` response?
> zoffline currently returns `{"isEnabled":false}` while retail server returns

Of course. Retail server telemetry overwrites garbage and no disconnect calculated.

> Have you tried removing `game_1_19_system_alerts` from `/experimentation/v1/variant`?

Yes, this method cuts the issue, but my patch (I hope) cures it.
