### ISSUE TITLE
MAP_OVERRIDE not always applied

### ISSUE THREAD

**Issue by ursoft** [zoffline/zwift-offline#153]
Maybe, start date & time sometimes points to the future?
My UTC offset = +5.
Just replaced to 2020 year in my fork: https://github.com/ursoft/zwift-offline/commit/bada3bb15f06d117eb5d2753d79ae4717c453aa8

**Comment by oldnapalm** [comment]
You are correct, depending on your time zone the start date may be tomorrow.
