### ISSUE TITLE
SSL Certificates Requiring Passwords

### ISSUE THREAD

**Issue by l0r3m-1p5um** [zoffline/zwift-offline#16]
Hello!  Thank you for putting together this project.  During setup I'm being prompted for a password to the certificates.  That said, if the password is no longer available, would it be possible to suggest a method for creating my own certificates?  Thanks!

**Comment by zoffline** [comment]
There's no password, but you may be prompted anyway depending on the platform. If prompted, just leave the password blank and continue on (hit Enter, or OK, etc.).

If you want to create your own you can take a look at a guide on creating self signed certificates (e.g. https://www.digitalocean.com/community/tutorials/openssl-essentials-working-with-ssl-certificates-private-keys-and-csrs#generating-ssl-certificates) and just use *.zwift.com as the CN (aka FQDN).

**Comment by l0r3m-1p5um** [comment]
Thank you for following-up.  I'm still having issues importing the certificate.  I'll create a certificate. Thank you for the guidance.

**Comment by oldnapalm** [comment]
If you are on Mac OS, make sure you select "System" and not "System Root" under Keychains. If you select "System Root" it won't accept the blank password.

**Comment by zoffline** [comment]
Assuming this is resolved and closing.
