### ISSUE TITLE
Old Zwift connection blocking method causing issues with current client

### ISSUE THREAD

**Issue by goddardYYZ** [zoffline/zwift-offline#179]
I'm not sure how the old client would block connections to Zwift but it is now causing issues like, not being able to download the Zwift client from the official site and the launcher crashing on startup. I cannot find a reference to what method was used to block the connections to the Zwift servers so I am unsure how to fix the issue other than a fresh windows install.

**Comment by oldnapalm** [comment]
Comment out the line with Zwift hosts in `C:\Windows\System32\Drivers\etc\hosts` (https://github.com/zoffline/zwift-offline#enablingdisabling-zoffline), you should be able to download and install the latest client.
