### ISSUE TITLE
Badges are gone

### ISSUE THREAD

**Issue by stapa** [zoffline/zwift-offline#184]
Almost all badges are gone in the last zoffline version. Level and drops remained.

**Comment by oldnapalm** [comment]
From which version did you update?

Achievements were migrated around update 1.0.100541, they should have been converted to the new format
https://github.com/zoffline/zwift-offline/commit/80027269ad7653b50e57ea7a68781d90e06063ec

If you have a backup of your profile.bin you can try to run the conversion again to obtain the achievements.bin file, then you can use to the current profile.bin again.

**Comment by stapa** [comment]
I recently skipped several versions , this could be the cause of my problem. I'm no sure from which version exactly, but I still have a backup. How can I run the conversion manually?

**Comment by oldnapalm** [comment]
Stop zoffline, put the backup profile.bin in storage/<ID> (backup current one first), delete achievements.bin, run zoffline and start Zwift, a new achievements.bin should be created when Zwift calls /achievement/loadPlayerAchievements. Make sure you update zoffline from git and not only update the xml files.

**Comment by stapa** [comment]
It works, thank you!
