### ISSUE TITLE
Request: protobuf use

### ISSUE THREAD

**Issue by mayfield** [zoffline/zwift-offline#187]
Hi, Great project here!  I found this while reverse engineering the zwift API and a google search for one of the URLs led to this project.  Really impressive stuff.

I am building a HUD alternative for Zwift and would really like to use your `.protobuf` files as a starting point if possible.  I'm not unfamiliar with reverse engineering protobufs from the wire myself, but it would sure save me LOT of time if I could leverage your work.

My program is a distributed application for Macs and Windows machines, so I'm not 100% clear on how the AGPL requirements are best satisfied.  My program obviously has a user interface but the derivative work would be just these protobuf definitions (The AGPL makes some specific mention of user interface code).

So I wanted to formally ask if you're agreeable to my use of these files in the first place and how you would prefer I do any sort of attribution/release-of-liability?  I don't have a licenses page yet, but I could probably add one around the same place I have to put all the legal footers.

**Comment by oldnapalm** [comment]
Hi.

I'm not the project owner, can't grant or deny your request.

I know some projects (mainly for live streamers) use [zwift-packet-monitor](https://github.com/jeroni7100/zwift-packet-monitor), guess most you need is in https://github.com/jeroni7100/zwift-packet-monitor/blob/master/zwiftMessages.proto

There's also this .NET port with improved protobuf by @ursoft https://github.com/ursoft/ZwiftPacketMonitor

**Comment by ursoft** [comment]
As for my protobuf add-ons, they are all completely free. You can mention me if you use them, but it is not necessary.

**Comment by oldnapalm** [comment]
> As for my protobuf add-ons, they are all completely free. You can mention me if you use them, but it is not necessary.

Worth to mention that all recent protobuf improvements in zoffline is @ursoft work and comes from his fork https://github.com/ursoft/zwift-offline so I guess you are free to use.

**Comment by mayfield** [comment]
Thanks guys!  Again, really cool project!
