### ISSUE TITLE
Invalid certification

### ISSUE THREAD

**Issue by Reverbsz** [zoffline/zwift-offline#189]
I got this message of Invalid certification if anyone can help?

Running both zwift offline latest version and current version zwift

![image](https://user-images.githubusercontent.com/107463683/173521216-169fb4b2-7558-4794-ae50-3901a328f03c.png)

**Comment by daktak** [comment]
You imported the z-offline certs as per the Readme? certutil.exe -importpfx Root cert-zwift-com.p12 (windows example)

**Comment by oldnapalm** [comment]
Appending the certificate to cacert.pem is also required.

If you are updating from an old zoffline version (earlier than January 2022) you need to redo those steps because the certificate was updated.

**Comment by Reverbsz** [comment]
Yes, correct I haven't update my zoffline for a while. Can you guide me where should I read the Readme? 
Apologise for being a newbie.

**Comment by oldnapalm** [comment]
You can just run the configure_client script from https://github.com/zoffline/zwift-offline/releases/tag/zoffline_helper

It would be the step 2 from Readme and the password is blank (just press enter).

**Comment by Reverbsz** [comment]
My bad, I seems running earlier version of zoffline-helper that is why it doesn't quite work.

All good now.

**Comment by Reverbsz** [comment]
Sorry in separate matter, is this the correct way for the folder setup for pace partner?

Is the folder name for the routes and power has to be exact as per the portal?

![image](https://user-images.githubusercontent.com/107463683/173723041-d7ba8a7e-54c9-4083-bcd0-8e82b0923914.png)

**Comment by oldnapalm** [comment]
Yes, that's correct (assuming zoffline.exe is also in the "Zwift Offline" folder).

No, the folder name doesn't matter. Although, the files profile.bin and route.bin must remain untouched. There's something wrong in your picture, profile.bin should be just 1 KB, not the same size as the route.

To avoid mistakes and make it easier, download the full repo as zip and extract only the folders you want.

https://github.com/zoffline/zwift-offline/archive/refs/heads/master.zip

![2022-06-14 23_44_49-Window](https://user-images.githubusercontent.com/38410858/173725895-42d38207-978d-41e0-8c75-400aabb50b47.png)

**Comment by Reverbsz** [comment]
Great, thanks for the tips all is working properly now.

Really appreciate your help.

**Comment by oldnapalm** [comment]
Glad you sorted it out.

I updated the instructions regarding pace partners in the release.
