### ISSUE TITLE
Can't get ghost nor pace partners

### ISSUE THREAD

**Issue by JeromeO** [zoffline/zwift-offline#192]
Hi,

thank you so much for this work.

I can't find a way to get pace partners to appear, nor can I get the ghosts to be recorded.

I tried both the exe file (putting the pace_partners directory in the same directory as the exe file) and the python source on a Windows 10, running Zwift on this same machine.

I tried to use a fresh profile or my old one.

When I launch Zwift, I select the box to record ghosts. But when I'm done, no ghosts directory is created in my storage/1 directory).

I can see the list of pace partners available on the main screen. But if I select a pace partner, I end up being all by myself in the game.

Any idea what I'm doing wrong ?

Thank you.

**Comment by oldnapalm** [comment]
Hi.

Looks like Zwift is having problem connecting to zoffline TCP and UDP servers, check the Log.txt file which is in your Documents\Zwift\Logs folder.

**Comment by JeromeO** [comment]
The problem is indeed a network problem, and it concerns my VPN (NordVPN actually). Using "split Tunneling" doesn't allow me to use pace partners. I don't know why, but if  I disable "Split Tunneling", it works. I'll investigate later.

Thank you for your answer. I close the issue.
