### ISSUE TITLE
Instructions for self signed certificates

### ISSUE THREAD

**Issue by peteh** [zoffline/zwift-offline#196]
Hi, 

I think some instructions for creating self signed certificates would be great. Especially for the docker version. 

Maybe another approach could be to generate the certs at first server start if they don't exist yet and instruct the user to copy them to the right places. 

The current solution might open a few security concerns, even though I'm not sure how big the issue is. Can you create new certs with the certs provided in the repo?

**Comment by oldnapalm** [comment]
There are many guides on creating self signed certificates, e.g. https://devopscube.com/create-self-signed-certificates-openssl/

**Comment by peteh** [comment]
Well obviously, but I assume the certificate has to match certain criteria like domain names and such which is not documented. 

And I think in the end the docker compose file would have to be modified to map /usr/src/app/ssl/key-zwift-com.pem to the created file to make it work.

**Comment by oldnapalm** [comment]
Yes, it has to match the domain names you are redirecting in the hosts file, I believe that's obvious too.

I don't have experience with Docker, can't comment on that.

**Comment by oldnapalm** [comment]
> And I think in the end the docker compose file would have to be modified to map /usr/src/app/ssl/key-zwift-com.pem to the created file to make it work.

After doing a little search in #223 I believe this can be achieved by adding a volume in docker-compose.yml, for example
```
        volumes:
           - ./storage/:/usr/src/app/zwift-offline/storage
           - ./ssl/:/usr/src/app/zwift-offline/ssl
```

Feel free to open a PR with the proposed instructions or alternative approach and I will request @zoffline review. Personally I don't think it's necessary for the average user, I believe most are happy with the provided certs since this has never been asked before.
