### ISSUE TITLE
new version Zwift_1.0.105318

### ISSUE THREAD

**Issue by voodoopt** [zoffline/zwift-offline#197]
anyone else with this problem?

Patcher: Local manifest is "Zwift_1.0.105318_83ccee8f_manifest.xml".
Patcher: Server manifest is "Zwift_1.0.105233_27ea3fb2_manifest.xml".

**Comment by voodoopt** [comment]
patch-zoffline-for-update.sh
must be run from top of zwift-offline repo,
but im running docker

**Comment by oldnapalm** [comment]
You need to update Zwift_ver_cur.xml in the Docker filesystem (/usr/src/app/zwift-offline/cdn/gameassets/Zwift_Updates_Root). Anyway the Docker image should be already updated now.
