### ISSUE TITLE
zoffline 105318 sqlite error

### ISSUE THREAD

**Issue by pdn-ussr** [zoffline/zwift-offline#198]
After upgrading to version 105318, an error appears when trying to launch Zwift (see screenshot):

![zoffline_105318_error](https://user-images.githubusercontent.com/57845118/193412238-f6cc3ac0-c987-4fd0-b830-61e74fb30f5d.jpg)

**Comment by oldnapalm** [comment]
Something went wrong with the database migration. There's a backup of your db file in the storage folder (zwift-offline.db.v2.xxxxxxxxxx.bak), try to remove the new one, copy the backup to zwift-offline.db (with zoffline closed) and run zoffline again.

**Comment by pdn-ussr** [comment]
Restoring a backup did not help. Rolled back to version 1.0.105233.

**Comment by oldnapalm** [comment]
I don't know what can be causing the issue, if you can send me your db backup I can investigate. You can send me privately on Discord https://discord.gg/kw4dAUQUx4

**Comment by voodoopt** [comment]
docker problem 
ImportError: cannot import name 'sqlalchemy' from 'flask_sqlalchemy' (/root/.local/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py)
Traceback (most recent call last):
  File "/usr/src/app/zwift-offline/standalone.py", line 26, in <module>
    import zwift_offline as zo
  File "/usr/src/app/zwift-offline/zwift_offline.py", line 36, in <module>
    from flask_sqlalchemy import sqlalchemy, SQLAlchemy
after update 
wont start

**Comment by oldnapalm** [comment]
> docker problem ImportError: cannot import name 'sqlalchemy' from 'flask_sqlalchemy' (/root/.local/lib/python3.10/site-packages/flask_sqlalchemy/**init**.py) Traceback (most recent call last): File "/usr/src/app/zwift-offline/standalone.py", line 26, in import zwift_offline as zo File "/usr/src/app/zwift-offline/zwift_offline.py", line 36, in from flask_sqlalchemy import sqlalchemy, SQLAlchemy after update wont start

Fixed in https://github.com/zoffline/zwift-offline/commit/2cfbf6ac5c964286b8f3c96c67dbb011cdf5c22e
