### ISSUE TITLE
Zwift crashes on MacOS

### ISSUE THREAD

**Issue by paul-grundmann** [zoffline/zwift-offline#200]
In the most recent version Zwift crashes on MacOS on Apple Silicon with a segmentation fault in combination with the zwift-offline server. Zwift without the zwift-offline server runs fine.
I assume this has something to do with some telemetry that is expected in the communication protocol between the emulated server and the Zwift client. On Windows everything works fine. 
I also reinstalled zwift, the zwift-offline server and also ran it in a docker container to exclude errors from the environment.

The client crashes always with the following log:
```
[15:00:31 2022-11-12] Downloader::ForgetCompleted path=ZwiftMac_ver_cur.xml[15:00:31 2022-11-12] Downloader::ForgetCompleted path=LauncherMac_ver_cur.xml[15:00:31 2022-11-12] Launcher: Calling Update Launcher Check
[15:00:31 2022-11-12] Launcher: Calling Update Process Available
[15:00:31 2022-11-12] Launcher: Update Not Found.
[15:00:32 2022-11-12] Launcher: Webview loaded some URL.
[15:00:32 2022-11-12] Launcher: Webview loaded some URL.
[15:00:32 2022-11-12] Launcher: Found Zwift Scheme.
[15:00:32 2022-11-12] Launcher: Access Code Received.
2022-11-12T15:00:32> [INFO] CNL 3.22.2
2022-11-12T15:00:32> [INFO] Machine Id: 2-47ac965e-5f98-4e08-a312-e64d84a51fd5
2022-11-12T15:00:32> [INFO] CNL initialized
2022-11-12T15:00:32> [INFO] Session ID: 2775fd31-5d5e-4811-a2f6-be8f4c789447 (secure)
2022-11-12T15:00:32> [INFO] Logged in
2022-11-12T15:00:32> [INFO] Requesting seeds...
2022-11-12T15:00:32> [INFO] Player ID: 1
2022-11-12T15:00:32> [INFO] Analytics ID:
```

Could it be that in that in the new version there needs to be an analytics ID in the `/experimentation/v1/variant` POST request? Maybe the client fails during the serialization of the servers response.

**Comment by oldnapalm** [comment]
Do you see something related in `/experimentation/v1/variant` on Mac? I don't see anything on Windows, we are sending the same thing as Zwift server.

If the issue is with telemetry, you can try to enable it, now zoffline returns https://github.com/zoffline/zwift-offline/blob/07a057a7bf9f20753d840932b19725cd7b037004/zwift_offline.py#L1371

Response from Zwift server is like
```
{
    "analyticsEvents": True,
    "batchInterval": 120,
    "innermostCullingRadius": 1500,
    "isEnabled": True,
    "key": "aXBSdlpza3p1aVlNOENrMTBQSzZEZ004Z2pwRm8zZUE6",
    "remoteLogLevel": 3,
    "sampleInterval": 60,
    "url": "https://api.segment.io/v1/track",
    "urlBatch": "https://us-or-rly101.zwift.com/hvc-ingestion-service/batch"
}
```

and `POST https://us-or-rly101.zwift.com/hvc-ingestion-service/batch` returns
```
{
    "success": True
}
```

If the problem is lacking "Analytics ID" you can try adding this
```
            if not profile.mix_panel_distinct_id:
                profile.mix_panel_distinct_id = str(uuid.uuid4())
```
after this line https://github.com/zoffline/zwift-offline/blob/07a057a7bf9f20753d840932b19725cd7b037004/zwift_offline.py#L1447

![2022-11-12 13_01_35-GitHub Desktop](https://user-images.githubusercontent.com/38410858/201482924-04ccc9b2-1267-4774-a1f0-fcb6bcb29ebd.png)

**Comment by paul-grundmann** [comment]
Thank you very much for the quick answer. Unfortunately, none of this worked :( 

These are the logs on the server side:
```
127.0.0.1 - - [12/Nov/2022 18:21:36] "GET /gameassets/Zwift_Updates_Root/ HTTP/1.1" 200 -
INFO:zoffline:127.0.0.1 - - [2022-11-12 18:21:36] "GET /api/auth HTTP/1.1" 200 215 0.005406
INFO:zoffline:127.0.0.1 - - [2022-11-12 18:21:36] "GET /launcher/realms/zwift/protocol/openid-connect/auth?client_id=Game_Launcher&redirect_uri=http%3A%2F%2Fzwift%2F&login=true&response_type=code HTTP/1.1" 200 3528 0.006841
INFO:zoffline:127.0.0.1 - - [2022-11-12 18:21:36] "GET /style/site.css HTTP/1.1" 304 181 0.002038
INFO:zoffline:127.0.0.1 - - [2022-11-12 18:21:36] "GET /style/background.jpg HTTP/1.1" 304 189 0.000567
INFO:zoffline:127.0.0.1 - - [2022-11-12 18:21:36] "GET /favicon.ico HTTP/1.1" 404 331 0.000442
127.0.0.1 - - [12/Nov/2022 18:21:37] "GET /gameassets/Zwift_Updates_Root/ HTTP/1.1" 200 -
127.0.0.1 - - [12/Nov/2022 18:21:37] "GET /gameassets/Zwift_Updates_Root/ZwiftMac_ver_cur.xml HTTP/1.1" 200 -
127.0.0.1 - - [12/Nov/2022 18:21:37] "GET /gameassets/Zwift_Updates_Root/LauncherMac_ver_cur.xml HTTP/1.1" 200 -
INFO:zoffline:127.0.0.1 - - [2022-11-12 18:21:38] "POST /start-zwift HTTP/1.1" 302 334 0.000900
INFO:zoffline:127.0.0.1 - - [2022-11-12 18:21:38] "GET /ride HTTP/1.1" 302 4019 0.000404
INFO:zoffline:127.0.0.1 - - [2022-11-12 18:21:38] "POST /auth/realms/zwift/protocol/openid-connect/token HTTP/1.1" 200 3741 0.000611
INFO:zoffline:127.0.0.1 - - [2022-11-12 18:21:38] "GET /api/telemetry/config HTTP/1.1" 200 128 0.000360
INFO:zoffline:127.0.0.1 - - [2022-11-12 18:21:38] "GET /api/auth HTTP/1.1" 200 215 0.000351
INFO:zoffline:127.0.0.1 - - [2022-11-12 18:21:38] "POST /auth/realms/zwift/protocol/openid-connect/token HTTP/1.1" 200 3741 0.000502
INFO:zoffline:127.0.0.1 - - [2022-11-12 18:21:38] "POST /experimentation/v1/variant HTTP/1.1" 200 196 0.002186
INFO:zoffline:127.0.0.1 - - [2022-11-12 18:21:38] "POST /api/users/login HTTP/1.1" 200 257 0.000264
INFO:zoffline:127.0.0.1 - - [2022-11-12 18:21:38] "GET /relay/worlds/hash-seeds HTTP/1.1" 200 200 0.000318
INFO:zoffline:127.0.0.1 - - [2022-11-12 18:21:38] "GET /api/profiles/me HTTP/1.1" 200 140 0.000317
INFO:zoffline:127.0.0.1 - - [2022-11-12 18:21:38] "POST /experimentation/v1/variant HTTP/1.1" 200 115 0.001340
```

I will try to debug the communication a bit more to find out where the client might crash

**Comment by oldnapalm** [comment]
The last line in client log (Log.txt) is `[INFO] Analytics ID:`? Do you see a UUID now?

If the last line in server log is `POST /experimentation/v1/variant` then it might be some issue there. Which was the last working version?

You can try to sniff the communication with Zwift server and check that request, maybe Mac requests some feature that Windows doesn't.

Or just print que request stream and check if there's some value which is not present in variants.txt

![2022-11-12 14_51_37-GitHub Desktop](https://user-images.githubusercontent.com/38410858/201487820-6d9c564a-1bc9-4ccf-9069-c57b91137ee5.png)

**Comment by paul-grundmann** [comment]
Ok it seems there is a new request / flag called: `zwift_launcher_osx_metal`
With this here added to the variants.txt everything works again:
```
    {
      "name": "zwift_launcher_osx_metal",
      "value": true,
      "values": {}
    }
```

I will test how this might effect my windows installation and if it works create a pull request :)
Thanks again for the help!

**Comment by oldnapalm** [comment]
Nice. It won't affect Windows because we only return what the client requests.

Thanks for the fix.
