### ISSUE TITLE
Zwift Launcher crashes on macOS with version 1.0.105865

### ISSUE THREAD

**Issue by PeterBlanz** [zoffline/zwift-offline#202]
After updating both the Zwift client and zoffline to version 1.0.105865, the launcher crashes with a segmentation fault. The launcher succeeds in starting the Zwift client application when zoffline is NOT used (i.e. with the "real" server). Looking at the attached crash report, this seems to be somehow related to the method that checks if Metal is available. It is also worth noting that BEFORE the update, using zoffline resulted in the launcher starting the Metal version (ZwiftAppMetal), but AFTER the update, and without zoffline, the launcher starts the non-Metal (OpenGL?) version (ZwiftApp).

We have tried doing a clean install of the Zwift client (and reapplying all the certificate hacks). This didn't have any effect.

The same instance of zoffline (running in a Raspberry Pi) works fine with a Windows-based Zwift client.

P.S. Thank you for developing a GREAT piece of software!

[ZwiftLauncher-OSX_2022-11-15-212535.txt](https://github.com/zoffline/zwift-offline/files/10015691/ZwiftLauncher-OSX_2022-11-15-212535.txt)

**Comment by oldnapalm** [comment]
Did you update zoffline after November 12?

See #200
