### ISSUE TITLE
companion app not signing in

### ISSUE THREAD

**Issue by gnostisus** [zoffline/zwift-offline#203]
hello,

after downloading zoffline_1.0.105825 I successfully upgraded zwift client in windows and successfully connected to zoffline, I then went to launch the companion app and android went to upgrade it I uninstalled it, I had downloaded the companion app from a link you provided but the link was dead so i followed the instructions Step 7 [OPTIONAL]: Install Zwift Companion App: Android (non-rooted device) and created a patched apk and installed it on my phone, I have been using the change dns to zoffline server method, when I go to sign in i get invalid email or password message and on the zoffline server i get

fake_dns: NXDOMAIN('The DNS query name does not exist: octopi.local.')
Traceback (most recent call last):
  File "src\\gevent\\greenlet.py", line 908, in gevent._gevent_cgreenlet.Greenlet.run
  File "gevent\baseserver.py", line 34, in _handle_and_close_when_done
  File "gevent\server.py", line 233, in wrap_socket_and_handle
  File "gevent\_ssl3.py", line 796, in wrap_socket
  File "gevent\_ssl3.py", line 312, in __init__
  File "gevent\_ssl3.py", line 308, in __init__
  File "gevent\_ssl3.py", line 666, in do_handshake
ssl.SSLError: [SSL: SSLV3_ALERT_CERTIFICATE_UNKNOWN] sslv3 alert certificate unknown (_ssl.c:997)
2022-11-15T21:32:42Z <Greenlet at 0x1f02a9bc820: _handle_and_close_when_done(<bound method StreamServer.wrap_socket_and_handle , <bound method StreamServer.do_close of <WSGIServer, (<gevent._socket3.socket [closed] at 0x1f02aaa9a80)> failed with SSLError

so it appears to be reaching the server

this was my first attempt to patch the companion app I installed the latest Node.js and Java downloaded Zwift Companion
3.41.1 for Android from apkpure renamed it zca.apk then downloaded zwift-com.pem zca.apk from the github page and ran "apk-mitm --certificate cert-zwift-com.pem zca.apk" and was able to generate a patched apk that I installed did I miss something or need to install another component?

any advice?

Thanks in advance

**Comment by gnostisus** [comment]
I also upgraded to zoffline_1.0.105865

**Comment by oldnapalm** [comment]
Hi.

Apparently you did all that's needed.

Are you sure you used the correct certificate file (https://raw.githubusercontent.com/zoffline/zwift-offline/master/ssl/cert-zwift-com.pem) and installed the patched apk (not the original one)? Other than that I have no idea what can have gone wrong.

I usually download the apk from https://apkcombo.com/pt/downloader/#package=com.zwift.android.prod and 3.41.1 is working for me.

**Comment by gnostisus** [comment]
Thanks,

I downloaded the files from the links you provided and it worked. Does the cert-zwift-com.pem get updated or do I use this same one so for next time I just download the new apk (I bookmarked the link).

thanks again

**Comment by oldnapalm** [comment]
It isn't updated often. It was updated in January when Zwift launcher moved from IE to Edge because the old cert didn't fill a requirement (#154). Hopefully it won't need to be updated soon (it's valid for 10 years).

**Comment by gnostisus** [comment]
good to know 

thanks
