### ISSUE TITLE
Zoffline server on raspberry Pi?

### ISSUE THREAD

**Issue by gnostisus** [zoffline/zwift-offline#204]
I saw in another issue that someone commented they were running zoffline on a raspberry Pi, is there a guide somewhere how to do that or a diskimage, i have a Pi 3 i was using with octoprint that i upgraded to a Pi 4 so i was wondering if that would work, it would be great to go mobile to friends with it.

Thanks in advance

**Comment by oldnapalm** [comment]
I think the "Linux, Windows, or macOS (from source)" instructions will work. Make sure you don't use Python 3.11 because some dependencies are not ready for that version yet, use 3.10 or earlier. You may need to run the pip3 command with sudo.

There's this image for Pi but it's outdated, I don't know how easy it would be to update (there are new requirements and some modules may need to be updated), maybe it's easier to make a new install from scratch
https://github.com/v4mp1/zwift-offline/tree/server-update#server-install

**Comment by gnostisus** [comment]
i'll give the image a try first, would you suggest any particular distro of linux  for a new install or will the  Pi OS based on debian be alright it looks like it has Python 3.5 i'll search around to see if that would be able to be downgraded? when it says in the guide "Clone or download this repo" where does that get placed, i use putty to ssh into octoprint and win scp to browse and manage files so i would copy it to the pi and extract it.

thanks

**Comment by oldnapalm** [comment]
I installed zoffline on a Pi once, but it's been a while and I don't remember if it required something special.

```
pi@raspberrypi:~ $ uname -a
Linux raspberrypi 4.19.118-v7l+ #1311 SMP Mon Apr 27 14:26:42 BST 2020 armv7l GNU/Linux
pi@raspberrypi:~ $ python3 --version
Python 3.7.3
```

Python 3.5 is older than 3.11, not sure if it will work, you may need to update to 3.7 at least.

You can place it anywhere, I put in user home (`/home/pi`), you can clone via ssh directly (`git clone https://github.com/zoffline/zwift-offline.git`).

**Comment by gnostisus** [comment]
> Python 3.5 is older than 3.11, not sure if it will work, you may need to update to 3.7 at least.

i  read it fast and thinking it was 3.1.1 easier to upgrade then.

> You can place it anywhere, I put in user home (`/home/pi`), you can clone via ssh directly (`git clone https://github.com/zoffline/zwift-offline.git`)

i'm gonna give it a try from scratch on the Pi OS based on debian and see how it goes

thanks again

**Comment by PeterBlanz** [comment]
I'm running zoffline in a Raspberry Pi 2. Here are (roughly) the steps that I followed:

1. Used Raspberry Pi Imager to drop Ubuntu Server 22.10 (32-bit because of the ancient hardware) on an SD card.
2. Started the system, connected to Internet, installed all available updates with apt.
3. Installed pip3 with apt.
4. Followed oldnapalm's Linux instructions, had to run pip3 as sudo. (I know this is not recommended, but couldn't figure out how to run zoffline in a user-specific Python environment.)
5. **Ran into some missing dependencies, had to use apt to install them. If (big IF!) I remember correctly, these were python3-cffi and libffi-dev.**
6. Once I was finally able to run zoffline (as sudo), tested the system using a Windows client.
7. Turned zoffline into a service with Systemctl.

I hope this helps!

**Comment by gnostisus** [comment]
PeterBlanz

thanks for the walk through, yours was the comment i saw.

> 3. Installed pip3 with apt.

if you type "python3 --version"
what version of python is installed?


> 7. Turned zoffline into a service with Systemctl.
this loads it when booting, right? 
what do you type to do this

 
> I hope this helps!
yes, i tried the old image and couldn't get it working, then tried the pi os, no luck was going to try one of the distros in the pi imager wasn't sure which one to use. i'll give this a try


thanks

**Comment by oldnapalm** [comment]
About setting up as system service
https://medium.com/codex/setup-a-python-script-as-a-service-through-systemctl-systemd-f0cc55a42267

**Comment by daktak** [comment]
To solve the python dependencies i used virtualenv
```
mkdir /opt/zwift
cd /opt/zwift
virtualenv -p /usr/bin/python3 .
source ./bin/activate
pip install .xxx.
```

Then my service runs python from the virtualenv dir

```
[Unit]
Description=Zwift Server
After=network.target syslog.target

[Service]
Type=simple
User=root
WorkingDirectory=/opt/git/zwift-offline/
ExecStart=/opt/zwift/bin/python3 /opt/git/zwift-offline/standalone.py
Restart=on-abort
StandardOutput=journal

[Install]
WantedBy=multi-user.target
```

**Comment by PeterBlanz** [comment]
So THAT's how you do it without potentially messing up the root Python environment. Makes perfect sense!

To answer gnostisus' earlier question, my Python version is 3.10.7.

**Comment by gnostisus** [comment]
thanks for the replies

i haven't had any luck I tried all solutions but to no avail, my understanding of linux is limited so instructions have to be very specific and in order with no assumptions, I  loaded Ubuntu Server 22.10 64bit version and ran upgrade, the Python version is 3.10.7 at first i wasn't getting it to boot up it was stopping loading i tried the 32 bit and legacy versions and havn't had the energy to do anything over the weekend, turns out my pi imager was configured to set up ssh and wi fi, i turned those settings off put a ssh file in boot and was able to boot up and sign in through putty, i tried to follow the linux install at github and i didn't understand when the commands daktak  listed

mkdir /opt/zwift
cd /opt/zwift
virtualenv -p /usr/bin/python3 .
source ./bin/activate
pip install .xxx.

were to be run or if virtualenv or anything is needed to be installed before and is .xxx. a command or a stand in for something and if so what and when to git clone zoffline i rewrote the image and am now back at Ubuntu Server 22.10 64bit version after upgrade, and the Python version is 3.10.7 

also am not adept at setting a service so before i set about doing that is there a command line that will run zoffline through  to make sure it is working before writing the service

thanks in advance

**Comment by daktak** [comment]
Sorry this wasn't meant to be instructions, more on how you could pip install the dependencies as listed in the README. I've update the above comment

**Comment by gnostisus** [comment]
thanks, 

i initially thought i had to do the pip3 install flask protobuf...etc.. and then run your code, after that didn't work i thought the .xxx. wasn't literal just a stand in for something, now it makes sense that's how you install flask protobuf...etc..  

only question i have is virtualenv normally installed or does it need to be with the apt-get command or another way? other than that i should be able to handle it

i'll give it a go tomorrow

thanks again

**Comment by daktak** [comment]
Yea May need to be apt-get. In fedora it is python3-virtualenv

**Comment by gnostisus** [comment]
i think i successfully got everything in daktak's instructions done, i did change the directories from /opt to the user dir because i was having access problems so when i cd to the zoffline dir and entered the command i got this not sure if it's a linux issue or zoffline issue.

> ubuntu@ubuntu:~/zwift-offline$ sudo ~/zwift/bin/python3.10 ~/zwift-offline/standalone.py
> Traceback (most recent call last):
>   File "/home/ubuntu/zwift-offline/standalone.py", line 908, in <module>
>     from fake_dns import fake_dns
>   File "/home/ubuntu/zwift-offline/fake_dns.py", line 1, in <module>
>     import dns.resolver
> ModuleNotFoundError: No module named 'dns'

i ran zwift on my pc and got a pop up that read:

> Zwift encountered the following error: Unable to connect to the
> remote server No connection could be made because the target
> machine actively refused it 192.168.1.15:443 If the problem persists
> please contact Zwift Support.

Is Fedora good for Raspberry Pi?
With Fedora 37, Raspberry Pi 4 is now officially supported, including accelerated graphics using the V3D GPU,” reads the Fedora Wiki (opens in new tab) entry on the subject.Aug 4, 2022

daktak you mention Fedora is that what you are running on a pi? if i have to start over i can try that.

thanks again in advance

**Comment by oldnapalm** [comment]
> ubuntu@ubuntu:~/zwift-offline$ sudo ~/zwift/bin/python3.10 ~/zwift-offline/standalone.py
> Traceback (most recent call last):
> File "/home/ubuntu/zwift-offline/standalone.py", line 908, in 
> from fake_dns import fake_dns
> File "/home/ubuntu/zwift-offline/fake_dns.py", line 1, in 
> import dns.resolver
> ModuleNotFoundError: No module named 'dns'

That's because you are missing dnspython (should be added to the `pip install` command if you wish to enable the fake DNS by creating `fake-dns.txt` in storage).

**Comment by gnostisus** [comment]
> That's because you are missing dnspython (should be added to the pip install command if you wish to enable the fake DNS by creating fake-dns.txt in storage).

i copied my storage dir which has a fake-dns.txt, to run companion, so i just renamed it and huzzah! it worked and i was able to sign in with my account.

to install dnspython i'm guessing i have to pip install after  going cd /zwift then typing 

> source ./bin/activate
> pip install dnspython

i'll make an image of my sd card first then try later

as usual thanks again

**Comment by gnostisus** [comment]
i guess i successfully installed dnspython when i run zoffline i get
i can still launch zwift and it works though.

> ubuntu@ubuntu:~/zwift-offline$ sudo ~/zwift/bin/python3.10 ~/zwift-offline/standalone.py
> Exception in thread Thread-6 (fake_dns):
> Traceback (most recent call last):
>   File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
> INFO:zoffline:Server is running.
>     self.run()
>   File "/usr/lib/python3.10/threading.py", line 953, in run
>     self._target(*self._args, **self._kwargs)
>   File "/home/ubuntu/zwift-offline/fake_dns.py", line 61, in fake_dns
>     dns.start()
>   File "/home/ubuntu/zwift-offline/fake_dns.py", line 54, in start
>     server = socketserver.UDPServer((HOST, PORT), DNSUDPHandler)
>   File "/usr/lib/python3.10/socketserver.py", line 452, in __init__
>     self.server_bind()
>   File "/usr/lib/python3.10/socketserver.py", line 466, in server_bind
>     self.socket.bind(self.server_address)
> OSError: [Errno 98] Address already in use

i was able to load zwift launcher on my other pc and add an account and join my account.
any ideas i can always not use companion with it.

 
thanks again in advance

**Comment by oldnapalm** [comment]
The problem is that Ubuntu has systemd-resolved listening on port 53.

See https://www.linuxuprising.com/2020/07/ubuntu-how-to-free-up-port-53-used-by.html

**Comment by gnostisus** [comment]
that did the trick
companion is working
the only glitch is before zoffline started i got this:

> sudo: unable to resolve host ubuntu: Name or service not known

the whole execution looked like this

> ubuntu@ubuntu:~/zwift-offline$ sudo ~/zwift/bin/python3.10 ~/zwift-offline/standalone.py
> sudo: unable to resolve host ubuntu: Name or service not known
> INFO:zoffline:Server is running.

next step is getting the service running

once more thank you

**Comment by gnostisus** [comment]
i should add that
the resolved.conf now looks like this:
i used 1.1.1.1 for the dns
should i use 127.0.0.1 for local
and should i add a fallback dns

> DNS=1.1.1.1
> #FallbackDNS=
> #Domains=
> #DNSSEC=no
> #DNSOverTLS=no
> #MulticastDNS=no
> #LLMNR=no
> #Cache=no-negative
> #CacheFromLocalhost=no
> DNSStubListener=no
> #DNSStubListenerExtra=
> #ReadEtcHosts=yes
> #ResolveUnicastSingleLabel=no

thank you

**Comment by oldnapalm** [comment]
> i should add that the resolved.conf now looks like this: i used 1.1.1.1 for the dns

That's fine, but did you do steps 2 and 3?

**Comment by oldnapalm** [comment]
> that did the trick companion is working the only glitch is before zoffline started i got this:
> 
> > sudo: unable to resolve host ubuntu: Name or service not known

Maybe you need to add `127.0.0.1 ubuntu` to `/etc/hosts`

**Comment by gnostisus** [comment]
> Maybe you need to add 127.0.0.1 ubuntu to /etc/hosts

yup that  did it

now on to getting the service running

thank you once again

**Comment by gnostisus** [comment]
got the service running using daktak's instructions modified to my path's rebooted and everything is working just one last question

the next time you update zoffline do i just type git clone https://github.com/zoffline/zwift-offline.git or is there something to add to not overwrite the contents of the storage directory?

Thanks for all the help

**Comment by daktak** [comment]
config directory is not touched, just to "git pull" in the directory

**Comment by gnostisus** [comment]
ok
thanks
another successful task

Ride On!
