### ISSUE TITLE
Version 1.1.1 support

### ISSUE THREAD

**Issue by alesito85** [zoffline/zwift-offline#207]
I've installed zwift-offline on my Mac and have followed all the instruction for the first two steps. But when I launch Zwift I get an error code ZLM04 - could not connect to the server.

Is this version not supported yet?

Or can it not be supported anymore because of the encryption thingy?

![image](https://user-images.githubusercontent.com/4399118/210317924-17e39515-cdde-4fd0-b272-149a63f016c6.png)

**Comment by oldnapalm** [comment]
Hi. I noticed you forked from my fork, it has modifications to run with Apache proxy pass (listen on different ports), you should use the main repo instead.
