### ISSUE TITLE
Cannot install zoffline on Windows

### ISSUE THREAD

**Issue by hollysheep** [zoffline/zwift-offline#208]
I can't get zofflie to work on Windows. There are some contradictory statements. On top you are writing

> zoffline must be installed and run on a system before running Zwift

below

> 
If Zwift is not installed, install it before installing zoffline.

I've installed the last version of Zwift, thats 1.1.5 on Windows. But the last release of zoffline is for version 1.0.106405. Does zoffline only work with an older version? The last version for android is 1.0.106405.

When i try to run

`certutil.exe -importpfx Root cert-zwift-com.p12`

this end with an error

`0x8007000d (WIN32: 13 ERROR_INVALID_DATA)`

**Comment by oldnapalm** [comment]
1.1.5 is the launcher version and 1.0.106405 is the app version.

When you run the setup (https://cdn.zwift.com/app/ZwiftSetup.exe) it installs only the launcher. When you run the launcher it "updates" the app (actually downloads the game data if it's the first run).

Make sure you download the actual cert-zwift-com.p12 file and not the html view (use the download button, don't right click and "save as" the GitHub page).

**Comment by hollysheep** [comment]
And what is the correct order? First i install zoffline server, then the exe that "installs" the launcher and then i start the launcher to update zwift? I run teh launcher when zoffline isn't running?

When all updates are downloaded i configure zwift client (step 2), i stop the client, start zoffline, then i start zwift client and hope the best?

**Comment by oldnapalm** [comment]
1) You need to have Zwift installed and working with the official server (don't need to login, just let it update if it's the first time you are running Zwift).

2) With Zwift closed, do the step 2 (or run configure_client script from zoffline_helper).

3) Run zoffline, then run Zwift.

Make sure Zwift is fully closed (right click the Zwift system tray icon and exit) when switching between online and zoffline servers (https://github.com/zoffline/zwift-offline#enablingdisabling-zoffline).

**Comment by hollysheep** [comment]
OK i got it to work on windows 10 with running the client on the same machine as the server. But i can't download the profile. When i run "get_profile.exe" i enter the email and teh password and then i have this error. I tried this several times:

```
HTTP Request failed: HTTPSConnectionPool(host='secure.zwift.com', port=443): Max retries exceeded with url: /auth/realms/zwift/tokens/access/codes (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000029349842140>: Failed to establish a new connection: [WinError 10061] Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte'))
Traceback (most recent call last):
  File "get_profile.py", line 212, in <module>
  File "get_profile.py", line 199, in main
  File "get_profile.py", line 152, in login
TypeError: cannot unpack non-iterable NoneType object
[2888] Failed to execute script 'get_profile' due to unhandled exception!
```

This also works with a zwift client on my smartphone and with a zoffline server on ubuntu. As i started zwift on smartphone with windows server i had to enter my email and password. after that there where no other zwifters - of course because its offline. Then i tried the ubuntu server and now the "username" is something like "z offline" and i see other zwifters. Not as much as normal, but there are others using zwift when i use the offline server. Is this normal?

**Comment by oldnapalm** [comment]
To use get_profile you need to comment out the line in hosts file (it needs to connect to the official server, not zoffline).

The Android client requires login. If you didn't enable multiplayer (step 6) any login and password will work.

The other zwifters you see on the Ubuntu server (if it's your server and not someone else's with other riders) must be the pace partners. If you want to add them in the Windows server (considering you are using the exe release) you need to download the source package and extract the folder pace_partners to the same folder zoffline exe is in. You can also have other bot riders enabling ghosts and bots, see #56.

**Comment by hollysheep** [comment]
OK, i think all is working. At the Moment i'm ill i will test zwift in a few days.

It also works in a raspberry pi. Server start needs some moments but its running.

**Comment by advanceduser1** [comment]
hi. i cant install and run zoffline from source code. Zwift version 1.0.107174. 

"If your Zwift version is newer than 1.0.106405 and zoffline is not running from source: wait for zoffline to be updated."

I understand that I answered my own question ?

**Comment by oldnapalm** [comment]
Yes. Unfortunately I won't be able to update zoffline soon.

You can try this (untested, build by GitHub workflow) https://github.com/oldnapalm/zwift-offline/releases/tag/nightly-build

For the new features (new map, holo replay for routes) it will require a proper update, I will do it after February 8 if nobody does it first.
