### ISSUE TITLE
Disable Zwift Updates at Start

### ISSUE THREAD

**Issue by hollysheep** [zoffline/zwift-offline#217]
At the moment i use Zwift on my normal tablet but i plan to buy an old cheap tablet to only us it on my indoor bike. The update process is annoying when i want to do a spontaneous ride. It also can by that older tablets will not supported from newer versions of zwift. For that i want to disable updates completely. I know the app i've installed using google play is only the launcher. Is there any way to prevent the launcher app from updating zwift? blocking URLs in /etc/hosts?

**Comment by oldnapalm** [comment]
Maybe disable auto update in play store

https://techtrickz.com/how-to/disable-auto-update-of-particular-apps-on-android-device/

**Comment by hollysheep** [comment]
As i understand zwift this only disables updating of the launcher app. The zwift updates are downloaded by the launcher app.

**Comment by oldnapalm** [comment]
I think on Android it's different, the app is updated, then the game assets are downloaded (when you need to run the patcher app if device is not rooted). If you prevent the app from updating, it won't download the new assets.

**Comment by daktak** [comment]
Running the client with wine on linux, I kill the zwiftlauncher with a script as soon as possible this the game will not update, but the client will still launch

https://gist.github.com/daktak/937a3db8843623d4a86eb547864fc701

**Comment by ursoft** [comment]
You cannot dasable updates with retail zwift servers. Only with your own zoffline setup.
