### ISSUE TITLE
Guide about how to update Zwift-Offline to include zwift changes

### ISSUE THREAD

**Issue by lifeunexpected** [zoffline/zwift-offline#218]
Hey is it possible to get a more detailed guide regarding what is needed to upgrade zwift manually if you are not here to upgrade it yourself?

I mean for example regarding they added a new map and courses, where do you get the distances originally to where to add them.
And how to add them properly inside the 

https://github.com/zoffline/zwift-offline/pull/213
This pull request mentions that "Still need to update variants.txt and game_info.txt" so how can someone else know where these files are and how update them correctly? :)

I know its probably a lot of work but was hoping you had some type of documentation or could make some regarding how to upgrade if zwift just made a new version without adding any maps like a minor update.

And a guide regarding how to upgrade if zwift made a major upgrade like adding courses or adding a new map like now.

If this was done maybe more people could easily help out on this project :)

**Comment by ursoft** [comment]
To obtain retail game_info you can use https://github.com/ursoft/zwift-offline/blob/master/storage/game_info_get.py script with your retail Zwift credentials. For variants you should use mitm attack to https protocol.
