### ISSUE TITLE
new zwift mac client has no cacert.pem file

### ISSUE THREAD

**Issue by divfor** [zoffline/zwift-offline#219]
if you upgrade to the newest zwift on macos, you will find there is no below file to append cert-zwift-com.pem:

Using a text editor open ~/Library/Application Support/Zwift/data/cacert.pem
Append the contents of ssl/cert-zwift-com.pem to cacert.pem

so zwift client will not login and always says your password is not correct.

**Comment by oldnapalm** [comment]
See https://github.com/zoffline/zwift-offline/issues/215#issuecomment-1418261259

**Comment by divfor** [comment]
okey, this resolved my issue.
