### ISSUE TITLE
The underlying connection was closed: An unexpected error occurred on a receive

### ISSUE THREAD

**Issue by oldnapalm** [zoffline/zwift-offline#22]
I'm getting this error on first Zwift launch, I believe it started after Windows 1903 feature update.

Looks like it's related to TLS 1.2, I don't know if it was disabled or not present before the update, but if I disable it in internet settings, Zwift launches fine.

Edit: I tried to disable TLS 1.2 from server with
```
import ssl

def run_standalone():
    context = ssl.SSLContext(ssl.PROTOCOL_TLS)
    context.options |= ssl.OP_NO_TLSv1_2
    context.load_cert_chain('%s/ssl/cert-zwift-com.pem' % SCRIPT_DIR, '%s/ssl/key-zwift-com.pem' % SCRIPT_DIR)
    app.run(ssl_context=context,
            port=443,
            threaded=True,
            host='0.0.0.0')
```
and now the error stopped even in the exact same scenario it happened before. Go figure.

**Comment by zoffline** [comment]
Thanks for the update, debugging, and solution. Much appreciated. Evidently, my device is "not ready yet" for the 1903 update so I'll confirm and update when it's upgraded.

**Comment by oldnapalm** [comment]
I mean, the error is gone, even with original zoffline and TLS 1.2 enabled in internet options, no idea what happened. I'm closing the issue for now, will reopen and comment if I find something.
