### ISSUE TITLE
Zwift companion not displaying all rides offline and online

### ISSUE THREAD

**Issue by vinnieismyaccountname** [zoffline/zwift-offline#224]
I have followed the steps exactly, however zwift companion will not display previous zwift rides other then the offline ones.   What method would you recommend to get around this?  Perhaps importing the data?  I am wanting to have all the zwift rides offline and online in ideally one list.  

Probably worth noting the offline progress does not sync up with online

Also activity details could not be loaded in the zwift companion app

**Comment by ursoft** [comment]
ZCA support is very limited now, activity history is not implemented

**Comment by oldnapalm** [comment]
As of https://github.com/zoffline/zwift-offline/commit/87f6eeafe1bbdee59e1c6216e23f93b4d744f71c offline activities will appear in online companion app if you save your credentials in "Settings - Get Zwift profile" in zoffline launcher.

**Comment by oldnapalm** [comment]
Details for offline activities are displayed now (https://github.com/zoffline/zwift-offline/commit/1d66ad75eb73f37fa20c0f48cb4221ab8d47e7de)
