### ISSUE TITLE
intervals.icu is good than strava, can zoffline support it?

### ISSUE THREAD

**Issue by divfor** [zoffline/zwift-offline#226]
https://intervals.icu/
<img width="358" alt="image" src="https://user-images.githubusercontent.com/3319979/220885365-73833192-f0c3-400c-8e28-3d269c65313f.png">

**Comment by divfor** [comment]
my env can use docker container only. It cannot be connected (white window) when I built it from dockerfile. Is there a pre-built docker images I can download?

**Comment by divfor** [comment]
wait a long time the launcher UI shows but losts tab menu:
<img width="443" alt="image" src="https://user-images.githubusercontent.com/3319979/221503036-4cd04ffd-e26d-40c7-9dec-6b5d00926f0a.png">

**Comment by oldnapalm** [comment]
Menu options moved inside "settings".

**Comment by oldnapalm** [comment]
Try if delay is resolved after last commit (https://github.com/oldnapalm/zwift-offline/commit/05747f97434b1eb47d92c6a49e4d3c8d1589c49e).

**Comment by divfor** [comment]
yes. this resolved the two delays. I will retry the uploading in the few days riding trainings.

**Comment by oldnapalm** [comment]
Merged in https://github.com/zoffline/zwift-offline/commit/8e1d7d9fe63f9d18f6db7035be73bf892c1d9577

Maybe workouts download can be added if #199 is resolved.

**Comment by divfor** [comment]
it strange that the delay returns again after I reboot host:
<img width="794" alt="image" src="https://user-images.githubusercontent.com/3319979/222420175-276d6d22-70b6-4c4b-b07c-fb0ec4aacfac.png">

**Comment by oldnapalm** [comment]
If it's only when you launch zoffline, it's normal because it will try to reach Google public DNS (which I suppose is not available in your region).

It should not take longer than 5 seconds
```
The resolution lifetime expired after 5.005 seconds: Server 8.8.8.8 UDP port 53 answered The DNS operation timed out.
INFO:zoffline:Server is running.
```

If it fails, it won't try again until the next reboot.

**Comment by divfor** [comment]
it spends more than 5 minutes.. I have no issue to reach 8.8.8.8 as the docker host redirect all dns requests to dnsmasq -> 8.8.8.8 via a vpn tunnel. inside the container, it show python is requesting huge memory:
<img width="582" alt="image" src="https://user-images.githubusercontent.com/3319979/222443344-41f748e0-8394-4c10-aea7-96a3d6d26abf.png">

**Comment by divfor** [comment]
when it is ready, the memory reduces as following:
<img width="572" alt="image" src="https://user-images.githubusercontent.com/3319979/222444141-e5b9c964-5ba0-4def-9543-a152d0505361.png">

**Comment by oldnapalm** [comment]
I have no idea what could be causing this huge delay. It might be a local issue in your setup because you had this delay opening the launcher and it was fixed when we changed to an initial try, meaning zoffline was trying to resolve external hostnames when the client was opening the launcher, which should not happen unless the client needs updating (in normal use with up to date client, only files from zoffline repo are requested by the launcher).

Removing lines 89-104 should fix the initial delay
https://github.com/zoffline/zwift-offline/blob/7ce3768c8b7c3551f21fc2c079b9b672bbbee0df/standalone.py#L89

**Comment by divfor** [comment]
I meam the delay is not due to DNS. DNS response is very quick when nslookup any domain from inside the container:
```bash
/usr/src/app # time nslookup www.google.com
Server:		127.0.0.11
Address:	127.0.0.11:53

Non-authoritative answer:
Name:	www.google.com
Address: 142.250.191.68

Non-authoritative answer:
Name:	www.google.com
Address: 2607:f8b0:4005:810::2004

real	0m 0.00s
user	0m 0.00s
sys	0m 0.00s
/usr/src/app # time nslookup www.go.com
Server:		127.0.0.11
Address:	127.0.0.11:53

Non-authoritative answer:
Name:	www.go.com
Address: 34.216.127.34
Name:	www.go.com
Address: 54.70.181.249
Name:	www.go.com
Address: 54.244.12.90

Non-authoritative answer:

real	0m 0.00s
user	0m 0.00s
sys	0m 0.00s
/usr/src/app # time nslookup www.twritter.com
Server:		127.0.0.11
Address:	127.0.0.11:53

Non-authoritative answer:

Non-authoritative answer:
Name:	www.twritter.com
Address: 134.119.176.30

real	0m 0.33s
user	0m 0.00s
sys	0m 0.00s
/usr/src/app # time nslookup www.zwift.com
Server:		127.0.0.11
Address:	127.0.0.11:53

Non-authoritative answer:
www.zwift.com	canonical name = zwift.com

Name:	www.zwift.com
Address: 10.50.0.1

real	0m 0.00s
user	0m 0.00s
sys	0m 0.00s
/usr/src/app # time nslookup www.strava.com
Server:		127.0.0.11
Address:	127.0.0.11:53

Non-authoritative answer:
www.strava.com	canonical name = d3u3hkafyj3iak.cloudfront.net
Name:	d3u3hkafyj3iak.cloudfront.net
Address: 2600:9000:221a:8800:1f:5eea:9700:93a1
Name:	d3u3hkafyj3iak.cloudfront.net
Address: 2600:9000:221a:e200:1f:5eea:9700:93a1
Name:	d3u3hkafyj3iak.cloudfront.net
Address: 2600:9000:221a:e600:1f:5eea:9700:93a1
Name:	d3u3hkafyj3iak.cloudfront.net
Address: 2600:9000:221a:e400:1f:5eea:9700:93a1
Name:	d3u3hkafyj3iak.cloudfront.net
Address: 2600:9000:221a:a00:1f:5eea:9700:93a1
Name:	d3u3hkafyj3iak.cloudfront.net
Address: 2600:9000:221a:2800:1f:5eea:9700:93a1
Name:	d3u3hkafyj3iak.cloudfront.net
Address: 2600:9000:221a:fe00:1f:5eea:9700:93a1
Name:	d3u3hkafyj3iak.cloudfront.net
Address: 2600:9000:221a:e800:1f:5eea:9700:93a1

Non-authoritative answer:
www.strava.com	canonical name = d3u3hkafyj3iak.cloudfront.net
Name:	d3u3hkafyj3iak.cloudfront.net
Address: 18.65.185.98
Name:	d3u3hkafyj3iak.cloudfront.net
Address: 18.65.185.127
Name:	d3u3hkafyj3iak.cloudfront.net
Address: 18.65.185.108
Name:	d3u3hkafyj3iak.cloudfront.net
Address: 18.65.185.39

real	0m 0.00s
user	0m 0.00s
sys	0m 0.00s
/usr/src/app # time nslookup www.garmin.com
Server:		127.0.0.11
Address:	127.0.0.11:53

Non-authoritative answer:
www.garmin.com	canonical name = www.garmin.com.cdn.cloudflare.net
Name:	www.garmin.com.cdn.cloudflare.net
Address: 104.16.220.96
Name:	www.garmin.com.cdn.cloudflare.net
Address: 104.17.43.97

** server can't find www.garmin.com: REFUSED

Command exited with non-zero status 1
real	0m 2.50s
user	0m 0.00s
sys	0m 0.00s
```

**Comment by divfor** [comment]
here are the logs of dnsmasq on the host:
Mar  2 15:48:39 dnsmasq[346590]: query[AAAA] www.intervals.icu from 127.0.0.1
Mar  2 15:48:39 dnsmasq[346590]: forwarded www.intervals.icu to 202.106.46.151
Mar  2 15:48:39 dnsmasq[346590]: query[A] www.intervals.icu from 127.0.0.1
Mar  2 15:48:39 dnsmasq[346590]: forwarded www.intervals.icu to 202.106.46.151
Mar  2 15:48:40 dnsmasq[346590]: reply www.intervals.icu is <CNAME>
Mar  2 15:48:40 dnsmasq[346590]: reply intervals.icu is NODATA-IPv6
Mar  2 15:48:41 dnsmasq[346590]: reply www.intervals.icu is <CNAME>
Mar  2 15:48:41 dnsmasq[346590]: reply intervals.icu is 23.88.75.177
Mar  2 15:48:41 dnsmasq[346590]: reply intervals.icu is 157.90.183.62
Mar  2 15:48:41 dnsmasq[346590]: reply intervals.icu is 142.132.253.200

**Comment by oldnapalm** [comment]
Did you try removing the lines 89 to 104 from standalone.py?

Based on your previous reports I believe it's due to DNS resolution using dnspython module.

**Comment by divfor** [comment]
so .. how to set up the dns cdn?

**Comment by divfor** [comment]
looks like I need to allow some domains of zwift to public internet.
```bash
root@labnuc:/opt/zwift# cat /etc/dnsmasq.d/hosts
#address=/zwift.com/10.50.0.1
address=/us-or-rly101.zwift.com/10.50.0.1
address=/secure.zwift.com/10.50.0.1
#address=/cdn.zwift.coma/10.50.0.1
address=/launcher.zwift.com/10.50.0.1
```

```bash
Mar  2 16:08:08 dnsmasq[446522]: query[A] cdn.zwift.com from 10.50.0.2
Mar  2 16:08:08 dnsmasq[446522]: forwarded cdn.zwift.com to 202.106.46.151
Mar  2 16:08:08 dnsmasq[446522]: reply cdn.zwift.com is 18.65.202.21
Mar  2 16:08:08 dnsmasq[446522]: reply cdn.zwift.com is 18.65.202.7
Mar  2 16:08:08 dnsmasq[446522]: reply cdn.zwift.com is 18.65.202.51
Mar  2 16:08:08 dnsmasq[446522]: reply cdn.zwift.com is 18.65.202.57
Mar  2 16:08:08 dnsmasq[446522]: query[A] us-or-rly101.zwift.com from 10.50.0.2
Mar  2 16:08:08 dnsmasq[446522]: config us-or-rly101.zwift.com is 10.50.0.1
Mar  2 16:08:09 dnsmasq[446522]: query[A] launcher.zwift.com from 10.50.0.2
Mar  2 16:08:09 dnsmasq[446522]: config launcher.zwift.com is 10.50.0.1
Mar  2 16:08:22 dnsmasq[446522]: query[A] intervals.icu from 10.50.0.2
Mar  2 16:08:22 dnsmasq[446522]: forwarded intervals.icu to 202.106.46.151
Mar  2 16:08:22 dnsmasq[446522]: reply intervals.icu is 23.88.75.177
Mar  2 16:08:22 dnsmasq[446522]: reply intervals.icu is 142.132.253.200
Mar  2 16:08:22 dnsmasq[446522]: reply intervals.icu is 157.90.183.62
Mar  2 16:08:30 dnsmasq[446522]: query[A] beacons.gvt2.com from 10.50.0.2
Mar  2 16:08:30 dnsmasq[446522]: forwarded beacons.gvt2.com to 202.106.46.151
Mar  2 16:08:30 dnsmasq[446522]: reply beacons.gvt2.com is 114.250.63.34
```

**Comment by oldnapalm** [comment]
I don't have experience with dnsmasq setup, but this looks odd

```
Mar  2 16:01:14 dnsmasq[346590]: query[type=65] cdn.zwift.com from 10.50.0.2
Mar  2 16:01:14 dnsmasq[346590]: forwarded cdn.zwift.com to 202.106.195.68
Mar  2 16:01:14 dnsmasq[346590]: reply cdn.zwift.com is NODATA
```

For what I understand, when your dnsmasq clients query cdn.zwift.com (as well as other subdomains) it should be always resolved to the zoffline IP (10.50.0.1) and not forwarded when query type is 65.

**Comment by oldnapalm** [comment]
> ```shell
> #address=/cdn.zwift.coma/10.50.0.1
> ```

Is this a typo (.coma)?

**Comment by divfor** [comment]
> I don't have experience with dnsmasq setup, but this looks odd
> 
> ```
> Mar  2 16:01:14 dnsmasq[346590]: query[type=65] cdn.zwift.com from 10.50.0.2
> Mar  2 16:01:14 dnsmasq[346590]: forwarded cdn.zwift.com to 202.106.195.68
> Mar  2 16:01:14 dnsmasq[346590]: reply cdn.zwift.com is NODATA
> ```
> 
> For what I understand, when your dnsmasq clients query cdn.zwift.com (as well as other subdomains) it should be always resolved to the zoffline IP (10.50.0.1) and not forwarded when query type is 65.

this is dnsmasq's orignal setting that will resolve any *.zwift.com to 10.50.0.1 (the host):
<img width="306" alt="image" src="https://user-images.githubusercontent.com/3319979/222485834-7c0914e4-2cf7-4fd6-b62e-2fc2d7b48cba.png">

**Comment by divfor** [comment]
> > ```shell
> > #address=/cdn.zwift.coma/10.50.0.1
> > ```
> 
> Is this a typo (.coma)?

yes it is a typo but it is not used. the first line covered it

**Comment by oldnapalm** [comment]
So, removing the *.zwift.com rule resolves the delay?

cdn.zwift.com is needed for map override and cdn/gameassets files.

**Comment by divfor** [comment]
> So, removing the *.zwift.com rule resolves the delay?
> 
> cdn.zwift.com is needed for map override and cdn/gameassets files.

no. my zwift has to pass same dnsmasq via wireguard. so remove *.zwift.com will lead it to visit official zwift. 
Is there any CDN proxy setting file to skip the code I require to put in storage folder?

**Comment by divfor** [comment]
during the delay, it is keeping querying cdn.zwift.com:
Mar  2 16:28:00 dnsmasq[446636]: config cdn.zwift.com is 10.50.0.1
Mar  2 16:28:00 dnsmasq[446636]: query[A] cdn.zwift.com from 172.18.0.2
Mar  2 16:28:00 dnsmasq[446636]: config cdn.zwift.com is 10.50.0.1
Mar  2 16:28:00 dnsmasq[446636]: query[A] cdn.zwift.com from 172.18.0.2
Mar  2 16:28:00 dnsmasq[446636]: config cdn.zwift.com is 10.50.0.1
Mar  2 16:28:00 dnsmasq[446636]: query[A] cdn.zwift.com from 172.18.0.2
Mar  2 16:28:00 dnsmasq[446636]: config cdn.zwift.com is 10.50.0.1
Mar  2 16:28:00 dnsmasq[446636]: query[A] cdn.zwift.com from 172.18.0.2
Mar  2 16:28:00 dnsmasq[446636]: config cdn.zwift.com is 10.50.0.1
Mar  2 16:28:00 dnsmasq[446636]: query[A] cdn.zwift.com from 172.18.0.2
Mar  2 16:28:00 dnsmasq[446636]: config cdn.zwift.com is 10.50.0.1

**Comment by oldnapalm** [comment]
> Is there any CDN proxy setting file to skip the code I require to put in storage folder?

cdn-proxy.txt file in storage folder makes it skip the dnspython code, but it also enables the proxy of cdn/gameassets files which is not a good idea for you since it will probably cause the same delay when client tries to download the map schedule.

**Comment by divfor** [comment]
looks my zwift client was broken. I will re-install it tomorrow and update you the result.

**Comment by oldnapalm** [comment]
> during the delay, it is keeping querying cdn.zwift.com, looks like it enters into a loop:
> 
> ```shell
> Mar  2 16:28:00 dnsmasq[446636]: config cdn.zwift.com is 10.50.0.1
> Mar  2 16:28:00 dnsmasq[446636]: query[A] cdn.zwift.com from 172.18.0.2
> Mar  2 16:28:00 dnsmasq[446636]: config cdn.zwift.com is 10.50.0.1
> Mar  2 16:28:00 dnsmasq[446636]: query[A] cdn.zwift.com from 172.18.0.2
> Mar  2 16:28:00 dnsmasq[446636]: config cdn.zwift.com is 10.50.0.1
> Mar  2 16:28:00 dnsmasq[446636]: query[A] cdn.zwift.com from 172.18.0.2
> Mar  2 16:28:00 dnsmasq[446636]: config cdn.zwift.com is 10.50.0.1
> Mar  2 16:28:00 dnsmasq[446636]: query[A] cdn.zwift.com from 172.18.0.2
> Mar  2 16:28:00 dnsmasq[446636]: config cdn.zwift.com is 10.50.0.1
> Mar  2 16:28:00 dnsmasq[446636]: query[A] cdn.zwift.com from 172.18.0.2
> Mar  2 16:28:00 dnsmasq[446636]: config cdn.zwift.com is 10.50.0.1
> ```

This makes no sense to me, as you can see the lines 89-104 (which appear to be causing the delay) only try to resolve google.com using 8.8.8.8

**Comment by oldnapalm** [comment]
Instead of removing lines 89-104, try changing line 92 as following and test if the delay persists
`        resolver = dns.resolver.Resolver(configure=False)`

**Comment by divfor** [comment]
> looks my zwift client was broken. I will re-install it tomorrow and update you the result.

the broken client has been fixed as hotfix by Zwift:
cat ZwiftMac_ver_cur.xml
<Zwift version="1.0.108507" sversion="1.33.4 (108507)" gbranch="rc/1.33.4-language-zh-hotfix" gcommit="9a92adcc396f3d48add91916d7936ffaa359d56a" GAME_URL="https://us-or-rly101.zwift.com" manifest="ZwiftMac_1.0.108507_fc8f6630_manifest.xml" manifest_checksum="-1529806891" ver_cur_checksum="1287531553"/>

**Comment by divfor** [comment]
I finally resolve this delay by excluding container's source ip for dnsmasq in iptables rule: 
```bash
*nat
:PREROUTING ACCEPT [18508:1117794]
:INPUT ACCEPT [35304:2106758]
:OUTPUT ACCEPT [18420:1105450]
:POSTROUTING ACCEPT [18433:1106125]
:DOCKER - [0:0]
-A PREROUTING ! -s 172.18.0.2/32 -p udp -m udp --dport 53 -j DNAT --to-destination 127.0.0.1:60053
-A PREROUTING -m addrtype --dst-type LOCAL -j DOCKER
-A OUTPUT -p udp -m udp --dport 53 -m owner ! --uid-owner 113 -j DNAT --to-destination 127.0.0.1:60053
```
