### ISSUE TITLE
Can I customize the name of  bots?

### ISSUE THREAD

**Issue by jricoclq** [zoffline/zwift-offline#229]
Hi,
The game interface displays bots from a few hours or days ago. Can I customize the names and nationalities of these bots ?
It is hoped you will give me guidance.

![933748d2df6796297b311b79406d75c](https://user-images.githubusercontent.com/102775665/229292706-1df58654-ea95-47fc-8eeb-1d1cef365e3b.png)

**Comment by oldnapalm** [comment]
Hi.

You can but it's not a configuration option, you need to edit the source code.

Bot name, country and sex are set here https://github.com/zoffline/zwift-offline/blob/91369062f621e279d497d963c2833c59caec311c/standalone.py#L546

Country code is the [ISO 3166-1 numeric](https://en.wikipedia.org/wiki/ISO_3166-1_numeric) code.

**Comment by jricoclq** [comment]
Thank you very much!

**Comment by jricoclq** [comment]
It's done. Thank you.
![Uploading mmexport1680414555080.png…]()

**Comment by oldnapalm** [comment]
More complete version which loads data from file [bot.txt](https://raw.githubusercontent.com/oldnapalm/zwift-offline/master/bot.txt) and also sets random body type.

```python
def load_bots():
    import json
    with open('%s/bot.txt' % SCRIPT_DIR, encoding='utf-8') as f:
        data = json.load(f)
    i = 1
    for name in os.listdir(STORAGE_DIR):
        path = '%s/%s/ghosts' % (STORAGE_DIR, name)
        if os.path.isdir(path):
            for (root, dirs, files) in os.walk(path):
                for f in files:
                    if f.endswith('.bin'):
                        p = profile_pb2.PlayerProfile()
                        p.CopyFrom(zo.random_profile(p))
                        p.id = i + 1000000
                        global_bots[p.id] = PacePartnerVariables()
                        bot = global_bots[p.id]
                        bot.route = udp_node_msgs_pb2.Ghost()
                        with open(os.path.join(root, f), 'rb') as fd:
                            bot.route.ParseFromString(fd.read())
                        bot.position = random.randrange(len(bot.route.states))
                        p.last_name = random.choice(data['last_names'])
                        p.body_type = random.choice(data['body_types'])
                        p.is_male = bool(random.getrandbits(1))
                        if p.is_male: p.first_name = random.choice(data['first_names_male'])
                        else:
                            p.first_name = random.choice(data['first_names_female'])
                            p.body_type += 1
                        p.country_code = random.choice(data['country_codes'])
                        bot.profile = p
                        i += 1
```

**Comment by jricoclq** [comment]
thank you so very much! all done.

**Comment by jricoclq** [comment]
![微信图片_20230402212453](https://user-images.githubusercontent.com/102775665/229355776-693ffc81-270b-469f-8d28-ecf29ca0f7bb.png)
