### ISSUE TITLE
Error after Update to Zwift 1.0.38296

### ISSUE THREAD

**Issue by stapa** [zoffline/zwift-offline#23]
I had installed zwift-offline already on my Windows 10. Version from May 28, 2019 worked fine, but with the current version I got the following error:
```
 * Serving Flask app "zwift_offline" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on https://0.0.0.0:443/ (Press CTRL+C to quit)
[2019-08-24 09:19:27,619] ERROR in app: Exception on /api/auth [GET]
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\flask\app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python27\lib\site-packages\flask\app.py", line 1827, in full_dispatch_request
    self.try_trigger_before_first_request_functions()
  File "C:\Python27\lib\site-packages\flask\app.py", line 1874, in try_trigger_before_first_request_functions
    func()
  File "C:\Python27\zwift-offline-master\zwift_offline.py", line 551, in init_database
    cur_version = cur.execute('SELECT version FROM version')
OperationalError: no such table: version
127.0.0.1 - - [24/Aug/2019 09:19:27] "GET /api/auth HTTP/1.1" 500 -
```

I tried reinstall Zwift, but the error still persist.

**Comment by zoffline** [comment]
It appears your db is somehow missing the version table (which should be impossible, heh). Try removing/moving zwift-offline.db from your storage directory. This will remove all of your old segment results and such though. I can give more detailed instructions to save those if removing/moving that file fixes things and you still want to save your old segments, etc.

**Comment by stapa** [comment]
It looks like a write privilege issue. The server created just an empty db file. I ran initialize_db.sql manually in the DB Browser for SQLite. So update is done, but I lost all my progress in the game (level, distance, avatar settings, ...). I tought all of these is in the Documents\Zwift folder so i backed up just this folder and deleted old zwift-offline-master folder. Do you know what should I edit on the server side according to my Documents\Zwift backup?

**Comment by oldnapalm** [comment]
The game progress is stored in profile.bin

**Comment by zoffline** [comment]
As oldnapalm said your level, distance, etc. is stored in profile.bin within the zoffline storage directory. Segment results, activities, etc. are stored in zwift-offline.db within that same directory. Unfortunately all progress state is stored server side. The only way to recover your progress is if you have a back up of your deleted old zwift-offline-master folder and copy it's storage directory to your new zwift-offline-master.

**Comment by stapa** [comment]
OK, it's time to start a new game. Thank you for your time.
