### ISSUE TITLE
Different schedules!

### ISSUE THREAD

**Issue by jricoclq** [zoffline/zwift-offline#230]
Hi!
I found a bug in version 1.0.109384. Can you fix it? Please see the picture.
![1680740845616](https://user-images.githubusercontent.com/102775665/230243075-6abe1a47-f1ef-4735-a838-4daf96b5933a.jpg)

**Comment by oldnapalm** [comment]
Hello.

Looks like Yorkshire (which will always pair with London) and New York (pairs with Makuri Islands) should no longer be in the schedule.

Fixed in https://github.com/zoffline/zwift-offline/commit/3622f650e4d2901d0bd558985cecbf2c3f0f7237

**Comment by jricoclq** [comment]
thanks, i close it.
