### ISSUE TITLE
the RIDE TYPE list no longer shows the dates

### ISSUE THREAD

**Issue by jricoclq** [zoffline/zwift-offline#234]
Hello, it's me again!
I found during the riding training course that since the new version update, the RIDE TYPE list no longer shows the dates that have been ridden. As shown in the picture, on April 14th and 16th, I rode two training courses, 0120 and 0121, respectively. The previous page schedule shows the records, but RIDE TYPE does not show them. Please correct it. TKS!
![无标题](https://user-images.githubusercontent.com/102775665/232526203-ba3dc02d-ab14-4289-84b2-0d926f0687a5.png)

**Comment by jricoclq** [comment]
It's 0120 and 0121 ,sorry

**Comment by oldnapalm** [comment]
Hi. This started after the 1.34 (109673) update?

It doesn't look like a zoffline issue. If the summary appears in the schedule it means the client received the activity data.

Open your zwift-offline.db with https://sqlitebrowser.org/ and check if the activities in question contain the workoutHash and progressPercentage

![2023-04-17 12_52_44-DB Browser for SQLite - C__Users_Cassio_Documents_GitHub_zoffline_zwift-offline_](https://user-images.githubusercontent.com/38410858/232543298-21439e96-bf4b-421c-8c9b-c288fb740e88.png)

**Comment by oldnapalm** [comment]
You can try removing `AND date > date('now', '-1 month')` (or change to `AND date(date) > date('now', '-1 month')`) in this line https://github.com/zoffline/zwift-offline/blob/0ffa14fb501c239fe00678dcdbf8857707ff4953/zwift_offline.py#L1843

I think it's the only change in zoffline which could affect that.

**Comment by oldnapalm** [comment]
Actually this information doesn't come from the DB, so the previous suggestions won't help. The data is (was) stored in the user profile and my guess is that as of version 1.34 it's stored somewhere else.

**Comment by oldnapalm** [comment]
Hi. This started after the 1.34 (109673) update?

Looks like this information is (was) stored in the user profile and my guess is that as of version 1.34 it's stored somewhere else.

I will wait for the next update because it can be a Zwift bug (wouldn't be the first time... https://forums.zwift.com/t/lost-training-plan-progress-nov-2022-1-31/593268).

**Comment by jricoclq** [comment]
Yes, it happened since the 109673 upgrade.
Well, thank you very much.
I have a training course today. I will ride it again and give you feedback.

**Comment by oldnapalm** [comment]
Does it happen with all workouts or only with custom ones?

Just a wild guess, you can try changing variants.txt like this

![2023-04-18 07_52_43-Window](https://user-images.githubusercontent.com/38410858/232756612-61ebd046-c403-4b53-bf12-2d8d27a62aec.png)

**Comment by jricoclq** [comment]
Hello, I'm sorry, it was a bit late riding due to a delay.
Now that I have finished riding, the issues still exist.
I just saw your reply and there is currently no time for cycling today.
This is happening in custom workout training. I haven't tried any other training courses. I will modify the file first and reply to you early tomorrow. thank you。
![微信图片_20230418193101](https://user-images.githubusercontent.com/102775665/232765450-f79b50e7-f36d-4b50-912f-f739bbf19c39.png)

**Comment by jricoclq** [comment]
Hello, after updating zoffline today, I just finished riding a training course and there is still no date record in the custom workflows.

**Comment by oldnapalm** [comment]
Hi, nothing has changed regarding this issue, recent updates only address route badges in the companion app.

**Comment by oldnapalm** [comment]
I tested with the official server and it doesn't show the date too.

A record containing the workout hash and a float value was saved to my profile, but not a record with (workout hash + 1) and the timestamp, like the past activities.

If I add the timestamp record manually, the date appears.

![2023_04_19_14_31_46_Zwift](https://user-images.githubusercontent.com/38410858/233156734-ff85f2be-fdb4-400e-a374-a7f6f28850c2.png)

So my guess is that it's either a Zwift bug, or they are intentionally not adding the timestamp.

If you can confirm that the date also doesn't appear with the official server you can report the bug in the Zwift forum.

**Comment by jricoclq** [comment]
Okay, I understand. I'll try the official server cycling course. If the problem is like this, I'll report it to the Zwift forum. Thank you very much, I'll close this issue now

**Comment by oldnapalm** [comment]
https://forums.zwift.com/t/workout-last-completed-date-stamp-not-appearing-april-2023/606076
