### ISSUE TITLE
what’ｓ the password of cacert.pem

### ISSUE THREAD

**Issue by lianyanjiajia** [zoffline/zwift-offline#235]
when I want to edit this file by mixporler.It need a password.How can I edit it? I have the root permission

**Comment by oldnapalm** [comment]
There is no password, it's a text file, you should be able to edit with any text editor if you have write permission.

If you are talking about a rooted Android device, try following the instructions in https://github.com/zoffline/zwift-offline#step-2-configure-zwift-client-to-use-zoffline

**Comment by lianyanjiajia** [comment]
> 

thank you very mush.It likes the problem of the mixplorer.I can edit it with another text editor.
