### ISSUE TITLE
Can robots be used in Fondo mode

### ISSUE THREAD

**Issue by xiaolei-neu** [zoffline/zwift-offline#240]
Can robots be used in Fondo mode，I found only free mode can use bots.

**Comment by oldnapalm** [comment]
What is "Fondo mode"?

**Comment by xiaolei-neu** [comment]
![图片](https://user-images.githubusercontent.com/90369593/236727537-c5dd8236-b8ab-43f0-a9d4-ac55ed141baf.png)
just like these

**Comment by oldnapalm** [comment]
If you mean ghosts in events, it should work, but you need to select the same category (A, B, C or D) as the ride when the ghost was saved, because each category start in a different place (road ID) and only ghosts starting on the same road are loaded.

**Comment by xiaolei-neu** [comment]
what do you mean by ghosts? my passed ride or bots, I hope some bots can play with me.

**Comment by oldnapalm** [comment]
Yes, ghosts are your previous rides. Bots are the same as ghosts, the difference is that ghosts start riding with you and bots stay riding all the time. See https://github.com/zoffline/zwift-offline/wiki/Ghosts-and-bots for details.

**Comment by xiaolei-neu** [comment]
> Yes, ghosts are your previous rides. Bots are the same as ghosts, the difference is that ghosts start riding with you and bots stay riding all the time. See https://github.com/zoffline/zwift-offline/wiki/Ghosts-and-bots for details.

I've read this link, but I still don't quite get it，I noticed that there is also a pace_partners setting, but after entering the game, only one partner can be selected, so I have two questions now, first, can this partner only choose one? second, since the event can be online for other real people to register and join, is it possible to use robots to participate instead of just using ghosts？

**Comment by oldnapalm** [comment]
Regarding pace partners, if you are using the Windows release (executable) of zoffline, you need to copy the pace_partners folder from the source package to the same folder zoffline is in.

About your second question, when you are using zoffline, you don't connect to the official Zwift server, the events are fake, their only purpose is to allow you to join event-only routes. There's no such thing as ride with robots or real-time ranking. Ghosts and bots in zoffline are based on your previous rides.

**Comment by xiaolei-neu** [comment]
1,That's what I'm doing now, but can only choose one partner
2,I probably understand this principle, I just want to say whether there is such a possibility, because zwift-offline supports multiplayer, other real players can register to the offline server, and join the game to ride together, so I am wondering if it is possible to simulate this through the protocol players, to achieve riding and ranking with the robot

**Comment by xiaolei-neu** [comment]
> Regarding pace partners, if you are using the Windows release (executable) of zoffline, you need to copy the pace_partners folder from the source package to the same folder zoffline is in.
> 
> About your second question, when you are using zoffline, you don't connect to the official Zwift server, the events are fake, their only purpose is to allow you to join event-only routes. There's no such thing as ride with robots or real-time ranking. Ghosts and bots in zoffline are based on your previous rides.

1,That's what I'm doing now, but can only choose one partner
2,I probably understand this principle, I just want to say whether there is such a possibility, because zwift-offline supports multiplayer, other real players can register to the offline server, and join the game to ride together, so I am wondering if it is possible to simulate this through the protocol players, to achieve riding and ranking with the robot

**Comment by oldnapalm** [comment]
1. If you copied the folder with all sub-folders, you should have 52 pace partners (48 for cycling and 4 for running), click and drag to the left to see more
![2023_05_09_00_27_20_Window](https://user-images.githubusercontent.com/38410858/236986783-464d56d9-3ff0-41a4-ab7a-5d7131a6bfbe.png)
2. Yes, that's exactly how ghosts and bots work, zoffline gets the data from previous rides and sends to you like if they were other real people connected to the server. It's possible to implement what you say, but it's not implemented. For now what you can do is download the bots package from the link and optionally set a multiplier in the file enable_bots.txt, but they will be just random riders, they will not be participating in an event with you.

**Comment by xiaolei-neu** [comment]
> 1. If you copied the folder with all sub-folders, you should have 52 pace partners (48 for cycling and 4 for running), click and drag to the left to see more
>        ![2023_05_09_00_27_20_Window](https://user-images.githubusercontent.com/38410858/236986783-464d56d9-3ff0-41a4-ab7a-5d7131a6bfbe.png)
> 
>     2. Yes, that's exactly how ghosts and bots work, zoffline gets the data from previous rides and sends to you like if they were other real people connected to the server. It's possible to implement what you say, but it's not implemented. For now what you can do is download the bots package from the link and optionally set a multiplier in the file enable_bots.txt, but they will be just random riders, they will not be participating in an event with you.

I think I figured it out, thanks for your reply.this issue can be closed.
