### ISSUE TITLE
[Companion App]  "#1 HOST CHANGER - BEST FOR GAMING no supported on Android 13

### ISSUE THREAD

**Issue by paccW** [zoffline/zwift-offline#241]
Hi, Im using MIUI 14.0.2.0 and Android 13 and I cant install the HOST CHANGER App needed to run the Companion App because the Android version is not supported. Is there another way to change the host on Android?

**Comment by oldnapalm** [comment]
https://play.google.com/store/apps/details?id=com.gamingvpn works on Android 13.

There's also the fake DNS alternative described in the readme.
