### ISSUE TITLE
Assitance for Mac

### ISSUE THREAD

**Issue by OriolMaso** [zoffline/zwift-offline#242]
Hi team,

First of all, thanks a lot to facilitate this tool for all cyclist out there! 

But unfortunately, I have not been able to installed in my Mac, it is way too much complicated to me. My skills are very low to be honest, and for Mac I read it's much more complicated than for Windows. I'm sure that the majority of users can follow the instructions with no issue, but are written in a way that assumes a lot of knowledge from the reader, which unfortunately is not my case. 

Therefore, may I ask you if is there someone who has a screen record video or screenshots steps on how to install this on Mac, so the dummies can follow it?

Thanks you very much in advance from Barcelona!
Oriol

**Comment by jricoclq** [comment]
https://www.bilibili.com/video/BV1DL411o7vw/

**Comment by OriolMaso** [comment]
Thanks a lot @jricoclq for your quick response!

I followed all the process described in the video as I could (in Chinese typo), but unfortunately just in the last step I receive an error:

<img width="583" alt="Error in last step - Zoffline on Mac" src="https://github.com/zoffline/zwift-offline/assets/104131998/9ccaef9a-75a7-4a02-a23d-cda5788abe12">

According to the video, the response should be "Server is running", but instead I got this "No module named 'fitdecode'

I assuming that:

- I made a mistake in the process. 
- Zwift is keeping updating and the current zoffline package available for Mac is not valid anymore. 

Any further thoughts on this case? It would be much appreciatted. 

Thanks a lot again for your help! 
Oriol

**Comment by oldnapalm** [comment]
The video seem to have a mistake, the command `pip3 freeze > requirements.txt` should not be run. Instead, you should use the file [requirements.txt](https://raw.githubusercontent.com/zoffline/zwift-offline/master/requirements.txt) from this repo when running `pip3 install -r requirements.txt` then the other pip3 install commands are not necessary.

**Comment by jricoclq** [comment]
> 

Run pip3 install fitdecode ` in terminal.

When updating the zwift version, the first step is to delete the directional data in the hosts, perform a zwift update, then add the directional data back, download the latest zoffline, and overwrite it. This is all you need to do.

**Comment by jricoclq** [comment]
> The video seem to have a mistake, the command `pip3 freeze > requirements.txt` should not be run. Instead, you should use the file [requirements.txt](https://raw.githubusercontent.com/zoffline/zwift-offline/master/requirements.txt) from this repo when running `pip3 install -r requirements.txt` then the other pip3 install commands are not necessary.

That's because versions may cause files to become unusable, so I came up with an alternative method in case they cannot be used on other versions of MACOS, so I added this command.

**Comment by jricoclq** [comment]
> Run `pip3 install fitdecode` in terminal.
> 
> When updating the zwift version, the first step is to delete the directional data in the hosts, perform a zwift update, then add the directional data back, download the latest zoffline, and overwrite it. This is all you need to do.

Run pip3 install fitdecode in terminal.

When updating the zwift version, the first step is to delete the directional data in the hosts, perform a zwift update, then add the directional data back, download the latest zoffline, and overwrite it. This is all you need to do.

**Comment by OriolMaso** [comment]
Thanks again @oldnapalm and @jricoclq for your answers. 

In terms of IT skills, you are running and I'm starting to crawling, so it's hard for me to understand how to apply all your commands and suggestions. 

- 1: Delete the direction data in the host - No idea how and where to do that. 
- 2: Then, how to "overwrite it"? 

The only reason I got this far is because the video show me how to reproduce all the process like a mirror, not because I understood all the steps. 

I assume that you have plenty of more important things that help this dummy stranger to crack this puzzle :D So thanks a lot again, I will try my best on this!

**Comment by oldnapalm** [comment]
> That's because versions may cause files to become unusable, so I came up with an alternative method in case they cannot be used on other versions of MACOS, so I added this command.

The command `pip3 freeze > requirements.txt` creates a list of the modules currently installed in your system and the command `pip3 install -r requirements.txt` installs the modules from that list. In other words, running both commands in sequence does nothing at all.

The file requirements.txt provided in the repo contains a list of the required modules to run zoffline, with the versions known to work. Using different versions (even if they are newer) can cause zoffline not to work properly, that's why requirements.txt was introduced, see https://github.com/zoffline/zwift-offline/commit/7fafb50520e10e99b8a473364c80abcdd8d83c95

**Comment by jricoclq** [comment]
> Thanks again @oldnapalm and @jricoclq for your answers.
> 
> In terms of IT skills, you are running and I'm starting to crawling, so it's hard for me to understand how to apply all your commands and suggestions.
> 
> * 1: Delete the direction data in the host - No idea how and where to do that.
> * 2: Then, how to "overwrite it"?
> 
> The only reason I got this far is because the video show me how to reproduce all the process like a mirror, not because I understood all the steps.
> 
> I assume that you have plenty of more important things that help this dummy stranger to crack this puzzle :D So thanks a lot again, I will try my best on this!

![1684411622446](https://github.com/zoffline/zwift-offline/assets/102775665/9558b025-960c-4071-94f4-5aab1c5a7e3a)

**Comment by oldnapalm** [comment]
> * 1: Delete the direction data in the host - No idea how and where to do that.

Delete the line you added in the hosts file (or "comment it out" by adding a # in front of it). This is not necessary if you can reach the Google DNS (8.8.8.8), just updating zoffline is enough.

> * 2: Then, how to "overwrite it"?

Just download the new zoffline version like you did the first time and replace the old one.

**Comment by oldnapalm** [comment]
If it opens the normal Zwift it means the line is not present in the hosts file, or maybe you need to fully close and re-open Zwift, I don't know if it stays in background on Mac, on Windows you need to close the launcher in system tray.

Run `ping launcher.zwift.com` in terminal to test, it should return 127.0.0.1 if the hosts file is modified properly.

About updating zoffline, eventually re-doing some steps from the initial setup can be necessary, but usually just re-downloading the zip is enough.

**Comment by OriolMaso** [comment]
Definitely, I didn't do it properly because it doesn't return 127.0.0.1

So I start the process all over again and new problems are coming up that wasn't there the first time. For example, I can't find the route ~/Library/Application Support/Zwift/...
<img width="831" alt="No Zwift Application Support" src="https://github.com/zoffline/zwift-offline/assets/104131998/e5e1f446-fc6b-4b55-86a2-ebcdfa712b8a">

It was there the first time, I don't know what happen. I restart, reinstall Zwift... still nothing there. 

I'm loosing all hope at this point guys :'(

**Comment by oldnapalm** [comment]
You didn't need to start all over, the problem was in the hosts file.

I didn't watch all the video, but if following the steps resolved it for the first time, it should work again now. If it's a hidden folder you can find it running `open ~/Library/Application\ Support/Zwift` in terminal.

**Comment by OriolMaso** [comment]
Guys, I am surrending. I don't know what I am messing up...

<img width="581" alt="Captura de pantalla 2023-05-18 a las 19 20 07" src="https://github.com/zoffline/zwift-offline/assets/104131998/52afe919-6209-48fe-ba50-8b23e12b15a2">

**Comment by OriolMaso** [comment]
It seems I got it!

Now, of course, another problem: Zoffline is open fine, but just in about 1 second, an alert pops up forcing me to open Zwift without changing the settings. Any advise to get ridd of this alert window?
<img width="581" alt="Captura de pantalla 2023-05-18 a las 19 20 07" src="https://github.com/zoffline/zwift-offline/assets/104131998/4aaff550-e543-41d6-9e98-e519f415d540">

Also, when I disconnect the Wifi, the app opens normally, without the zoffline launch.

**Comment by oldnapalm** [comment]
This is because of the "staggered release" Zwift is using, it should be fixed in a couple days. You can fix it by renaming the file `cdn/gameassets/Zwift_Updates_Root/ZwiftMac_ver_cur.xml` to `ZwiftMac_ver_cur.111622.xml` and doing the same change in the file `variants.txt` under `zwift_launcher_osx_rollout` (you will need to undo these changes in a couple days when Zwift moves to the standard update format).

It's this or you are still on version 1.39, in this case you should use previous zoffline version (before 1.0.111622 update) https://github.com/zoffline/zwift-offline/tree/7705643f64994cc66f70a1249dd82fa595df13da

**Comment by OriolMaso** [comment]
Great. That means that, if I understood correctly, if I stay patient in a couple of days my current configuration should work without changing anything. Is that correct?

Thanks again!

**Comment by oldnapalm** [comment]
If you are already on version 1.40, yes. You will notice a small update when you connect to the official server, then it will work with zoffline without the error.

**Comment by oldnapalm** [comment]
If you used the commands from the video instead of using the file requirements.txt from the repo and the commands didn't contain dnspython, you should run `pip3 install dnspython` then the update should work with zoffline enabled (without removing the line from hosts and with zoffline running).

**Comment by OriolMaso** [comment]
Ok, I runned  pip3 install dnspython, but no chance so far, same result. 

So after a couple of days when Zwift fixed the "staggered release", should I just open Zwift with Zoffline active? Befefore you mention "You will notice a small update when you connect to the official server, then it will work with zoffline without the error."

Is that means that I will need to desactivate zoffline, connect to Zwift normally, exit, and run Zoffline again?

**Comment by oldnapalm** [comment]
> Is that means that I will need to desactivate zoffline, connect to Zwift normally, exit, and run Zoffline again?

Exactly.

If it didn't work after installing dnspython (did you restart zoffline?) then you will need to deactivate zoffline to update from the official server.

**Comment by jricoclq** [comment]
I found the reason why my update operation is so troublesome because I missed the installation of the dnspython dependency.

**Comment by oldnapalm** [comment]
Yes, if you had used the provided requirements.txt as recommended in the instructions it would not be missing.

**Comment by jricoclq** [comment]
> 

Yes, it's like waking up from a dream now. Thank you very much.

**Comment by oldnapalm** [comment]
Also, the easiest way to download zoffline if you are running from source is to "git clone" the repo instead of downloading the zip, then you just need to "git pull" to update. If you don't want to use terminal commands, use https://desktop.github.com/

**Comment by OriolMaso** [comment]
> 

No, I runned dnspython without any other modification.

How can you connect and disconnect zoffline like a switch to access Zwift normally again?

**Comment by OriolMaso** [comment]
> Yes, if you had used the provided requirements.txt as recommended in the instructions it would not be missing.

I followed the instructions in the video. How to use this requirements? Copy pasting the content in the Terminal? I does not react.

Apologies again for my lack of knowledge, is not that obvious to me.

**Comment by OriolMaso** [comment]
Guys, amazing, I think we did it! 

I entered with my account and Strava and select "Just Watch". And by my surprise, there's more people there! As you can see in the image below. 

<img width="1358" alt="Not alone?" src="https://github.com/zoffline/zwift-offline/assets/104131998/6811ca7e-8f66-4459-8778-4857ac1868a4">

Is this correct? Maybe I'm in the normal Zwift and I don't know how to differentiate zoffline.

**Comment by oldnapalm** [comment]
Those are pace partners, they are included in the source. You can add other random bots, see https://github.com/zoffline/zwift-offline/wiki/Ghosts-and-bots#bots

What determines if you will use zoffline or official server is the line in the hosts file.
