### ISSUE TITLE
May I ask where the code for searching for Bluetooth is?

### ISSUE THREAD

**Issue by BCccccccccc** [zoffline/zwift-offline#243]
I would like to learn about the relevant codes for Bluetooth search and matching in the zwift app. Where can I find them.

**Comment by oldnapalm** [comment]
zoffline only does the server functions, sensors pairing is done by the client.

You can try https://github.com/ursoft/ANT_Libraries or https://github.com/ursoft/zwift-offline/tree/master/scripts/ZwiftApp

**Comment by BCccccccccc** [comment]
Thank you very much


im.baichuan
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zoffline/zwift-offline"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月31日(星期三) 晚上8:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题: &nbsp;Re: [zoffline/zwift-offline] 请问搜索蓝牙的代码在哪里？（第 243 期）





 
zoffline 仅执行服务器功能，传感器配对由客户端完成。
 
您可以尝试https://github.com/ursoft/ANT_Libraries或https://github.com/ursoft/zwift-offline/tree/master/scripts/ZwiftApp
 
—
直接回复此邮件，在 GitHub 上查看，或取消订阅。
您收到此消息是因为您创作了该线程。Message ID: ***@***.***&gt;
