### ISSUE TITLE
Zwift is "Unzipping Files" without Internet connection

### ISSUE THREAD

**Issue by hollysheep** [zoffline/zwift-offline#246]
Hi,

i don't use Zwift so offen so every time i started the app on my tablet i hade to wait until the updates are downloaded and installed. Zwift always hangs a long time. So i disabled updates in play store AND blocked the tablet from internet before i started the zwift app. But today i have again the download and unzipping message. What files is zwift installing here when i can't download files? I didn't start the app for weeks. Is zwift running in background and downloading files that are installed when running the app the next time?

**Comment by oldnapalm** [comment]
Unrelated to zoffline.

For more details please refer to https://forums.zwift.com/t/is-zwift-or-zwift-launcher-running-in-background-24-7/611690
