### ISSUE TITLE
Why can't my ZCA connect to Zoffline?

### ISSUE THREAD

**Issue by jricoclq** [zoffline/zwift-offline#249]
Why can't my ZCA connect to Zoffline?
![image](https://github.com/zoffline/zwift-offline/assets/102775665/c6e76a33-083b-4f62-85e9-2cf3b3827fc6)
![59d916b97ad1c3b35eb4f958dde4ca1](https://github.com/zoffline/zwift-offline/assets/102775665/827e1a94-8335-4eec-b901-f806bc7c90cc)
The above is the display of zoffline and phone. I would like to know the reason or help me see how to solve this problem，pls!

**Comment by oldnapalm** [comment]
Did you follow all instructions from [step 7](https://github.com/zoffline/zwift-offline#step-7-optional-install-zwift-companion-app)? Looks like something is missing, you should also see these messages in zoffline log
```
GET /api/auth
POST /auth/realms/zwift/protocol/openid-connect/token
POST /api/push/fcm/production
```

**Comment by jricoclq** [comment]
Yes.i followed

**Comment by oldnapalm** [comment]
Make sure everything is up to date (zoffline 1.0.114012 and ZCA 3.48.0).

Try to clear ZCA data and cache in Android settings (Applications / Companion), you should be prompted to login again (if not using multiplayer, type any login and password).

Just tested and it's working.

**Comment by jricoclq** [comment]
yes,it is up to date , zoffline 1.0.114012 and ZCA 3.48.0.
I have tried all previous versions and they all have the same issue. Zoffline only displays these contents, there is nothing else, and the phone also stays in this screen together.
![image](https://github.com/zoffline/zwift-offline/assets/102775665/1e1a9f3a-13b5-4ca5-9508-93405f0c1134)
After clearing the cache, I opened ZCA, which is the interface that requires login.
![2caf8367d8398b8fca76e074da2172c](https://github.com/zoffline/zwift-offline/assets/102775665/99129f33-4958-4cad-b72e-7e9c3008369a)

**Comment by jricoclq** [comment]
![9fe9ea11be2feb86786a04a6698dcf8](https://github.com/zoffline/zwift-offline/assets/102775665/dc22a0cf-4a92-4c8a-bb91-aade62329b55)
Like this, constantly loading

**Comment by jricoclq** [comment]
Alternatively, could you please provide me with your encapsulated zca patched. apk for download so that I can try and see if it's a problem with the phone.

**Comment by oldnapalm** [comment]
If you are using Gaming VPN to change hosts, make sure you have a line break in hosts.txt, not both in the same line

```
192.168.31.233 us-or-rly101.zwift.com
192.168.31.233 secure.zwift.com
```

https://drive.google.com/drive/folders/1Zvc0Mw6iUsR6xufGLNqurLcKSAtxioMe?usp=share_link

**Comment by jricoclq** [comment]
![image](https://github.com/zoffline/zwift-offline/assets/102775665/bf224810-8b3f-4b6c-838f-346ac9dd2060)
There are two lines in hosts.txt with a line break.

**Comment by oldnapalm** [comment]
Same thing with my patched apk?

**Comment by jricoclq** [comment]
Yes, the same thing.😂

**Comment by oldnapalm** [comment]
Do you have any other VPN app which may be conflicting with Gaming VPN?

I would try uninstalling Gaming VPN, disabling any other VPN and using the fake DNS method.

> Optionally, instead of using the "Host Changer" app, you can create a fake-dns.txt file in the storage directory and set the "DNS 1" of your phone Wi-Fi connection to the IP address of the PC running zoffline

**Comment by jricoclq** [comment]
> Do you have any other VPN app which may be conflicting with Gaming VPN?
> 
> I would try uninstalling Gaming VPN, disabling any other VPN and using the fake DNS method.
> 
> > Optionally, instead of using the "Host Changer" app, you can create a fake-dns.txt file in the storage directory and set the "DNS 1" of your phone Wi-Fi connection to the IP address of the PC running zoffline

I deleted other VPN applications, but it still hasn't worked.
I have also tried the methods listed above, but the same result cannot be connected.
And fake-dns.txt in the storage directory will cause this error.
![6cab0f65ef60fa6e09c2fb818093a1d](https://github.com/zoffline/zwift-offline/assets/102775665/109ef231-7346-421b-bca7-63ef871d2c90)

**Comment by oldnapalm** [comment]
The fake DNS error is because the UDP port 53 is already in use, you would need to stop the service using it. If you don't know which service is, it's probably Internet Connection Sharing (ICS) https://superuser.com/questions/1633432/why-windows-10-has-a-svchost-process-that-listen-on-port-53

Although, I'm not sure it will help. If you already tried to stop other VPN and using only the Gaming VPN app, there's probably something else in your phone preventing the redirection of one of the hosts. Can you reach zoffline through both https://us-or-rly101.zwift.com and https://secure.zwift.com from your phone's browser?

**Comment by daktak** [comment]
You phone is on the same network and can reach the 192 IP?

**Comment by jricoclq** [comment]
> You phone is on the same network and can reach the 192 IP?

It is a routing segment within the local area network。

**Comment by paccW** [comment]
I followed all Steps mentioned in 7), patched the APK and did the hosts but when I open my Companion App it doesnt do anything, it wont connect to Zwift Offline on a ride, its just the normal home screen. My Zwift Offline CMD doesnt say anything

**Comment by oldnapalm** [comment]
> its just the normal home screen. My Zwift Offline CMD doesnt say anything

Looks like the hosts redirection is not working for some reason. You can try the fake DNS method (you may need to set both DNS to the zoffline IP).

This can also happen if you didn't fully close the Companion app after using the official server. You can try to force stop and clear the app cache and data in Android settings (applications).

**Comment by jricoclq** [comment]
> The fake DNS error is because the UDP port 53 is already in use, you would need to stop the service using it. If you don't know which service is, it's probably Internet Connection Sharing (ICS) https://superuser.com/questions/1633432/why-windows-10-has-a-svchost-process-that-listen-on-port-53
> 
> Although, I'm not sure it will help. If you already tried to stop other VPN and using only the Gaming VPN app, there's probably something else in your phone preventing the redirection of one of the hosts. Can you reach zoffline through both https://us-or-rly101.zwift.com and https://secure.zwift.com from your phone's browser?

NO,it can't reach.
![image](https://github.com/zoffline/zwift-offline/assets/102775665/35f4e689-8b24-471b-bb48-33bcd8013ad2)
I use my mobile browser to access https://us-or-rly101.zwift.com And https://secure.zwift.com . These two addresses, zoffline shows this message, and mobile browsing cannot access them. 404 error, it seems that the connection cannot be made due to issues with the mobile phone's certificate.

**Comment by oldnapalm** [comment]
The SSL error is normal because the browser does not trust the zoffline certificate (that's why we need to patch ZCA) but it means your phone is able to reach zoffline through both domains. No idea why ZCA doesn't work. See the updated instructions, the suggested app to modify hosts is now Virtual Hosts, since Gaming VPN is no longer available on Play Store, but I don't think it will make any difference.

**Comment by jricoclq** [comment]
> The SSL error is normal because the browser does not trust the zoffline certificate (that's why we need to patch ZCA) but it means your phone is able to reach zoffline through both domains. No idea why ZCA doesn't work. See the updated instructions, the suggested app to modify hosts is now Virtual Hosts, since Gaming VPN is no longer available on Play Store, but I don't think it will make any difference.


Yes.i have 3 apps to modify hosts, but all of them are unable to work.
May I ask what brand of phone you are using? If my phone doesn't work, I will try changing it or flashing a similar firmware.
And I would like to seek your instant messaging, such as WeChat.

**Comment by oldnapalm** [comment]
I'm using a Samsung Galaxy S20 but it's been confirmed to work with various other brands and models of Android phones.

Try uninstalling all other host changing apps and use only Virtual Hosts. Notice this detail from README, for me it's indispensable

> select the created hosts.txt file, fully close (touch the "overview" button and swipe up) the app and run it again
