### ISSUE TITLE
Strava Token Not Uploading rides

### ISSUE THREAD

**Issue by BigShoots** [zoffline/zwift-offline#25]
First off thanks for your hard work on this.

I've followed the steps to create a strava token file and zoffline will not upload my rides to strava after finishing.

I've even used curl to generate my own API Access token and refresh token and tried using those in the strava_token.txt and it doesn't work either.

Am I doing something wrong? I didn't import my user, I just created a new one when launching. I'm not sure if this would have anything to do with it. 

The only other issue I ran into when installing was importing the SSL cert, it requires a password that was not provided in the instructions. I'm not sure if this would cause issues either.

*EDIT just realized I can add the certs with no password

**Comment by oldnapalm** [comment]
Please check if strava_token.txt is located in the storage folder and contains 5 lines (client_id, client_secret, access_token, refresh_token and expires_at).

Also make sure your activity has at least 5 km, Zwift won't upload activities shorter than that to Strava.

**Comment by BigShoots** [comment]
Ahh that would be why, I haven't been doing full rides, I've just been testing. 

The file is in the storage folder and has the proper 5 lines.

One other issue I notice is that if I create a new profile the save button at the end of the ride doesnt have the strava uploads icon, if I import my previous zwift account then it has the strava icon on the upload button.

**Comment by BigShoots** [comment]
Just tested a 5k ride and it uploaded, but when using my imported previous account it says I only have 25km (20km now) of free trial left, will this clear after a while or should I just use a new offline account?

**Comment by oldnapalm** [comment]
Not sure, I never tried to import an online account.

If you create a new profile, it will upload your rides to Strava, even if there's no icon in the save button.

**Comment by BigShoots** [comment]
Thanks, I'll use an offline account.

**Comment by zoffline** [comment]
"One other issue I notice is that if I create a new profile the save button at the end of the ride doesnt have the strava uploads icon, if I import my previous zwift account then it has the strava icon on the upload button."
They likely added/changed a strava field in profile data. I'll have to look into enabling that icon if strava_token.txt exists. It's purely cosmetic though.

"Just tested a 5k ride and it uploaded to strava, but when using my imported previous zwift account it says I only have 25km (20km now) of free trial left, will this clear after a while or should I just use a new offline account?"
I've not seen this before. Was your imported Zwift account a trial account? If so, that's probably why. In which case it's possible zwift will stop you from riding after 25km. The profile has an account type in it, which can be toggled from a trial user to a normal user, which will presumably fix this, but I don't have code written to do that.

**Comment by BigShoots** [comment]
I had used it for a trial period and used up the 25km, when I imported the account zoffline reset the 25km.

**Comment by BigShoots** [comment]
I think this issue can be closed, but first I thought I would ask why my screenshots don't upload. It shows the screenshot, when I finish my ride, but doesn't upload it to Strava.

**Comment by zoffline** [comment]
Glad things seem to be working. Screenshots seems to be a feature they added that I never noticed. I'll need to obtain network traces of what occurs to implement, but it's very low priority. Will leave ticket open to remind me.

**Comment by zoffline** [comment]
Actually, going to close this and open up a new ticket for screenshots.
