### ISSUE TITLE
I can't create a custom

### ISSUE THREAD

**Issue by Xi-QQir** [zoffline/zwift-offline#250]
I can create a custom training course, but after I restart the software, the training file disappears, I can still find the training file in the Document/Zwift/Workouts/1, and I import the training file into Document/Zwift/Workouts/1, zwift can't read it, what should I do?
(Sorry,my English is not good and I'm not sure if you can understand my expressions, but I need your help

**Comment by Xi-QQir** [comment]
zwift can create files in Documents/Zwift/Workouts/1, but cannot read from them

**Comment by oldnapalm** [comment]
I understood that, but there's nothing I can do without more details, post your log files or look them yourself. I suppose you will find some error regarding the workout file in Documents\Zwift\Logs\Log.txt. Try using only characters A-Z and 0-9 in workout title and description.

**Comment by Xi-QQir** [comment]
Ok thank you
