### ISSUE TITLE
ModuleNotFoundError: No module named 'urllib3'

### ISSUE THREAD

**Issue by OriolMaso** [zoffline/zwift-offline#259]
Hi team,

Trying to get back to my zoffline routine on my Mac. I update Zwift to the latest 121395 version and same for the zoffline zip package. 

But now when I run the activation code "sudo python3 /Users/oriol/Desktop/zwift-offline-master/standalone.py" I found the following error mentioning a module:

Traceback (most recent call last):
  File "/Users/oriol/Desktop/zwift-offline-master/standalone.py", line 15, in <module>
    from urllib3 import PoolManager
ModuleNotFoundError: No module named 'urllib3'

How can I fix this problem? Thank you in advance.
Oriol

**Comment by fatsbrown** [comment]
Did you follow the installation instructions for "Linux, Windows, or macOS (from source)"? If you did and still get error, try running pip3 with sudo (`sudo pip3 install -r requirements.txt`) or use venv
```
cd /Users/oriol/Desktop/zwift-offline-master
python3 -m venv venv
source venv/bin/activate
pip3 install -r requirements.txt
deactivate
```
Then run zoffline with the command `sudo /Users/oriol/Desktop/zwift-offline-master/venv/bin/python3 /Users/oriol/Desktop/zwift-offline-master/standalone.py`

**Comment by OriolMaso** [comment]
Hi,

Thanks for your reply.

Well, I used zoffline in the past months quite a lot, so yes, the installation at least back then was correct. 

Now after using the venv that you shared and running the following command, the error is:

<img width="580" alt="Captura de pantalla 2023-10-14 a las 10 20 37" src="https://github.com/zoffline/zwift-offline/assets/104131998/50b5ab78-5060-42bc-89a4-3c2b717a2e87">

Any idea of what whoud be my next step?

thank you again for your help.
Oriol

**Comment by fatsbrown** [comment]
Update to the latest version of Zwift and zoffline, delete the venv folder and redo the steps, it should work now.

If it still doesn't work it might be an issue with Python 3.12, I'm not sure zoffline has been tested with it yet.

**Comment by fatsbrown** [comment]
Update to the latest version of Zwift and zoffline, delete the venv folder and redo the steps, it should work now.

**Comment by oldnapalm** [comment]
@OriolMaso any luck?

This error was caused by a Werkzeug update, the compatible version was added to requirements.txt in https://github.com/zoffline/zwift-offline/commit/21e8817633d556638c5a508914e2fa6d7fc02876

It should work if you update zoffline and reinstall the requirements as suggested.
