### ISSUE TITLE
Add bots in macos and docker

### ISSUE THREAD

**Issue by serbasan** [zoffline/zwift-offline#260]
Hello.
I have Docker on an external machine and run the version on MacOs. Everything works perfect but I want to add ghosts and bots. I follow what it says here https://github.com/zoffline/zwift-offline/wiki/Ghosts-and-bots#bots but they don't appear. Should they appear on all maps or on a specific one? Where do I place the "pace_partners" folder in Macos?
Thanks for this great project.
<img width="470" alt="Captura de pantalla 2023-10-14 a las 9 53 00" src="https://github.com/zoffline/zwift-offline/assets/21089192/582930b3-6422-42f7-b6ae-08e727c0309a">

**Comment by fatsbrown** [comment]
Hi.

Observe this step of the Docker instructions:

> If you are not running zoffline on the same PC that Zwift is running: create a server-ip.txt file in the </path/to/host/storage> directory containing the IP address of the PC running zoffline.

The pace partners folder is included in the Docker image, they should appear when you do the step above, as well as the bots.

**Comment by serbasan** [comment]
Perfect, that was it. Add server-ip.txt in docker storage. Thank you so much.
