### ISSUE TITLE
Problems on Android

### ISSUE THREAD

**Issue by jyhjson** [zoffline/zwift-offline#263]
When using an Android phone, you need to log in. It always prompts whether the password has been changed. If the password is wrong, you cannot register a new user.

**Comment by fatsbrown** [comment]
Unless something changed in a recent update, if you are running zoffline in single player mode (default) any login and password will work on Android. If you enabled multiplayer you need to signup at `https://<zoffline ip>/signup/` then use this account to login.

**Comment by oldnapalm** [comment]
Duplicate of #236
