### ISSUE TITLE
transfer from pc to another pc

### ISSUE THREAD

**Issue by mesterumanele** [zoffline/zwift-offline#264]
Hello, is not a big issue; 
I'd like to setup on a different pc but i'd like to keep my profile, achievements, if possible. 
I did read a note on the your site to retain the storage folder, but not sure if retain means i can copy to a different install? just as is? or do i have to skip some files/folders? (maybe encryptionkey.bin? stravatoken.txt? garth folder?). Also i did try to move profile.bin and achievements.bin from my old storage to the new storage but still asked me for a new profile. (which is still ok, if not possible)

Thank you!

**Comment by fatsbrown** [comment]
Hi. Just copy the storage folder as is (including all its files and sub folders) and it will work exactly the same in the new PC.
