### ISSUE TITLE
Zwift told me password error

### ISSUE THREAD

**Issue by fzxvvc** [zoffline/zwift-offline#265]
Hi there.I installed zoffline of docker in my NAS and installed zwift on my Mac.I think I did everything correctly except for this step
> `Using a text editor open ~/Library/Application Support/Zwift/data/cacert.pem
Append the contents of the SSL certificate ssl/cert-zwift-com.pem to cacert.pem (only the certificate and not the included private key)`

I don't quite understand what is"only the certificate and not the included private key".
I just copied all the contents of this file `ssl/cert-zwift-com.pem` to `~/Library/Application Support/Zwift/data/cacert.pem`this file.
Now when I open zwift, I can see the Zwift launcher.But after clicking Start, you need to log in.
Can you tell me in detail how to operate this step? Thank you.

**Comment by fatsbrown** [comment]
Hello.

The file ssl/cert-zwift-com.pem contains a private key (lines 1 to 28) and a certificate (lines 29 to 53). You have to copy only the certificate to cacert.pem, not the private key.

**Comment by fzxvvc** [comment]
solved, Thanks a lot!
