### ISSUE TITLE
Zoffline on AppleTV

### ISSUE THREAD

**Issue by fzxvvc** [zoffline/zwift-offline#266]
I'm not sure if it's possible to implement zwift on Apple TV?
My router can change the domain name direction. I tried to point the four domain names in the host file to my zoffline IP, but Apple TV cannot use zwift properly.
Perhaps we can figure out the solution of Apple TV?

**Comment by fatsbrown** [comment]
I believe you need to jailbreak it to be able to append the certificate to cacert.pem and maybe you need to generate a new certificate meeting Apple requirements (https://www.ismoothblog.com/2021/06/generate-trusted-root-certificates-with-openssl.html).

This explains how to modify cacert.pem on iOS (no idea if it works on AppleTV)
https://github.com/v4mp1/zwift-offline/tree/work-dir#client-install

**Comment by oldnapalm** [comment]
> Perhaps we can figure out the solution of Apple TV?

This depends on Apple TV owners to investigate.

Please reopen if you are planning to work on this.
