### ISSUE TITLE
Launch the native Apple Silicon version on MacOS

### ISSUE THREAD

**Issue by PeterBlanz** [zoffline/zwift-offline#269]
On MacOS, launching Zwift via zoffline's launcher seems to still start the old Intel-emulated version. This is evident in the attached screenshots, as the riders/bikes cast simplified shadows. You can also see this in the activity monitor, in the "Kind" column. If you launch Zwift via the on-line launcher, it starts the native Apple Silicon version, which consumes less resources and looks better.

![SimpleShadow1](https://github.com/zoffline/zwift-offline/assets/106299703/0d046f51-dbef-4ab6-8c0d-7e3e5d06f50b)
![SimpleShadow2](https://github.com/zoffline/zwift-offline/assets/106299703/59ad372f-875c-4f2d-810b-976fb317f5ca)
![IntelEmulation](https://github.com/zoffline/zwift-offline/assets/106299703/f5d4d83a-ff5a-4e10-b184-b8c7a01e9e38)

**Comment by oldnapalm** [comment]
I suppose this is happening due to a wrong or missing FeatureResponse. Unfortunately I can't investigate this, the Mac (osx) related features were users contributions.

Try setting zwift_launcher_osx_silicon to true in variants.txt

```
    {
      "name": "zwift_launcher_osx_silicon",
      "value": true,
      "values": {}
    },
```

Also look for "Unknown feature" in zoffline log.

**Comment by oldnapalm** [comment]
If you want to do some further investigation, add this in `experimentation_v1_variant()` after `req.ParseFromString(request.stream.read())` (zwift_offline.py)

```python
    for user_attr in req.user_attrs:
        print(user_attr, req.user_attrs[user_attr])
```

**Comment by PeterBlanz** [comment]
Cool, I'll try these suggestions as soon as I get access to the Mac. (It's not mine, I'm on PC.) Thanks!

**Comment by yingqiangyu** [comment]
> I suppose this is happening due to a wrong or missing FeatureResponse. Unfortunately I can't investigate this, the Mac (osx) related features were users contributions.
> 
> Try setting zwift_launcher_osx_silicon to true in variants.txt
> 
> ```
>     {
>       "name": "zwift_launcher_osx_silicon",
>       "value": true,
>       "values": {}
>     },
> ```
> 
> Also look for "Unknown feature" in zoffline log.

Hi @oldnapalm  It works for me.
Thanks a lot

**Comment by PeterBlanz** [comment]
Yep, works in our system as well. Thanks for the help!
