### ISSUE TITLE
Mac launcher issues

### ISSUE THREAD

**Issue by oldnapalm** [zoffline/zwift-offline#27]
Mac launcher tries to connect to www.google.com and launcher.zwift.com, if you are offline you need to add those to the hosts file too.

It presents this error and even choosing Yes the window stays blank
> Zwift couldn't connect to the update servers and will close. Please check your internet connection and try again. Would you like to try to launch Zwift anyway? Error ZLM01

**Comment by zoffline** [comment]
Requiring www.google.com is very odd (and annoying). I've not used Zwift in a while, but will look into this eventually. Thanks for the report.

**Comment by oldnapalm** [comment]
Current version of Mac launcher does not connect to www.google.com anymore, but now it stops at "GET /api/auth"

> Zwift encountered a communication error. If the problem persists, please contact Zwift Support with the error code ZLM06.

Changing /api/auth route to return `'{"realm":"zwift","launcher":"https://launcher.zwift.com/launcher","url":"https://secure.zwift.com/auth/"}'` (which is currently returned by official server) the client requests "GET /launcher/realms/zwift/protocol/openid-connect/auth?client_id=Game_Launcher&redirect_uri=http%3A%2F%2Fzwift%2F&login=true&response_type=code"

Adding that route to launch_zwift() makes it work again, but if not using autolaunch, map override links in embed-noauto.html do not work

> Failed to load resource: The resource could not be loaded because the App Transport Security policy requires the use of a secure connection.

Also, embed.html is not loaded because now it's requested over https.

Not sure if the /api/auth change affects Windows client, will test it later.

**Comment by zoffline** [comment]
Resolved by you in #41. Thanks!

**Comment by oldnapalm** [comment]
Looks like this is not needed anymore, tested on 10.13 and 10.15

> * Using a text editor (with admin privileges) open ``/Applications/Zwift.app/Contents/Info.plist``
>   * Append these keys:
>     ```
>     <key>NSAppTransportSecurity</key>
>    	<dict>
> 	       <key>NSExceptionDomains</key>
> 	       <dict>
> 	           <key>zwift.com</key>
> 	           <dict>
> 	               <key>NSExceptionAllowsInsecureHTTPLoads</key>
> 	               <true/>
> 	               <key>NSIncludesSubdomains</key>
> 	               <true/>
> 	           </dict>
> 	       </dict>
>    	</dict>
>     ```
> 

Now we have another issue in Mac launcher, the file selection dialog (upload) doesn't open.

**Comment by oldnapalm** [comment]
> Now we have another issue in Mac launcher, the file selection dialog (upload) doesn't open.

Not a big issue since drag and drop works.
