### ISSUE TITLE
Request: Setting gear of Strava activity

### ISSUE THREAD

**Issue by crckd** [zoffline/zwift-offline#273]
Is it possible to set the gear_id on the uploaded Strava activity?

I have tested stravalib and was able to update the gear_id of the activity using the code below.

update = client.update_activity(activity.id, gear_id='b13500722')

Can this be called after uploading the activity to Strava?

**Comment by oldnapalm** [comment]
You can try replacing this line https://github.com/zoffline/zwift-offline/blob/e93b9f0f685c8bc46e1df465872ffd34bccceb5b/zwift_offline.py#L2070
with
```python
        activity_uploader = strava.upload_activity(BytesIO(activity.fit), data_type='fit', name=activity.name)
        activity_uploader.wait()
        strava.update_activity(activity_uploader.activity_id, gear_id='b13500722')
```

You may need to change this line
https://github.com/zoffline/zwift-offline/blob/e93b9f0f685c8bc46e1df465872ffd34bccceb5b/zwift_offline.py#L740
like this
```python
                                  scope=['activity:read', 'activity:write'])
```

**Comment by crckd** [comment]
Thanks! Got it working. (revoke previous strava token and issue new with added scope)

**Comment by daktak** [comment]
Alternatively is to use something like https://www.activityfix.com/ to set the gear when the type is virtual.
