### ISSUE TITLE
just a note

### ISSUE THREAD

**Issue by mesterumanele** [zoffline/zwift-offline#274]
Hi, 
today after i downloaded the last file i just run it on 'just watch' mode.
when i tried to Teleport and join a pacer group, after the 8seconds pedal, the app just closed. if this is normal, please ignore my note. it is not important in watch mode anyway; i didn't try it live, as i don't use this feature anyway... just a note, thanks

**Comment by oldnapalm** [comment]
Hi. I can't reproduce it. After the initial assist the counter restarts at 50 seconds as usual. Can you confirm it doesn't happen with the official server?

**Comment by jricoclq** [comment]
You must update the latest version of zoffline.
