### ISSUE TITLE
Docker: Error starting userland proxy: listen udp4 0.0.0.0:53: bind: address already in use

### ISSUE THREAD

**Issue by peteh** [zoffline/zwift-offline#276]
Hi, 

I'm running into the following error message on ubuntu systems for running the server: 
```
Error starting userland proxy: listen udp4 0.0.0.0:53: bind: address already in use
```

On ubuntu systems per default systemd-resolved uses port 53. However, the docker image exposes port 53 as well. 

Is this really necessary or can I modify the compose file to exclude the port if I am just using a modified hosts file on the zwift client pc?

**Comment by fatsbrown** [comment]
Hi. You can delete that line from compose file, it's only necessary if you will use the fake-dns option (custom DNS for Companion or Zwift client on non-rooted Android devices).

If you want to use fake-dns you can [free up port 53](https://www.linuxuprising.com/2020/07/ubuntu-how-to-free-up-port-53-used-by.html).

**Comment by peteh** [comment]
Thanks for the quick answer. I don't need the companion app, so I think I'm good to go with commenting out the 53 port on the compose file.
