### ISSUE TITLE
Questions about the Docker installation process...

### ISSUE THREAD

**Issue by wbrione** [zoffline/zwift-offline#278]
Hello. First of all, congratulations and thank you very much for the project. Now, about the installation, I really found some details about installing the service in Docker confusing... why is this... "**If you are not running zoffline on the same PC that Zwift is running: create a server-ip.txt file in the </path/to/host/storage> directory containing the IP address of the PC running zoffline**."... Naturally, shouldn't the service be accessed by the IP of the host running docker? What exactly would this configuration be for, the client? But haven't we already "fooled" you by adjusting the name resolution part (host file), forcing client requests to be directed to the offline server? Anyway, another question that remains is in relation to ports 80 and 443, these are generally very popular ports on a server system, and to get around this, I am using NGINX Proxy Manager as a reverse proxy, where it receives the request on port 80/443, and redirects it to the zoffline container, but the zwift client cannot connect to the service, giving a certificate error. I tried to install the certificate, but NPM fails the import process, as it doesn't accept password-protected certificates, Ok... the password is blank, but NPM doesn't know that, and for it, it's still a certificate key password protected :-(

Anyway, my scenario is the following, I would really like to have a decentralized installation, with zoffline installed on my server, in this case, a NAS (OpenMediaVault), and the client installed, for example, on a laptop or tablet... I believe that the client part of the installation is very clear, but if I am making any mistakes in my understanding, precisely through this message, I seek guidance.

Thank you in advance.

**Comment by oldnapalm** [comment]
> Naturally, shouldn't the service be accessed by the IP of the host running docker? What exactly would this configuration be for, the client? But haven't we already "fooled" you by adjusting the name resolution part (host file), forcing client requests to be directed to the offline server?

That's how Zwift server works, zoffline is just replicating it. Client connects to "us-or-rly101" (which is indeed redirected to zoffline) and receives the IP address of a telemetry server. On retail server there are many telemetry servers. In zoffline's case it will be the same as the relay server, we could try to guess through which interface the client will connect, but would probably guess wrong in some cases, that's why you should specify the IP address (could be a public IP, LAN or even some virtual interface).

> Anyway, another question that remains is in relation to ports 80 and 443, these are generally very popular ports on a server system, and to get around this, I am using NGINX Proxy Manager as a reverse proxy, where it receives the request on port 80/443, and redirects it to the zoffline container, but the zwift client cannot connect to the service, giving a certificate error. I tried to install the certificate, but NPM fails the import process, as it doesn't accept password-protected certificates, Ok... the password is blank, but NPM doesn't know that, and for it, it's still a certificate key password protected :-(

I've never used NGINX, but I used Apache proxy and this is how I did it https://github.com/oldnapalm/zwift-offline/blob/master/apache/000-default.conf

Regarding the certificate import, if you are having trouble importing the P12 due to the password, try importing the PEM file instead.

**Comment by wbrione** [comment]
@oldnapalm, thank you very much for your feedback.

Your information was essential to achieve my objective, however, I was forced to make some adjustments to my server system, in this case, OpenMediaVault...

1) Change the OMV web interface port from 80 to 81
2) Once port 80 is free, adjust NPM to listen on ports 80 and 443, and change the port of your web interface to 8181
3) Import the key/certificate in .PEM format into NPM (as you suggested)
4) Create 2 proxy rules, the first, for the domain "cdn.zwift.com", directing to the container at "http://zoffline:80", and the other, for the domains "us-or-rly101 .zwift.com secure.zwift.com launcher.zwift.com", directing to "https://zoffline:443", in both cases it is necessary to activate the previously imported certificate.

It is not necessary to export ports 80 and 443 from the zoffline container, as both NPM and zoffline are in the same custom network in docker, in my case, I created a "bridge" type network with the name "apps_default", by default, activating "name resolution", and the container can be referenced by name (e.g.: zoffline), remembering that it is NPM that manages the traffic on ports 80 and 443 of the host, directing the flow according to pre-defined rules , fulfilling its role as a reverse proxy ;-)

Note: The NPM rules were also based on your tips, in this case, the Apache configurations. Unfortunately it is not possible, at least I haven't found a way, to allow the same domain to operate in 2 different schemes/protocols, so the domain "cdn.zwift.com" only has a rule in the "http" scheme and not in " https" according to your example, but from the looks of it, this is not a problem for the Zwift client, or NPM must perform some internal operation, when the domain is referenced via https... anyway, the fact is... the scenario works , and I'm super happy :-)

Once again, thank you very much, and I hope to help other people who want to achieve the same goal with this information.

If you want to insert/adapt this information in the zoffline documentation, feel free to do so, as I believe that this client/server scenario can make sense for many people, especially when the objective is to centralize the storage of information, and especially , if zoffline is configured for multiplayer mode.

**Comment by oldnapalm** [comment]
> "cdn.zwift.com" only has a rule in the "http" scheme and not in " https" according to your example

I added in both because the Mac client used to request cdn files over https, but I don't use Zwift on Mac for years, so I don't know if it's still necessary.

**Comment by backcountrymountains** [comment]
@wbrione, can you share your nginx conf file? Thanks

**Comment by wbrione** [comment]
> @wbrione, can you share your nginx conf file? Thanks

As I said and demonstrated above, I used NPM, precisely because it is simpler to configure. So, you can install it, apply the rules I mentioned above, then investigate the configuration files to select the rules and apply them natively to your Ngnix installation ;-)

**Comment by backcountrymountains** [comment]
I've got it working using docker-compose (portainer) and nginx.
I downloaded the ssl files for nginx and made the following ```zoffline.conf``` for nginx:
(my portainer is at 192.168.1.73)
```
server {
    listen 443 ssl;
    http2 on;
	
    server_name secure.zwift.com us-or-rly101.zwift.com launcher.zwift.com cdn.zwift.com;

    ssl_certificate     /etc/nginx/certs/zoffline/cert-zwift-com.pem;
    ssl_certificate_key /etc/nginx/certs/zoffline/key-zwift-com.pem;
    include /etc/nginx/conf.d/options-ssl-nginx.conf;

    location / {
	proxy_pass https://192.168.1.73:4443/;
    }
}

server {
        listen 80;
        server_name cdn.zwift.com;

   location / {
	proxy_set_header  Host $host;
        proxy_set_header  X-Real-IP $remote_addr;
        proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header  X-Forwarded-Proto $scheme;

        proxy_read_timeout  90;
	proxy_pass http://192.168.1.73:8181;
    }
}
```
For the docker container I just mapped ports 8181 to 80 and 4443 to 443 and it seems to work.

Docker Compose file:
```
version: "3.7"
services:
    zoffline:
        image: zoffline/zoffline:latest
        container_name: zoffline
        depends_on:
          - nginx
        networks:
          - net
        stdin_open: true
        tty: true
        environment:
          - TZ=America/Denver
        volumes:
          - /mnt/d/12700/zoffline:/usr/src/app/zwift-offline/storage
        ports:
          - 8181:80
          - 4443:443
          - 3024:3024/udp
          - 3025:3025
        restart: unless-stopped
```
I have no idea what I'm doing so I'm not sure if my nginx config is "correct" but it is working.
