### ISSUE TITLE
Support Zwift screenshots

### ISSUE THREAD

**Issue by zoffline** [zoffline/zwift-offline#28]
Add support for at least Strava upload screenshots.

**Comment by daktak** [comment]
Also naming the activity in Zwift does not populate through to Strava

**Comment by oldnapalm** [comment]
As of version 1.2.0 photo uploading is supported by stravalib.

https://github.com/stravalib/stravalib/releases/tag/v1.2.0

**Comment by oldnapalm** [comment]
Gave it a shot without luck.

https://github.com/stravalib/stravalib/pull/318#issuecomment-1440756009

If someone wants to try: https://github.com/oldnapalm/zwift-offline/commit/3e92fe45e97283ec623e0ba098d8c86d59c97141

Need to `pip install Pillow` and authorize Strava again allowing to read activities.

**Comment by ogperalta** [comment]
Donde puedo encontrar las imágenes de las actividades en un dispositivo Android? la idea es al menos tener la opción de cargar las imágenes manualmente.

**Comment by oldnapalm** [comment]
I don't know where (or if) the images are saved on the Android device. I can make zoffline save them, but for now they are not saved.

**Comment by ogperalta** [comment]
Ahh ya entiendo...entonces una buena opción sería que zoffline los guarde en algún lado y posteriormente se podrían subir manualmente...sería perfecto...

**Comment by oldnapalm** [comment]
Exactly. Pull the latest commit or download the artifact from https://github.com/zoffline/zwift-offline/actions/runs/8254711881 if you use the Windows exe. Images should be found in storage/1/images.

**Comment by ogperalta** [comment]
Hola...hice la prueba con la versión que envió, sin embargo, en la sesión realizada no guardó las imágenes en la ruta que indicó. las sesiones las estoy haciendo con un dispositivo Android.
Como cosa particular he visto que las sesiones no cargan a Strava inmediatamente se termina la actividad sino que debo cerrar la app en android y volver a ejecutarla, en ese momento la actividad si carga a Strava

**Comment by oldnapalm** [comment]
> Como cosa particular he visto que las sesiones no cargan a Strava inmediatamente se termina la actividad sino que debo cerrar la app en android y volver a ejecutarla, en ese momento la actividad si carga a Strava

Did this already happen previously or just with the latest version?

Post the zoffline output after finishing an activity (copy and paste the text from zoffline window).

**Comment by ogperalta** [comment]
INFO:zoffline:192.168.2.18 - - [2024-03-13 06:06:02] "GET /api/profiles?id=1210078&id=1180093&id=1470025&id=1200026 HTTP/1.1" 200 621 0.001405
INFO:zoffline:192.168.2.18 - - [2024-03-13 06:06:05] "GET /api/profiles?id=1340027&id=1360062&id=1290062 HTTP/1.1" 200 486 0.001156
INFO:zoffline:192.168.2.18 - - [2024-03-13 06:06:08] "GET /api/profiles?id=1450080&id=1110049 HTTP/1.1" 200 357 0.000994
INFO:zoffline:192.168.2.18 - - [2024-03-13 06:06:12] "GET /api/profiles?id=1330062&id=1290039&id=1480053&id=1030058&id=1360028&id=1360041 HTTP/1.1" 200 862 0.000000
INFO:zoffline:192.168.2.18 - - [2024-03-13 06:06:18] "GET /api/profiles?id=1050038&id=1380058&id=1000058&id=1090060 HTTP/1.1" 200 589 0.000998
INFO:zoffline:192.168.2.18 - - [2024-03-13 06:06:20] "GET /relay/teleport-targets?mapRevisionId=13 HTTP/1.1" 200 988 0.000997
INFO:zoffline:192.168.2.18 - - [2024-03-13 06:06:22] "GET /api/profiles?id=1240027&id=1300044 HTTP/1.1" 200 359 0.000000
INFO:zoffline:192.168.2.18 - - [2024-03-13 06:06:25] "GET /api/profiles?id=1170035&id=1270038&id=1270039 HTTP/1.1" 200 467 0.000000
INFO:zoffline:192.168.2.18 - - [2024-03-13 06:06:28] "GET /api/profiles?id=1430082&id=1210029&id=1300079&id=1460063&id=1480093 HTTP/1.1" 200 728 0.000000
INFO:zoffline:192.168.2.18 - - [2024-03-13 06:06:32] "GET /api/profiles?id=1160050&id=1460026&id=1370052 HTTP/1.1" 200 488 0.000000
INFO:zoffline:192.168.2.18 - - [2024-03-13 06:06:35] "GET /api/profiles?id=1130026&id=1070066&id=1260065&id=1150062&id=1260037 HTTP/1.1" 200 706 0.000000
INFO:zoffline:192.168.2.18 - - [2024-03-13 06:06:37] "POST /hvc-ingestion-service/batch HTTP/1.1" 200 125 0.000000
INFO:zoffline:192.168.2.18 - - [2024-03-13 06:06:39] "GET /api/profiles?id=1090027&id=1240026&id=1220065&id=1460060&id=1370078&id=1430061&id=1280040&id=1490069&id=1260029 HTTP/1.1" 200 1222 0.000000
INFO:zoffline:192.168.2.18 - - [2024-03-13 06:06:42] "GET /api/profiles?id=1360065 HTTP/1.1" 200 233 0.000000
INFO:zoffline:192.168.2.18 - - [2024-03-13 06:06:45] "GET /api/profiles?id=1440029&id=1100044&id=1300063&id=1070081&id=1340041&id=1410051 HTTP/1.1" 200 840 0.000990
INFO:zoffline:192.168.2.18 - - [2024-03-13 06:06:50] "GET /relay/teleport-targets?mapRevisionId=13 HTTP/1.1" 200 989 0.000998
INFO:zoffline:192.168.2.18 - - [2024-03-13 06:06:53] "GET /api/profiles?id=1260057 HTTP/1.1" 200 234 0.000000
INFO:zoffline:192.168.2.18 - - [2024-03-13 06:06:57] "GET /api/profiles?id=1230093&id=1210065&id=1420032&id=1230057&id=1160046&id=1400059&id=1150029 HTTP/1.1" 200 951 0.000000
INFO:zoffline:192.168.2.18 - - [2024-03-13 06:07:00] "GET /api/profiles?id=1320060&id=1430024&id=1330057 HTTP/1.1" 200 475 0.000986
INFO:zoffline:192.168.2.18 - - [2024-03-13 06:07:04] "GET /api/profiles?id=1470063&id=1250027&id=1010026 HTTP/1.1" 200 478 0.000000
INFO:zoffline:192.168.2.18 - - [2024-03-13 06:07:08] "GET /api/profiles?id=1460051&id=1330040&id=1390087 HTTP/1.1" 200 470 0.000998
INFO:zoffline:192.168.2.18 - - [2024-03-13 06:07:11] "GET /api/profiles?id=1190065 HTTP/1.1" 200 231 0.000000
INFO:zoffline:192.168.2.18 - - [2024-03-13 06:07:15] "GET /api/profiles?id=1040058&id=1070063&id=1220062&id=1220036&id=1030031 HTTP/1.1" 200 717 0.000000
INFO:zoffline:192.168.2.18 - - [2024-03-13 06:07:19] "GET /api/profiles?id=1390061&id=1010051&id=1140072 HTTP/1.1" 200 466 0.000000
INFO:zoffline:192.168.2.18 - - [2024-03-13 06:07:20] "GET /relay/teleport-targets?mapRevisionId=13 HTTP/1.1" 200 989 0.000997
INFO:zoffline:192.168.2.18 - - [2024-03-13 06:07:22] "GET /api/profiles?id=1280059 HTTP/1.1" 200 232 0.001084
INFO:zoffline:192.168.2.18 - - [2024-03-13 06:07:25] "GET /api/profiles?id=1310062 HTTP/1.1" 200 229 0.000996
INFO:zoffline:192.168.2.18 - - [2024-03-13 06:07:25] "GET /api/profiles?id=1250037&id=1460087&id=1020065 HTTP/1.1" 200 484 0.000997
INFO:zoffline:192.168.2.18 - - [2024-03-13 06:07:29] "GET /api/profiles?id=1000066&id=1310062&id=1000085 HTTP/1.1" 200 461 0.000000
INFO:zoffline:192.168.2.18 - - [2024-03-13 06:07:35] "GET /api/profiles?id=1210059&id=1410063&id=1390034&id=1480080&id=1120030&id=1310026 HTTP/1.1" 200 837 0.000984
INFO:zoffline:192.168.2.18 - - [2024-03-13 06:07:38] "GET /api/profiles?id=1260080&id=1430030&id=1290073 HTTP/1.1" 200 479 0.000000
INFO:zoffline:192.168.2.18 - - [2024-03-13 06:07:41] "GET /api/profiles?id=1270065&id=1100050&id=1280044 HTTP/1.1" 200 494 0.000998
INFO:zoffline:192.168.2.18 - - [2024-03-13 06:07:44] "GET /api/profiles?id=1350039&id=1120087 HTTP/1.1" 200 363 0.000998
INFO:zoffline:192.168.2.18 - - [2024-03-13 06:07:47] "GET /api/profiles?id=1030065&id=1190070&id=1480064&id=1240053 HTTP/1.1" 200 601 0.000999
INFO:zoffline:192.168.2.18 - - [2024-03-13 06:07:50] "GET /relay/teleport-targets?mapRevisionId=13 HTTP/1.1" 200 989 0.000000
INFO:zoffline:192.168.2.18 - - [2024-03-13 06:07:51] "GET /api/profiles?id=1000031 HTTP/1.1" 200 237 0.000000
INFO:zoffline:192.168.2.18 - - [2024-03-13 06:07:54] "GET /api/profiles?id=1410069 HTTP/1.1" 200 243 0.000997
INFO:zoffline:192.168.2.18 - - [2024-03-13 06:07:57] "GET /api/profiles?id=1480072&id=1090050 HTTP/1.1" 200 348 0.000000
INFO:zoffline:192.168.2.18 - - [2024-03-13 06:08:00] "POST /relay/worlds/attributes HTTP/1.1" 201 134 0.012957
INFO:zoffline:192.168.2.18 - - [2024-03-13 06:08:00] "GET /api/profiles?id=1020085&id=1150065&id=1110044 HTTP/1.1" 200 468 0.000000
INFO:zoffline:192.168.2.18 - - [2024-03-13 06:08:03] "GET /api/profiles?id=1370046&id=1150064 HTTP/1.1" 200 365 0.001003
INFO:zoffline:192.168.2.18 - - [2024-03-13 06:08:06] "GET /api/profiles?id=1260035&id=1370038 HTTP/1.1" 200 359 0.000000
INFO:zoffline:192.168.2.18 - - [2024-03-13 06:08:09] "GET /api/profiles?id=1160061&id=1310028&id=1340050 HTTP/1.1" 200 482 0.000000
INFO:zoffline:192.168.2.18 - - [2024-03-13 06:08:12] "GET /api/profiles?id=1410062&id=1330072&id=1480037 HTTP/1.1" 200 483 0.001993
INFO:zoffline:192.168.2.18 - - [2024-03-13 06:08:15] "GET /api/profiles?id=1080033&id=1260045 HTTP/1.1" 200 363 0.000989
INFO:zoffline:192.168.2.18 - - [2024-03-13 06:08:18] "GET /api/profiles?id=1320073&id=1400027&id=1230024&id=1110029 HTTP/1.1" 200 590 0.000000
INFO:zoffline:192.168.2.18 - - [2024-03-13 06:08:20] "GET /relay/teleport-targets?mapRevisionId=13 HTTP/1.1" 200 987 0.000913
INFO:zoffline:192.168.2.18 - - [2024-03-13 06:08:21] "GET /api/profiles?id=1100079&id=1460039&id=1010050 HTTP/1.1" 200 460 0.000000
INFO:zoffline:192.168.2.18 - - [2024-03-13 06:08:24] "GET /api/profiles?id=1460063&id=1060077&id=1020060&id=1490069&id=1300079 HTTP/1.1" 200 735 0.000000
INFO:zoffline:192.168.2.18 - - [2024-03-13 06:08:27] "GET /api/profiles?id=1370065&id=1150062&id=1370066&id=1270051 HTTP/1.1" 200 613 0.000995
INFO:zoffline:192.168.2.18 - - [2024-03-13 06:08:30] "GET /api/profiles?id=1150049&id=1410081&id=1090073 HTTP/1.1" 200 478 0.000985
INFO:zoffline:192.168.2.18 - - [2024-03-13 06:08:33] "GET /api/profiles?id=1300063&id=1230093&id=1370078&id=1070081&id=1390029 HTTP/1.1" 200 717 0.001198
INFO:zoffline:192.168.2.18 - - [2024-03-13 06:08:56] "GET /api/profiles?id=1470063&id=1150063 HTTP/1.1" 200 361 0.000998
INFO:zoffline:192.168.2.18 - - [2024-03-13 06:08:57] "GET /api/profiles?id=1070030&id=1070032&id=1140072 HTTP/1.1" 200 473 0.000997
INFO:zoffline:192.168.2.18 - - [2024-03-13 06:08:57] "GET /api/profiles?id=1340087&id=1220062&id=1490049&id=1130061 HTTP/1.1" 200 600 0.000000
INFO:zoffline:192.168.2.18 - - [2024-03-13 06:08:57] "GET /api/profiles?id=1300070&id=1460087&id=1440093&id=1260080&id=1410063&id=1390087&id=1480038&id=1070063&id=1000085&id=1040029&id=1210063&id=1240030&id=1310042&id=1430085&id=1030051 HTTP/1.1" 200 1913 0.000918
INFO:zoffline:192.168.2.18 - - [2024-03-13 06:08:57] "GET /relay/teleport-targets?mapRevisionId=13 HTTP/1.1" 200 990 0.001000
INFO:zoffline:192.168.2.18 - - [2024-03-13 06:08:59] "GET /api/profiles?id=1420030 HTTP/1.1" 200 246 0.000995
INFO:zoffline:192.168.2.18 - - [2024-03-13 06:09:02] "GET /api/profiles?id=1270069&id=1000042&id=1430066 HTTP/1.1" 200 490 0.000996
INFO:zoffline:192.168.2.18 - - [2024-03-13 06:09:05] "GET /api/profiles?id=1420062&id=1390038 HTTP/1.1" 200 357 0.000000
INFO:zoffline:192.168.2.18 - - [2024-03-13 06:09:08] "GET /api/profiles?id=1270085&id=1260063 HTTP/1.1" 200 354 0.000996
INFO:zoffline:192.168.2.18 - - [2024-03-13 06:09:11] "GET /api/profiles?id=1110046&id=1190029&id=1360059&id=1000050 HTTP/1.1" 200 598 0.000995
INFO:zoffline:192.168.2.18 - - [2024-03-13 06:09:17] "GET /api/profiles?id=1400077&id=1070050&id=1110026&id=1040023 HTTP/1.1" 200 605 0.000997
INFO:zoffline:192.168.2.18 - - [2024-03-13 06:09:20] "GET /relay/teleport-targets?mapRevisionId=13 HTTP/1.1" 200 990 0.000997
INFO:zoffline:192.168.2.18 - - [2024-03-13 06:09:20] "GET /api/profiles?id=1210025&id=1490063&id=1360066 HTTP/1.1" 200 460 0.000999
INFO:zoffline:192.168.2.18 - - [2024-03-13 06:09:23] "GET /api/profiles?id=1040031&id=1350063&id=1110036&id=1470033&id=1190037&id=1030080&id=1200061 HTTP/1.1" 200 965 0.000997
INFO:zoffline:192.168.2.18 - - [2024-03-13 06:09:27] "GET /api/profiles?id=1090037&id=1220042 HTTP/1.1" 200 365 0.000000
TCPHandler loop exception: ConnectionAbortedError(10053, 'Se ha anulado una conexión establecida por el software en su equipo host', None, 10053, None)
TCPHandler loop exception: ConnectionResetError(10054, 'Se ha forzado la interrupción de una conexión existente por el host remoto', None, 10054, None)
TCPHandler loop exception: ConnectionResetError(10054, 'Se ha forzado la interrupción de una conexión existente por el host remoto', None, 10054, None)
INFO:zoffline:127.0.0.1 - - [2024-03-13 06:15:12] "GET /api/telemetry/config HTTP/1.1" 200 413 0.001461
INFO:zoffline:127.0.0.1 - - [2024-03-13 06:15:12] "POST /experimentation/v1/machine-id-variant HTTP/1.1" 200 180 0.009689
127.0.0.1 - - [13/Mar/2024 06:15:12] "GET /gameassets/Zwift_Updates_Root/Zwift_ver_cur.xml HTTP/1.1" 200 -
127.0.0.1 - - [13/Mar/2024 06:15:12] "GET /gameassets/Zwift_Updates_Root/Launcher_ver_cur.xml HTTP/1.1" 200 -
INFO:zoffline:127.0.0.1 - - [2024-03-13 06:15:12] "POST /hvc-ingestion-service/batch HTTP/1.1" 200 125 0.001134
INFO:zoffline:127.0.0.1 - - [2024-03-13 06:17:12] "POST /hvc-ingestion-service/batch HTTP/1.1" 200 125 0.000997
INFO:zoffline:127.0.0.1 - - [2024-03-13 06:19:12] "POST /hvc-ingestion-service/batch HTTP/1.1" 200 125 0.000995
INFO:zoffline:127.0.0.1 - - [2024-03-13 06:21:12] "POST /hvc-ingestion-service/batch HTTP/1.1" 200 125 0.000997
INFO:zoffline:127.0.0.1 - - [2024-03-13 06:23:12] "POST /hvc-ingestion-service/batch HTTP/1.1" 200 125 0.000995
INFO:zoffline:127.0.0.1 - - [2024-03-13 06:25:12] "POST /hvc-ingestion-service/batch HTTP/1.1" 200 125 0.001991
INFO:zoffline:127.0.0.1 - - [2024-03-13 06:27:12] "POST /hvc-ingestion-service/batch HTTP/1.1" 200 125 0.001004
INFO:zoffline:127.0.0.1 - - [2024-03-13 06:29:12] "POST /hvc-ingestion-service/batch HTTP/1.1" 200 125 0.000996
INFO:zoffline:127.0.0.1 - - [2024-03-13 06:31:12] "POST /hvc-ingestion-service/batch HTTP/1.1" 200 125 0.000996
INFO:zoffline:127.0.0.1 - - [2024-03-13 06:33:12] "POST /hvc-ingestion-service/batch HTTP/1.1" 200 125 0.000996
INFO:zoffline:127.0.0.1 - - [2024-03-13 06:35:12] "POST /hvc-ingestion-service/batch HTTP/1.1" 200 125 0.001001
INFO:zoffline:127.0.0.1 - - [2024-03-13 06:37:12] "POST /hvc-ingestion-service/batch HTTP/1.1" 200 125 0.000997
INFO:zoffline:127.0.0.1 - - [2024-03-13 06:39:12] "POST /hvc-ingestion-service/batch HTTP/1.1" 200 125 0.000980
INFO:zoffline:127.0.0.1 - - [2024-03-13 06:41:12] "POST /hvc-ingestion-service/batch HTTP/1.1" 200 125 0.000000
INFO:zoffline:127.0.0.1 - - [2024-03-13 06:43:12] "POST /hvc-ingestion-service/batch HTTP/1.1" 200 125 0.000000
INFO:zoffline:127.0.0.1 - - [2024-03-13 06:45:12] "POST /hvc-ingestion-service/batch HTTP/1.1" 200 125 0.000000
INFO:zoffline:127.0.0.1 - - [2024-03-13 06:47:12] "POST /hvc-ingestion-service/batch HTTP/1.1" 200 125 0.001215
INFO:zoffline:127.0.0.1 - - [2024-03-13 06:49:12] "POST /hvc-ingestion-service/batch HTTP/1.1" 200 125 0.000997
INFO:zoffline:127.0.0.1 - - [2024-03-13 06:51:12] "POST /hvc-ingestion-service/batch HTTP/1.1" 200 125 0.000991
INFO:zoffline:127.0.0.1 - - [2024-03-13 06:53:12] "POST /hvc-ingestion-service/batch HTTP/1.1" 200 125 0.000000
INFO:zoffline:127.0.0.1 - - [2024-03-13 06:55:12] "POST /hvc-ingestion-service/batch HTTP/1.1" 200 125 0.000000
INFO:zoffline:127.0.0.1 - - [2024-03-13 06:57:13] "POST /hvc-ingestion-service/batch HTTP/1.1" 200 125 0.000997
INFO:zoffline:127.0.0.1 - - [2024-03-13 06:59:13] "POST /hvc-ingestion-service/batch HTTP/1.1" 200 125 0.000000
INFO:zoffline:127.0.0.1 - - [2024-03-13 07:01:13] "POST /hvc-ingestion-service/batch HTTP/1.1" 200 125 0.001038
INFO:zoffline:127.0.0.1 - - [2024-03-13 07:03:13] "POST /hvc-ingestion-service/batch HTTP/1.1" 200 125 0.000000
INFO:zoffline:192.168.2.18 - - [2024-03-13 07:03:28] "GET /gameassets/MapSchedule_v2.xml HTTP/1.1" 200 31051 0.001011
INFO:zoffline:192.168.2.18 - - [2024-03-13 07:03:28] "GET /gameassets/ZwiftAndroid_ver_cur.xml HTTP/1.1" 200 505 0.001993
INFO:zoffline:192.168.2.18 - - [2024-03-13 07:03:34] "GET /api/telemetry/config HTTP/1.1" 200 413 0.000000
INFO:zoffline:192.168.2.18 - - [2024-03-13 07:03:34] "POST /hvc-ingestion-service/batch HTTP/1.1" 200 125 0.000997
INFO:zoffline:192.168.2.18 - - [2024-03-13 07:03:35] "GET /api/auth HTTP/1.1" 200 215 0.000000
INFO:zoffline:192.168.2.18 - - [2024-03-13 07:03:35] "POST /auth/realms/zwift/protocol/openid-connect/token HTTP/1.1" 200 3741 0.000996
INFO:zoffline:192.168.2.18 - - [2024-03-13 07:03:36] "POST /api/users/login HTTP/1.1" 200 9363 0.003985
INFO:zoffline:192.168.2.18 - - [2024-03-13 07:03:36] "GET /relay/worlds/hash-seeds HTTP/1.1" 200 198 0.000999
INFO:zoffline:192.168.2.18 - - [2024-03-13 07:03:36] "GET /api/profiles/me HTTP/1.1" 200 3040 0.001144
INFO:zoffline:192.168.2.18 - - [2024-03-13 07:03:36] "GET /api/profiles/1/followees?include-follow-requests=false HTTP/1.1" 200 129 0.000996
INFO:zoffline:192.168.2.18 - - [2024-03-13 07:03:36] "GET /api/achievement/loadPlayerAchievements HTTP/1.1" 200 292 0.002486
INFO:zoffline:192.168.2.18 - - [2024-03-13 07:03:36] "GET /api/power-curve/best/all-time HTTP/1.1" 200 200 0.003125
INFO:zoffline:192.168.2.18 - - [2024-03-13 07:03:36] "GET /api/private_event/feed?organizer_only_past_events=false&start_date=-1800000 HTTP/1.1" 200 129 0.002129
INFO:zoffline:192.168.2.18 - - [2024-03-13 07:03:36] "GET /api/player-playbacks/player/settings HTTP/1.1" 200 115 0.001129
INFO:zoffline:192.168.2.18 - - [2024-03-13 07:03:36] "POST /experimentation/v1/variant HTTP/1.1" 200 10443 0.005650
INFO:zoffline:192.168.2.18 - - [2024-03-13 07:03:36] "GET /api/profiles/1/activities HTTP/1.1" 200 778 0.002272
INFO:zoffline:192.168.2.18 - - [2024-03-13 07:03:36] "POST /api/analytics/event HTTP/1.1" 200 115 0.000000
INFO:zoffline:192.168.2.18 - - [2024-03-13 07:03:36] "GET /api/profiles/1/goals HTTP/1.1" 200 129 0.000997
INFO:zoffline:192.168.2.18 - - [2024-03-13 07:03:37] "GET /relay/dropin HTTP/1.1" 200 1195324 0.917540
INFO:zoffline:192.168.2.18 - - [2024-03-13 07:03:38] "GET /api/profiles/1/activities HTTP/1.1" 200 778 0.001995
INFO:stravalib.protocol.ApiV3:POST 'https://www.strava.com/oauth/token' with params {'client_id': 28117, 'client_secret': '41b7b7b76d8cfc5dc12ad5f020adfea17da35468', 'refresh_token': 'b2397089a92bf1fe286f5b48b142ae207a4726a9', 'grant_type': 'refresh_token'}
INFO:stravalib.protocol.ApiV3:POST 'https://www.strava.com/api/v3/uploads' with params {'data_type': 'fit', 'name': "Zwift - 01. Let's Get Moving in Makuri Islands"}
INFO:zoffline:runalyze_token.txt missing, skip Runalyze activity update
INFO:zoffline:intervals_credentials.bin missing, skip Intervals.icu activity update
INFO:zoffline:192.168.2.18 - - [2024-03-13 07:03:43] "PUT /api/profiles/1/activities/4?upload-to-strava=true HTTP/1.1" 200 137 5.599524
INFO:zoffline:192.168.2.18 - - [2024-03-13 07:03:43] "GET /gameassets/PortalRoadSchedule_v1.xml HTTP/1.1" 200 7555 0.000995
INFO:zoffline:192.168.2.18 - - [2024-03-13 07:03:43] "GET /api/game-asset-patching-service/manifest?gameVersion=1.60.0&hash=E3B0C44298FC1C149AFBF4C8996FB92427AE41E4649B934CA495991B7852B855 HTTP/1.1" 200 115 0.000000
INFO:zoffline:192.168.2.18 - - [2024-03-13 07:03:43] "PUT /api/profiles/1/in-game-fields HTTP/1.1" 204 118 0.001503
INFO:zoffline:192.168.2.18 - - [2024-03-13 07:03:43] "POST /api/events/search?limit=100 HTTP/1.1" 200 33493 0.001994
INFO:zoffline:192.168.2.18 - - [2024-03-13 07:03:44] "POST /api/analytics/event HTTP/1.1" 200 115 0.000997
INFO:zoffline:192.168.2.18 - - [2024-03-13 07:03:44] "PUT /api/profiles/1 HTTP/1.1" 204 118 0.001993
INFO:zoffline:192.168.2.18 - - [2024-03-13 07:03:44] "PUT /api/profiles/1/in-game-fields HTTP/1.1" 204 118 0.000997
INFO:zoffline:192.168.2.18 - - [2024-03-13 07:03:44] "POST /api/analytics/event HTTP/1.1" 200 115 0.001082
INFO:zoffline:192.168.2.18 - - [2024-03-13 07:03:46] "POST /api/analytics/event HTTP/1.1" 200 115 0.000953
INFO:zoffline:192.168.2.18 - - [2024-03-13 07:03:46] "GET /api/zfiles/list?folder=workouts HTTP/1.1" 200 129 0.002989
INFO:zoffline:192.168.2.18 - - [2024-03-13 07:03:46] "GET /api/quest/quests/my-quests HTTP/1.1" 200 110 0.000000
INFO:zoffline:192.168.2.18 - - [2024-03-13 07:03:46] "GET /api/quest/quests/all-quests?limit=20&page=0 HTTP/1.1" 200 110 0.000000
INFO:zoffline:192.168.2.18 - - [2024-03-13 07:03:47] "GET /api/partners/trainingpeaks/auth/access-token HTTP/1.1" 404 331 0.000000
INFO:zoffline:192.168.2.18 - - [2024-03-13 07:03:47] "GET /api/zfiles/list?folder=customworkouts HTTP/1.1" 200 1021 0.000997
INFO:zoffline:192.168.2.18 - - [2024-03-13 07:03:47] "GET /api/zfiles/list?folder=customgearing HTTP/1.1" 200 170 0.000997
INFO:zoffline:192.168.2.18 - - [2024-03-13 07:03:47] "GET /api/zfiles/19/download HTTP/1.1" 200 3753 0.006978
INFO:zoffline:192.168.2.18 - - [2024-03-13 07:03:47] "GET /api/zfiles/4/download HTTP/1.1" 200 368 0.002989
INFO:zoffline:192.168.2.18 - - [2024-03-13 07:03:47] "POST /api/zfiles HTTP/1.1" 200 170 0.002127
INFO:zoffline:192.168.2.18 - - [2024-03-13 07:03:47] "POST /api/zfiles HTTP/1.1" 200 168 0.002990

**Comment by ogperalta** [comment]
incluí información desde que inicié la actividad hasta que se cargó a strava

**Comment by oldnapalm** [comment]
> Como cosa particular he visto que las sesiones no cargan a Strava inmediatamente se termina la actividad sino que debo cerrar la app en android y volver a ejecutarla, en ese momento la actividad si carga a Strava

I ask again...

Did this already happen previously or just with the latest version?

This is the reason the screenshots are not being uploaded to zoffline, they should be uploaded when you finish the activity but instead the client is disconnecting prematurely for some reason.

> TCPHandler loop exception: ConnectionAbortedError(10053, 'Se ha anulado una conexión establecida por el software en su equipo host', None, 10053, None)

Post the Android client log from this activity https://support.zwift.com/locating-log-files-BykKO63fr#Android

**Comment by ogperalta** [comment]
si...ocurría antes también...
La desconexión podría ser porque el pc entra en modo suspensión? aunque lo tengo configurado para que no lo haga nunca o tal vez instabilidad de la red wifi?
[Log (old 4).txt](https://github.com/zoffline/zwift-offline/files/14589435/Log.old.4.txt)
[Log (old 3).txt](https://github.com/zoffline/zwift-offline/files/14589436/Log.old.3.txt)
![2024-03-13 09_51_34-Editar la configuración del plan](https://github.com/zoffline/zwift-offline/assets/24832591/5a80a89d-3fc8-4033-80bf-8388df18ae6a)

**Comment by oldnapalm** [comment]
If the server is suspended, the connection will surely close. It can also be caused by wireless network instability.

Looks like the activity starts around 5:44, 25 minutes later the connection closes and is never restored.

> [6:08:59] [ERROR] Failed to send telemetry [400] Failed to send telemetry

You can test with a short activity (300 meters), take a screenshot and see if it works.

Your issue is probably unrelated to the screenshots.

**Comment by ogperalta** [comment]
Hola...hice varias pruebas y efectivamente cuando se desconecta no se guardan las imagenes en la ruta indicada...en el primer intento solo creó la carpeta pero no cargó imagenes...en el segundo intento las imagenes se guardaron...en el tercer intento justo cuando estaba guardando la actividad vi en la consola el mensaje de desconexión y no se guardaron las imagenes...en el cuarto intento las imagenes se cargaron bien...conclusión: cuando se desconecta no se guardan las imagenes....todas las pruebas fueron realizadas con la versión que me envió...

**Comment by oldnapalm** [comment]
That's expected, if there's no network connection it's impossible to save images or the activity itself. Zwift freezing if it can't communicate with the server when trying to save an activity is also normal.

Not much to be done here, apparently you have a network instability issue.

**Comment by oldnapalm** [comment]
Partially implemented in https://github.com/zoffline/zwift-offline/commit/7bc726a711352dce605019e86fb028903ae0e586 (only upload from Zwift client to zoffline). Uploading to Strava is not possible because it's available only for partner apps, and now Strava became yet more restrictive (#323) only allowing API apps to have a single user unless submitted for review and approved.
