### ISSUE TITLE
Drops transfer

### ISSUE THREAD

**Issue by MartinGranados** [zoffline/zwift-offline#282]
Are drops supposed to "sync" to the online version of Zwift? there's a discrepancy of about 30,000 drops between the two accounts. Not a big deal but im also worried that if I buy a bike in offline mode it won't show up in online mode if I decide to go back

**Comment by daktak** [comment]
Online and offline stats are separate. You can copy your online profile into the offline server, but it will overwrite your offline progress. You cannot sync into the online server.
