### ISSUE TITLE
Hosts on Android "wrong"

### ISSUE THREAD

**Issue by ptzulu** [zoffline/zwift-offline#283]
Hi there!
I managed to make it work just fine on Windows, and then tried android (so, i can use my pc to watch something while riding :) )

So, i've checked your instructions, and was not able to make it work, and assumed it was an android problem, since seemed hosts was not taking effect. The problem was your instructions on Android has one entry missing:

<zoffline ip> us-or-rly101.zwift.com
<zoffline ip> secure.zwift.com
<zoffline ip> cdn.zwift.com
<zoffline ip> launcher.zwift.com    ->> this one is missing, after compared to my PC, that was working.

A simple thing, yet, it took me about 2 days os headscratching for suck a simple thing!

Thank you for your accomplishments!

**Comment by oldnapalm** [comment]
Hello.

The launcher hostname is not required for Android, the client doesn't even have a launcher. It was probably a coincidence that it worked after you added it.

Sometimes you may need to fully close (touch the "overview" button and swipe up) and relaunch the Virtual Hosts app after selecting the hosts file.

**Comment by oldnapalm** [comment]
Added clarification on Virtual Hosts app usage https://github.com/zoffline/zwift-offline/commit/1e00d9a6d22167e2d4b3fa049238fcea5e76dd7f
