### ISSUE TITLE
after last update, strava didn't upload

### ISSUE THREAD

**Issue by mesterumanele** [zoffline/zwift-offline#284]
Hi, 
not sure if last update is the issue. maybe i just need to enter strava credentials again? if that's the case, ignore my message. (garmin did upload, no issue!) So far, after all updates, uploading to strava worked perfect without doing anything. 

Is there a certain step that i should do in order to upload properly, other than puting my strava user/pass? i mean i should logoff and log back in every week? month? (is it possible to upload a past workout?)
Thank you

**Comment by fatsbrown** [comment]
You need to authorize again only if you remove the token or revoke access on https://www.strava.com/settings/apps

You can upload the FIT file of a past activity from Documents\Zwift\Activities to https://www.strava.com/upload/select

**Comment by mesterumanele** [comment]
So strange: i did two 3min trial just now, before trying to remove token, and now it did upload both! 
Thanks for the fit file detail
Thanks

**Comment by fatsbrown** [comment]
How do you run zoffline? (Windows exe, Docker or from source?)

There was this change a few days ago which may be related, depending on your time zone and when was the previous upload, but it was after the last exe release, so it would only be possible if you run from source or using Docker and updated after https://github.com/zoffline/zwift-offline/commit/4515679e28417cf240e7b555c807a915a9f160db

**Comment by mesterumanele** [comment]
Windows exe
I remember when did the install was 3h old. The file that missed from strava was yesterday 4pm
(Seems to be working now, without doing anything from my part) 
Thanks again
