### ISSUE TITLE
Portal climb badges don't work

### ISSUE THREAD

**Issue by stapa** [zoffline/zwift-offline#285]
I rode a portal climb today (Old La Honda - France), but I didn't get the badge.
![portal-badges](https://github.com/zoffline/zwift-offline/assets/1619452/47d5fd65-0966-418a-aaa6-ca03c86e685c)
I have the latest release for Windows (1.0.122968).

**Comment by oldnapalm** [comment]
Maybe these badges are not posted by the client since they depend on historic data.

Can you test this? https://github.com/zoffline/zwift-offline/tree/achievements

If you use the Windows exe, download the artifact from https://github.com/zoffline/zwift-offline/actions/runs/7169547370

**Comment by stapa** [comment]
Thank you for the fix, it works.
![obrazek](https://github.com/zoffline/zwift-offline/assets/1619452/5760ce94-0a89-4d9d-9cfc-4c402e31dadb)

**Comment by stapa** [comment]
Hello again,
today I did 10th climb without the Climb Portal Pro badge. It looks like the fix doesn't work fully. I'm attaching `segment_id`s from my portal rides:

Ski Lift Climb
1000000
1000001
1000002
1000003
1000004
1000005
1000006
1000007
1000008
1000009

Climb to Hollywood Sign
1000100
10001
1000101
1000102
1000103
1000104
1000105
1000106
1000107
1000108

Old La Honda
1001800
10018
1001801
1001802
1001803
1001804
1001805
1001806
1001807
1001808
1001809

Col des Aravis
1000500
10005
1000501
1000502
1000503
1000504
1000505
1000506
1000507
1000508
1000509

Eazy Rider
10002125
1000212500
1000212501
1000212502
1000212503
1000212504
1000212505
1000212506
1000212507
1000212508
1000212509

Cote de Trebiac
1000900
10009
1000901
1000902
1000903
1000904
1000905
1000906
1000907
1000908
1000909

Cote de Pike
1000312500
10003125
1000312501
1000312502
1000312503
1000312504
1000312505
1000312506
1000312507
1000312508
1000312509

Old Willunga Hill
1002012500
10020125
1002012501
1002012502
1002012503
1002012504
1002012505
1002012506
1002012507
1002012508
1002012509

Cote de Domancy
1000712500
10007125
1000712501
1000712502
1000712503
1000712504
1000712505
1000712506
1000712507
1000712508
1000712509

Crow Road
1001200
10012
1001201
1001202
1001203
1001204
1001205
1001206
1001207
1001208
1001209

**Comment by oldnapalm** [comment]
Only the 100% difficulty climbs are being counted and apparently the "Ski Lift Climb" doesn't have the full segment result, only the partials.

Can you check which entries you have in the route_result table?

If you don't mind attaching your zwift-offline.db it will be easier for me to test.

**Comment by stapa** [comment]
You are right, I switched to 125% before some climbs. I can try them again. The Ski Lift Climb should be comlete, I forgot to copy one `segment_id`.

In the `route_result` table are following `rout_hash`es:
10000
10001
10002
10003
10005
10007
10009
10012
10018
10020

**Comment by oldnapalm** [comment]
I think we can switch to checking route results instead of segment results, then the difficulty won't matter.

Can you test this? https://github.com/zoffline/zwift-offline/actions/runs/7534371916

**Comment by stapa** [comment]
Thank you for the fix, it works well.
![portal-badges-fixed2](https://github.com/zoffline/zwift-offline/assets/1619452/0a89f84b-0e12-44b3-80d6-3779eb9201c7)
