### ISSUE TITLE
Edge 120.0.2210.61 forces https redirection

### ISSUE THREAD

**Issue by oldnapalm** [zoffline/zwift-offline#286]
After the latest Edge update map override from launcher no longer works because the request is redirected to https.

**Comment by oldnapalm** [comment]
https://github.com/zoffline/zwift-offline/commit/535302ff236cb93f8495a1acd01fdd47747bde65 may remove the need of patching Mac launcher Info.plist with NSExceptionAllowsInsecureHTTPLoads.

Any Mac user available to test?

**Comment by bisayajin** [comment]
hi, will the Calendar fix be updated for the exe version ?

**Comment by oldnapalm** [comment]
> hi, will the Calendar fix be updated for the exe version ?

Hi. It will be in the next release. Meanwhile you can download artifact from https://github.com/zoffline/zwift-offline/actions/runs/7181114656

**Comment by bisayajin** [comment]
thank you
