### ISSUE TITLE
Operation not permitted [Certificate]

### ISSUE THREAD

**Issue by JulBa408** [zoffline/zwift-offline#287]
Can anybody help with the problem? 
When pasting the command 
_"sudo codesign --force --deep --sign - /Applications/Zwift.app"_ 
from step 2, my terminal returns the following two lines

_/Applications/Zwift.app: replacing existing signature
/Applications/Zwift.app: Operation not permitted_

If important: I am running MacOS 14.1.2 on an M1 Mac. 

Thanks in advance!

**Comment by JulBa408** [comment]
For future references: The error was that terminal did not have full disk access.

**Comment by oldnapalm** [comment]
Patching Info.plist and running the codesign command may not be necessary after a recent change, I just didn't remove from instructions yet because I'm not 100% sure since I can't test. If you can test with the original launcher and confirm it works, then I will update the instructions. Please see #286

> Zwift starts normally and I will have to log in

If you mean in the launcher, probably missing the change in hosts. If it's after ZwiftApp started, probably mistake appending certificate to cacert.pem (private key must not be included).

**Comment by JulBa408** [comment]
@oldnapalm thanks for your reply!
The launcher already starts with me being signed in. My hosts doc looks like this

_##
# Host Database
#
# localhost is used to configure the loopback interface
# when the system is booting.  Do not change this entry.
##
127.0.0.1	localhost
XXX	broadcasthost
::1             localhost
<zoffline ip> us-or-rly101.zwift.com secure.zwift.com cdn.zwift.com launcher.zwift.com_

I just replaced the boradcasthost with XXX. Maybe I have done an error with appending the last line?

Thanks!

**Comment by JulBa408** [comment]
@oldnapalm I tried what you said and used the original /Applications/Zwift.app.
This solves the problem of the launcher, however still brings the problem of the Zwift App. I guess I should then patch Info.plist?

**Comment by oldnapalm** [comment]
What do you mean with "brings the problem of the Zwift App"?

**Comment by JulBa408** [comment]
Sorry for being inaccurate. The Zwift app starts and I am asked to log into my account after starting Zwift with the launcher. 
Error message "Whoops. Wrong email or password. Let's try this again".

**Comment by oldnapalm** [comment]
This is usually caused by a mistake when appending the certificate to cacert.pem

You should append only lines 29 to 53

https://github.com/zoffline/zwift-offline/blob/master/ssl/cert-zwift-com.pem#L29

If you append the full file, this problem will happen.

**Comment by JulBa408** [comment]
Strange. I tried thought I took care of that, as I read multiple issues on that comment. However you were right, the private key snuck in. 
So I can now hereby confirm, that it's working for me with the unmodified Zwift. Thank you a lot!

**Comment by oldnapalm** [comment]
Could you confirm if the map override in launcher also works (select a map or climb instead of leaving as "calendar")?

**Comment by JulBa408** [comment]
Yup, works both, thank you a lot!

**Comment by oldnapalm** [comment]
Thanks.
