### ISSUE TITLE
Regarding the issue of long file name strings in robot files?

### ISSUE THREAD

**Issue by jricoclq** [zoffline/zwift-offline#290]
hello
When I use custom workouts, especially workouts with Chinese names, the file names of the robot files generated by ZOFFLINE appear to be very long strings, as shown in the figure below. Is there a way to simplify the names of such bin files, as the path of such long string file names may exceed the length of the longest address path in the WIN system, causing zoffline to fail to run. Or can the file name appear in the name as a Chinese names.
![186748dda80f0347459cef22200207a](https://github.com/zoffline/zwift-offline/assets/102775665/ad75cbed-3994-4943-84d5-5132c7d7beda)

**Comment by fatsbrown** [comment]
Hello.

You can disable the path length limit through a registry key

https://docs.python.org/3/using/windows.html#removing-the-max-path-limitation

When you install Python on Windows, after the installation is finished the installer offers to make this configuration for you.

Alternatively you can change the file name to be only the date and time, without the activity name

https://github.com/zoffline/zwift-offline/blob/ec9329061b833c64591fc45da2e0ed19599c0cb1/standalone.py#L445

Change to

```python
        f = '%s/%s.bin' % (folder, datetime.now(timezone.utc).strftime("%Y-%m-%d-%H-%M-%S"))
```

You can also try removing `quote()` to see if it works with Chinese characters, but it may cause error if the activity name contains characters which are not allowed in file names

https://github.com/zoffline/zwift-offline/blob/ec9329061b833c64591fc45da2e0ed19599c0cb1/zwift_offline.py#L2262

Change to

```python
        save_ghost(activity.name, player_id)
```

**Comment by jricoclq** [comment]
OK,thank ypu very much. I try it.
