### ISSUE TITLE
Erg - disconnected

### ISSUE THREAD

**Issue by mesterumanele** [zoffline/zwift-offline#292]
Hi, 
During the ride the erg got disconnected (this is second time in a row). Eventually, after i stoped pedalling, got reconnected after 3-4 seconds! Not sure if it's software or hardware issue! 
Thank you

**Comment by fatsbrown** [comment]
Hello.

Even if it's a software issue, I don't think it's related to zoffline, because the connection with the trainer is handled by the client (ZwiftApp) and does not depend on the server.
