### ISSUE TITLE
Old leveling scheme

### ISSUE THREAD

**Issue by stapa** [zoffline/zwift-offline#295]
Hello,
it looks like zoffline is still using the old leveling scheme mentioned in [this article](https://zwiftinsider.com/level-100/). As you can see on my screenshot below and the table from the article, XP UNTIL NEXT LEVEL should be 4,500 instead of 20,000. I upgraded to [zoffline_1.0.123458](https://github.com/zoffline/zwift-offline/releases/download/zoffline_1.0.123458/zoffline_1.0.123458.exe) at level 36.
![ZwiftXPstreak](https://github.com/zoffline/zwift-offline/assets/1619452/b22d8f08-b1e5-4286-8052-55bc0f9bd0c7)
![ZwiftLevels](https://github.com/zoffline/zwift-offline/assets/1619452/147defed-b295-4651-8e42-f8e6cbd0ac96)

**Comment by fatsbrown** [comment]
I think this is related to the "game_Economy2023" feature. When I connect to the official server (level 7) I get the value 2 for "ServerConfigXP" and see the 2 chevrons/wheelie icon in the menu

![level](https://github.com/zoffline/zwift-offline/assets/123950591/35dd24c5-9ba2-4c82-a05c-20d9965b6bc3)

But using zoffline (level 39) if I change "ServerConfigXP" my profile is reset to level 0 and the game crashes when I click the menu button. Same thing if I import my online profile into zoffline.

https://github.com/zoffline/zwift-offline/blob/ec9329061b833c64591fc45da2e0ed19599c0cb1/variants.txt#L1038C23-L1038C23

**Comment by stapa** [comment]
Thank you @oldnapalm I partially tested your fix:

1. I was level 65 instantly, all stuff up to that level was unlocked.
2. The first attempt to start the ride crashed, the second was fine.
3. It fixed the XP points.
4. I'm plannig a proper ride for tomorrow.

![obrazek](https://github.com/zoffline/zwift-offline/assets/1619452/125f2e77-90b1-4405-a37f-37ab150997d8)
![ZwiftXPstreak-fixed](https://github.com/zoffline/zwift-offline/assets/1619452/21ced9bb-fdd6-40ba-821c-97ec61972815)

**Comment by jricoclq** [comment]
> Zwift now expects an "economy config" in login response, see https://github.com/zoffline/zwift-offline/tree/economy_config
> 
> Although, after adding this response (obtained from level 1 online trial account), I got an immediate level promotion using my offline profile. I guess it's due to lacking "transitionStart" and "transitionEnd" fields (these values probably depend on current level and XP points).
> 
> If you want to test, make sure to backup your profile. Windows exe is available in https://github.com/zoffline/zwift-offline/actions/runs/7422347446 artifact.

After taking this step, my level has changed to level 100. What is the reason for this?
Previously, it was normal to increase from level 59 to level 60, and then level 60 experience did not increase.
![80525c2eecb57c2c60555f487f0dd7e](https://github.com/zoffline/zwift-offline/assets/102775665/3153c6e2-7988-4ae6-9a6e-4f4df38c09bc)

**Comment by oldnapalm** [comment]
> After taking this step, my level has changed to level 100. What is the reason for this?

Reason is unknown, this is just a test, it's far from being a proper fix. I guess it's because you already have enough XP to be level 100 (see article linked in OP), same reason @stapa went from level 37 to 65.

There are new fields in player profile (see https://github.com/zoffline/zwift-offline/commit/79a4fb6c5ce4e2f07e34c4abaee96f466ca97ffe) which need investigation. Maybe some of those fields need to be handled server side, together with the "transition" fields in economy config, to achieve the same progress pace as the official server (with accelerated leveling and discounts). Honestly I don't think it's worth.

**Comment by jricoclq** [comment]
> > After taking this step, my level has changed to level 100. What is the reason for this?
> 
> Reason is unknown, this is just a test, it's far from being a proper fix. I guess it's because you already have enough XP to be level 100 (see article linked in OP), same reason @stapa went from level 37 to 65.
> 
> There are new fields in player profile (see [79a4fb6](https://github.com/zoffline/zwift-offline/commit/79a4fb6c5ce4e2f07e34c4abaee96f466ca97ffe)) which need investigation. Maybe some of those fields need to be handled server side, together with the "transition" fields in economy config, to achieve the same progress pace as the official server (with accelerated leveling and discounts). Honestly I don't think it's worth.

Okay, thank you very much.

**Comment by oldnapalm** [comment]
This is a simple way to preserve the current level and enable the new levels, but you will lose your XP https://github.com/zoffline/zwift-offline/commit/18d0771bf1b097dd3d94d16077ed9be353114125 (exe in https://github.com/zoffline/zwift-offline/actions/runs/7432235585).

Notice that you must use the profile backup from before the first test.

**Comment by stapa** [comment]
Ride done, everything works. Agree with @oldnapalm we don't need accelerated leveling and discounts.

**Comment by oldnapalm** [comment]
@stapa what did you test? Moving to level 65 or reducing XP to stay on 37?

Actually I don't think it's a good idea to modify the profile, I prefer leaving it to the client.

@jricoclq if you want to play levels 60-100 you can modify the file economy_config.txt to your liking. This script will add an offset to all levels from current and set the transition limits

```python
import json
import protobuf.profile_pb2

profile = protobuf.profile_pb2.PlayerProfile()
with open('storage/1/profile.bin', 'rb') as f:
    profile.ParseFromString(f.read())

with open('economy_config.txt') as f:
    economy_config = json.load(f)

current_level = profile.achievement_level // 100
print('Current level:', current_level, '\nXP:', profile.total_xp)
levels = [x for x in economy_config['cyclingLevels'] if x['level'] >= current_level]
if len(levels) > 1 and profile.total_xp > levels[1]['xp']:
    offset = profile.total_xp - levels[0]['xp']
    print('Offset:', offset)
    levels = [x for x in economy_config['cyclingLevels'] if x['xp'] < profile.total_xp]
    transition_end = levels[-1]['level'] if len(levels) > 0 else 100
    print('Transition start:', current_level, '\nTransition end:', transition_end)
    for level in economy_config['cyclingLevels']:
        if level['level'] >= current_level:
            level['xp'] += offset
    economy_config['transition_start'] = current_level
    economy_config['transition_end'] = transition_end
    with open('economy_config.txt', 'w') as f:
        json.dump(economy_config, f, indent=2)
```

**Comment by jricoclq** [comment]
> @stapa what did you test? Moving to level 65 or reducing XP to stay on 37?
> 
> Actually I don't think it's a good idea to modify the profile, I prefer leaving it to the client.
> 
> @jricoclq if you want to play levels 60-100 you can modify the file economy_config.txt to your liking. This script will add an offset to all levels from current and set the transition limits
> 
> Edit: I merged the script in [6324bde](https://github.com/zoffline/zwift-offline/commit/6324bdee090fdd2d9d6639b5ccb71852b68b2d92), it will save a custom economy_config.txt in the profile directory (exe in https://github.com/zoffline/zwift-offline/actions/runs/7440827661). I'm not sure about the transition values or if it makes any difference (at least the wheelie icon appears).

OK，tks

**Comment by stapa** [comment]
I tested the version mentioned below at level 65.

> Forgot to add the config parameters to the exe, this one should work https://github.com/zoffline/zwift-offline/actions/runs/7423228737

**Comment by oldnapalm** [comment]
I'm merging the version that creates a custom economy config staring at the current level if the player has more XP than the required for the next level, so by default the level will be kept and the requirements for the remaining levels will be according to the new system (except for accelerated leveling and discounts which I won't investigate for now). Players who have enough XP to be at a higher level on the new system and want to move instantly can just copy the default config file from the repo to their profile folder, overwriting the generated one.
