### ISSUE TITLE
cannot find ~/Library/Application Support/Zwift/ZwiftMac_ver_cur.xml with zwift version 1.1.11(1)

### ISSUE THREAD

**Issue by Nannnnnn** [zoffline/zwift-offline#296]
Hi, I cannot find the file while configuring Zwift to MacOs, https://github.com/zoffline/zwift-offline?tab=readme-ov-file#step-2-configure-zwift-client-to-use-zoffline. Will it be a probelm if I just ingore it?

**Comment by fatsbrown** [comment]
Hello.

You don't need that file because zoffline is up to date with latest Zwift version, but anyway it should be there. Notice that ~/Library/Application Support/Zwift is downloaded when you run Zwift for the first time.

**Comment by Nannnnnn** [comment]
> Hello.
> 
> You don't need that file because zoffline is up to date with latest Zwift version, but anyway it should be there. Notice that ~/Library/Application Support/Zwift is downloaded when you run Zwift for the first time.

Super and i didn't expect such a prompt reply! thanks for that! and you are exactly right about the file, I checked accountant of it after executing the program and they are matched! Really impressive! No, I'm just wondering how to keep zwift and zoff synced during the time. is it more like an event trigger manner?

**Comment by fatsbrown** [comment]
That file is present in the repo to avoid Zwift updating while zoffline is active. If you disable zoffline (comment out the line in /etc/hosts) and Zwift updates, then you can copy the updated file to avoid Zwift downgrading when you use zoffline. But it's not guaranteed that it will work, the best practice is updating zoffline from the repo (if an update is available of course).
