### ISSUE TITLE
Uploading Rides to Zwift

### ISSUE THREAD

**Issue by xflyinghighx** [zoffline/zwift-offline#297]
First of all i want to say that this a great projectwith awesome work.

Im using Zwift on Windows 10. I managed to use my Zwift profile with Zwift offline and I did a ride. Afterwards I could not figure out, how I can upload the ride and the progress of my profile to the Zwift servers. Any help on how to do this would be appreciated.

**Comment by fatsbrown** [comment]
Activities can be uploaded by saving Zwift credentials in launcher Settings/Zwift. Profile progress can't be uploaded.

**Comment by xflyinghighx** [comment]
Ok. That is what I thought I had to do. But sadly this does not work for me. I always get the folowing: Error saving C:\Program Files (x86)\Zwoffline/storage\1\zwift_credentials.bin

I must be missing something.

**Comment by fatsbrown** [comment]
Try moving the folder "Zwoffline" to somewhere you have write permission or run zoffline as administrator. Looks like your user can't write to "C:\Program Files (x86)".

**Comment by xflyinghighx** [comment]
I found the error myself. Thanks for helping me
