### ISSUE TITLE
past zwift workouts can be imported

### ISSUE THREAD

**Issue by mesterumanele** [zoffline/zwift-offline#299]
Hello, 
i discovered an old account that has 5 long-hard rides; is it possible to add those rides to the actual activities?
Thank you

**Comment by fatsbrown** [comment]
Hello.

It's possible by editing the database manually, you can use https://sqlitebrowser.org/

It can be simple if the activities are in the same database (just change the player_id), but can be trickier if it's another database.

**Comment by mesterumanele** [comment]
Hello,
Thank you for reply; sorry if i didn't explain correctly: my discovered account is a normal online zwifft account that has 5 long rides (i guess i got 1 week free) my question refers to these 5 activities if they can be combined with my actual zofflne?)
Thank you again

**Comment by fatsbrown** [comment]
zoffline does not support importing online activities, only online profile and achievements can be imported.
