### ISSUE TITLE
AH00534: httpd: Configuration error: No MPM loaded.

### ISSUE THREAD

**Issue by oldnapalm** [zoffline/zwift-offline#3]
zwift-offline exits because apache fails to start with error "AH00534: httpd: Configuration error: No MPM loaded."

Needed to add "LoadModule mpm_event_module modules/mod_mpm_event.so" to httpd.conf

**Comment by zoffline** [comment]
Thanks for reporting! Looks like they changed the httpd docker image to use shared MPM modules... bet that broke more than a few docker images.
