### ISSUE TITLE
can't import certificate in windows 7

### ISSUE THREAD

**Issue by Dmitriy260190** [zoffline/zwift-offline#30]
dont work. 

step 2
Open Command Prompt as an admin, cd to that location and run
certutil.exe -importpfx Root cert-zwift-com.p12

result:
![Безымянный](https://user-images.githubusercontent.com/58209615/69612495-d7a3a980-1040-11ea-992f-bf12291be3d2.jpg)

win7

**Comment by oldnapalm** [comment]
Looks like you are missing the file name (cert-zwift-com.p12) in the command line.

**Comment by Dmitriy260190** [comment]
> Looks like you are missing the file name (cert-zwift-com.p12) in the command line.


![Безым878755янный](https://user-images.githubusercontent.com/58209615/69623378-d465e900-1053-11ea-95a1-3b424cc190c3.jpg)

**Comment by oldnapalm** [comment]
Did you run command prompt as administrator?

Please translate the error messages to english.

**Comment by Dmitriy260190** [comment]
yes, run as admin

translate:
the command is NOT DONE
parameter set incorrectly

**Comment by oldnapalm** [comment]
Try

certutil.exe -importpfx Root cert-zwift-com.pem

**Comment by Dmitriy260190** [comment]
same result

**Comment by oldnapalm** [comment]
Try with CA instead of Root, or leave without CertificateStoreName

certutil.exe -importpfx CA cert-zwift-com.p12
certutil.exe -importpfx cert-zwift-com.pem

If it doesn't work try this to see help, maybe Windows 7 needs different parameters (I have only tried in Windows 10)

certutil.exe -?
certutil.exe -importpfx -?

**Comment by Dmitriy260190** [comment]
i try
certutil.exe -importpfx cert-zwift-com.p12

and see this
![Б34345677езымянный](https://user-images.githubusercontent.com/58209615/69638149-354ceb80-106b-11ea-92a5-f40fc4f76c5b.jpg)

translate:
"certificate added to store
command successfully executed"

this is what I need?

**Comment by oldnapalm** [comment]
Yes, I believe you can go on with further steps.

**Comment by Dmitriy260190** [comment]
thank u, friend
i will try to run later and tell here how it works.
thank u for help!

**Comment by oldnapalm** [comment]
Ok, no problem.

**Comment by Dmitriy260190** [comment]
then i start zwift after zoffline see this and forever loading
![Безымянный](https://user-images.githubusercontent.com/58209615/69656159-165d5200-1089-11ea-94b5-0c61b7cf4e14.jpg)

cmd screen
![Безы32423444мянный](https://user-images.githubusercontent.com/58209615/69656224-3856d480-1089-11ea-94cb-456111437e86.jpg)

**Comment by oldnapalm** [comment]
I believe your Zwift version is newer than 1.0.39812, you need to update zoffline. I don't know how to update the Windows .exe, I suggest that you install zoffline the normal way (not the simplest for Windows only) and then copy (don't move) the file `Zwift_ver_cur.xml` from `C:\Program Files (x86)\Zwift` to `zwift-offline-master\cdn\gameassets\Zwift_Updates_Root` (replace existing) before running zoffline.

**Comment by Dmitriy260190** [comment]
omg it works!
thank u again.

**Comment by oldnapalm** [comment]
You are welcome.

Please edit the issue title with something meaningful like "can't import certificate in windows 7", so someone with the same problem can find the solution here.

**Comment by zoffline** [comment]
Glad things are working. Thanks for providing all the support oldnapalm.
