### ISSUE TITLE
ConnectionResetError: [WinError 10054]  - windows 11 installation

### ISSUE THREAD

**Issue by ubbax** [zoffline/zwift-offline#301]
I ty to run zwift offline on windows 11 but I have some problems where I do not know how to overcome them.

What I did so far:
-	Installed latest Zwift 1.0.123458
-	Downloaded latest zwift-offline source code files (exe was blocked by my virus scan)
-	Configured the zwift client according “STEP 2”
-	Run the the standalone.py
-	Start Zwift with standalone.py running
What then happens is that zwift window opens and starts to download updates. After about 80% it it stops and I get a “error message”:
  File  File "C:\Users\klemt\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\gevent\ssl.py", line 673, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [WinError 10054] Eine vorhandene Verbindung wurde vom Remotehost geschlossen
2024-01-07T16:00:16Z <Greenlet at 0x25f0d6074c0: _handle_and_close_when_done(<bound method StreamServer.wrap_socket_and_handle , <bound method StreamServer.do_close of <WSGIServer, (<gevent._socket3.socket [closed] at 0x25f09648dc0)> failed with ConnectionResetError

Now I get the same error now everytime I run “standalone.py”. Independent from whether the computer is online or offline.
When I then also run Zwift then it is starting, but stops where I have to enter username and passwort saying that it was entered wrongly.
Any idea what I do wrong?

**Comment by fatsbrown** [comment]
This error usually means missing certificate in cacert.pem (step 2). Notice that this file is downloaded when you run Zwift for the first time.

If the update didn't finish, try to disable zoffline (comment out the line in hosts and close the launcher in system tray icon) and do a clean Zwift install. You should run Zwift before enabling zoffline and wait until the update finishes.

**Comment by ubbax** [comment]
this solved the problem!

Thanks a lot!
