### ISSUE TITLE
Database is not writable

### ISSUE THREAD

**Issue by JulBa408** [zoffline/zwift-offline#304]
Hello together,

I have just noticed, that my Zwift is not saving my activity to my account. 
After investigation I found out that terminal returns the following error, when I start standalone.py

ERROR:root:zwift-offline.db is not writable. Unable to upgrade database!

any ideas how to fix that?

Many thanks in advance!

**Comment by JulBa408** [comment]
Note for other users: fixed by changing the permissions for all users to write for the Zwift-offline.db.
Solved.

**Comment by fatsbrown** [comment]
Hello.

Make sure you have write permission to the storage directory because other files are saved (like storage\1\profile.bin), not only the database.
