### ISSUE TITLE
installing companion app

### ISSUE THREAD

**Issue by mesterumanele** [zoffline/zwift-offline#305]
Hello, 
just a small clarification on this note:
"you can create a fake-dns.txt file in the storage directory"
my questions are: 

- [ ] what this file should have inside? same info as hosts.txt?
- [ ] and storage directory is in the computer were zoffline is running?

Thank you

**Comment by fatsbrown** [comment]
Hello.

> what this file should have inside? same info as hosts.txt?

It does not need any content, just create an empty file.

> and storage directory is in the computer were zoffline is running?

Yes, inside zoffline directory.

**Comment by mesterumanele** [comment]
Hello again,
thanks for help; i made it work. i see the riders from the screen on the
companion app, on the correct order; but when i click on a name all is
empty...

all i can see is map, and i can change views;

my question: is this normal behaviour? if yes, please ignore my email.
Thank you again

**Comment by fatsbrown** [comment]
If they are bots it's normal. If they are real riders you should see their data.

**Comment by mesterumanele** [comment]
Hello,

Sorry, just have this question, last!

The apk should be build every time there is a new update of the companion
app? (in order to have better/more features? or same apk can run for long
time?

Thank you

**Comment by fatsbrown** [comment]
Have to wait and see. Based on past updates, not all bring new features and some require zoffline update to work (like when routes and segments were added to companion).

**Comment by mesterumanele** [comment]
Hello,
just come back to this question a bit; I understand that bots have empty,
but i did check every single rider and were all empty! is that possible? or
only a certain type of ride have real riders? or is there a certain type or
feature to identify real riders (i guess one of them is if the rider is not
vingegaard or pogacar... but even them, i can give my own name lance
armstrong, right?)

Thank you

**Comment by fatsbrown** [comment]
By "real riders" I mean other people connected to the same server (see https://github.com/zoffline/zwift-offline?tab=readme-ov-file#step-6-optional-enable-multiplayer). This is only possible if they are on the same network or if you setup an online server (like https://github.com/oldnapalm/zwift-offline/wiki/Creating-a-server-on-Oracle-Cloud-Free-Tier).

**Comment by mesterumanele** [comment]
Hello, 

Just a quick note/question: companion app is great; i did install virtual and set up the dns1. (Should it matter? If i dont use virtual hosts the dns should pick up, no?) sometimes when i move between apps, my game gets stuck, i have to restart companion couple times; sometimes i see the name of real zwift, sometimes the name off the zoffline, what i mean by all this is that is a bit unstable! My question is: just for me? Or is it normal? If normal, please ignore my note

Thank you

**Comment by fatsbrown** [comment]
The DNS method is an alternative to the Virtual Hosts app, you should not use both. If you change the DNS, zoffline must be running, otherwise Android will lose internet connection.

**Comment by mesterumanele** [comment]
Appreciate your fast reply: 
What are saying is use one or another; and the virtualhost is better. 
Thank you again
