### ISSUE TITLE
connect zwift profile error

### ISSUE THREAD

**Issue by Dmitriy260190** [zoffline/zwift-offline#31]
cant connect zwitf profile
email and password 100% correct
![Screenshot_1](https://user-images.githubusercontent.com/58209615/69904987-f26a7b00-13be-11ea-8a24-ac38bd023abc.jpg)

**Comment by oldnapalm** [comment]
You have to comment out (add # before) or delete the line added to hosts file before running the command. See "Enabling/Disabling zoffline" in README file.

**Comment by zoffline** [comment]
Problem solved Dmitriy?

**Comment by scouseman** [comment]
I am also having a problem connecting to my zwift profile.
I have ran the get_profile script successfully and it has created the profile.bin file.
I have put the profile.bin file into the storage folder but when I run zwift with zoffline, I cant get passed the zwift login page, error ' Failed to login check internet connection'
