### ISSUE TITLE
Possibility of adding workouts?

### ISSUE THREAD

**Issue by estebitistis** [zoffline/zwift-offline#310]
Thank you very much for the project! 

Do you finally have any way to add custom workouts?

Thx!!

**Comment by fatsbrown** [comment]
Put the ZWO files in the folder Documents\Zwift\Workouts\1

For Android you need to use Windows or Mac client to add the workouts. Once synchronized to zoffline they will appear on Android. Make sure to use only plain ASCII characters in the file name (no accents) otherwise they will not sync.

**Comment by estebitistis** [comment]
It works perfectly! Thank you very much! 

Once again, I want to thank you for the effort and dedication in this project! In my case, it contributes a lot to me, since I don't do races or online events, and I only do personalized workouts

thx for all!
