### ISSUE TITLE
zoffline on Synology via Docker?

### ISSUE THREAD

**Issue by tomh79** [zoffline/zwift-offline#311]
Would it be possible to run this on a Synology? If so - how would I have to set it up?

**Comment by fatsbrown** [comment]
Quoting a reply from a member of the Discord server (unfortunately I don't have access to a Synology NAS so can't give more details)

> I used to host my zoffline server on my SynologyNAS. I really never used the UI that comes from Synology to create my containers, I just SSH into it and used docker compose (on synology, you have to install docker compose by hand, since it doesn't have it -> this was like a year ago since I tried it, so maybe compose is already part of the Synology Docker package you will have to check).
> But yes, you can host zoffline on a Synology NAS

**Comment by tomh79** [comment]
Thanks! Which Discord was this on?
