### ISSUE TITLE
Certificate is asking for password

### ISSUE THREAD

**Issue by Reverbsz** [zoffline/zwift-offline#312]
Hi,

I have been trying to import ssl/cert-zwift-com.p12 on Mac but it keeps asking for password.

I left it blank but for some reason it keeps giving me an error.

macOS Monterey running zwift 126283.

Thank you.

**Comment by fatsbrown** [comment]
Hello. Try importing the PEM file instead.

**Comment by Reverbsz** [comment]
ok thanks

**Comment by Reverbsz** [comment]
All good.
