### ISSUE TITLE
Zwift stuck at login

### ISSUE THREAD

**Issue by Reverbsz** [zoffline/zwift-offline#313]
Hi, 

My zwift offline is stuck at this login. I am not sure what to do?

It says zoffline login (the password section is blank), below that says: Failed to log in. Check internet connection.

Thank you for the helps.

<img width="1251" alt="Screen Shot 2024-02-28 at 11 06 45 am" src="https://github.com/zoffline/zwift-offline/assets/107463683/8cef3e07-02a8-495b-914f-8ebbca50111f">

**Comment by fatsbrown** [comment]
Looks like you did not append the certificate from cert-zwift-com.pem to cacert.pem, or copied also the private key (lines 1 to 28) when you should copy only the certificate (lines 29 to 53).

**Comment by Reverbsz** [comment]
This is what I currently have, if I made a mistake is there a way to download the original cacert.pem?
![Screen Shot 2024-02-28 at 11 34 52 am](https://github.com/zoffline/zwift-offline/assets/107463683/153ab5e0-5730-4aa8-b947-dac5e9c26579)

**Comment by fatsbrown** [comment]
Just delete the private key (lines 3938 to 3965).

**Comment by Reverbsz** [comment]
Silly me, must have been copying the whole things. Thanks a lot, it all works now.
