### ISSUE TITLE
When I run standalone.py on my Mac, it doesn't work

### ISSUE THREAD

**Issue by Beansonwoo** [zoffline/zwift-offline#317]
When I run standalone.py, it shows like that:
INFO:zoffline:server-ip.txt not found, using 192.168.31.191
INFO:zoffline:Server is running.
But I'm running Zwift on the same PC, and Zwift cannot launch at all, Zwift version is 1.0.127000, macOS Sonoma 14.3.1
What can I do now?
<img width="569" alt="截屏2024-03-08 02 20 48" src="https://github.com/zoffline/zwift-offline/assets/162622305/d76423d0-5628-4b94-b76e-0a7253e61304">

**Comment by fatsbrown** [comment]
This is the expected zoffline behavior.

Have you configured Zwift client to use zoffline (step 2)?

**Comment by Beansonwoo** [comment]
Yes, I followed all the steps in Step 2, then opened Zwift, but it doesn’t work, Zwift can’t launch. I tried changing the IP addresses in the hosts file <zoffline ip> us-or-rly101.zwift.com secure.zwift.com cdn.zwift.com launcher.zwift.com to 127.0.0.1 and 192.168.31.191, but neither worked.

**Comment by Beansonwoo** [comment]
The problem occurred after me updated Zwift and zoffline today, I have reinstalled several times and every time I open the Zwift client, it only shows a blank page, and zoffline also doesn't display any information in the terminal.

**Comment by fatsbrown** [comment]
You probably made some mistake.

Notice that `<zoffline ip>` must be replaced with the IP address (I have seen people leaving the `<>`).

The line added to the hosts file must look like this

`127.0.0.1 us-or-rly101.zwift.com secure.zwift.com cdn.zwift.com launcher.zwift.com`

**Comment by Beansonwoo** [comment]
Wow you're so great! Thank you a lot! It works for me, I truly didn't remove the <>

**Comment by myjc1** [comment]
I still have this problem, but I had removed the <>.What can I do?

**Comment by fatsbrown** [comment]
Show your hosts file.

**Comment by myjc1** [comment]
<img width="662" alt="119173f8d416fa28f1bffb15cb335e9" src="https://github.com/zoffline/zwift-offline/assets/111404361/e50417a9-bfca-46ed-93f2-e9cd964cbbfc"
<img width="662" alt="119173f8d416fa28f1bffb15cb335e9" src="https://github.com/zoffline/zwift-offline/assets/111404361/e6870012-00a6-4614-8039-09c1faccaabc">

**Comment by fatsbrown** [comment]
Try running `ping launcher.zwift.com` in terminal and see if it resolves to 127.0.0.1

Don't you see any message in zoffline terminal when you run Zwift?

**Comment by myjc1** [comment]
![Uploading 微信图片_20240408223131.png…]()

**Comment by myjc1** [comment]
![1](https://github.com/zoffline/zwift-offline/assets/111404361/53a65b10-2463-4cc7-9456-dab31c3c0652)

**Comment by fatsbrown** [comment]
Until this part all looks correct. Don't you see the zoffline screen in the launcher?

> ![1](https://private-user-images.githubusercontent.com/111404361/320524664-53a65b10-2463-4cc7-9456-dab31c3c0652.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1ODk4NTYsIm5iZiI6MTcxMjU4OTU1NiwicGF0aCI6Ii8xMTE0MDQzNjEvMzIwNTI0NjY0LTUzYTY1YjEwLTI0NjMtNGNjNy05NDU2LWRhYjMxYzNjMDY1Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwOFQxNTE5MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YWM4MGU0ODNiMWM0N2EwY2ZlYzE0NjRlMzc2YmE2NTM2ZTE3ZTM1Y2Y4MTk3YmQ5Y2U1MGY2NGY0OGY2OTc4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.l91qUl51TyFa2T23CpquG6sDwC6MNI9YAGhCys7alSI)

**Comment by fatsbrown** [comment]
I mean Zwift launcher with zoffline content instead of default Zwift content.

![Captura de tela 2024-04-08 123437](https://github.com/zoffline/zwift-offline/assets/123950591/57c768d7-c5d5-4d5f-ae81-58da5a818544)

**Comment by myjc1** [comment]
Zwift screen still show the default content

**Comment by myjc1** [comment]
Unfortunately, I have not solved this problem so far.
