### ISSUE TITLE
Crashing after login - Mac Ventura

### ISSUE THREAD

**Issue by RNall17** [zoffline/zwift-offline#318]
I have followed the instructions as best I can, and attempted some of the fixes in resolved issues (e.g., editing the variants file as in issue #200 ).

I am able to log in and pair sensors, but the app crashes when attempting to ride or "just watch." Terminal shows Segmentation Fault: 11 after the crash. 
![Screenshot 2024-03-08 at 9 06 32 AM](https://github.com/zoffline/zwift-offline/assets/162513037/a45c518b-8b58-41ae-9278-f0d3932c5063)
This is the cacert file with the added certificate
![Screenshot 2024-03-08 at 9 06 50 AM](https://github.com/zoffline/zwift-offline/assets/162513037/eeece391-97cd-453d-8f3f-ae8f50fbcdfe)
I have also updated the ZwiftMac_Ver_Curr file in Zwift_Updates_Root

Lastly, here is the changed host file line.
![Screenshot 2024-03-08 at 9 07 13 AM](https://github.com/zoffline/zwift-offline/assets/162513037/ebf28fe8-7b3c-411f-830a-7a623fb29910)

Any help is much appreciated!

**Comment by fatsbrown** [comment]
> I have also updated the ZwiftMac_Ver_Curr file in Zwift_Updates_Root

You should not need to do that because zoffline is up to date with the latest Zwift client. If you are updating an old zoffline installation, you should update from the repository instead. If everything is up to date but the client still crashes, the file Log.txt (Documents/Zwift/Logs) may contain some hint about the crash reason.

**Comment by RNall17** [comment]
Thanks for the quick reply! 

I assumed this was updated, and I cloned the repo, so everything should be up to date. The variants file change wa removed after I tried it yesterday. 

Here is the last bit of the most recent log showing an internal server error. 
![Screenshot 2024-03-08 at 9 42 17 AM](https://github.com/zoffline/zwift-offline/assets/162513037/97d4c7b9-4ede-4290-b50a-85146c6d032d)

**Comment by fatsbrown** [comment]
Please show the zoffline output, it probably contains an error right before a `PUT /api/profiles/1/in-game-fields` request.

Make sure you have the versions of Python modules specified in the file requirements.txt

**Comment by RNall17** [comment]
Here is the zoffline output. You are correct that there is an error prior to PUT /api/profiles/1/in-game-fields
 ![Screenshot 2024-03-08 at 10 55 39 AM](https://github.com/zoffline/zwift-offline/assets/162513037/dffdcaa0-13ed-4529-8fea-f7acebc289bb)

I have checked permissions for both terminal and python, both have full access to all folders and docs in the documents folder. I toggled this off and back on to make sure, and still get the same error.

**Comment by fatsbrown** [comment]
It does look like a permission issue, odd because Python needs to be run as root to be able to bind to privileged ports.

I would try cloning the repository outside Documents (directly in your home directory).

This may help https://discuss.python.org/t/mac-ventura-permissions-error-with-os-module-solved/29580

**Comment by RNall17** [comment]
I seem to have fixed the permissions issue by manually granting all users read/write permissions to each of the files with a permissions error in the zoffline output (these persisted when cloning to the home directory). So, one step in the right direction!

However, now I get a broken pipe error with the same symptoms as before - zwift crashes after login. 
![Screenshot 2024-03-08 at 11 32 46 AM](https://github.com/zoffline/zwift-offline/assets/162513037/4ac468ad-a2bf-47e8-b04f-fa5740356fa4)

For what it's worth, I noticed the zwift username is now set to zoffline. Before, it was my username. Now it will log in no matter what password is input and I cannot change the username.

**Comment by RNall17** [comment]
@fatsbrown That was the remaining issue. You're a legend. After re-downloading the latest version of zwift and recopying the ZwiftMac_Ver_Curr file in Zwift_Updates_Root it seems to be working. You're patience and assistance are very much appreciated!

**Comment by fatsbrown** [comment]
Glad you got it working. One detail, I noticed there are no requests from the launcher in zoffline output, are you executing the app binary directly? The launcher is not mandatory but it has useful features (also skips the login screen where you mentioned the username is zoffline).

**Comment by RNall17** [comment]
To be perfectly honest, I have no idea how, but I think I was launching the app directly. When I reinstalled Zwift, there was a launcher screen that I cannot remember having seen before... In case it hasn't been readily apparent, I am not exactly well-versed in this level of computer detail. It is working now, however, and you're the one to thank. Hopefully, any other mac users as inept as me will find your useful comments here.
