### ISSUE TITLE
Upload bots 

### ISSUE THREAD

**Issue by Leenkss** [zoffline/zwift-offline#319]
Can i add more bots ?
Or update bots

**Comment by fatsbrown** [comment]
Bots are based on your past rides (ghosts), see https://github.com/zoffline/zwift-offline?tab=readme-ov-file#ghosts-and-bots

You can download the bots pack and set a multiplier value in the file enable_bots.txt (set 10 and you will have 4850 bots).

If you want to contribute with your bots, open a pull request to https://github.com/oldnapalm/zoffline-bots
