### ISSUE TITLE
Can't register with android client

### ISSUE THREAD

**Issue by Elixeer** [zoffline/zwift-offline#320]
Hi. I cant register using android. '192.168.0.101/signup' - file not found. Help please.
![Screenshot_2024-03-11-21-36-26-728_com android chrome](https://github.com/zoffline/zwift-offline/assets/163038141/c931b6b0-234d-4d1d-86d7-569a43f4af20)

**Comment by fatsbrown** [comment]
Hi. You must use HTTPS (https://192.168.0.101/signup/) and accept the self signed certificate (advanced).

Notice this is only required if you enabled multiplayer (step 6), otherwise you can type any username and password in the Zwift login screen.

**Comment by Elixeer** [comment]
thank you. But its written "wrong email/password" LOG:
Server is running.
192.168.0.100 - - [2024-03-11 22:24:51] "POST /auth/realms/zwift/protocol/openid-connect/token HTTP/1.1" 401 125 0.015590
192.168.0.100 - - [2024-03-11 22:24:51] "POST /auth/realms/zwift/protocol/openid-connect/token HTTP/1.1" 200 4622 0.140631

**Comment by fatsbrown** [comment]
If you enabled multiplayer, then you have to sign up (https://192.168.0.101/signup/) and type the username and password you signed up with.

**Comment by Elixeer** [comment]
Not works. I tried 2 times with two different accounts. Logs are thr same. 
In browser i can log in without problems, but cant in client

**Comment by fatsbrown** [comment]
The log should look like this

```
Server is running.
192.168.0.104 - - [2024-03-11 17:06:35] "GET /api/telemetry/config HTTP/1.1" 200 413 0.001521
192.168.0.104 - - [2024-03-11 17:06:35] "POST /hvc-ingestion-service/batch HTTP/1.1" 200 125 0.001484
192.168.0.104 - - [2024-03-11 17:06:54] "GET /api/auth HTTP/1.1" 200 215 0.000376
192.168.0.104 - - [2024-03-11 17:06:54] "POST /auth/realms/zwift/protocol/openid-connect/token HTTP/1.1" 200 3741 0.001099
192.168.0.104 - - [2024-03-11 17:06:54] "POST /api/users/login HTTP/1.1" 200 9362 0.002797
192.168.0.104 - - [2024-03-11 17:06:55] "GET /relay/worlds/hash-seeds HTTP/1.1" 200 199 0.000780
192.168.0.104 - - [2024-03-11 17:06:55] "GET /api/profiles/me HTTP/1.1" 200 3210 0.001477
```

Maybe you redirected only the secure subdomain and not us-or-rly101?

**Comment by fatsbrown** [comment]
Try to fully close and clear the app cache (Android settings - applications - Zwift - storage - clear cache).

**Comment by Elixeer** [comment]
My fault. It was mistake in ip of cdn server - 192.186.0.101. cured it and all works. Thank you!!
