### ISSUE TITLE
mac zoffline cannot find bluetooth device

### ISSUE THREAD

**Issue by kazuki-hehe** [zoffline/zwift-offline#321]
mac zoffline cannot find bluetooth
The official version can search for Bluetooth

**Comment by kazuki-hehe** [comment]
After deactivating the official Bluetooth device, the device still cannot be found.

**Comment by kazuki-hehe** [comment]
> 您是否在 zoffline 窗口中看到任何“未知功能”？

no

**Comment by kazuki-hehe** [comment]
> Do you see any "unknown feature" in the zoffline window?

did not see

**Comment by kazuki-hehe** [comment]
The same client only changed hosts. The official version can search for Bluetooth devices, but Zoffline cannot search for Bluetooth devices.

**Comment by fatsbrown** [comment]
There are various features in `data/variants.txt` regarding BLE, you can try to enable/disable them (the values are from a Windows client request, so they may be different for a Mac client)

```
game_1_21_ble_data_guard_v2
game_1_29_ble_middleware
game_1_34_cached_ble_service_filter
game_1_34_monitor_zc_ble_bridge_scanning
game_1_43_3_ble_dll_v2
game_1_44_ble_queue
game_1_45_0_ble_source_lock
game_1_49_ble_adv_fix_pc_android
game_1_52_ble_adv_sd
```

To disable, delete the line `"value": true,` below the `"name"` line if it exists. To enable, add that line if it does not exist.

**Comment by kazuki-hehe** [comment]
It is the Ziwft official version that records Bluetooth devices. You need to delete the Bluetooth configuration file in the Zwift official version.
