### ISSUE TITLE
companion question

### ISSUE THREAD

**Issue by mesterumanele** [zoffline/zwift-offline#322]
Hello, 
just a note: 
today companion didn't connect properly... few points:
- i connect through virtual host (i did this successfully until today, without changing anything in the meantime)
- it shows the map and zwifters correctly
- the problem was that the workout was greyed out, not populated with the work data; the pointer was at 0 all the time... i did try to reconnect many times...
- now, after 3h, i just tried again with another custom zwo file and it worked!... is it possible that the greyed out screen was because was an imported zwo file?, and is something with that file?
- my question is: the companion workout screen is working with all custom zwo files or only with some? is a problem with some zwo files that prevents companion workout to populate?

Thank you

**Comment by fatsbrown** [comment]
> my question is: the companion workout screen is working with all custom zwo files or only with some?

If I understand correctly, you already answered this question (it did not work with one, therefore it does not work with all).

> is a problem with some zwo files that prevents companion workout to populate?

I think this is very likely. The easier way to figure it out is investigating a file which does not work. Maybe you can attach it?

**Comment by mesterumanele** [comment]
Thank you for reply and here is the file. 
[10_376_tss61_gampenpass4.zip](https://github.com/zoffline/zwift-offline/files/14623850/10_376_tss61_gampenpass4.zip)

**Comment by fatsbrown** [comment]
This file has a `)` character after `<workout>` which probably should not be there. Other than that, if you compare this file with others created by Zwift, there are details which may cause problem, like missing `sportType` and different `tags` formatting (no `name` attribute).

**Comment by mesterumanele** [comment]
thank you again, i just did now tried another custom file, attached, and it worked, first try. these files are from same source, fulgaz; so going forward, in order for the companion to populate the workout screen would be better to chose system workouts instead of custom, which would be totally fine by me, or go through them and bring them to zwift standards

Thank you again
[13_252_tss53_Mulholland_Highway_Climb.zip](https://github.com/zoffline/zwift-offline/files/14624059/13_252_tss53_Mulholland_Highway_Climb.zip)

**Comment by fatsbrown** [comment]
Differently from the first file, this one does not have the extra `)` character, the problem could be that. You can confirm by deleting the said character from the first file and testing.

**Comment by mesterumanele** [comment]
i did try to edit 10.file but now it doesn't show in my zwiftonline custom files!? 
i see one 10.file inside zwift folder and same file inside zwiftonline under customworkouts... which should i edit? thanks again

**Comment by fatsbrown** [comment]
Edit both to be sure, I don't know which one is used by Companion.

Maybe it's better to rename the file.

**Comment by mesterumanele** [comment]
great. i just did another way: after i press on the custom file instead of pressing "Start ride" i did Edit and checkmark 'interval' and re-saved the file, so the system will clean/add tags/etc of the file... after this step, all my files that showed grey game screen, now they work! thank you for your pointers and quick answers!
