### ISSUE TITLE
Uploading activities to Strava

### ISSUE THREAD

**Issue by oldnapalm** [zoffline/zwift-offline#323]
The [Strava's New Developer Program](https://communityhub.strava.com/t5/developer-knowledge-base/our-developer-program/ta-p/8849) requests that all applications using their external API are submitted for review. The application used by zoffline can't comply and has stopped working, therefore users who have authorized activity uploading using the default client ID and secret will need to authorize again using their own API application, operating in "Single Player Mode".

# Authorizing activity uploading

* Get CLIENT_ID and CLIENT_SECRET from https://www.strava.com/settings/api
* __NOTE:__ instead of performing the steps below you can instead set the authorization callback domain of your API application to ``launcher.zwift.com`` and use the "Settings - Strava" button in the launcher window (Windows and macOS only).
* Run ``scripts/strava_auth.py --client-id CLIENT_ID --client-secret CLIENT_SECRET``
  * Or, if using the Windows zoffline.exe version without Python installed you can run ``strava_auth.exe`` obtained from https://github.com/zoffline/zwift-offline/releases/tag/zoffline_helper in place of ``scripts/strava_auth.py``
* Open http://localhost:8000/ and authorize.
* Move the resulting ``strava_token.txt`` into the ``storage/1`` directory.

**Comment by evgenybf** [comment]
@oldnapalm is this OK that when zwift launcher is used, the `strava-token.txt` file doesn't appear in the `storage` directory and there is no button to download it? As soon as the client is authorized, I get redirected back to the Config dialog.

**Comment by oldnapalm** [comment]
The file ``strava_token.txt`` should be created in the directory ``storage/1`` and the "Strava" button should become "Remove Strava token".

Do you see any error in the zoffline window?

**Comment by evgenybf** [comment]
No
```
INFO:zoffline:127.0.0.1 - - [2024-03-27 23:21:14] "GET /strava HTTP/1.1" 302 905 0.001001
INFO:stravalib.protocol.ApiV3:POST 'https://www.strava.com/oauth/token' with params {'client_id': xxx, 'client_secret': 'xxx', 'code': 'xxx', 'grant_type': 'authorization_code'} 
INFO:zoffline:127.0.0.1 - - [2024-03-27 23:21:19] "GET /authorization?state=&code=xxx&scope=read,activity:write HTTP/1.1" 302 537 0.599706
INFO:zoffline:127.0.0.1 - - [2024-03-27 23:21:19] "GET /settings/zoffline/ HTTP/1.1" 200 3630 0.001982
INFO:zoffline:127.0.0.1 - - [2024-03-27 23:21:19] "GET /style/site.css HTTP/1.1" 304 183 0.002012 
INFO:zoffline:127.0.0.1 - - [2024-03-27 23:21:19] "GET /style/background.jpg HTTP/1.1" 304 191 0.001003 
```

**Comment by evgenybf** [comment]
Hm.. but, now I see the file in `storage/1` and the button "Remove Strava token"

**Comment by evgenybf** [comment]
Deleted the file manually and it was successfully re-created via the dialog. My apologies then.  It works.

It may relate to the fact, that I set a proper `launcher.zwift.com` only today.

**Comment by oldnapalm** [comment]
> I notice you uploaded a new update, do you think installing this new version fixes the automatic update with Strava?

There was no change in zoffline regarding upload to Strava since this issue was open. If you already performed the steps described here, I suggest that you upload the FIT file manually to https://www.strava.com/upload/select and after your next activity, check the zoffline window for errors if the upload fails again.

Anyway, it's always a good idea to keep Zwift and zoffline up to date.

**Comment by oldnapalm** [comment]
@geovanni14 also check if your API app is authorized in https://www.strava.com/settings/apps

I've seen cases of Strava "losing" the authorization, even with the official Zwift server. If it's the case, remove the authorization in zoffline launcher and authorize again (or create a new strava_token.txt if you use the strava_auth script).

**Comment by geovanni14** [comment]
> @geovanni14 also check if your API app is authorized in https://www.strava.com/settings/apps
> 
> I've seen cases of Strava "losing" the authorization, even with the official Zwift server. If it's the case, remove the authorization in zoffline launcher and authorize again (or create a new strava_token.txt if you use the strava_auth script).

Hi @oldnapalm ; I installed the latest version (zoffline_1.0.138664.exe), then followed your instructions «remove the authorization in zoffline launcher and authorize again» and it worked!!!, thank you very much!!!!
