### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by mesterumanele** [zoffline/zwift-offline#324]
For the last 2 workouts the strava was not updated, only garmin! Should i remove strava token and redo the login? And if i'm on this screen, i noticed zwift tab; if i log in with zwift user/pass and check download achievements and upload activities, it will break anything on my setup? What's your recommendation? Thank you

**Comment by oldnapalm** [comment]
Please refer to #323

Downloading online profile/achievements will replace your local files, make sure to have a backup before trying, see #308

Closing as duplicate of #323
