### ISSUE TITLE
incline instead of erg on workout (just a note)

### ISSUE THREAD

**Issue by mesterumanele** [zoffline/zwift-offline#325]
Hello 
just used the last update and i noticed this: 
-if i choose a workout is not erg mode by default (before the update, same workout went into erg mode)
-on the companion i see incline; press it, and then it shows erg
-i tried 2 workouts and they did not go into erg mode; had to change manually to erg

Thank you

**Comment by fatsbrown** [comment]
Hi. Are you sure this is a Zwift-offline issue? Have you tested with normal (online) Zwift?

**Comment by mesterumanele** [comment]
Hi, 
-just did try online and workout is not loaded in erg; i have to manually switch it to erg! 

Thank you

**Comment by fatsbrown** [comment]
Not a Zwift-offline issue then, it's a change (intentional or bug) in the Zwift update.
