### ISSUE TITLE
Is there a new version of Zwift

### ISSUE THREAD

**Issue by jbiribi** [zoffline/zwift-offline#326]
I downloaded the Zwift app for windows, but when I opened the instaler, the version was 1.1.128160, but zoffline is for 1.0.128160. Is there a new version or is it the same?

**Comment by fatsbrown** [comment]
The latest Zwift version is 1.0.128160, there is no 1.1.128160.

The latest version of the launcher is 1.1.12, it's a different thing.

https://forums.zwift.com/t/what-are-the-latest-zwift-game-and-zwift-companion-app-version-numbers/486839
