### ISSUE TITLE
how to display or own all items in MY GARAGE ?

### ISSUE THREAD

**Issue by jricoclq** [zoffline/zwift-offline#328]
May I ask how to display or own all items in MY GARAGE, such as frame wheels and jersey and so on, except for those purchased in the DROP SHOP? Thanks a lot!
![image](https://github.com/zoffline/zwift-offline/assets/102775665/d924b4a2-f792-4073-9339-5fd2f1d75a08)

**Comment by fatsbrown** [comment]
I don't know an easy way to do that.

Most items are level locked, so being at level 100 you should already own them.

Some items are unlocked when you complete a challenge, like the Tron bike when you climb 50.000 meters in the Everest challenge. You can hack the profile and add `elevation_gain_in_meters` (after selecting the challenge) as explained in #308.

Some items are "entitlements", a way to get them in zoffline is setting as `entitlement_2` in `storage/1/economy_config.txt` for levels you have already achieved. For example, replace `"entitlement_2": "ENTITLEMENT_NONE"` by `"entitlement_2": "ENTITLEMENT_BIKE_PINARELLODOGMAX2024"`. You can find them in `C:\Program Files (x86)\Zwift\assets\global.wad\Entitlements.xml`.

```
Game 1.52.0
ENTITLEMENT_CYCLING_HEADGEAR_ONBOARDINGHELMET
ENTITLEMENT_CYCLING_JERSEY_CLUBS_BACKPEDAL2023
ENTITLEMENT_CYCLING_JERSEY_CLUBS_EZR2023
ENTITLEMENT_CYCLING_JERSEY_EVENTS_NOVEMBERFONDO2023
ENTITLEMENT_CYCLING_JERSEY_EVENTS_DECEMBERFONDO2023
ENTITLEMENT_CYCLING_JERSEY_CLUBS_TEAMCASTELLI2023
ENTITLEMENT_CYCLING_JERSEY_CLUBS_ABUSSYNERGYMEN2023
ENTITLEMENT_PAINTJOB_ZWIFTACADEMY2023
Game 1.53.0
ENTITLEMENT_CYCLING_JERSEY_CLUBS_EINTRACHTFRANKFURT2023
ENTITLEMENT_CYCLING_JERSEY_CLUBS_ZIRT2023
ENTITLEMENT_CYCLING_JERSEY_CLUBS_BL13LADIES2023
ENTITLEMENT_CYCLING_JERSEY_CLUBS_ABUSSYNERGYLADIES2023
ENTITLEMENT_CYCLING_JERSEY_CLUBS_PRIMORRWBESPORTS2023
ENTITLEMENT_CYCLING_JERSEY_PRO_TEAMS_TWENTY242024
ENTITLEMENT_CYCLING_JERSEY_CLUBS_5W4T2023
ENTITLEMENT_CYCLING_JERSEY_CLUBS_BASEPERFORMANCE2023
ENTITLEMENT_CYCLING_JERSEY_CLUBS_WLBB2023
ENTITLEMENT_CYCLING_JERSEY_CLUBS_CHASINGRACING2023
ENTITLEMENT_CYCLING_JERSEY_CLUBS_TOYOTAELITE2023
ENTITLEMENT_CYCLING_JERSEY_CLUBS_ZTBR2023
ENTITLEMENT_CYCLING_JERSEY_CLUBS_PAINCAVEHEROES2023
ENTITLEMENT_CYCLING_JERSEY_CLUBS_SUNRISERACING2023
Game 1.54.0
ENTITLEMENT_RUNNING_OUTFIT_TOURDEZWIFT2024
ENTITLEMENT_CYCLING_JERSEY_EVENTS_JANUARYFONDO2023
ENTITLEMENT_RUNNING_SHORTS_INNOVATIONRUNNING2023
ENTITLEMENT_RUNNING_SHORTS_FILMMYRUN2023
ENTITLEMENT_CYCLING_JERSEY_CLUBS_COALITIONALPHAMEN2023
ENTITLEMENT_CYCLING_JERSEY_CLUBS_COALITIONALPHAWMN2023
ENTITLEMENT_CYCLING_JERSEY_CLUBS_METIER2023
ENTITLEMENT_CYCLING_JERSEY_CLUBS_AMANI2023
ENTITLEMENT_CYCLING_JERSEY_CLUBS_HPLCYCLING2023
ENTITLEMENT_RUNNING_OUTFIT_ZLDR2023
ENTITLEMENT_CYCLING_JERSEY_EVENTS_RAPHA5002023
Game 1.55.0
ENTITLEMENT_CYCLING_JERSEY_CLUBS_DODDIEAID2024
ENTITLEMENT_RUNNING_SHIRT_TUGAZRUN2023
Game 1.56.0
ENTITLEMENT_CYCLING_JERSEY_COMPANIES_LETAPE2024
Game 1.56.0
ENTITLEMENT_CYCLING_JERSEY_PRO_TEAMS_USAC_CHAMP2024
ENTITLEMENT_CYCLING_JERSEY_PRO_TEAMS_CYCLINGCANADA_CHAMP2024
ENTITLEMENT_CYCLING_JERSEY_DCF_CHAMPS2024
ENTITLEMENT_CYCLING_JERSEY_FFC_CHAMPS2024
ENTITLEMENT_CYCLING_JERSEY_PRO_TEAMS_FDJSUEZ2024
ENTITLEMENT_CYCLING_JERSEY_PRO_TEAMS_MOVISTAR2024
ENTITLEMENT_CYCLING_JERSEY_PRO_TEAMS_INEOS2024
ENTITLEMENT_CYCLING_JERSEY_PRO_TEAMS_CANYONSRAMRACING2024
ENTITLEMENT_CYCLING_JERSEY_PRO_TEAMS_PROJECTECHELON2024
Game 1.57.0
ENTITLEMENT_SOCKS_SOCKS_ZWIFTGAMES2024
ENTITLEMENT_CYCLING_GLOVES_ZWIFTGAMES2024
ENTITLEMENT_CYCLING_HEADGEAR_CYCLINGCAPZWIFTGAMESGOLDCAP2024
ENTITLEMENT_CYCLING_JERSEY_EVENTS_ZWIFTGAMESKIT2024
ENTITLEMENT_CYCLING_SHOES_ADIDASTEMPOBOA2024L
ENTITLEMENT_CYCLING_JERSEY_EVENTS_TOUROFMARCH2024
ENTITLEMENT_CYCLING_HEADGEAR_BIGSPIN2024
ENTITLEMENT_WHEELS_ZWIFTBIGSPIN2024
ENTITLEMENT_CYCLING_HEADGEAR_HEADPHONESBIGSPIN2024
ENTITLEMENT_CYCLING_SHOES_BIGSPIN2024L
ENTITLEMENT_SOCKS_SOCKS_BIGSPIN
Game 1.58.0
ENTITLEMENT_CYCLING_HEADGEAR_BUCKETHAT_BIGSPINUNIONFLAG2024
ENTITLEMENT_CYCLING_JERSEY_EVENTS_SUNFLOWERKIT2024
ENTITLEMENT_CYCLING_JERSEY_ORIGINALS_BIGSPIN2024MAKURIKIT
ENTITLEMENT_CYCLING_JERSEY_EVENTS_TOMUNDERGROUNDMAP2024
ENTITLEMENT_GLASSES_BIGSPINGLASSES2024
ENTITLEMENT_RUNNING_HEADGEAR_BACKWARDSBASEBALLCAP2024
ENTITLEMENT_CYCLING_JERSEY_ORIGINALS_BASEBALLKIT2024
ENTITLEMENT_BIKE_ZWIFTCONCEPTGOLD
ENTITLEMENT_RUNNING_HEADGEAR_CYCLINGCAP_BIGSPINBERET2024
ENTITLEMENT_BIKE_ZWIFTBIGSPINCRUISER2024
Game 1.59.0
ENTITLEMENT_GLASSES_OAKLEYSPHAERA
Game 1.60.0
ENTITLEMENT_CYCLING_HEADGEAR_CYCLINGCAPSPRINGTRAININGHAT2024
ENTITLEMENT_GLASSES_SPRINGTRAININGSUNGLASSES2024
ENTITLEMENT_CYCLING_JERSEY_ORIGINALS_SPRINGTRAINING2024
Game 1.60.0
ENTITLEMENT_CYCLING_JERSEY_PRO_TEAMS_SCFCHAMP2024
ENTITLEMENT_CYCLING_JERSEY_PRO_TEAMS_AUSCYCLINGCHAMP2024
ENTITLEMENT_SOCKS_SOCKS_CONFETTITRAILS
Game 1.62.0
ENTITLEMENT_CYCLING_JERSEY_EVENTS_SLT2024BLUE
ENTITLEMENT_CYCLING_JERSEY_EVENTS_SLT2024GREEN
ENTITLEMENT_CYCLING_JERSEY_EVENTS_SLT2024GREY
ENTITLEMENT_CYCLING_JERSEY_EVENTS_SLT2024ORANGE
ENTITLEMENT_CYCLING_JERSEY_EVENTS_SLT2024PALEBLUE
ENTITLEMENT_CYCLING_JERSEY_EVENTS_SLT2024PALEGREEN
ENTITLEMENT_CYCLING_JERSEY_EVENTS_SLT2024PALEORANGE
ENTITLEMENT_CYCLING_JERSEY_EVENTS_SLT2024PINK
ENTITLEMENT_CYCLING_JERSEY_EVENTS_SLT2024PURPLE
ENTITLEMENT_CYCLING_JERSEY_EVENTS_SLT2024RED
ENTITLEMENT_RUNNING_SHIRT_SLT2024BLUE
ENTITLEMENT_RUNNING_SHIRT_SLT2024GREEN
ENTITLEMENT_RUNNING_SHIRT_SLT2024GREY
ENTITLEMENT_RUNNING_SHIRT_SLT2024ORANGE
ENTITLEMENT_RUNNING_SHIRT_SLT2024PALEBLUE
ENTITLEMENT_RUNNING_SHIRT_SLT2024PALEGREEN
ENTITLEMENT_RUNNING_SHIRT_SLT2024PALEORANGE
ENTITLEMENT_RUNNING_SHIRT_SLT2024PINK
ENTITLEMENT_RUNNING_SHIRT_SLT2024PURPLE
ENTITLEMENT_RUNNING_SHIRT_SLT2024RED
ENTITLEMENT_RUNNING_SHORTS_SLT2024
Game 1.63.0
ENTITLEMENT_BIKE_PINARELLODOGMAX2024
```

**Comment by jricoclq** [comment]
I just tested it and it works. Thank you very much, big PRO!

**Comment by jricoclq** [comment]
Can you help me extract the Entitlements.XML file? I am unable to extract it.

**Comment by fatsbrown** [comment]
I used this https://github.com/ursoft/zwift-offline/tree/master/scripts/wad_unpack

**Comment by jricoclq** [comment]
How to use it？

> I used this https://github.com/ursoft/zwift-offline/tree/master/scripts/wad_unpack

**Comment by fatsbrown** [comment]
Need to build it, then run the executable passing the WAD file as argument, or use the Total Commander WCX plugin. But you don't really need to, I posted all the entitlements above. If you really want, search how to build Visual Studio solution.

**Comment by jricoclq** [comment]
I just want this Entitlements.xml file. thank you.

**Comment by jricoclq** [comment]
> I don't know an easy way to do that.
> 
> Most items are level locked, so being at level 100 you should already own them.
> 
> Some items are unlocked when you complete a challenge, like the Tron bike when you climb 50.000 meters in the Everest challenge. You can hack the profile and add `elevation_gain_in_meters` (after selecting the challenge) as explained in #308.
> 
> Some items are "entitlements", a way to get them in zoffline is setting as `entitlement_2` in `storage/1/economy_config.txt` for levels you have already achieved. For example, replace `"entitlement_2": "ENTITLEMENT_NONE"` by `"entitlement_2": "ENTITLEMENT_BIKE_PINARELLODOGMAX2024"`. You can find them in `C:\Program Files (x86)\Zwift\assets\global.wad\Entitlements.xml`.
> 
> ```
> Game 1.52.0
> ENTITLEMENT_CYCLING_HEADGEAR_ONBOARDINGHELMET
> ENTITLEMENT_CYCLING_JERSEY_CLUBS_BACKPEDAL2023
> ENTITLEMENT_CYCLING_JERSEY_CLUBS_EZR2023
> ENTITLEMENT_CYCLING_JERSEY_EVENTS_NOVEMBERFONDO2023
> ENTITLEMENT_CYCLING_JERSEY_EVENTS_DECEMBERFONDO2023
> ENTITLEMENT_CYCLING_JERSEY_CLUBS_TEAMCASTELLI2023
> ENTITLEMENT_CYCLING_JERSEY_CLUBS_ABUSSYNERGYMEN2023
> ENTITLEMENT_PAINTJOB_ZWIFTACADEMY2023
> Game 1.53.0
> ENTITLEMENT_CYCLING_JERSEY_CLUBS_EINTRACHTFRANKFURT2023
> ENTITLEMENT_CYCLING_JERSEY_CLUBS_ZIRT2023
> ENTITLEMENT_CYCLING_JERSEY_CLUBS_BL13LADIES2023
> ENTITLEMENT_CYCLING_JERSEY_CLUBS_ABUSSYNERGYLADIES2023
> ENTITLEMENT_CYCLING_JERSEY_CLUBS_PRIMORRWBESPORTS2023
> ENTITLEMENT_CYCLING_JERSEY_PRO_TEAMS_TWENTY242024
> ENTITLEMENT_CYCLING_JERSEY_CLUBS_5W4T2023
> ENTITLEMENT_CYCLING_JERSEY_CLUBS_BASEPERFORMANCE2023
> ENTITLEMENT_CYCLING_JERSEY_CLUBS_WLBB2023
> ENTITLEMENT_CYCLING_JERSEY_CLUBS_CHASINGRACING2023
> ENTITLEMENT_CYCLING_JERSEY_CLUBS_TOYOTAELITE2023
> ENTITLEMENT_CYCLING_JERSEY_CLUBS_ZTBR2023
> ENTITLEMENT_CYCLING_JERSEY_CLUBS_PAINCAVEHEROES2023
> ENTITLEMENT_CYCLING_JERSEY_CLUBS_SUNRISERACING2023
> Game 1.54.0
> ENTITLEMENT_RUNNING_OUTFIT_TOURDEZWIFT2024
> ENTITLEMENT_CYCLING_JERSEY_EVENTS_JANUARYFONDO2023
> ENTITLEMENT_RUNNING_SHORTS_INNOVATIONRUNNING2023
> ENTITLEMENT_RUNNING_SHORTS_FILMMYRUN2023
> ENTITLEMENT_CYCLING_JERSEY_CLUBS_COALITIONALPHAMEN2023
> ENTITLEMENT_CYCLING_JERSEY_CLUBS_COALITIONALPHAWMN2023
> ENTITLEMENT_CYCLING_JERSEY_CLUBS_METIER2023
> ENTITLEMENT_CYCLING_JERSEY_CLUBS_AMANI2023
> ENTITLEMENT_CYCLING_JERSEY_CLUBS_HPLCYCLING2023
> ENTITLEMENT_RUNNING_OUTFIT_ZLDR2023
> ENTITLEMENT_CYCLING_JERSEY_EVENTS_RAPHA5002023
> Game 1.55.0
> ENTITLEMENT_CYCLING_JERSEY_CLUBS_DODDIEAID2024
> ENTITLEMENT_RUNNING_SHIRT_TUGAZRUN2023
> Game 1.56.0
> ENTITLEMENT_CYCLING_JERSEY_COMPANIES_LETAPE2024
> Game 1.56.0
> ENTITLEMENT_CYCLING_JERSEY_PRO_TEAMS_USAC_CHAMP2024
> ENTITLEMENT_CYCLING_JERSEY_PRO_TEAMS_CYCLINGCANADA_CHAMP2024
> ENTITLEMENT_CYCLING_JERSEY_DCF_CHAMPS2024
> ENTITLEMENT_CYCLING_JERSEY_FFC_CHAMPS2024
> ENTITLEMENT_CYCLING_JERSEY_PRO_TEAMS_FDJSUEZ2024
> ENTITLEMENT_CYCLING_JERSEY_PRO_TEAMS_MOVISTAR2024
> ENTITLEMENT_CYCLING_JERSEY_PRO_TEAMS_INEOS2024
> ENTITLEMENT_CYCLING_JERSEY_PRO_TEAMS_CANYONSRAMRACING2024
> ENTITLEMENT_CYCLING_JERSEY_PRO_TEAMS_PROJECTECHELON2024
> Game 1.57.0
> ENTITLEMENT_SOCKS_SOCKS_ZWIFTGAMES2024
> ENTITLEMENT_CYCLING_GLOVES_ZWIFTGAMES2024
> ENTITLEMENT_CYCLING_HEADGEAR_CYCLINGCAPZWIFTGAMESGOLDCAP2024
> ENTITLEMENT_CYCLING_JERSEY_EVENTS_ZWIFTGAMESKIT2024
> ENTITLEMENT_CYCLING_SHOES_ADIDASTEMPOBOA2024L
> ENTITLEMENT_CYCLING_JERSEY_EVENTS_TOUROFMARCH2024
> ENTITLEMENT_CYCLING_HEADGEAR_BIGSPIN2024
> ENTITLEMENT_WHEELS_ZWIFTBIGSPIN2024
> ENTITLEMENT_CYCLING_HEADGEAR_HEADPHONESBIGSPIN2024
> ENTITLEMENT_CYCLING_SHOES_BIGSPIN2024L
> ENTITLEMENT_SOCKS_SOCKS_BIGSPIN
> Game 1.58.0
> ENTITLEMENT_CYCLING_HEADGEAR_BUCKETHAT_BIGSPINUNIONFLAG2024
> ENTITLEMENT_CYCLING_JERSEY_EVENTS_SUNFLOWERKIT2024
> ENTITLEMENT_CYCLING_JERSEY_ORIGINALS_BIGSPIN2024MAKURIKIT
> ENTITLEMENT_CYCLING_JERSEY_EVENTS_TOMUNDERGROUNDMAP2024
> ENTITLEMENT_GLASSES_BIGSPINGLASSES2024
> ENTITLEMENT_RUNNING_HEADGEAR_BACKWARDSBASEBALLCAP2024
> ENTITLEMENT_CYCLING_JERSEY_ORIGINALS_BASEBALLKIT2024
> ENTITLEMENT_BIKE_ZWIFTCONCEPTGOLD
> ENTITLEMENT_RUNNING_HEADGEAR_CYCLINGCAP_BIGSPINBERET2024
> ENTITLEMENT_BIKE_ZWIFTBIGSPINCRUISER2024
> Game 1.59.0
> ENTITLEMENT_GLASSES_OAKLEYSPHAERA
> Game 1.60.0
> ENTITLEMENT_CYCLING_HEADGEAR_CYCLINGCAPSPRINGTRAININGHAT2024
> ENTITLEMENT_GLASSES_SPRINGTRAININGSUNGLASSES2024
> ENTITLEMENT_CYCLING_JERSEY_ORIGINALS_SPRINGTRAINING2024
> Game 1.60.0
> ENTITLEMENT_CYCLING_JERSEY_PRO_TEAMS_SCFCHAMP2024
> ENTITLEMENT_CYCLING_JERSEY_PRO_TEAMS_AUSCYCLINGCHAMP2024
> ENTITLEMENT_SOCKS_SOCKS_CONFETTITRAILS
> Game 1.62.0
> ENTITLEMENT_CYCLING_JERSEY_EVENTS_SLT2024BLUE
> ENTITLEMENT_CYCLING_JERSEY_EVENTS_SLT2024GREEN
> ENTITLEMENT_CYCLING_JERSEY_EVENTS_SLT2024GREY
> ENTITLEMENT_CYCLING_JERSEY_EVENTS_SLT2024ORANGE
> ENTITLEMENT_CYCLING_JERSEY_EVENTS_SLT2024PALEBLUE
> ENTITLEMENT_CYCLING_JERSEY_EVENTS_SLT2024PALEGREEN
> ENTITLEMENT_CYCLING_JERSEY_EVENTS_SLT2024PALEORANGE
> ENTITLEMENT_CYCLING_JERSEY_EVENTS_SLT2024PINK
> ENTITLEMENT_CYCLING_JERSEY_EVENTS_SLT2024PURPLE
> ENTITLEMENT_CYCLING_JERSEY_EVENTS_SLT2024RED
> ENTITLEMENT_RUNNING_SHIRT_SLT2024BLUE
> ENTITLEMENT_RUNNING_SHIRT_SLT2024GREEN
> ENTITLEMENT_RUNNING_SHIRT_SLT2024GREY
> ENTITLEMENT_RUNNING_SHIRT_SLT2024ORANGE
> ENTITLEMENT_RUNNING_SHIRT_SLT2024PALEBLUE
> ENTITLEMENT_RUNNING_SHIRT_SLT2024PALEGREEN
> ENTITLEMENT_RUNNING_SHIRT_SLT2024PALEORANGE
> ENTITLEMENT_RUNNING_SHIRT_SLT2024PINK
> ENTITLEMENT_RUNNING_SHIRT_SLT2024PURPLE
> ENTITLEMENT_RUNNING_SHIRT_SLT2024RED
> ENTITLEMENT_RUNNING_SHORTS_SLT2024
> Game 1.63.0
> ENTITLEMENT_BIKE_PINARELLODOGMAX2024
> ```
> 
> The "entitlement" items will be unlocked when you get the next XP (ride 1 km or 1 mile).

Can you tell me what ENTITLEMENT has been updated on 1.64 ？Thank you !

**Comment by oldnapalm** [comment]
You can find a compiled wad_unpack in my fork https://github.com/oldnapalm/zwift-offline/blob/master/scripts/wad_unpack.exe

**Comment by jricoclq** [comment]
> You can find a compiled wad_unpack in my fork https://github.com/oldnapalm/zwift-offline/blob/master/scripts/wad_unpack.exe

Thank you very much!

**Comment by fatsbrown** [comment]
This issue is addressed in https://github.com/zoffline/zwift-offline/commit/364423f0fa19913488b4ed55826b8c02e73e876f

**Comment by jricoclq** [comment]
> This issue is addressed in [364423f](https://github.com/zoffline/zwift-offline/commit/364423f0fa19913488b4ed55826b8c02e73e876f)

Thank you very much.
The new version of ENTITLEMENT is indeed convenient to obtain. I have another request, how can I get those before ID=1687? Thank you.

**Comment by fatsbrown** [comment]
``` python
import json
data = []
for i in range(1, 1826):
    data.append({'id': i})
with open('entitlements.txt', 'w') as f:
    json.dump(data, f)
```

**Comment by fatsbrown** [comment]
Added option to unlock all equipment in https://github.com/zoffline/zwift-offline/commit/23722e0227cb186553ca10e3513cb7090383e170

**Comment by jricoclq** [comment]
> Added option to unlock all equipment in [23722e0](https://github.com/zoffline/zwift-offline/commit/23722e0227cb186553ca10e3513cb7090383e170)

Thanks a lot !

**Comment by jricoclq** [comment]
> Added option to unlock all equipment in [23722e0](https://github.com/zoffline/zwift-offline/commit/23722e0227cb186553ca10e3513cb7090383e170)

Can the paintjob attribute be added to the bot.txt file?

**Comment by fatsbrown** [comment]
See #352 and #354

**Comment by jricoclq** [comment]
> You can find a compiled wad_unpack in my fork https://github.com/oldnapalm/zwift-offline/blob/master/scripts/wad_unpack.exe

May I ask if there is a WAD reverse tool for quantity, which is the pack tool？ thank you a lot.

**Comment by oldnapalm** [comment]
> May I ask if there is a WAD reverse tool for quantity, which is the pack tool？ thank you a lot.

Not that I'm aware of.
