### ISSUE TITLE
How to free up necessary ports

### ISSUE THREAD

**Issue by jgrzesczyk** [zoffline/zwift-offline#329]
Hi,
I've got zoffline 1.0.128160 on windows. I know that 443 and 80 ports should be free and that's probably the reason why the error below appears, but I don't know what's the best method to do it.
I had the working version a few months ago, I needed to disable some services using "net stop", but I can't remind myself which ones were necessary to be disabled.
Does someone have the best method how to free up these ports?

![image](https://github.com/zoffline/zwift-offline/assets/33606865/d976002c-40ef-4462-9bd3-66d25725c872)

**Comment by fatsbrown** [comment]
Hello.

You can use `resmon.exe` to find which process is using the port (see #314 but in your case it's port 80).

Then you can use Task Manager or Services (type in Search) to stop it.

**Comment by jgrzesczyk** [comment]
`net stop http` command resolves this issue
