### ISSUE TITLE
Clean setup method?

### ISSUE THREAD

**Issue by Egosumumbravir** [zoffline/zwift-offline#33]
![zwift bombs](https://user-images.githubusercontent.com/59627813/71939873-08602c80-3204-11ea-90e5-71aab86b1dbf.PNG)
Shiny new windows.  Time to do some zwifting.  Except I'm obviously missing something.

Download zoffline_1.0.43784.exe (& the source zip to get the certs)
Download ZwiftSetup.exe installer from https://zwift.com/download/ (ver1.0.50 it seems?)
Edit hosts file, appending "127.0.0.1 us-or-rly101.zwift.com secure.zwift.com cdn.zwift.com"
Import certs

ISSUE #1: without zwift being installed, there is no C:\Program Files (x86)\Zwift\data\cacert.pem to edit

Continuing on regardless

Fire up zoffline_1.0.43784.exe, looks to load correctly
Run ZwiftSetup.exe.  Install as per defaults.  Once it's installed, needs to update.  With hosts file edits in place, updater throws error "Z110 at line 526 in Patcher.cpp" (screenshot attached)

Then: comment out the hosts file entry.  Now Zwift runs through it's updates.  Once complete, close Zwift.
Re-enable the hosts entries.
Now we have a "C:\Program Files (x86)\Zwift\data\cacert.pem" to edit.  Appends done.
Relaunch Zwift, and it bombs again with the same error.  Telling it to ignore the error and load anyway just hangs it.

Please, what am I missing?
How is this supposed to work when Zwift pushes a newer version by default?  How do you get an old version that's compatible with zoffline?

**Comment by Egosumumbravir** [comment]
Following up after some playing around.
Kill all Zwift processes, fire it up, yes to the "allow the application to make changes prompt" and then, if you're quick enough to hit any of the launcher links before it pops up the "update failed, error code Z110", it'll load and work.

**Comment by oldnapalm** [comment]
Please read this comment, I believe it's the same situation
https://github.com/zoffline/zwift-offline/issues/30#issuecomment-558737262

**Comment by zoffline** [comment]
I believe @oldnapalm is correct, but I've now updated zoffline for the latest Zwift version so things should "just work" if you try again. I really need to automate Zwift updates...

**Comment by Egosumumbravir** [comment]
haha, yes  oldnapalm is correct.
I spent the morning fiddling with python and the source zip to make it all work fine :)
With the versioning issues sorted, it just needs a minor fiddle for the install routine.

For the next person who finds this issue
1. Install Zwift. No need to sign in, just run it and let it update.
2. Download zoffline (hopefully it's versions matches the current Zwift)
3. Edit cacert.pem
4. Edit hosts
5. Inject the new certificates
6. Run zoffline
7. Run zwift

If the versions are mismatching
A. Install Zwift. No need to sign in, just run it and let it update.
B. Download and extract the zoffline source archive.
C. Edit cacert.pem
D. Edit hosts
E. Inject the new certificates
F. Download python and install (note, changing the path seems to break pim.exe in both x86 and x64 versions)
G. **COPY** the file "Zwift_ver_cur.xml" from from C:\Program Files (x86)\Zwift to zwift-offline-master\cdn\gameassets\Zwift_Updates_Root overwriting the one that's there.
H. cross yer fingers and fire them both up!
