### ISSUE TITLE
macbook launch issue

### ISSUE THREAD

**Issue by qqq19021305** [zoffline/zwift-offline#336]
my mac can't launch zwift, but i don;t know how to fix it.
<img width="261" alt="Screenshot 2024-05-20 at 20 11 01" src="https://github.com/zoffline/zwift-offline/assets/170328332/2bffd841-566d-4e2c-b0e6-a8b2e2d00403">

**Comment by fatsbrown** [comment]
Once you perform step 2 of readme, zoffline must be running before launching Zwift.
