### ISSUE TITLE
How can I migrate offline Zwfit profile?

### ISSUE THREAD

**Issue by maxisvest** [zoffline/zwift-offline#338]
The zoffline server and Zwift client are both in my local computer(MacOS), If I change it to another mac, how can I migrate the 'offline-profile', I won't lose my progress.

**Comment by fatsbrown** [comment]
I recommend to copy the entire `storage` folder to preserve all your data (personal records, holo replays, etc) but if you want only the profile, copying the folder `storage/1` will do it.
