### ISSUE TITLE
How to reflect these paintjob in the frame garage?

### ISSUE THREAD

**Issue by jricoclq** [zoffline/zwift-offline#339]
How to reflect these paintjob in the frame garage?
![image](https://github.com/zoffline/zwift-offline/assets/102775665/230ccf51-757d-4af8-8f0b-5106fafb20c7)
Like this
![image](https://github.com/zoffline/zwift-offline/assets/102775665/c49bba01-690c-4ad0-9d40-cc6baa69fb6a)
Thank you for teach me !

**Comment by fatsbrown** [comment]
Addressed in https://github.com/zoffline/zwift-offline/commit/23722e0227cb186553ca10e3513cb7090383e170

**Comment by jricoclq** [comment]
> Addressed in [23722e0](https://github.com/zoffline/zwift-offline/commit/23722e0227cb186553ca10e3513cb7090383e170)

Tks a lot!
