### ISSUE TITLE
connect to server error

### ISSUE THREAD

**Issue by hflyf123** [zoffline/zwift-offline#340]
I have deployed a service on an Ubuntu server, and an Android device is trying to connect. The error stack trace on the server side is as follows:

<gevent.ssl.SSLSocket at 0x7f4aecd227a0 server=True, cipher='' object, fd=10, family=2, type=1, proto=0>: (from ('183.192.45.118', 10772)) Invalid HTTP method: '\x16\x03\x01\x02\x00\x01\x00\x01ü\x03\x03þï\x82Á½kè"Ã\x98w\x86!\x1f\x1bT%\'ä-PÎAÌ\x13&7ò¶ÁøG \x85Y]\x16#5Ô\x86ÀÇ\x13\x17½êàr\x89\x0e \\]$D[ý\x9d)\tn»ãb\x00>\x13\x02\x13\x03\x13\x01À,À0\x00\x9fÌ©Ì¨ÌªÀ+À/\x00\x9eÀ$À(\x00kÀ#À\'\x00gÀ\n'
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 908, in gevent._gevent_cgreenlet.Greenlet.run
  File "/usr/local/lib/python3.10/dist-packages/gevent/baseserver.py", line 34, in _handle_and_close_when_done
    return handle(*args_tuple)
  File "/usr/local/lib/python3.10/dist-packages/gevent/server.py", line 210, in wrap_socket_and_handle
    return self.handle(ssl_socket, address)
  File "/usr/local/lib/python3.10/dist-packages/gevent/pywsgi.py", line 1700, in handle
    handler.handle()
  File "/usr/local/lib/python3.10/dist-packages/gevent/pywsgi.py", line 581, in handle
    self.socket.sendall(response_body)
  File "/usr/local/lib/python3.10/dist-packages/gevent/ssl.py", line 544, in sendall
    return socket.sendall(self, data, flags)
  File "/usr/local/lib/python3.10/dist-packages/gevent/_socketcommon.py", line 702, in sendall
    return _sendall(self, data_memory, flags)
  File "/usr/local/lib/python3.10/dist-packages/gevent/_socketcommon.py", line 391, in _sendall
    timeleft = __send_chunk(socket, chunk, flags, timeleft, end)
  File "/usr/local/lib/python3.10/dist-packages/gevent/_socketcommon.py", line 320, in __send_chunk
    data_sent += socket.send(chunk, flags)
  File "/usr/local/lib/python3.10/dist-packages/gevent/ssl.py", line 518, in send
    return socket.send(self, data, flags, timeout)
  File "/usr/local/lib/python3.10/dist-packages/gevent/_socketcommon.py", line 725, in send
    return self._sock.send(data, flags)
ConnectionResetError: [Errno 104] Connection reset by peer
2024-06-19T13:55:02Z <Greenlet at 0x7f4aecca63e0: _handle_and_close_when_done(<bound method StreamServer.wrap_socket_and_handle , <bound method StreamServer.do_close of <WSGIServer, (<gevent._socket3.socket [closed] at 0x7f4aecc8022)> failed with ConnectionResetError

However, I have successfully connected a few times before.This confusion puzzles me, could you please help me

**Comment by hflyf123** [comment]
> Have you tried setting SSL MinProtocol to TLSv1.0? (https://github.com/zoffline/zwift-offline?tab=readme-ov-file#extra-optional-steps)

Yes, but the issue remains.
![image](https://github.com/zoffline/zwift-offline/assets/28125387/08e85364-18a0-4afa-8ab6-722d8d5cd659)
![image](https://github.com/zoffline/zwift-offline/assets/28125387/faddf5e2-5427-4af1-a097-6656d9d98a52)

**Comment by hflyf123** [comment]
find someone like me #288

**Comment by fatsbrown** [comment]
> find someone like me #288

Yes, I suggested the same thing (https://github.com/zoffline/zwift-offline/issues/288#issuecomment-1857935107) but they never replied, that's why I suggested again.

You could try using Docker.

Unfortunately I don't have any other idea.

**Comment by hflyf123** [comment]
> > find someone like me #288
> 
> Yes, I suggested the same thing ([#288 (comment)](https://github.com/zoffline/zwift-offline/issues/288#issuecomment-1857935107)) but they never replied, that's why I suggested again.
> 
> You could try using Docker.
> 
> Unfortunately I don't have any other idea.

yes, i try every suggestion in that issue, but cant solve. thans a lot to anwser me!

**Comment by fatsbrown** [comment]
Is the Zwift app cacert.pem properly patched using ZofflineObb (or adb shell in case of a rooted device)?

**Comment by hflyf123** [comment]
> Is the Zwift app cacert.pem properly patched using ZofflineObb (or adb shell in case of a rooted device)?

yes，In fact, I have succeeded in about 5hours ago，but its not work now

**Comment by fatsbrown** [comment]
Are the client and the server on the same LAN? Do you use proxy or VPN?

**Comment by hflyf123** [comment]
> Are the client and the server on the same LAN? Do you use proxy or VPN?

no，the server is on ecs，i just use virtual hosts

**Comment by hflyf123** [comment]
> > Is the Zwift app cacert.pem properly patched using ZofflineObb (or adb shell in case of a rooted device)?
> 
> yes，In fact, I have succeeded in about 5hours ago，but its not work now

![Screenshot_2024-06-20-01-02-11-317_com zoffline zofflineobb](https://github.com/zoffline/zwift-offline/assets/28125387/42902d47-95c3-431b-904a-f3178fc50faa)

**Comment by hflyf123** [comment]
> > find someone like me #288
> 
> Yes, I suggested the same thing ([#288 (comment)](https://github.com/zoffline/zwift-offline/issues/288#issuecomment-1857935107)) but they never replied, that's why I suggested again.
> 
> You could try using Docker.
> 
> Unfortunately I don't have any other idea.

i use docker to deploy, then it works just once, when i change my phone network, same question happen in docker

**Comment by hflyf123** [comment]
the zwift launcher is always work
![image](https://github.com/zoffline/zwift-offline/assets/28125387/3ce18314-0bf5-4d44-b789-a10ca9f38aa2)

**Comment by fatsbrown** [comment]
> the zwift launcher is always work

Is this from phone browser or Windows Zwift launcher? If it's from browser I assume you are ignoring invalid SSL certificate. Do you see errors in zoffline log?

**Comment by fatsbrown** [comment]
> when i change my phone network, same question happen in docker

You could try the fake DNS method to rule out a Virtual Hosts issue, it's a bit tricky because you will need to free up port 53 UDP (https://github.com/oldnapalm/zwift-offline/wiki/Creating-a-server-on-Oracle-Cloud-Free-Tier#free-up-port-53).

**Comment by hflyf123** [comment]
> > the zwift launcher is always work
> 
> Is this from phone browser or Windows Zwift launcher? If it's from browser I assume you are ignoring invalid SSL certificate. Do you see errors in zoffline log?

both phone and browser can touch it , but the game connect error

**Comment by fatsbrown** [comment]
The SSL errors opening launcher from browser are expected because it does not trust the certificate, but the error `gevent.ssl.SSLSocket: Invalid HTTP method` on Zwift client request `GET /api/telemetry/config` is odd, specially that it works once then stops working. I have only seen this error in this issue and in #288, what both have in common is the server running on a VPS, so my guess is that it's caused by some VPS setting regarding SSL.

**Comment by hflyf123** [comment]
![image](https://github.com/zoffline/zwift-offline/assets/28125387/b4412f1c-0e97-4a3a-a7d0-995fca5d4a8d)
Is this the method called by Android login? I hit a breakpoint here, but it didn't enter

**Comment by fatsbrown** [comment]
> Is this the method called by Android login? I hit a breakpoint here, but it didn't enter

Yes, but it's failing in the first call, then it never gets there.

This is the sequence of requests from Android client (first login)
```
GET /api/telemetry/config
POST /hvc-ingestion-service/batch
GET /api/auth
POST /auth/realms/zwift/protocol/openid-connect/token
POST /api/users/login
GET /relay/worlds/hash-seeds
GET /api/profiles/me
```

**Comment by fatsbrown** [comment]
You can try running with werkzeug instead of gevent

![Captura de tela 2024-06-21 191614](https://github.com/zoffline/zwift-offline/assets/123950591/beaefc9d-d08f-48d5-a524-fddbf2011919)

**Comment by hflyf123** [comment]
> You can try running with werkzeug instead of gevent
> 
> ![Captura de tela 2024-06-21 191614](https://private-user-images.githubusercontent.com/123950591/341903099-beaefc9d-d08f-48d5-a524-fddbf2011919.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxNTM2MTksIm5iZiI6MTcxOTE1MzMxOSwicGF0aCI6Ii8xMjM5NTA1OTEvMzQxOTAzMDk5LWJlYWVmYzlkLWQwOGYtNDhkNS1hNTI0LWZkZGJmMjAxMTkxOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyM1QxNDM1MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZmFlYTg3NjNhNzU3ZTJmZTZmNGRhNDlhOGJhMGU2ZjU0YTY1N2U1NjQxNDMyMTYzODhkZmYyMTNiZDdmZTAwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jucOhNxIJGK6-G1L5heFf4BhsksSOX6BjiMYv7a9Rm8)

thanks, i will try.  yesterday i change another vps service, the question is same when i change a network

**Comment by fatsbrown** [comment]
Have you tested with a local server? Just to make sure the problem is not client side.

**Comment by hflyf123** [comment]
> Have you tested with a local server? Just to make sure the problem is not client side.

yes, local server always work ! But i dont want to open my pc when i ride XD

**Comment by hflyf123** [comment]
![image](https://github.com/zoffline/zwift-offline/assets/28125387/785cf3bd-ba52-4f2f-acc8-803b26be0126)
saddly, i can login on launcher,but the game is still connect error.( but i dont see the error log ,i am make suer the host on my phone is correct)

**Comment by fatsbrown** [comment]
This error seems to usually happen when a plain HTTP request is sent over HTTPS (I can reproduce locally running `curl http://us-or-rly101.zwift.com:443/api/telemetry/config`). We know the client makes HTTPS requests since it works with local server, so my guess is that something in the VPS network setup is causing the problem.

I have a server running on Oracle Cloud (configured following instructions from https://github.com/oldnapalm/zwift-offline/wiki/Creating-a-server-on-Oracle-Cloud-Free-Tier) and it works flawlessly.

**Comment by hflyf123** [comment]
i try with azure, everything is ok...

**Comment by kanhao100** [comment]
I have same issue on china mainland servers provoider
