### ISSUE TITLE
Patching ZCA 3.59.0 with apk-mitm fails building resources

### ISSUE THREAD

**Issue by fatsbrown** [zoffline/zwift-offline#342]
```
I: Building resources...
W: res\values\styles.xml:3186: error: expected enum but got (raw string) 0.
W: res\values\styles.xml:3262: error: expected enum but got (raw string) 1.
W: res\values\styles.xml:3331: error: expected enum but got (raw string) 1.
W: res\values\styles.xml:3345: error: expected enum but got (raw string) 1.
W: error: failed linking references.
```

This can be fixed by running apktool decode with the `-resm dummy` argument (https://apktool.org/docs/in-depth/resource-modes/#dummy). Edit `%USERPROFILE%\AppData\Roaming\npm\node_modules\apk-mitm\dist\tools\apktool.js` and add
``` js
            '-resm',
            'dummy',
```
It should be like this
``` js
    decode(inputPath, outputPath) {
        return this.run([
            'decode',
            '-resm',
            'dummy',
            inputPath,
            '--output',
            outputPath,
            '--frame-path',
            this.options.frameworkPath,
        ], 'decoding');
    }
```

**Comment by mesterumanele** [comment]
Hello, 
i'm doing exactly as in the above instruction, but gives me this error: 
"Failed!  An error occurred:

Unrecognized option: -resm"  which means, at least, i'm manipulating the correct file/path... 
Thank you (not critical, my previous install works)

**Comment by fatsbrown** [comment]
> Unrecognized option: -resm

Try updating apk-mitm to the latest version, maybe the one you are using has apktool earlier than v2.9.0 which does not have this option.
