### ISSUE TITLE
Easy way to see if somebody is actively riding?

### ISSUE THREAD

**Issue by peteh** [zoffline/zwift-offline#344]
Hi

I'm trying to use this server to see if Zwift is running and connected. 

Use case: When I start the app, I want to start the fan too. 

Idea: use one of the zoffline server's api endpoints to see if somebody is connected. 

Does such an api endpoint exist that could be used?

**Comment by fatsbrown** [comment]
Hi. There isn't an API but since it's open source you can implement something directly in zoffline. The length of the [online](https://github.com/zoffline/zwift-offline/blob/master/standalone.py#L86) dictionary tells you how many players are currently connected to the UDP server and `online[player_id]` contains the last [PlayerState](https://github.com/zoffline/zwift-offline/blob/master/protobuf/udp-node-msgs.proto#L112) received from that player. I suppose you can check speed to know if the player is moving or heartrate if you want to set the fan speed accordingly.

If you want to control the fan from another app, a possibility would be adding something like this in CDNHandler [do_GET()](https://github.com/zoffline/zwift-offline/blob/master/standalone.py#L111) to expose the value through HTTP

```python
        if self.path.startswith('/speed/'):
            try:
                player_id = int(self.path.split('/')[-1])
                if player_id in online:
                    self.send_response(200)
                    self.send_header('Content-type', 'application/json')
                    self.end_headers()
                    output = json.dumps({'speed': online[player_id].speed})
                    self.wfile.write(output.encode())
                    return
            except:
                pass
```

Then you can access `http://127.0.0.1/speed/<player_id>`

**Comment by peteh** [comment]
Ah that would be perfect. I could even adjust light settings based on current power

**Comment by peteh** [comment]
Small update, for me the `online` variable is always empty. I tried both in docker and standalone on a linux machine but it seems to never be update. Even when I ride.

**Comment by peteh** [comment]
Ah thank you very much, that works. 

Does it make any difference if I add the api to the cdn or to the swift api server? The latter can specify routes easier within the flask app.  

I would add something like /api_ext/players/[player_id]

Another question on the side: 
When switching from single to multiplayer, is there anything to be done with the profile? It looks like I cannot log into the single player account when switching to multiplayer via multiplayer.txt

**Comment by fatsbrown** [comment]
> Does it make any difference if I add the api to the cdn or to the swift api server? The latter can specify routes easier within the flask app.

Not much, but flask already has it (I edited my first reply), `/relay/dropin` contains a list of online riders and `/relay/worlds/1/players/<player_id>` contains the last player state.

> When switching from single to multiplayer, is there anything to be done with the profile? It looks like I cannot log into the single player account when switching to multiplayer via multiplayer.txt

When multiplayer is enabled you need to sign up (`/signup`). The first account will be profile 1 which is the default in single player mode. Also notice that if multiplayer is enabled you need to login (POST username and password to `/login`) to have access to `/relay/dropin`.

**Comment by peteh** [comment]
**API**
Looks like the existing points are not json but Protobuf. So either I add a ?encode=json parameter or add new endpoints. But this seems doable. 

**Users**
I have a single player profile which I cannot log into when switching to multiplayer. Can I create a new profile and then upload the profile.bin to make it work?

**Comment by fatsbrown** [comment]
> Looks like the existing points are not json but Protobuf. So either I add a ?encode=json parameter or add new endpoints. But this seems doable.

Dropin already has a json response if "Accept" header is "application/json" (https://github.com/zoffline/zwift-offline/blob/master/zwift_offline.py#L2993). The other route only returns protobuf but you can decode in your script. If there isn't protobuf library for the language you are using, you can run command line protoc, for instance:
```
curl -k https://us-or-rly101.zwift.com/relay/worlds/1/players/1 -o 1.bin
protoc --decode PlayerState udp-node-msgs.proto < 1.bin
```

> Can I create a new profile and then upload the profile.bin to make it work?

Yes, or you can rename your current profile folder in storage to 1.

**Comment by fatsbrown** [comment]
Dropin example for multiplayer:

```
curl -k -c cookie.txt -F username=user@email.com -F password=xxx https://us-or-rly101.zwift.com/login/
curl -k -b cookie.txt https://us-or-rly101.zwift.com/relay/dropin -o dropin.bin
protoc --decode DropInWorldList world.proto < dropin.bin
```
or
```
curl -k -b cookie.txt https://us-or-rly101.zwift.com/relay/dropin | protoc --decode DropInWorldList world.proto
curl -k -b cookie.txt https://us-or-rly101.zwift.com/relay/worlds/1/players/1 | protoc --decode PlayerState udp-node-msgs.proto
```
