### ISSUE TITLE
some questions about servers

### ISSUE THREAD

**Issue by jricoclq** [zoffline/zwift-offline#346]
I have some questions about servers
Question 1: The zwift-offline.db file contains many users who no longer use the server. How to delete these users because they occupy the list when using ZCA for MEETUP, which can cause selection errors?
Question 2: When using MEETUP, I only selected a subset of users, but all users on the server can access it. Can I set it so that only invited users can participate, and those uninvited users will not automatically enter MEETUP?
Question 3: Can the function of adding routes to the list be implemented using ZCA?
![402a752dc3b7b3c80d3ab4bdb68795a](https://github.com/user-attachments/assets/83f775fd-83b2-451a-9fa4-51fa8e90e6c3)

**Comment by fatsbrown** [comment]
1. Just delete the user from DB. Using https://sqlitebrowser.org/ select the row, click delete and write changes (make sure zoffline is closed when you make changes to DB).
![Captura de tela 2024-07-29 084001](https://github.com/user-attachments/assets/f4f3a342-3dc1-4c35-ac20-215f641d82ed)
2. You would need to implement changes in zoffline code. Currently meetups are available for all users.
3. I don't think it's possible.

**Comment by jricoclq** [comment]
> 1. Just delete the user from DB. Using https://sqlitebrowser.org/ select the row, click delete and write changes (make sure zoffline is closed when you make changes to DB).
>    ![Captura de tela 2024-07-29 084001](https://private-user-images.githubusercontent.com/123950591/353032567-f4f3a342-3dc1-4c35-ac20-215f641d82ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzMDg1NDUsIm5iZiI6MTcyMjMwODI0NSwicGF0aCI6Ii8xMjM5NTA1OTEvMzUzMDMyNTY3LWY0ZjNhMzQyLTNkYzEtNGMzNS1hYzIwLTIxNWY2NDFkODJlZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDczMFQwMjU3MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iODBkMDdjMmM2MWE5ZWU0OTk5ZTc5NDlhZTRmMmJlZGQ5MzE1YTI5NTE5YWQ0ZDdiM2MxYzFmN2NlNWUyY2EwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5wl2PtIVpi3HbAjG-ObtMW_WSL4AsAdSZETdKkk1hDw)
> 2. You would need to implement changes in zoffline code. Currently meetups are available for all users.
> 3. I don't think it's possible.

Q1 & Q3 Tks a lot!
Q2 :May I ask how and where to modify the code? thanks.

**Comment by fatsbrown** [comment]
Try this https://github.com/fatsbrown/zwift-offline/commit/a431cd709610346586f99ff7a77dd4bdc7df474a

**Comment by jricoclq** [comment]
> Try this [fatsbrown@a431cd7](https://github.com/fatsbrown/zwift-offline/commit/a431cd709610346586f99ff7a77dd4bdc7df474a)

THANKS A LOT，it worked!
