### ISSUE TITLE
Identify protobuf profile value for paintjob

### ISSUE THREAD

**Issue by daktak** [zoffline/zwift-offline#351]
I wish to set the paintjob on the bots bike, so need to identify the correct profile value.
Took a guess it was bike_frame_colour , but this is incorrect.

https://github.com/daktak/zwift-offline/tree/bike_frame_color

**Comment by fatsbrown** [comment]
The paint job signature is stored in the 32 most significant bits, the least significant contain the color value.

``` xml
<PAINTJOB name="Specialized Shiv S-Works-Specialized Shiv S-Works Black" signature="1570565867"/>
```
```
6745529034978885713 >> 32 = 1570565867
6745529034978885713 & 0x0000ffff = 81
```
``` xml
<PAINTJOB name="Specialized Shiv S-Works-Specialized Shiv S-Works Purple" signature="1259279195"/>
```
```
5408562959058206800 >> 32 = 1259279195
5408562959058206800 & 0x0000ffff = 80
```

**Comment by daktak** [comment]
#352 can closes this
