### ISSUE TITLE
Windows Defender alert still visible?

### ISSUE THREAD

**Issue by rafaldrozd95** [zoffline/zwift-offline#356]
I'd like to share this project with my parents who use Zwift a lot but they don't care about the community at all. Is there any possibility to built it differently and avoid Windows Defender alert?

**Comment by fatsbrown** [comment]
Using pyinstaller there are some things you can do, but they are not very simple.

1. Build a custom bootloader https://pyinstaller.org/en/stable/bootloader-building.html
2. Sign the executable using a certificate issued by a trusted certificate authority.

There are others tools to create executables from Python programs (like https://nuitka.net), but I have never used them.

In my opinion, the best way to avoid virus alert is running from source. You can create Windows shortcuts to run (`python.exe standalone.py`) and update zoffline (`git pull`).

**Comment by oldnapalm** [comment]
This is a known issue, it's mentioned in every release. You can add zoffline as an exclusion to Windows Security, or run from source.

> The executable is made with pyinstaller. An unfortunate side effect is that some anti-virus software may falsely flag pyinstaller executables as malware. This is a known issue (https://github.com/pyinstaller/pyinstaller/issues?utf8=%E2%9C%93&q=is%3Aissue+virus) and unavoidable. If you prefer, you can not use this exe and instead run zoffline directly from the source code (2nd installation method in the README).
