### ISSUE TITLE
Update failed during patching Error code Z110

### ISSUE THREAD

**Issue by il-frans** [zoffline/zwift-offline#36]
Clean install, Zoffline and followed instruction of step 2 and run exe.
Download Zwift installer from zwift site and run it. 
Run zwift and I can see it hitting the Zoffline local server on the same machine..

For some reason it is failing to update zwift from the ZOffline. A dialog box comes up closing it makes Zwift close. Also the ZOffline shows some 404s.

![Annotation 2020-03-24 153810](https://user-images.githubusercontent.com/5260042/77437945-897f9680-6de5-11ea-9c02-522f0e9f1cf7.png)

![Annotation 2020-03-24 153916](https://user-images.githubusercontent.com/5260042/77438040-a3b97480-6de5-11ea-88ed-3f4967c03bb0.png)

**Comment by oldnapalm** [comment]
The exe is outdated, install using second method (install Python and run from source).

Please see issue #33 for more details.

**Comment by il-frans** [comment]
Worked by using the method you suggested. Thanks a lot. How about removing the exe and updating the read me?

**Comment by oldnapalm** [comment]
You are welcome.

I think @zoffline has been busy. I added a new release in my fork just in case.

https://github.com/oldnapalm/zwift-offline/releases/tag/Zwift_1.0.46903

**Comment by stapa** [comment]
@oldnapalm Thanks for the release.
