### ISSUE TITLE
MacOS zwift official client&ZOFFLINE Cannot find Bluetooth device

### ISSUE THREAD

**Issue by kazuki-hehe** [zoffline/zwift-offline#366]
MacOS zwift official client binds Bluetooth device,
Then use Zwift-offline to search for Bluetooth device but cannot find it
Switch back to official client and can find Bluetooth device again
How to solve

**Comment by fatsbrown** [comment]
Isn't it the same as #321 again?

**Comment by kazuki-hehe** [comment]
yes

**Comment by kazuki-hehe** [comment]
Still not solved

**Comment by fatsbrown** [comment]
What do you mean by "Need to delete the Zwift official version Bluetooth profile"? I understood that was the solution. Can you elaborate?

**Comment by kazuki-hehe** [comment]
The Bluetooth device bound to the official version of MAC ZWIFT causes Zoffiline to be unable to search for the Bluetooth device

**Comment by fatsbrown** [comment]
And if you unbind it from the official server session, doesn't it become available in zoffline session?

**Comment by kazuki-hehe** [comment]
Unbind and still can't find

**Comment by fatsbrown** [comment]
You can try this https://www.youtube.com/watch?v=i7kZ51B-SzQ

Switching between official server and zoffline is like using different user profiles on official server, because the user ID is different.

**Comment by kazuki-hehe** [comment]
Thanks, I'll try it later.

**Comment by fatsbrown** [comment]
If that doesn't help (meaning it's not a problem of device being already paired), maybe it's some feature which is configured differently between official server and zoffline, the easiest way to check is sniffing the response from official server to the request `POST /experimentation/v1/variant`, this can be done using MITM attack against HTTPS protocol using a tool like mitmproxy. There are various BLE related features which may get a different response when requested by a Mac client (the values included in zoffline are sniffed from Windows client session)

```
game_1_21_ble_data_guard_v2
game_1_29_ble_middleware
game_1_34_cached_ble_service_filter
game_1_34_monitor_zc_ble_bridge_scanning
game_1_43_3_ble_dll_v2
game_1_44_ble_queue
game_1_45_0_ble_source_lock
game_1_49_ble_adv_fix_pc_android
game_1_52_ble_adv_sd
game_1_68_ble_discovery_analytics
game_1_71_prevent_sending_ble_messages_prior_com_setup
```
