### ISSUE TITLE
 docker安装遇到问题

### ISSUE THREAD

**Issue by 55404** [zoffline/zwift-offline#367]
INFO:zoffline:server-ip.txt not found, using 192.168.31.8
Traceback (most recent call last):
  File "/usr/src/app/zwift-offline/standalone.py", line 789, in <module>
    httpd = socketserver.ThreadingTCPServer(('', 80), CDNHandler)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/socketserver.py", line 457, in __init__
    self.server_bind()
  File "/usr/local/lib/python3.12/socketserver.py", line 473, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address in use
INFO:zoffline:server-ip.txt not found, using 192.168.31.8

**Comment by kazuki-hehe** [comment]
Port 80 is occupied

**Comment by fatsbrown** [comment]
Never used Synology NAS myself but someone on [Discord](https://discord.com/channels/771069316262527036/771069316262527039/1126671607088287874) suggested using [macvlan](https://docs.docker.com/engine/network/drivers/macvlan/) in this situation.

`sudo docker network create -d macvlan -o parent=eth0 --subnet=192.168.29.0/24 --gateway=192.168.29.1 --ip-range=192.168.29.64/28 zwift`

`sudo docker create --name zwift-offline --network zwift --ip 192.168.29.64 --restart unless-stopped -p 443:443 -p 80:80 -p 3024:3024/udp -p 3025:3025 -p 53:53/udp -v /volume1/zwift:/usr/src/app/zwift-offline/storage -e TZ=America/Chicago zoffline/zoffline`

> if you've found this on a search, update your parent (probably still eth0), ip (you don't have to set it, but you should), volume (/volume1/zwift is the folder i made on my NAS, but your's will be different), gateway and subnet will depend on your router -- check your ip config, and ip-range should be within your router's subnet but outside of its DHCP (as large or small as you need it to be)

**Comment by 55404** [comment]
> 我自己从未使用过 Synology NAS，但 [Discord](https://discord.com/channels/771069316262527036/771069316262527039/1126671607088287874) 上的某人建议在这种情况下使用 [macvlan](https://docs.docker.com/engine/network/drivers/macvlan/)。
> 
> `sudo docker network create -d macvlan -o parent=eth0 --subnet=192.168.29.0/24 --gateway=192.168.29.1 --ip-range=192.168.29.64/28 zwift`
> 
> `sudo docker create --name zwift-offline --network zwift --ip 192.168.29.64 --restart unless-stopped -p 443:443 -p 80:80 -p 3024:3024/udp -p 3025:3025 -p 53:53/udp -v /volume1/zwift:/usr/src/app/zwift-offline/storage -e TZ=America/Chicago zoffline/zoffline`
> 
> > 如果您在搜索中找到了这个，请更新您的父级（可能仍然是 eth0）、IP（您不必设置它，但您应该设置它）、卷（/volume1/zwift 是我在 NAS 上创建的文件夹，但您的文件夹会有所不同）、网关和子网将取决于您的路由器 -- 检查您的 IP 配置，ip-range 应该在路由器的子网内，但在其 DHCP 之外（根据您的需要）

 非常感谢您，解决了我的困扰
