### ISSUE TITLE
Zoffline is only using one Core on Raspberry Pi 4

### ISSUE THREAD

**Issue by hollysheep** [zoffline/zwift-offline#368]
Hi,

i've installed Zofflien on my Raspberry Pi 4. It takes a while to start Zofflien correct. I noticed its only using 1 or the 4 cores 100%, the others are 0%. Can i run Zoffline on 2 or more cores?

Only the start need so much cpu power. When i message

`INFO:zoffline:Server version 1.74.0 (135195) is running`

occurs the usage is under 1% when the client osn't connected.

**Comment by oldnapalm** [comment]
> Can i run Zoffline on 2 or more cores?

No, zoffline does not support multiprocessing.
