### ISSUE TITLE
Some server related issues.

### ISSUE THREAD

**Issue by jricoclq** [zoffline/zwift-offline#369]
1. Due to national network regulations, updates in some regions often encounter errors and cannot be completed. Can we place the downloaded version content package in the Zoffline folder, such as the "zwift-offline-master\cdn\gameassets\Zwift_Updates_Root" folder, so that every user connected to the server can directly download the upgrade content package of ZWIFT from ZOFFLINE.
2.Regarding the issue of robot frame paintjob that I requested earlier, the method you provided can only work on GHOSTS and will not work on BOTS. Please refer to the screenshot below.
![2024-10-07_12-58-15_0](https://github.com/user-attachments/assets/47a86c62-bd54-4c9e-9b89-5727296c1213)
![2024-10-07_13-01-39_0](https://github.com/user-attachments/assets/46f3f4a1-a176-4f4f-820b-bcb15a203061)
![2024-10-07_13-02-08_1](https://github.com/user-attachments/assets/cc511b6f-4ec2-4058-b851-dffbc5c50771)
Thank you.

**Comment by fatsbrown** [comment]
1. Delete cdn-proxy.txt from storage if it exists, delete lines 37 to 63 from standalone.py and run scripts/get_gameassets.py to download files.
2. It works also for bots (see https://github.com/zoffline/zwift-offline/commit/af549477bafba552d0b04ca699ab6174a216da30), bot.txt must contain bike_frame_colour_signature and matching bike_signature, run updated scripts/get_pro_names.py to generate it.

**Comment by jricoclq** [comment]
> 1. Delete cdn-proxy.txt from storage if it exists, delete lines 37 to 63 from standalone.py and run scripts/get_gameassets.py to download files.
> 2. It works also for bots (see [af54947](https://github.com/zoffline/zwift-offline/commit/af549477bafba552d0b04ca699ab6174a216da30)), bot.txt must contain bike_frame_colour and matching bike_frame, run updated scripts/get_pro_names.py to generate it.

1.  I test more,but it dosen't work.

**Comment by fatsbrown** [comment]
1. It works, I use it.
```
[06/Oct/2024 10:16:17] "GET /gameassets/Zwift_Updates_Root/Zwift_1.0.135674_9d4bbd19_manifest.xml HTTP/1.1" 200 -
[06/Oct/2024 10:16:26] "GET /gameassets/Zwift_Updates_Root/Zwift_1.0.135674_9d4bbd19/ZwiftHelper.exe HTTP/1.1" 200 -
[06/Oct/2024 10:16:26] "GET /gameassets/Zwift_Updates_Root/Zwift_1.0.135674_9d4bbd19/BleWin10Lib.dll HTTP/1.1" 200 -
[06/Oct/2024 10:16:26] "GET /gameassets/Zwift_Updates_Root/Zwift_1.0.135674_9d4bbd19/ANT_DLL.dll HTTP/1.1" 200 -
[06/Oct/2024 10:16:26] "GET /gameassets/Zwift_Updates_Root/Zwift_1.0.135674_9d4bbd19/BleWin10Lib_fallback.dll HTTP/1.1" 200 -
[06/Oct/2024 10:16:26] "GET /gameassets/Zwift_Updates_Root/Zwift_1.0.135674_9d4bbd19/ZwiftApp.exe HTTP/1.1" 200 -
[06/Oct/2024 10:16:27] "GET /gameassets/Zwift_Updates_Root/Zwift_1.0.135674_9d4bbd19/ZwiftSetup.exe HTTP/1.1" 200 -
[06/Oct/2024 10:16:27] "GET /gameassets/Zwift_Updates_Root/Zwift_1.0.135674_9d4bbd19/ZwiftWindowsCrashHandler.exe HTTP/1.1" 200 -
```
2. Dict key should be `bike_frame_colour` and the value must be shift to left by 32 bits. Use scripts/find_equip.py to find correct values.
```
python .\find_equip.py -p bora
{
  "bike_frame_colour": 7326306925199491072,
  "bike_frame_colour_name": "Specialized Tarmac SL7-Bora Hansgrohe",
  "bike_frame": 935373427,
  "bike_frame_name": "Specialized Tarmac SL7"
}
```

**Comment by jricoclq** [comment]
> 1. It works, I use it.
> 
> ```
> [06/Oct/2024 10:16:17] "GET /gameassets/Zwift_Updates_Root/Zwift_1.0.135674_9d4bbd19_manifest.xml HTTP/1.1" 200 -
> [06/Oct/2024 10:16:26] "GET /gameassets/Zwift_Updates_Root/Zwift_1.0.135674_9d4bbd19/ZwiftHelper.exe HTTP/1.1" 200 -
> [06/Oct/2024 10:16:26] "GET /gameassets/Zwift_Updates_Root/Zwift_1.0.135674_9d4bbd19/BleWin10Lib.dll HTTP/1.1" 200 -
> [06/Oct/2024 10:16:26] "GET /gameassets/Zwift_Updates_Root/Zwift_1.0.135674_9d4bbd19/ANT_DLL.dll HTTP/1.1" 200 -
> [06/Oct/2024 10:16:26] "GET /gameassets/Zwift_Updates_Root/Zwift_1.0.135674_9d4bbd19/BleWin10Lib_fallback.dll HTTP/1.1" 200 -
> [06/Oct/2024 10:16:26] "GET /gameassets/Zwift_Updates_Root/Zwift_1.0.135674_9d4bbd19/ZwiftApp.exe HTTP/1.1" 200 -
> [06/Oct/2024 10:16:27] "GET /gameassets/Zwift_Updates_Root/Zwift_1.0.135674_9d4bbd19/ZwiftSetup.exe HTTP/1.1" 200 -
> [06/Oct/2024 10:16:27] "GET /gameassets/Zwift_Updates_Root/Zwift_1.0.135674_9d4bbd19/ZwiftWindowsCrashHandler.exe HTTP/1.1" 200 -
> ```
> 
> 2. Dict key should be `bike_frame_colour` and the value must be shift to left by 32 bits. Use scripts/find_equip.py to find correct values.
> 
> ```
> python .\find_equip.py -p bora
> {
>   "bike_frame_colour": 7326306925199491072,
>   "bike_frame_colour_name": "Specialized Tarmac SL7-Bora Hansgrohe",
>   "bike_frame": 935373427,
>   "bike_frame_name": "Specialized Tarmac SL7"
> }
> ```

Sorry, I made a mistake in my previous settings, which caused the problem. Now everything is working. Thank you very much for your help.

**Comment by fatsbrown** [comment]
A suggestion, not mandatory but I do to save bandwidth when updating the server, rename the old game assets folder to the new folder before running get_gameassets.py, this way only the new and modified files will be downloaded, the rest will be only CRC checked. The new folder name can be found in Zwift_ver_cur.xml (same as `manifest` without trailing `_manifest.xml`). For example, rename `Zwift_1.0.135522_0b195230` to `Zwift_1.0.135674_9d4bbd19`.

**Comment by jricoclq** [comment]
> A suggestion, not mandatory but I do to save bandwidth when updating the server, rename the old game assets folder to the new folder before running get_gameassets.py, this way only the new and modified files will be downloaded, the rest will be only CRC checked. The new folder name can be found in Zwift_ver_cur.xml (same as `manifest` without trailing `_manifest.xml`). For example, rename `Zwift_1.0.135522_0b195230` to `Zwift_1.0.135674_9d4bbd19`.

I tested several computers today and all were successful! I had planned to manually operate it this way. It would be great if you could implement these from the code. Thank you very much.

**Comment by fatsbrown** [comment]
I think this would be difficult to implement because update files are served through SimpleHTTPRequestHandler and zoffline uses Flask-Login to authenticate users, you would need to re-implement CDNHandler using Flask. Maybe there's an easier way but I have no idea at the moment.

**Comment by jricoclq** [comment]
> I think this would be difficult to implement because update files are served through SimpleHTTPRequestHandler and zoffline uses Flask-Login to authenticate users, you would need to re-implement CDNHandler using Flask. Maybe there's an easier way but I have no idea at the moment.

Okay, thank you very much. If there is a way to achieve it in the future, please let me know. Thank you very much.

**Comment by fatsbrown** [comment]
Notice that zoffline was not designed to be exposed to the internet, so it's unlikely that such feature will be implemented. Moreover, it doesn't make much sense because users need access to the CDN files before signing up, to perform the initial update (Zwift installer contains only the launcher, the app is actually installed on the first run, before sign up/login).

A good practice if you are sharing the server with other users over the internet is using an upstream reverse proxy. See #278 for details on how to configure virtual hosts and reverse proxy using Apache or Nginx, this way zoffline can be only reached through zwift.com domains, avoiding robots and issues like https://github.com/gevent/gevent/issues/649

**Comment by fatsbrown** [comment]
> 1. delete lines 37 to 63 from standalone.py

With #382 you can create a disable_proxy.txt file in the storage directory instead of deleting those lines.

**Comment by jricoclq** [comment]
> > 1. delete lines 37 to 63 from standalone.py
> 
> With #382 you can create a disable_proxy.txt file in the storage directory instead of deleting those lines.

Thank you.
