### ISSUE TITLE
macOS/Docker/Error 53 port already in use 

### ISSUE THREAD

**Issue by imYerik** [zoffline/zwift-offline#371]
OS: macOS 14.6.1
ZOffline version: zoffline for Zwift 1.0.135674
Install mode: Docker compose
Start zoffline container and get error. 

Error: (HTTP code 500) server error - Ports are not available: exposing port UDP 0.0.0.0:53 -> 0.0.0.0:0: listen udp 0.0.0.0:53: bind: address already in use

MacOS has a mDNSResponder process which occupy 53 port.
$ netstat -an|grep 'LISTEN ' | grep 53
tcp6       0      0  *.53                   *.*                    LISTEN     
tcp4       0      0  *.53                   *.*                    LISTEN    

$  sudo lsof -i :53
COMMAND     PID           USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
mDNSRespo   170 _mdnsresponder   66u  IPv4 0x4f9b54239732476a      0t0  UDP *:domain
mDNSRespo   170 _mdnsresponder   67u  IPv6 0x8984c9451794b150      0t0  UDP *:domain
mDNSRespo   170 _mdnsresponder   68u  IPv4 0xb83ae18b2bfdc222      0t0  TCP *:domain (LISTEN)
mDNSRespo   170 _mdnsresponder   69u  IPv6 0xd8dd24ae463b670d      0t0  TCP *:domain (LISTEN)
PacketTun 21704          yerik   10u  IPv4 0xff2fcdfd8288ce6b      0t0  UDP 192.168.1.30:57152->192.168.1.1:domain

**Comment by imYerik** [comment]
After removing the following line in docker-compose.xml, container can be start. But I'm not sure if it has any potential issues for this.
#            - 53:53/udp

**Comment by fatsbrown** [comment]
> I'm not sure if it has any potential issues for this

Port 53 is only necessary for the "fake DNS" feature (for Android client or Companion app), if you are not using it, there's no problem removing it.
