### ISSUE TITLE
How to upload zwo workout file?

### ISSUE THREAD

**Issue by imYerik** [zoffline/zwift-offline#372]
How to upload zwo workout file?
I copy the zwo files to storage/1/customworkouts, but it doesn't work.

**Comment by fatsbrown** [comment]
Workouts must be added on the client side (Documents/Zwift/Workouts/1).

storage/1/customworkouts is used to sync workouts to other devices, adding files directly there won't work. Also notice that for syncing to work, the workout name can only contain plain ASCII characters.

**Comment by imYerik** [comment]
> Workouts must be added on the client side (Documents/Zwift/Workouts/1).
> 
> storage/1/customworkouts is used to sync workouts to other devices, adding files directly there won't work. Also notice that for syncing to work, the workout name can only contain plain ASCII characters.

It works, thanks a lot!
