### ISSUE TITLE
Adroid Client

### ISSUE THREAD

**Issue by k-jccc** [zoffline/zwift-offline#373]
Can anyone verify that the latest version is working with the android client (1.0.135738)?

I carefully followed the instructions. ZofflineObb does its job and Zwift starts perfectly fine. But it does not use zoffline which runs on my linux machine, even though I configured the hosts using the VirtualHosts app. Any thoughts?

**Comment by fatsbrown** [comment]
I can confirm the latest version is working.

Looks like Virtual Hosts is not working for you. Someone reported it doesn't work on Android 14 (#148).

Some tips that fix hosts redirection issues for some:
- If using Virtual Hosts:
  - Fully close (touch the "overview" button and swipe up) the app and run it again (as described in the README)
  - Turn on airplane mode, then re-enable wifi (prevents resolution through mobile data DNS)
- If using fake DNS:
  - Set both DNS 1 and 2 to the IP address of the PC running zoffline (for me, setting only DNS 1 doesn't work)

**Comment by k-jccc** [comment]
thanks @fatsbrown! the android settings were a good hint. turning off "Private DNS" did the trick for me.

**Comment by fatsbrown** [comment]
Interesting. What's your Android version? Did you have "private DNS" enabled or automatic? Mine is set to automatic and it still works (Android 13).

**Comment by k-jccc** [comment]
I am on Android 14 and the default setting for "private dns" was "automatic".

**Comment by fatsbrown** [comment]
Just to be sure before I propose changes to the documentation, you are still using Virtual Hosts, right?

Asking because I noticed that turning off private DNS also allows me to change only DNS 1 when using the fake DNS method.

**Comment by k-jccc** [comment]
Sure, I was about to mention it myself! I still use Virtual Hosts.

**Comment by fatsbrown** [comment]
Thanks. I also noticed that if private DNS is disabled I don't need to fully close and re-run the app after selecting the hosts file, so I think turning it off is a good suggestion regardless of the redirection method or Android version.
