### ISSUE TITLE
ZCA signing patched apk file failed!

### ISSUE THREAD

**Issue by jricoclq** [zoffline/zwift-offline#376]
After upgrading my computer from system WIN10 to WIN11, the newly installed. I installed all the necessary software for making ZCA_patched.apk according to the tutorial on the newly installed system, which is not the original system upgrade. The original WIN10 can make ZCA_patched.apk normally, but now this error has occurred. Please help me check what is causing this.
![image](https://github.com/user-attachments/assets/7daad4cd-b44e-478a-b86e-fdee0616e8c8)

**Comment by fatsbrown** [comment]
Post the full log mentioned in the last line. If it doesn't exist, run apk-mitm in Git Bash instead of Windows Terminal, then the error message on screen will be more detailed.

**Comment by jricoclq** [comment]
[encoding-aapt.failed.log](https://github.com/user-attachments/files/17445946/encoding-aapt.failed.log)
[encoding-aapt2.failed.log](https://github.com/user-attachments/files/17445950/encoding-aapt2.failed.log)
[decoding.log](https://github.com/user-attachments/files/17445952/decoding.log)

it's here!

**Comment by fatsbrown** [comment]
Not much more info in the logs. Could be a permissions issue, but it's odd because it can create other directories. Try running terminal as administrator and check if the script isn't blocked in Windows Security > Virus & threat protection > Controlled folder access > Block history.

**Comment by jricoclq** [comment]
I made it again today and recorded the screen.

https://github.com/user-attachments/assets/14c332c5-632c-4bcc-8a63-4b4607c038db

**Comment by jricoclq** [comment]
[decoding.log](https://github.com/user-attachments/files/17500861/decoding.log)
[encoding-aapt.failed.log](https://github.com/user-attachments/files/17500862/encoding-aapt.failed.log)
[encoding-aapt2.failed.log](https://github.com/user-attachments/files/17500863/encoding-aapt2.failed.log)

**Comment by fatsbrown** [comment]
Still the same issue. Notice that although the last message is "signing patched APK file", the error is not there (the patched APK is not even created), the problem is that apk-mitm can't open the folder `C:\Users\陈晓\AppData\Local\Temp\apk-mitm-b8c1078db354707befe6916bbc0486d4\decode\res` for some reason. Have you tried the suggestion in my previous comment?

**Comment by fatsbrown** [comment]
One thing you can try is using the `--tmp-dir` argument.

`apk-mitm --tmp-dir E:\ZCA\tmp --certificate cert-zwift-com.pem zca.apk`

Make sure `E:\ZCA\tmp` exists and you have full permissions to it.

**Comment by jricoclq** [comment]
> Still the same issue. Notice that although the last message is "signing patched APK file", the error is not there (the patched APK is not even created), the problem is that apk-mitm can't open the folder `C:\Users\陈晓\AppData\Local\Temp\apk-mitm-b8c1078db354707befe6916bbc0486d4\decode\res` for some reason. Have you tried the suggestion in my previous comment?

I tried, but the settings are the same as you said. I'm wondering if it's because there are Chinese characters on the path. In the previous WIN10 system, my username was my English name, but this time WIN11 is my Chinese name.

**Comment by jricoclq** [comment]
> One thing you can try is using the `--tmp-dir` argument.
> 
> `apk-mitm --tmp-dir E:\ZCA\tmp --certificate cert-zwift-com.pem zca.apk`
> 
> Make sure `E:\ZCA\tmp` exists and you have full permissions to it.

The error still occurred in the "I: Building resources..." stage, forget it, I gave up, thank you very much!
