### ISSUE TITLE
Share progress between different computers

### ISSUE THREAD

**Issue by hollysheep** [zoffline/zwift-offline#380]
Normally i use Zoffline Server on my normal computer (ubuntu) and zwift client on my android tablet. when I stay overnight with my girlfriend i use my Notebook with Windows 10 (both server and client). Can i copy the progress (or profile or what else) to the notebook?

**Comment by fatsbrown** [comment]
Stop zoffline (to ensure the database is not locked) and copy the entire storage folder. If you only care about profile progress (don't mind about other data like holo replays, segment times, goals, power curves, etc) you can copy only profile.bin.
