### ISSUE TITLE
UDPHandler ParseFromstring exception: DecodeError('Error parsing message')

### ISSUE THREAD

**Issue by jricoclq** [zoffline/zwift-offline#381]
Recently, the server often encounters this abnormal situation and consumes a significant amount of network bandwidth. Please help investigate the cause. Thank you .
![1730940835546](https://github.com/user-attachments/assets/ae00551d-a2ab-4ada-ac4d-e56d17101fa5)

**Comment by jricoclq** [comment]
One more thing, can I add all the routes in the list of all routes in MEETUP?

**Comment by fatsbrown** [comment]
What's the version of the client causing this exception? There was a [change](https://github.com/zoffline/zwift-offline/commit/9b8f02dbfe6c43a2713fcef31e1c7944adee0abf#diff-de1ad9ba2a87697a52f76b84d9769f9bb33c391392d9a7d2aebd48e96dbb2540R617) in update 1.0.135866 and if an older client connects to a new server, this will happen. If it's happening with the latest client, print the hex representation of the packet payload when this exception happens (`print(p.payload.hex())`) and paste it here (as text, not screenshot).

> can I add all the routes in the list of all routes in MEETUP?

Meetups are restricted to the routes available in the Companion app.

**Comment by jricoclq** [comment]
The current situation is that all clients connected to the server will download the latest client content package from this server, and there is basically no mismatch between the client and the server. They will connect and download updates as soon as possible, so they are all matched.

**Comment by fatsbrown** [comment]
Notice that Android clients are not required to update like Windows and Mac. If you are sure there are no outdated clients, do what I suggested in previous comment (line 619 of standalone.py)

> print the hex representation of the packet payload when this exception happens (`print(p.payload.hex())`) and paste it here (as text, not screenshot)

**Comment by jricoclq** [comment]
> Notice that Android clients are not required to update like Windows and Mac. If you are sure there are no outdated clients, do what I suggested in previous comment (line 619 of standalone.py)
> 
> > print the hex representation of the packet payload when this exception happens (`print(p.payload.hex())`) and paste it here (as text, not screenshot)

OK, I'll consult with my fellow riders. thank you!

**Comment by fatsbrown** [comment]
The client causing this error is not seeing other riders or bots, they are actually using less bandwidth because they are only sending their state to the server which is not sending any response due to the exception.

**Comment by jricoclq** [comment]
> The client causing this error is not seeing other riders or bots, they are actually using less bandwidth because they are only sending their state to the server which is not sending any response due to the exception.

Understood, thank you very much for your answer.
