### ISSUE TITLE
Could you add support for operations related to the 'Club' feature? 

### ISSUE THREAD

**Issue by w905581962** [zoffline/zwift-offline#383]
I want to complete a training course with my younger brother, but currently, team courses can only be created through the 'Club' option within the app. However, there’s no way to sync a user’s Club information with the offline account in Zoffline. I also tried creating it directly through the Android app, but I received an error saying the creation failed."

**Comment by hiSandog** [comment]
It would help to split this into concrete operations: syncing existing Club membership, creating/joining a Club, and creating a Club event/course may use different API objects. A captured, redacted response shape from the official client plus the error returned by the Android creation attempt would clarify the minimum offline data model. Starting with read-only membership/event sync may be a safer first scope than full Club administration.
