### ISSUE TITLE
not sure

### ISSUE THREAD

**Issue by mesterumanele** [zoffline/zwift-offline#385]
Hello, 
just noticed after last update:
-when i started zwift on computer, i had an error (first time i see it) that a folder cannot be accessed, error ZL0someting...
-i did reboot the computer and after i disabled some random 'windows security' settings it started
-when i did the workout i noticed that the wattage was very high for very low effort! 
-the trainer difficulty in settings is at 100%
-after i finished the workout, it didn't upload automatically to garmin as usual!
-also i did update the latest companion 363, but this time it never connected to the zoffline app... i did reboot the android phone...before i had it working all the time without any issue!

not sure if this is related with my setup only or is a known issue!
it could be the windows update? the android update? have to tweak something else? 

Thank you in advance

**Comment by fatsbrown** [comment]
It's not a known issue, I have everything up to date and working (latest Zwift tested on both Windows 10 and 11, latest companion on Android 13).

Check if the zoffline executable is allowed in Windows firewall for incoming and outgoing connections.

**Comment by mesterumanele** [comment]
![image](https://github.com/user-attachments/assets/bfc0fba9-99e0-452e-b435-d92034bf2e2b)

**Comment by fatsbrown** [comment]
If you have OneDrive configured to backup the Documents folder it may have been moved to a different location.

https://forums.zwift.com/t/documents-zwift-folder-again/503778

**Comment by mesterumanele** [comment]
Hi, 
I did manipulate some settings under defender > virus > ransomware protection > Allow an app through Controlled folder access > and it started! (I did reboot the pc and kept the settings!) 

- uploaded to garmin is ok
- seems to work and be responsive like before! 
- what is strange is that i didn't do anything prior to this change! This pc is only for spinning, nothing else! 
- can close the ticket.
Thank you

**Comment by mesterumanele** [comment]
> If you have OneDrive configured to backup the Documents folder it may have been moved to a different location.
> 
> 
> 
> https://forums.zwift.com/t/documents-zwift-folder-again/503778

Previous to your message i thought it might be onedrive and disabled it and stop from starting with os. After that i had same error as in my attachment! It worked after i manipulated the defender, but could be a combination of onedrive and defender.
Thank you again!
