### ISSUE TITLE
The macOS system has a configured hosts file, and Bluetooth cannot be found.

### ISSUE THREAD

**Issue by skyyuan** [zoffline/zwift-offline#387]
Hello,
On my Mac, if I don’t configure the hosts file with:
127.0.0.1 us-or-rly101.zwift.com secure.zwift.com cdn.zwift.com launcher.zwift.com
Zwift can find Bluetooth devices.
However, after configuring it, Bluetooth devices can no longer be detected.
I have tried deleting the Bluetooth configuration files in Zwift, but the issue still persists.

**Comment by fatsbrown** [comment]
See the last comment in #366

Not sure if it works since they never replied.

**Comment by skyyuan** [comment]
> See the last comment in #366
> 
> Not sure if it works since they never replied.

Yes, I read the previous Q&A, so I tried deleting Zwift's Bluetooth files.
Then I found that as long as the hosts file is modified, the Bluetooth files won’t be created when trying to connect to Bluetooth.

**Comment by fatsbrown** [comment]
I mean the hint from the video, turn the trainer off and on while on the pairing screen.

**Comment by jricoclq** [comment]
你把连接官服时的蓝牙连接给取消掉，让它不会自动连接后，再运行单机版就好了

**Comment by skyyuan** [comment]
> 你把连接官服时的蓝牙连接给取消掉，让它不会自动连接后，再运行单机版就好了

神奇我之前试了很多次都不行今天突然就可以了
