### ISSUE TITLE
404 when configuring Stava

### ISSUE THREAD

**Issue by joe-zhang3** [zoffline/zwift-offline#388]
New to this application, thanks for sharing.

Everything works except the integration with Strava. Follow the instruction, go to Settings -> Strava -> Enter the client id and secret and click the authorization button -> enter credential of Strava -> ended up with a 404

<img width="800" alt="image" src="https://github.com/user-attachments/assets/266098db-6ec3-489d-b1a9-48323c7b4342">

Logs:

127.0.0.1 - - [19/Nov/2024 09:20:28] "GET /gameassets/Zwift_Updates_Root/LauncherMac_ver_cur.xml HTTP/1.1" 200 -
INFO:zoffline:127.0.0.1 - - [2024-11-19 09:20:28] "GET /auth/realms/zwift/protocol/openid-connect/auth?response_type=code&client_id=Game_Launcher&redirect_uri=https%3A%2F%2Flauncher.zwift.com%2Flauncher%2Frealms%2Fzwift%2Fprotocol%2Fopenid-connect%2Fauth?client_id%3DGame_Launcher%26redirect_uri%3Dhttp%253A%252F%252Fzwift%252F%26login%3Dtrue%26response_type%3Dcode&state=73e51f32-401d-4ff3-97da-380dae07cd04&login=true&scope=openid HTTP/1.1" 200 6576 0.000665
INFO:zoffline:127.0.0.1 - - [2024-11-19 09:20:28] "GET /style/site.css HTTP/1.1" 200 1494 0.000738
INFO:zoffline:127.0.0.1 - - [2024-11-19 09:20:28] "GET /style/background.jpg HTTP/1.1" 304 190 0.000600
INFO:zoffline:127.0.0.1 - - [2024-11-19 09:20:28] "GET /favicon.ico HTTP/1.1" 404 331 0.000509
INFO:zoffline:127.0.0.1 - - [2024-11-19 09:20:32] "GET /settings/zoffline/ HTTP/1.1" 200 3273 0.000762
INFO:zoffline:127.0.0.1 - - [2024-11-19 09:20:32] "GET /style/site.css HTTP/1.1" 304 183 0.000575
INFO:zoffline:127.0.0.1 - - [2024-11-19 09:20:32] "GET /style/background.jpg HTTP/1.1" 304 190 0.000488
INFO:zoffline:127.0.0.1 - - [2024-11-19 09:20:32] "GET /favicon.ico HTTP/1.1" 404 331 0.000296
INFO:zoffline:127.0.0.1 - - [2024-11-19 09:20:35] "GET /profile/zoffline/ HTTP/1.1" 200 2826 0.006428
INFO:zoffline:127.0.0.1 - - [2024-11-19 09:20:35] "GET /style/site.css HTTP/1.1" 304 183 0.000608
INFO:zoffline:127.0.0.1 - - [2024-11-19 09:20:35] "GET /style/background.jpg HTTP/1.1" 304 190 0.000406
INFO:zoffline:127.0.0.1 - - [2024-11-19 09:20:35] "GET /favicon.ico HTTP/1.1" 404 331 0.000347
INFO:zoffline:127.0.0.1 - - [2024-11-19 09:20:40] "GET /settings/zoffline/ HTTP/1.1" 200 3273 0.000801
INFO:zoffline:127.0.0.1 - - [2024-11-19 09:20:40] "GET /style/site.css HTTP/1.1" 304 183 0.000566
INFO:zoffline:127.0.0.1 - - [2024-11-19 09:20:40] "GET /style/background.jpg HTTP/1.1" 304 190 0.000412
INFO:zoffline:127.0.0.1 - - [2024-11-19 09:20:40] "GET /favicon.ico HTTP/1.1" 404 331 0.000300
INFO:zoffline:127.0.0.1 - - [2024-11-19 09:20:42] "GET /garmin/zoffline/ HTTP/1.1" 200 1974 0.006148
INFO:zoffline:127.0.0.1 - - [2024-11-19 09:20:42] "GET /style/site.css HTTP/1.1" 304 183 0.000573
INFO:zoffline:127.0.0.1 - - [2024-11-19 09:20:42] "GET /style/background.jpg HTTP/1.1" 304 190 0.000427
INFO:zoffline:127.0.0.1 - - [2024-11-19 09:20:42] "GET /favicon.ico HTTP/1.1" 404 331 0.000289
INFO:zoffline:127.0.0.1 - - [2024-11-19 09:20:47] "GET /settings/zoffline/ HTTP/1.1" 200 3273 0.000687
INFO:zoffline:127.0.0.1 - - [2024-11-19 09:20:47] "GET /style/site.css HTTP/1.1" 304 183 0.000482
INFO:zoffline:127.0.0.1 - - [2024-11-19 09:20:47] "GET /style/background.jpg HTTP/1.1" 304 190 0.000426
INFO:zoffline:127.0.0.1 - - [2024-11-19 09:20:47] "GET /favicon.ico HTTP/1.1" 404 331 0.000301
INFO:zoffline:127.0.0.1 - - [2024-11-19 09:20:48] "GET /strava/zoffline/ HTTP/1.1" 200 2193 0.000763
INFO:zoffline:127.0.0.1 - - [2024-11-19 09:20:48] "GET /style/site.css HTTP/1.1" 304 183 0.000585
INFO:zoffline:127.0.0.1 - - [2024-11-19 09:20:48] "GET /style/background.jpg HTTP/1.1" 304 190 0.000495
INFO:zoffline:127.0.0.1 - - [2024-11-19 09:20:48] "GET /favicon.ico HTTP/1.1" 404 331 0.002830
INFO:zoffline:127.0.0.1 - - [2024-11-19 09:21:30] "GET /strava_auth HTTP/1.1" 302 905 0.000810
INFO:zoffline:127.0.0.1 - - [2024-11-19 09:22:27] "POST /hvc-ingestion-service/batch HTTP/1.1" 200 125 0.000336
INFO:zoffline:127.0.0.1 - - [2024-11-19 09:24:27] "POST /hvc-ingestion-service/batch HTTP/1.1" 200 125 0.000349

**Comment by fatsbrown** [comment]
Did you set the authorization callback domain of your API application to launcher.zwift.com?

**Comment by joe-zhang3** [comment]
yes I did:

<img width="597" alt="image" src="https://github.com/user-attachments/assets/90737356-bd18-4919-8dd4-07e7acd41bf2">

**Comment by fatsbrown** [comment]
Make sure there is not a space at the end.

**Comment by joe-zhang3** [comment]
Sure, no trail space in that field. Anyway, I got it sorted out by following the manual way of running a local Strava server with the port 8000. it is working now.

**Comment by fatsbrown** [comment]
Out of curiosity, do you have launcher.zwift.com redirected to 127.0.0.1 in the hosts file?
