### ISSUE TITLE
Wahoo and intervals.icu  integration

### ISSUE THREAD

**Issue by Am1S** [zoffline/zwift-offline#390]
Please append export activity to Wahoo and/or intervals.icu

Thanks!

**Comment by fatsbrown** [comment]
Upload activity to Intervals.icu already exists, configure it in the launcher Settings - Intervals (if using Android, access https://secure.zwift.com/user/zoffline/)

![Captura de tela 2024-11-20 085008](https://github.com/user-attachments/assets/56a45138-72e8-4fa0-af56-88de0e5096f9)

Copy "Athlete ID" and "API Key" from https://intervals.icu/settings (under "Developer Settings").

**Comment by Am1S** [comment]
Thanks! Not see this in a readme.
