### ISSUE TITLE
activities are not synced with Strava, Garmin

### ISSUE THREAD

**Issue by usenetj23** [zoffline/zwift-offline#392]
there is some issue with activities syncing? from last couple of days (24.11) activities are not synced with Garmin or Strava

**Comment by fatsbrown** [comment]
Strava upload is working, check if your API app is authorized in https://www.strava.com/settings/apps and authorize again if it's not. I've seen reports of issues with other apps.

Garmin upload is broken, need to wait for a garth update or apply the fix proposed in https://github.com/matin/garth/issues/73 manually.

**Comment by usenetj23** [comment]
![2024-11-27 16_31_32-Zwift Launcher](https://github.com/user-attachments/assets/2f2e796d-b973-483a-95d4-c1a78ecac1bd)
launcher info

**Comment by oldnapalm** [comment]
While garth is not updated you can try this branch https://github.com/oldnapalm/zwift-offline/tree/garmin_upload

If you use the Windows release, download from https://github.com/oldnapalm/zwift-offline/releases/tag/zoffline_1.0.136426_garmin
