### ISSUE TITLE
installing Step2 - Android non-rooted

### ISSUE THREAD

**Issue by mesterumanele** [zoffline/zwift-offline#393]
Hello, 
not sure what i'm doing wrong; i tried both with virtual host and fake-dns file.
this is what i observe:

-i start zoffline fully working (as the app started and a workout going on) on windows machine
-during the above i installed on android tablet, lenovo (with latest android update,16xx) all steps ok, successfully no errors
-when i start zwift on android tablet, i connect to my account and i see my name on screen, with the same short as in windows zoffline, with the same droppoints... so i guess i am preatty close
-but i don't see anything else... the 'bike' on android is waiting for connection while the one on windows is running... i did reinstall, with same result...
-i didn't run, as per instructions, the zwift app, until the update is done, etc... i am a bit familiar because i run successfully zwift companion from an android phone! (i know the hosts files are different; this is with 3 lines, the zc with 2 lines)
-or is that the client works on android, but phone only, and not tablet? 

Thank you

(i just installed zc on the same android tablet, i loaded the host files with 2 lines, and zc started first try! thanks again)

**Comment by fatsbrown** [comment]
If you want to use 2 devices simultaneously, you must enable multiplayer (step 6) and create a different account for the second device. If you use the same account on both, it won't work (login may work but one won't receive other riders data).

Also notice that Bluetooth can't pair with 2 devices simultaneously, if the sensor is paired with Windows, it won't appear on Android and vice-versa.

**Comment by mesterumanele** [comment]
My understanding on running the android is the same as  for running the z.companion on android. the android install (from Step 2 explanation) will pick the window session (i guess that's all redirections done with dns/virtual hosts, to comunicate with the windows zwift session)

- while zc is working as a client on the android device while zoofline/zwift works on windows, what i'm trying to do now (Step 2 (install zwift client to use zoffline) is not the same logic? to mirror my windows zwift on android screen?
- you say i 'want to use 2 devices simultaneously' which is not; i just try to do as zc; to run one machine (windows eunninf zofline+zwift and have client, same as zc, mirrored to the android device (so zc on android plus the windows machine will not make it 2 devices? and they still work, no?)
- ooh, just occurred to me, or do you mean i have to run only zoffline on windows (without running zwift app on windows) and zwift client on android, in this case, i see it running as only one session, no? i will try this very soon! unless you say that i have to run both zoffline+zwift on the windows machine! 

sorry if I’m a bit confusing, 
Thank you again

**Comment by fatsbrown** [comment]
> or do you mean i have to run only zoffline on windows (without running zwift app on windows) and zwift client on android, in this case, i see it running as only one session, no?

Exactly. You can't have Zwift client running on Windows and also on Android with the same account.

**Comment by fatsbrown** [comment]
Garmin upload stopped working this week (see https://github.com/zoffline/zwift-offline/issues/392). If you run zoffline from source or Docker, make sure it's up to date. If you use the Windows release, download the artifact from https://github.com/zoffline/zwift-offline/actions/runs/12097300676. If it still doesn't work, maybe the fix implemented in https://github.com/zoffline/zwift-offline/commit/d564f7c108051d6dbc875d8602288eb27d9e0895 doesn't work for you, in this case you need to wait for a garth update.

**Comment by mesterumanele** [comment]
just to understand better; when an update will be available, the updated will be aincluded on zofflineexe? or i will still have to initiate a garmin login from the windows zwift app, and that login will update the settings for my setup? i hope it makes sense my question, i am a bit confused myself... not finding maybe the best words/questions... thank you (i am ok with waiting for an update)

**Comment by fatsbrown** [comment]
If you have already saved your credentials, you shouldn't need to do it again, but it's unknown at this time if changes to zoffline code will be needed when garth is updated. Although, if you download the artifact.zip from the link above, it should work (it works for me, but we didn't have feedback from anyone else, not sure if it's a country or account related issue).

**Comment by mesterumanele** [comment]
thank you for pointing me to the artifact.zip, otherwise i wouldn't know what is about... i did unzziped and run the new file and garmin did upload (after i created my new tablet-android with the client i even moved my zwift-zoffline install from my old computer/bulky to a laptop... i did restore of the zwift/zoffline folders to the new laptop and all si there; my points, my routes, all... my point is that garmin uploaded the file even from my new laptop)

**Comment by mesterumanele** [comment]
Hello, strangely enough today i did a workout with same settings of 2 days back when i reported that artifact update uploaded to my garmin; today it didn't!!
Thank you
(and i noticed that the fit file now is local to android, is not in the windows machine where i run zoffline; what folders from android/zwift i have to backup in case of crash, so i don't lose my history, rides/etc, thanks again)

**Comment by fatsbrown** [comment]
The fit file should be in `zwift-offline\storage\1\fit`, if it's not there, it means the client didn't upload the activity to zoffline, that would explain why the upload to Garmin didn't work.

Notice that you must keep using the exe from the artifact, you can't use it only to enter the credentials and then revert to the exe from the latest release.

**Comment by mesterumanele** [comment]
cannot figure it out! that workout i did finish at 4:53pm today i found the fit file inside the windows-zoffline machine inside the storage\1\fit... but didn't upload to garmin! then i did 3 more short workouts of 3min+ and they didn't appear in 1\fit... just on the android logs/fit... also, every time i start a new test file, it starts from same amount of points... not the latest i did acumulate... i'm confused on how the android is picking up the windows machine, zoffline is working, i see the cmd zoffline screen populating with lines/my workout is working fine on android, erg, etc... (just a note... i don't see any ghost or any rider... is not supper important though)... something is going on... anyway, thanks for your prompt replies; we can close this ticket; i'll go to my old setup.
Thank you
