### ISSUE TITLE
new install - not showing Launcher

### ISSUE THREAD

**Issue by mesterumanele** [zoffline/zwift-offline#395]
Hello,
i try to do a new install into a laptop/surface. 
i did a fresh install of everything! (even windows 11)
when i start zwift i see diferent login screen, with the Change User and Let's go screen... (on my zoffline-working tower, zwift start with Zwift Launcher where i can input the garmin login/etc... on this laptop i don't see the launcher!!
and 
i'd like to keep same score/drops/etc
i did copy the storage from the last backup/tower to laptop/new, but it seems to pick the droppoints from online account! not my latest! 
:-(

just noticed: 
on my working setup/tower, when i start zwift the zoffline black screen start to create lines/logs/etc
on my new setup/laptop, when i start zwift the zoffline is not producing the lines... just black with one line: server version 1.79.0 (136993) is running.

Thank you

**Comment by mesterumanele** [comment]
step 2: If you are not running zoffline on the same PC that Zwift is running: create a server-ip.txt. 
I am running zoffline on the same pc with zwift, then i didn't create! i did create, with same result though!
:-( i even reverted back to original storage folder and same result...
i'll try and try again, i have a working setup, with my tower...
is not important, can even close the ticket!
thank you

**Comment by oldnapalm** [comment]
> step 2: If you are not running zoffline on the same PC that Zwift is running: create a server-ip.txt.

That is not step 2.

https://github.com/zoffline/zwift-offline?tab=readme-ov-file#step-2-configure-zwift-client-to-use-zoffline

**Comment by mesterumanele** [comment]
Sorry! My bad!! I dont know hiw i did it first time! Was easy! Now is like a puzzle! On first step there are 'run this first,' on step 2, is the opposite, 'run this first!' It is my fault 100%, because i have it working, but now is like my logic doesn't help me! I’ll give it some time and come back to it! 
Thank you again!

**Comment by oldnapalm** [comment]
I fail to see the confusion, it looks very clear to me (note that these instructions were written by a native English speaker, and my primary language is Portuguese)

> Setting up zoffline requires two primary steps. First, zoffline must be installed and run on a system before running Zwift (either on the system running Zwift or on another locally networked system). Second, Zwift must be configured to use zoffline instead of the official Zwift server.

If you have already installed zoffline (step 1) you just need to configure Zwift to use zoffline (step 2), which can be as simple as running configure_client.bat if you are using Windows.

Feel free to propose better instructions if you think this is confusing.
