### ISSUE TITLE
latest update

### ISSUE THREAD

**Issue by mesterumanele** [zoffline/zwift-offline#396]
Hello, 
my old setup windows tower+companion that i never touched and messed up with after today update didn't update to garmin
and
The today fit file i didn't find it under storage\1\fit even though i see in this folder fit files up to dec.01...
i found it under zwift folder inside Activities (also populated with fit files up to dec 01)
and
then i tried zoffline on windows(tower) + zwift client on android. it connects, i can select the workout, connects to devices
but the power is so easy (i checked the hardware setting is 100%)
and if i stop one session and start another session it will start again from same points/drops!
and it doesn't upload to garmin
i have attached some error that i see constatantly on zoffline window

Thank you

![IMG_9184](https://github.com/user-attachments/assets/0601e8b5-d057-447f-9889-5d7a65b3a330)

And this:
![image](https://github.com/user-attachments/assets/f9848211-a6db-4993-903c-d0bf6bfee9d3)

**Comment by fatsbrown** [comment]
#385 again?

**Comment by mesterumanele** [comment]
I am very sorry! This was my good cleanup setup! Previous coments were on new tries on laptop/etc... you dont have to answer, or not so fast! Thank you anyway (for the ride, pun intended!)

**Comment by fatsbrown** [comment]
In #385 you wrote

> Hi, I did manipulate some settings under defender > virus > ransomware protection > Allow an app through Controlled folder access > and it started! (I did reboot the pc and kept the settings!)
> 
>* uploaded to garmin is ok
> 
>* seems to work and be responsive like before!
> 
>* what is strange is that i didn't do anything prior to this change! This pc is only for spinning, nothing else!
> 
>* can close the ticket.
>       Thank you

New or old setup, looks like the same issue.

**Comment by mesterumanele** [comment]
sorry about all these messages! :-)

**Comment by mesterumanele** [comment]
sorry about all these messages! :-)
