### ISSUE TITLE
HTTP 413 errors when handling a long activity upload

### ISSUE THREAD

**Issue by kanhao100** [zoffline/zwift-offline#397]
When uploading a long activity data, the server logs show two main errors:
```
INFO:zoffline:202.119.26.84 - - [2024-12-08 17:58:28] "PUT /api/profiles/2/activities/5?upload-to-strava=true HTTP/1.1" 413 441 0.001989
<gevent.ssl.SSLSocket at 0x7fa65e184280 server=True, cipher=('TLS_AES_256_GCM_SHA384', 'TLSv1.3', 256) object, fd=140, family=2, type=1, proto=0>: (from ('202.119.26.84', 59889)) Invalid HTTP method: '\x08\x05\x10\x02\x18\x01"(Zwift - Zwift Games 2024 Epic in Watopia:\x142024-12-08T05:55:40ZB\x142024-12-08T09:58:29ZM«\x1dæGU@7\x15C]\x00\x00:CeöZéBm\x00\x00ïCu;\x05\x9aB}9ÿøB\x85\x01êÚ\x08A\x8d\x01\x0eë\x8cA\x95\x01p\x0eÀD\x9d\x01j\x12\x95DÂ\x01\x8eêT\x0e \x95Rþ4\x15\x00.FIT\x00\x00@\x00\x00\x00\x00\x07\x03\x04\x8c\x04\x04\x86\x08\x14\x07\x01\x02\x84\x02\x02\x84\x05\x02\x84\x00\x01\x00\x00\x00\x00\x00\x00Ûè·A\x06\x18`\x80\x06\x18`\x80\x06\x18`\x80\x06\x18`\x80(\x00\x00\x00\x04\x01\x00\x00\x00\x00\x04A\x00\x00\x17\x00\x12ý\x04\x86\x03\x04\x8c\x07\x04\x86\x1b\x14\x07\x02\x02\x84\x04\x02\x84\x05\x02\x84\n'
INFO:zoffline:202.119.26.84 - - [2024-12-08 17:58:28] "(Zwift - Zwift Games 2024 Epic in Watopia:2024-12-08T05:55:40ZB2024-12-08T09:58:29ZM«æGU@7C]:CeöZéBmïCu;B}9ÿøB
êAëApÀDDÂêT Rþ4.FIT@


                   Ûè·A````(Aý


                              " 413 - 0.071569
```

I noticed HTTP 413 (Request Entity Too Large) errors in the logs. I checked the activity FIT file - it's about 1.3MB for a 4-hour recording session. Is there a way we can handle files of this size or maybe it's my fault?

**Comment by fatsbrown** [comment]
Try increasing `MAX_CONTENT_LENGTH`
https://github.com/zoffline/zwift-offline/blob/65d887f54a8d14d1c1d2d1ea73d09be5ae4e1f10/zwift_offline.py#L156C13-L156C31

More details https://flask.palletsprojects.com/en/stable/patterns/fileuploads/

**Comment by kanhao100** [comment]
so, 1024 * 1024  means 1 MB (1024 KB), my fit file exceed this limit, that's why.
> https://github.com/zoffline/zwift-offline/blob/65d887f54a8d14d1c1d2d1ea73d09be5ae4e1f10/zwift_offline.py#L156

but, why this activity fit file size is so huge? just 4 hours, my 8 hours activity in the past just about 800KB

**Comment by fatsbrown** [comment]
> but, why this activity fit file size is so huge? just 4 hours, my 8 hours activity in the past just about 800KB

Maybe Zwift changed something recently that increased the FIT file size. I know there was a change which caused an issue with Garmin Connect https://forums.zwift.com/t/new-garmin-synching-issues/637909

What's the date of your 8 hours / 800 KB file?

You can try inspecting both files in https://www.fitfileviewer.com/

Anyway I think this limit should be increased a bit, the example in Flask documentation is 16 MB.

**Comment by kanhao100** [comment]
> > but, why this activity fit file size is so huge? just 4 hours, my 8 hours activity in the past just about 800KB
> 
> Maybe Zwift changed something recently that increased the FIT file size. I know there was a change which caused an issue with Garmin Connect https://forums.zwift.com/t/new-garmin-synching-issues/637909
> 
> What's the date of your 8 hours / 800 KB file?
> 
> You can try inspecting both files in https://www.fitfileviewer.com/
> 
> Anyway I think this limit should be increased a bit, the example in Flask documentation is 16 MB.

Oh, the 8-hours / 800 KB file is not from Zwift; it is just from my bike computer recording from July 2024.

**Comment by jricoclq** [comment]
I was originally curious why several records that took more than 3 hours were not automatically uploaded. Looking back at the zwift-offline.db , there was no information at the end of the data file. It turned out that there was a file size setting.TKS!
![image](https://github.com/user-attachments/assets/274e30ad-41ce-47e9-a882-037bc3e937e8)
