### ISSUE TITLE
Internal server error (500) on client launch

### ISSUE THREAD

**Issue by oldnapalm** [zoffline/zwift-offline#4]
Any plans on updating zoffline to work with 1.0.28901? I'm getting internal server error on client launch. Tried to uninstall, then reinstall after installing zoffline, but it still installs latest version instead of 1.0.26736.

**Comment by zoffline** [comment]
Updated to 1.0.28901, but there shouldn't be a reason for a 500 due to those version differences. If you still see it, please send logs (`docker logs zwift-offline` if using Docker).

Not sure why it would be installing the latest instead of 1.0.26736, you may have a configuration issue. The Zwift launcher queries http://cdn.zwift.com/gameassets/Zwift_Updates_Root/Zwift_ver_cur.xml to determine the latest version, which should have been 1.0.26736 had it been hitting your zwift-offline cdn instead of the real one (well, actually 1.0.25225 if using docker since all my docker automated build suddenly stopped being automated a few months ago... fixed now)

**Comment by oldnapalm** [comment]
Thanks! The 500 was actually a configuration issue (apache/python in docker image I guess), I installed under ubuntu and it worked, but still get an error trying to download 1.0.26736

Update failed during patching. Error code: Z110 at line 518 in Patcher.cpp

Before seeing your update I managed to "downgrade" to 1.0.26736 and got it working.

Trying to run 1.0.28901 got these 404
"GET /auth/realms/zwift/tokens/login?client_id=Game_Launcher&redirect_uri=http%3A%2F%2Fzwift%2F&login=true HTTP/1.1" 404 2643 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/605.1.15 (KHTML, like Gecko)"
"POST /auth/realms/zwift/tokens/access/codes HTTP/1.1" 404 458 "-" "Zwift/11 CFNetwork/902.1 Darwin/17.7.0 (x86_64)"
"GET /api/users?Machine%20Id=2-ba0f1512-a899ff76-8c9a043d&OS%20Type=macOS&OS=OSX%2010.X%2064bit&COMPUTER=iMac18%2C3 HTTP/1.1" 404 540 "-" "CNL/1.9.0 (macOS 10.13 High Sierra; Darwin Kernel 17.7.0) zwift/? curl/7.36.0-DEV"
"GET /api/telemetry/config HTTP/1.1" 404 540 "-" "CNL/1.9.0 (macOS 10.13 High Sierra; Darwin Kernel 17.7.0) zwift/? curl/7.36.0-DEV"

But I guess you already fixed it, will try the new version soon.

Thanks.

**Comment by zoffline** [comment]
Not sure about the patching error you had, but I see you're using Zwift on a Mac, which explains the version updating issue. Zwift on Mac looks for ZwiftMac_ver_cur.xml rather than Zwift_ver_cur.xml, but I forgot to add it.

If you're feeling ambitious, it'd be great if you could provide instructions for configuring zoffline on a Mac (I don't have access to one).

Let me know if you run into any further issues - you're in a bit of uncharted territory.

**Comment by zoffline** [comment]
Oh, and re: the 404s. I only saw "/api/telemetry/config" when testing 1.0.28901, which the Zwift client seems happy to ignore so it remains unimplemented. The others may be more serious and potentially fatal, but didn't occur for me.

**Comment by oldnapalm** [comment]
The patching error was on Windows (trying to install 1.0.26736 with zoffline running). On Mac I already had the latest version installed.

On Windows I had to let it install the latest version (disabling zoffline) then "downgrade" with http://cdn.zwift.com/gameassets/Zwift_Updates_Root/Zwift_1.0.26736/ZwiftApp.exe and xml files from this repo (cdn/gameassets/Zwift_Updates_Root).

I don't have zoffline on Mac, it's running on Linux in VirtualBox, just the Zwift Client is on Mac, which is not working, I guess it's because the "/api/users?Machine Id=..." 404.

The first 404 (/auth/realms/zwift/tokens/login) generates an error on the first launcher window (were cdn/static/web/launcher/embed.html should be shown), I got past it adding to auth_server.py

@app.route('/auth/realms/zwift/tokens/login', methods=['GET', 'POST'])
def auth_realms_zwift_tokens_login():
    return redirect("http://zwift/?code=abc", 302)

I did the same to "/auth/realms/zwift/tokens/access/codes" which became a 302 in apache log, but I don't know if it isn't causing the login error, or if it's caused by "/api/users?Machine Id=..." as you said "/api/telemetry/config" is ignored. I can get to the login screen (already inside Zwift) but it fails (says no internet connection).

Tomorrow I will do some more testing, try to sniff the traffic logging in to the real server.

**Comment by oldnapalm** [comment]
Windows version 1.0.28901 works fine with your update (guess it was missing MapSchedule_v2?)

The 404s occur only in Mac version, even in 1.0.26736

**Comment by oldnapalm** [comment]
Got it running on Mac (Zwift client only, zoffline is still on Linux).

Needed this in auth_server.py
```
@app.route('/auth/realms/zwift/tokens/login', methods=['GET'])
def auth_realms_zwift_tokens_login():
    return redirect("http://zwift/?code=abc", 302)

@app.route('/auth/realms/zwift/tokens/access/codes', methods=['POST'])
def auth_realms_zwift_tokens_access_codes():
    return '{"access_token":"abc","expires_in":10800,"refresh_expires_in":2592000,"refresh_token":"abc","token_type":"bearer","id_token":"abc","not-before-policy":1408458483,"session-state":"a-b-c"}', 200
```

I also put LauncherMac_ver_cur.xml in cdn/gameassets/Zwift_Updates_Root since I see "GET /gameassets/Zwift_Updates_Root/LauncherMac_ver_cur.xml HTTP/1.1" in apache log.

I'm posting instructions to run Zwift client on Mac:

On your Mac machine running Zwift, copy the following files in this repo to a known location:
* ssl/cert-us-or.p12
* ssl/cert-secure-zwift.p12 (please notice the name is inverted in your Windows instructions)
* ssl/cert-us-or.pem
* ssl/cert-secure-zwift.pem (please notice the name is inverted in your Windows instructions)

Open Keychain Access, select "System" under "Keychain", select "Certificates" under "Category", click "File - Import Items..." and import "ssl/cert-us-or.p12". Right click "secure.zwift.com", select "Get Info" and under "Trust" choose "When using this certificate: Always Trust". Repeat the procedure with "ssl/cert-us-or.p12" ("us-or-rly101.zwift.com").

Using a text editor open "~/Library/Application Support/Zwift/data/cacert.pem"
* Append the contents of ssl/cert-us-or.pem to cacert.pem
* Append the contents of ssl/cert-secure-zwift.pem to cacert.pem

Using a text editor (with admin privileges) open /etc/hosts
* Append this line: <zoffline ip> us-or-rly101.zwift.com secure.zwift.com cdn.zwift.com 
(Where <zoffline ip> is the ip address of the machine running zoffline. If it's running on the same machine as Zwift, use 127.0.0.1 as the ip.)

**Comment by zoffline** [comment]
Awesome work, thank you! I've added your instructions and changes.
