### ISSUE TITLE
Client configuration instructions

### ISSUE THREAD

**Issue by oldnapalm** [zoffline/zwift-offline#40]
I'm thinking if the instructions to configure Zwift client to use zoffline shouldn't be updated.

It says

> * If your Zwift version is newer than 1.0.48307 you may have to uninstall, then reinstall after installing zoffline.
> * If Zwift is not installed install it after installing zoffline (1.0.48307 will be installed instead of the latest).

In order for this to work, isn't Apache with ProxyPassMatch running in a different machine needed?

Most likely new users will choose the release or standalone.py instead of Docker. In this scenario the installer/updater will fail if run with zoffline enabled (see issues #33 and #36)

> Zwift encountered the following Error Code 110 in file /Patcher.cpp at Line 526 and will close.

What about instructing users to update zoffline (copy Zwift_ver_cur.xml from Zwift folder to cdn\gameassets\Zwift_Updates_Root) and hope the update didn't break zoffline?

**Comment by kateroo** [comment]
As a new user I can attest that I chose the release instead of docker and the copying the mentioned files (copy Zwift_ver_cur.xml from Zwift folder to cdn\gameassets\Zwift_Updates_Root) didn't work for me. I'm on a mac and followed the instructions you wrote (thank-you). The easiest thing for me is to locate an old installer and if that isn't fruitful I will start over from scratch.

**Comment by oldnapalm** [comment]
The release is Windows only, if you are on Mac you have to copy `ZwiftMac_ver_cur.xml` from `~/Library/Application Support/Zwift` to `zwift-offline/cdn/gameassets/Zwift_Updates_Root`

You can also try this release (make sure you move it out of Downloads folder before running) https://github.com/oldnapalm/zwift-offline/releases/tag/Zwift_1.0.48638_macOS

**Comment by zoffline** [comment]
You're right. Does https://github.com/zoffline/zwift-offline/commit/d4351859fd8b3bb597785a755b84cd1994b85936 address this sufficiently to you?

**Comment by oldnapalm** [comment]
Sure, I think it's fine.

Regarding Mac OS, I tried to add a "simplest" instruction in https://github.com/zoffline/zwift-offline/commit/0406174b1bfa1b6381f1b9056733f8394e8ad918 (and a bunch of other README edits, sorry about that) but gave up because it requires running in terminal with sudo (not much simpler than running from source) or, if using an AppleScript app, it gets blocked by "Security & Privacy" for being from an unidentified developer. Anyway, if you think it's relevant, I can build a pyinstaller release for Mac (command line or app).

**Comment by zoffline** [comment]
Great. As you said, a "simplest" release for OS X isn't much better than running from source given sudo is required and python is already installed on OS X. So I think source will be fine, plus then there isn't a need to maintain an additional release binary. Thanks for looking into it though.
