### ISSUE TITLE
Client crashes instantly while loading Watopia. (and other maps)

### ISSUE THREAD

**Issue by xkarpi** [zoffline/zwift-offline#403]
When I launch the client on Windows, select a route, and the screen with the message "Loading Watopia..." on a blue background appears, the window closes after a few seconds. I am attaching a screenshot of the last page of logs from the terminal.

Thank you for your support! Let me know if you need any more information.

![WhatsApp Image 2024-11-29 at 20 21 13](https://github.com/user-attachments/assets/5d451c66-9f4f-4c1a-93cc-2e9f632023d7)

**Comment by fatsbrown** [comment]
Please attach the file Log.txt from Documents\Zwift\Logs.

**Comment by xkarpi** [comment]
[logfile_MISSEDUPLOAD_%5B2024-11-29_20%3A37%3A10%5D 2.txt](https://github.com/user-attachments/files/18202969/logfile_MISSEDUPLOAD_.5B2024-11-29_20.3A37.3A10.5D.2.txt)

**Comment by fatsbrown** [comment]
This log is from 2024-11-29 and seems to be from `storage\1\logfiles`, not from `Documents\Zwift\Logs`.

My suggestion, disable zoffline, update to the latest version from the official server, then update zoffline to the matching version (it may be 1.0.136993 or 1.0.137546 because the phased rollout isn't finished yet). If it still crashes, attach the last log file.

**Comment by fatsbrown** [comment]
The 1.0.137546 update rollout is complete, you should update Zwift and zoffline to this version.

**Comment by fatsbrown** [comment]
This is probably a client side issue. This similar case on the official server (same error in log) was solved by a clean Zwift install

https://forums.zwift.com/t/1-80-richmond-windows-crash/642331/6

```
ASSERT: "RouteProgressInfo(): Calling new player tracking behavior when route is null", file=D:\git\zwift-game-client\Projects\ZwiftApp\CODE\RouteProgressInfo.cpp, line=621
ERROR: ZwiftApp Crashed
```
