### ISSUE TITLE
Zoffline as Linux Container (lxc)? 

### ISSUE THREAD

**Issue by chuckiebronco** [zoffline/zwift-offline#405]
I would love to install zoffline on a proxmox Server, which uses lxc. Help to set that up would be appreciated if even possible?!
i'm really a noob on that topic, sorry if my request should Sound dumb. 
Another possibility would be a docker inside Linux Container, which I'd rather like to avoid...

Thx for your insights...

**Comment by fatsbrown** [comment]
I have never used Proxmox, but I think if you create a Linux container (https://www.tecmint.com/proxmox-create-container/) and then follow the instructions for the "Linux, Windows, or macOS (from source)" installation method in the README, it should work.
