### ISSUE TITLE
Configuration with dynamic IP domain name 

### ISSUE THREAD

**Issue by mondjef** [zoffline/zwift-offline#406]
Looking for assistance from others that might have done this already or if it's even possible given the zoffline integration. 

I have zoffline working well using the docker method on a linux box where I have the host ip (local) in the server-ip.txt of the storage directory.  Android client configured using non-rooted instructions with hosts.txt file containing the local ip of the server.  This works well... and I would now like to enable multi-player mode to external clients.  I have correctly opened up the required ports and changed the local ip address in the server-ip.txt and hosts.txt files to my external ip and tested and all works fine as it should. 

What I'd like to do is instead of using my external public ip address is use my domain name that updates automatically to that of my public dynamic ip address.  Is this possible? My guess is that on android or any other client that instead of a hosts mapping of IP for select domains used by zoffline that I need something to map them to another domain... my domain (maybe a proxy app instead of the virtual hosts)? I tried putting my domain name in server-ip.txt file and restarting zoffline and it seems to still work but the password reset function emails a link with my domain name in url and when you click on this link nothing happens but if i replace my domain name in the url with my public ip it works just fine.  🤷‍♂️

The reason I want to do this is to avoid having to update files, restart server and communicate my updated public ip to users every time my ISP  changes it...

Any ideas?

**Comment by fatsbrown** [comment]
The file server-ip.txt must contain an IP address, can't be a host name. It's not used only for the password reset, but also for the TCP and UDP telemetry servers, those are IP addresses even in the official server. Notice that if you put a host name there, the players won't see each other.

What you want is doable, but you would need to modify zoffline to resolve your domain every time it uses the `server_ip` variable. For the client side you could use a custom DNS server. Proxy is not an option because Zwift does not support it.

Maybe a better option would be using a VPN and putting the virtual interface IP address in the server-ip and hosts files.

**Comment by mondjef** [comment]
Yeah I kind of was expecting this to not work completely out of the box.  I don't think my public ip address changes very often to be honest and I do get a notification when it does change and is updated for my dynamic dns domain name (no-ip). That being said I'm sure it will not be that big of an issue to have to adjust things periodically and send a new hosts.txt file to users.... just like to automate things or set it and forget it wherever possible.

I understand what you are proposing with patching zoffline to basically resolve my domain name every time it needs the server ip (instead of just getting from server-ip.txt file). Do you think this constant domain name resolving would be a bottle neck? 
Thanks

**Comment by fatsbrown** [comment]
> Do you think this constant domain name resolving would be a bottle neck?

Not really, it's not used that often, only when player logs in

https://github.com/zoffline/zwift-offline/blob/cea8c8fda607cc4c95e13482154119ce70685f4d/zwift_offline.py#L1375

then when player connects to the TCP server

https://github.com/zoffline/zwift-offline/blob/cea8c8fda607cc4c95e13482154119ce70685f4d/standalone.py#L273
https://github.com/zoffline/zwift-offline/blob/cea8c8fda607cc4c95e13482154119ce70685f4d/standalone.py#L278

and also for the password reset feature

https://github.com/zoffline/zwift-offline/blob/cea8c8fda607cc4c95e13482154119ce70685f4d/zwift_offline.py#L663

**Comment by mondjef** [comment]
Good to know... might give it a try.  The other challenge would be figuring out the easiest way for users clients (android phones) to use my domain name instead of those swift ones. hosts.txt and the virtual hosts app requires ip address. Need something else like the custom dns you had mentioned.

**Comment by fatsbrown** [comment]
The "fake DNS" included in zoffline could be an option, but you would need to modify it too, to check your domain periodically and update the DNS records if the IP changed.

> Optionally, instead of using the "Virtual Hosts" app, you can create a ``fake-dns.txt`` file in the ``storage`` directory and set the "DNS 1" of your phone Wi-Fi connection to the IP address of the PC running zoffline

https://github.com/zoffline/zwift-offline/blob/master/fake_dns.py

**Comment by kanhao100** [comment]
> Good to know... might give it a try. The other challenge would be figuring out the easiest way for users clients (android phones) to use my domain name instead of those swift ones. hosts.txt and the virtual hosts app requires ip address. Need something else like the custom dns you had mentioned.

If you find a swift tool in android phones without root,  please let me know. Thank you very much!

**Comment by fatsbrown** [comment]
Maybe an easy solution is setting up a cron job that resolves your domain and if the IP changed, updates server-ip.txt, restarts zoffline and sends and e-mail to the users with an updated hosts.txt file.

**Comment by mondjef** [comment]
> Maybe an easy solution is setting up a cron job that resolves your domain and if the IP changed, updates server-ip.txt, restarts zoffline and sends and e-mail to the users with an updated hosts.txt file.

This is the route I took as it will be the most flexible and less fiddling with zoffline code base.
Below is the Python script I created to accomplish it, it is ran in a cron job on docker host machine every ten minutes.  Hopefully it helps others or provides a starting point to build their own script for their needs.  I did add some error checking but I would say it is not the most resilient script so others may want to add more error checking to their implementations.

Big thanks to all those that provided suggestions, much appreciated and love this project!

```
#!/usr/bin/env python

import sqlite3
import os
import sys
import json
import docker
import smtplib
import ssl
from email import encoders
from email.mime.base import MIMEBase
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

'''
This script was created to monitor the external ip address of
the docker host where the zwift-offline docker container is
hosted from in order to update container server-ip.txt file
and send emails to server users with a new hosts.txt they can
use with their clients containing the updaed public ip address.

Targeted system is a linux machine (Gentoo) and most likely
will require some modifications depending on host environment and 
host OS for this to work for other systems.
'''

STORAGE_DIR = r'/opt/zoffline'

# get current external ip address set for server
SERVER_IP_FILE = os.path.join(STORAGE_DIR,'server-ip.txt')
if not os.path.exists(SERVER_IP_FILE):
    print('server-ip.txt file must exist in server storage directory!')
    sys.exit(1)

with open(SERVER_IP_FILE, 'r') as f:
    server_ip = f.read().rstrip('\r\n')

# get current external ip address of server host
# note: zwift server is running in docker and external ip address can be
#       obtained by ip address of host interface.  Method used here may
#       need to be modified to suit the environment...i.e. may need to use
#       external service to get public ip address in some setups.

def get_external_ip(interface: str='ppp0'):
    ip = None
    try:
        net_info = json.load(os.popen('ip -brief -f inet -json address show %s' % interface))
        ip = net_info[0].get('addr_info')[0].get('local')
    except:
        pass

    return ip

external_ip = get_external_ip()

if not external_ip:
    print('Failed to retrieve current external ip address!')
    sys.exit(1)

# compare current server ip address with current external ip to see if updates are required
if server_ip == external_ip:
    print('IP address did not change, no updates needed.')
    sys.exit(0)
else:
    print('IP address has changed, beginning updates.')

    # stop docker container (this is to ensure it is safe to connect to zwift-offline db
    # and will be needed for server to acknowledge new ip address.
    client = docker.from_env()
    container = client.containers.get('zwift-offline')
    try:
        container.stop()
    except:
        print('Failed to stop zwift-offline docker container!')
        sys.exit(1)

    # container is stopped, time to query all users, set new confirguration for container, etc
    with open(SERVER_IP_FILE, 'w+t') as f:
        f.write(external_ip)

    # get users from zwift db
    if not os.path.exists(os.path.join(STORAGE_DIR,'zwift-offline.db')):
        print('zwift-offline.db file not found in storage directory!')
        sys.exit(1)
    z_db = con = sqlite3.connect('file:' + os.path.join(STORAGE_DIR,'zwift-offline.db') + '?mode=ro', uri=True)

    sql = '''
             SELECT username
             FROM user
          '''

    cursor = z_db.execute(sql)
    results = cursor.fetchall()
    z_db.close()

    if not results:
        print('Failed to get users from db, container not resumed!')
        sys.exit(1)

    users = [row[0] for row in results]

    # create new hosts.txt file to send to users
    HOSTS_FILE = os.path.join(STORAGE_DIR, 'hosts.txt')
    with open(HOSTS_FILE, 'w+t') as f:
        f.write('\n'.join([f'{external_ip} us-or-rly101.zwift.com',f'{external_ip} secure.zwift.com',f'{external_ip} cdn.zwift.com']))


    def send_mail(users, sender_email, password):
        try:
            message = MIMEMultipart()
            message['From'] = sender_email
            message['Bcc'] = ','.join(users)
            message['Subject'] = "Updated hosts.txt client file"
            content = "Attached is an updated hosts.txt file to be used with clients to connect to remote server"
            with open(HOSTS_FILE, "rb") as attachment:
                # Add the attachment to the message
                part = MIMEBase("application", "octet-stream")
                part.set_payload(attachment.read())

            encoders.encode_base64(part)
            part.add_header(
                "Content-Disposition",
                f"attachment; filename=hosts.txt",
                )
            message.attach(MIMEText(content, 'plain'))
            message.attach(part)

            with smtplib.SMTP_SSL("smtp.gmail.com", 465, context=ssl.create_default_context()) as server:
                server.login(sender_email, password)
                server.sendmail(sender_email, users, message.as_string())
                server.close()

        except Exception as exc:
            print('send email:: %s' % repr(exc))
            return False
        return True

    with open(os.path.join(STORAGE_DIR,'gmail_credentials.txt')) as f:
        sender_email = f.readline().rstrip('\r\n')
        password = f.readline().rstrip('\r\n')

    send_mail_rc = send_mail(users, sender_email, password)
    os.remove(HOSTS_FILE)

    # start the container backup using the new external ip address
    try:
        container.start()
    except:
        print('Failed to restart zwift container!')
        sys.exit(1)
if send_mail:
    sys.exit()
else:
    sys.exit(1)

```
