### ISSUE TITLE
zoffline 1.0.48969 multiple profile on Andriod client

### ISSUE THREAD

**Issue by kienkhuat** [zoffline/zwift-offline#44]
I've run zoffline_1.0.48969 with both methodes but none of them worked.

-zoffline_1.0.48969.exe
![image](https://user-images.githubusercontent.com/54994446/79817370-89a48f00-83af-11ea-8c60-a82c3f95dbaa.png)
(it doesn't have the line "INFO:werkzeug: * Running on https://0.0.0.0:443/ (Press CTRL+C to quit)" 

-standalone.py methode
![image](https://user-images.githubusercontent.com/54994446/79817419-accf3e80-83af-11ea-8aba-873dffcee3d1.png)

I've disabled firewall but nothing have changed

Compare to the latest working version (for me): zoffline_1.0.48307
![image](https://user-images.githubusercontent.com/54994446/79817600-10f20280-83b0-11ea-8dde-246208b0d2b3.png)

**Comment by oldnapalm** [comment]
Check Windows Firewall, you may have allowed version 1.0.48307 but blocked 1.0.48969

![Capturar](https://user-images.githubusercontent.com/38410858/79818432-2a6a5e80-835e-11ea-8efc-20236e1ffec4.PNG)

About standalone.py method, you must use Python 2.7

**Comment by kienkhuat** [comment]
> Check Windows Firewall, you may have allowed version 1.0.48307 but blocked 1.0.48969
> 
> ![Capturar](https://user-images.githubusercontent.com/38410858/79818432-2a6a5e80-835e-11ea-8efc-20236e1ffec4.PNG)
> 
> About standalone.py method, you must use Python 2.7

Thanks a lot for your swift support. Everything works like charm again.

I notice another minor issue is that the cmd window doesn't show any log when connecting to zwift_offline server from my andriod client. 
![image](https://user-images.githubusercontent.com/54994446/79820090-a2b03e80-83b5-11ea-84d4-e20656196ddc.png)

It used to display a log in previous version (zoffline_1.0.48307) each time I connect from my andriod.
![image](https://user-images.githubusercontent.com/54994446/79819757-d6d72f80-83b4-11ea-8d19-0293208e67eb.png)

The only annoying things is that i can't  monitor whether the server is working or not :)
Anyway, just a minor issue.

**Comment by oldnapalm** [comment]
I don't know about this difference in logging, maybe it's related to the pyinstaller environment. Does it also happen if you run from standalone.py?

It may also be related to the changes I made to support multiple profiles. Does it work with Android? Unfortunately I don't have a rooted Android device to test with.

Could you test this please?
[zoffline_1.0.48969.zip](https://github.com/zoffline/zwift-offline/files/4507414/zoffline_1.0.48969.zip)

**Comment by kienkhuat** [comment]
> I don't know about this difference in logging, maybe it's related to the pyinstaller environment. Does it also happen if you run from standalone.py?
> 
> It may also be related to the changes I made to support multiple profiles. Does it work with Android? Unfortunately I don't have a rooted Android device to test with.
> 
> Could you test this please?
> [zoffline_1.0.48969.zip](https://github.com/zoffline/zwift-offline/files/4507414/zoffline_1.0.48969.zip)

I've tried the version you give. (1.0.4869 beta :D)
and logs display is back
![image](https://user-images.githubusercontent.com/54994446/79822511-83b4ab00-83bb-11ea-9b91-a787117d9e8e.png)

Multiple profiles on my andriod client is also supported. But it is a bit tricky and requires creating a new profile on pc first (via zwift pc). Then choose "change user" in Zwift andriod will swap between the profiles created.

Everything works fine and I think I can close this issue now.

**Comment by oldnapalm** [comment]
Good to know I didn't break it for Android :)

Is there an option to add a new user in Android? Could you attach a screenshot of the user selection screen?

**Comment by kienkhuat** [comment]
I've just found that multiple users on zwift andriod is unstable

At first I've two user profile "kienkhuat"(which is named 0 in storage) and "petitprince"(which is named 1 in storage of zoffline)
![1](https://user-images.githubusercontent.com/54994446/79896865-193f5180-8433-11ea-9547-15996e6eb056.PNG)
By default, without opening zwiftpc , "change user" option in zwift andriod actually doesn't change user at all. User name "kienkhuat" (0) is always choosed.
![Screenshot_20200422-002017650](https://user-images.githubusercontent.com/54994446/79897177-83f08d00-8433-11ea-8a16-8da3c777b567.jpg)

It's difference when I opened zwiftpc under user "petitprince" (1),
![1](https://user-images.githubusercontent.com/54994446/79896972-3ecc5b00-8433-11ea-8a07-19781d2ac798.PNG)

I kept it running under "petitprince"(1) on my pc
![2](https://user-images.githubusercontent.com/54994446/79897064-602d4700-8433-11ea-8eca-c5a0c118d072.PNG)

then started zwift andriod, choosed "change user" and sign in with random name and password.
![Screenshot_20200422-002017650](https://user-images.githubusercontent.com/54994446/79897154-7cc97f00-8433-11ea-8707-6289202acad7.jpg)
![Screenshot_20200422-002022737](https://user-images.githubusercontent.com/54994446/79897202-8fdc4f00-8433-11ea-82b7-dc2cb222d8c8.jpg)

Then the username was changed from (0) to "petitprince"(1) on my andriod
![Screenshot_20200422-002106993](https://user-images.githubusercontent.com/54994446/79897288-b00c0e00-8433-11ea-81c2-0c0f8852e6d6.jpg)
![Screenshot_20200422-002147222](https://user-images.githubusercontent.com/54994446/79897293-b1d5d180-8433-11ea-87e3-0aa26dda8d66.jpg)


But then weird things happened when I restart both zwiftpc and zwift andriod

My "kienkhuat"(0) user name disappeared and "petitprince"(1) became the only user available in my zwift launcher
![3](https://user-images.githubusercontent.com/54994446/79897325-c3b77480-8433-11ea-8cd5-cb3261fd7e23.PNG)

On zwift andriod it's still the same with "petitprince" user since onlyone username can be display at a time on andriod
![Screenshot_20200422-002159673](https://user-images.githubusercontent.com/54994446/79897331-c619ce80-8433-11ea-8429-aa2243828451.jpg)

**Comment by oldnapalm** [comment]
Thanks for testing and reporting.

Did you assign the numbers 0 and 1 manually (renaming the folders)?

The problem is player_id (which is used for folder name) is also present in profile.bin. First profile is created with id 1000, second with 1001 and so on. The folders should not be renamed because player_id in profile.bin will be different from folder name, that's probably the cause of the issue.

In order to allow folder rename we would have to ensure that player_id in profile.bin is always the same as the folder name, here
https://github.com/oldnapalm/zwift-offline/blob/master/zwift_offline.py#L91

and also here (probably update the database too)
https://github.com/oldnapalm/zwift-offline/blob/master/zwift_offline.py#L272

I'm attaching a release with those changes if you are willing to test
[zoffline_1.0.48969.zip](https://github.com/zoffline/zwift-offline/files/4512163/zoffline_1.0.48969.zip)

**Comment by kienkhuat** [comment]
> Thanks for testing and reporting.
> 
> Did you assign the numbers 0 and 1 manually (renaming the folders)?
> 
> The problem is player_id (which is used for folder name) is also present in profile.bin. First profile is created with id 1000, second with 1001 and so on. The folders should not be renamed because player_id in profile.bin will be different from folder name, that's probably the cause of the issue.
> 
> In order to allow folder rename we would have to ensure that player_id in profile.bin is always the same as the folder name, here
> https://github.com/oldnapalm/zwift-offline/blob/master/zwift_offline.py#L91
> 
> and also here (probably update the database too)
> https://github.com/oldnapalm/zwift-offline/blob/master/zwift_offline.py#L272
> 
> I'm attaching a release with those changes if you are willing to test
> [zoffline_1.0.48969.zip](https://github.com/zoffline/zwift-offline/files/4512163/zoffline_1.0.48969.zip)
> 
> Edit: I updated the release in https://github.com/oldnapalm/zwift-offline/releases
> I believe the logging issue is fixed too.

I haven't renamed any folders in the Storage.
The problem which I told you had happened once before (with user names 1001 and 1000), and I had deleted all player_id folders (1000 and 1001) except the file zwift-offline.db. 
Then after opening zwiftPc and creating new account twice, new folders "0" and "1" was created by zoffline automatically.

I think the problem is that I didn't delete  zwift-offline.db 
To use the lastest release, I've just deleted all files and folders in Storage (even zwift-offline.db). Then, I created 2 new users from my zwiftpc, it created 2 new folders 1000 and 1001 like you said
![3](https://user-images.githubusercontent.com/54994446/79933277-cb9a0780-8479-11ea-8f1d-816f4db60225.PNG)

After some test, I can now swap between users on andriod. Everything works ok, again

The only small problem exists is that if I want to change user from 1000 to 1001 on andriod, I stil have to open zwiftPC under user 1001 first. Without doing so, zoffline keeps choosing 1000 as my default user on my andriod. Anyway, it's not a big deal after changed to 1001 on andriod. 
![Screenshot_20200422-090611066](https://user-images.githubusercontent.com/54994446/79934988-0140ef80-847e-11ea-974b-86dd9afbf86d.jpg)
ZwiftAndriod still keep user 1001 available on start screen , until choose change user, it will automatically roll back to 1000. (on andriod only one user name can be display on start screen at a time)

**Comment by oldnapalm** [comment]
I don't understand why it created profiles with id 0 and 1. New profile should be 1000 if there are no profiles, or increment the last existing one. Probably it's not related to the db because it's only used to store activities and segment results.

Did you start the Android client with Zwift PC running? This may have caused the issue, because zoffline doesn't expect 2 simultaneous connections. I think we need to implement login to have multi profile working properly on Android. Now it doesn't check login, as you have noticed.

Actually this multi profile thing is something I came with because I share the Zwift PC with my wife. I don't know if it's implemented in a good way or if @zoffline will merge it.

I will think about a way to define the default profile. For now it's the first one (lowest id number).

I noticed you have a strava_token.txt in the storage folder. With multi profile it should be placed inside the profile folder.

**Comment by kienkhuat** [comment]
I did start the Andriod client with Zwift Pc running. This may be the origin of the issue.

I've tried the test version. Here was the procedure
First, i've got 2 profiles kienkhuat (1000) and petitprince (1001)
![1](https://user-images.githubusercontent.com/54994446/79986927-f9fa0000-84d6-11ea-9662-9785742892f7.PNG)
![2](https://user-images.githubusercontent.com/54994446/79986953-02523b00-84d7-11ea-8fa3-c0a1636a4ae8.PNG)


I started Andriod client with just zoffline_test running (no zwift Pc)

My default profile was 1000 (kienkhuat)
![Screenshot_20200422-201426452](https://user-images.githubusercontent.com/54994446/79987908-31b57780-84d8-11ea-9751-ded7cfcbdeed.jpg)

I choosed "changed user", then typed 1001 for player_id (as you've told) 
 ![Screenshot_20200422-201429704](https://user-images.githubusercontent.com/54994446/79987949-3ed26680-84d8-11ea-9b3b-af5d97e6b36c.jpg)
![Screenshot_20200422-201507904](https://user-images.githubusercontent.com/54994446/79987963-4560de00-84d8-11ea-9232-63a4ed785cd1.jpg)

Voilà, it was loged in sucessfully under user 1001 (petiprince)
![Screenshot_20200422-201540327](https://user-images.githubusercontent.com/54994446/79988042-6295ac80-84d8-11ea-87d9-7af4387cd74a.jpg)

Here's the log.txt of the procedure above
[log 1.0.48969_test.txt](https://github.com/zoffline/zwift-offline/files/4516370/log.1.0.48969_test.txt)
 (preview) 
![image](https://user-images.githubusercontent.com/54994446/79988812-49413000-84d9-11ea-9aea-c58cd5ae9642.png)

Afterward, I've switched between my two profiles (just by typing player_id as username)  three times and it worked flawlessly

Btw, the strava_token.txt in Storage is actually a back up file, just in case if I need to manually delete profile, again :D.

Cheers

**Comment by oldnapalm** [comment]
Thanks, glad it worked.

Could you do one more test just to be sure it's working properly? (now it checks if login is a number, should default to 1000 if other value is typed and create a new profile if it doesn't exist)
[zoffline_1.0.48969_test2.zip](https://github.com/zoffline/zwift-offline/files/4516891/zoffline_1.0.48969_test2.zip)

**Comment by kienkhuat** [comment]
> Thanks, glad it worked.
> 
> Could you do one more test just to be sure it's working properly? (now it checks if login is a number, should default to 1000 if other value is typed and create a new profile if it doesn't exist)
> [zoffline_1.0.48969_test2.zip](https://github.com/zoffline/zwift-offline/files/4516891/zoffline_1.0.48969_test2.zip)

Before testing, there had been only two profiles 1000 and 1001.

At the first attemp, I logged in as 1003
![Screenshot_20200422-221013281](https://user-images.githubusercontent.com/54994446/80000754-be1b6680-84e7-11ea-96b8-72842e66fb4d.jpg)
![Screenshot_20200422-220959286](https://user-images.githubusercontent.com/54994446/80000760-bfe52a00-84e7-11ea-9abb-03e8cf0f9bcf.jpg)

Then it created a new profile like it supposed to do.
![Screenshot_20200422-220857282](https://user-images.githubusercontent.com/54994446/80000770-c4a9de00-84e7-11ea-9874-683c4ca28a00.jpg)

Here the log
` * Debug mode: off
INFO:werkzeug: * Running on https://0.0.0.0:443/ (Press CTRL+C to quit)
INFO:werkzeug:192.168.100.4 - - [22/Apr/2020 22:11:35] "GET /gameassets/MapSchedule_v2.xml HTTP/1.1" 200 -
INFO:werkzeug:192.168.100.4 - - [22/Apr/2020 22:11:35] "GET /gameassets/ZwiftAndroid_ver_cur.xml HTTP/1.1" 200 -
INFO:werkzeug:192.168.100.4 - - [22/Apr/2020 22:11:42] "GET /api/telemetry/config HTTP/1.1" 404 -
INFO:werkzeug:192.168.100.4 - - [22/Apr/2020 22:11:47] "GET /api/telemetry/config HTTP/1.1" 404 -
INFO:werkzeug:192.168.100.4 - - [22/Apr/2020 22:11:52] "GET /api/telemetry/config HTTP/1.1" 404 -
INFO:werkzeug:192.168.100.4 - - [22/Apr/2020 22:11:57] "GET /api/telemetry/config HTTP/1.1" 404 -
INFO:werkzeug:192.168.100.4 - - [22/Apr/2020 22:12:03] "GET /api/telemetry/config HTTP/1.1" 404 -
INFO:werkzeug:192.168.100.4 - - [22/Apr/2020 22:12:08] "GET /api/telemetry/config HTTP/1.1" 404 -
INFO:werkzeug:192.168.100.4 - - [22/Apr/2020 22:12:09] "GET /api/auth HTTP/1.1" 200 -
WARNING:zoffline:##### username = 1003
WARNING:zoffline:##### player_id = 1003
INFO:werkzeug:192.168.100.4 - - [22/Apr/2020 22:12:09] "POST /auth/realms/zwift/protocol/openid-connect/token HTTP/1.1" 200 -
INFO:werkzeug:192.168.100.4 - - [22/Apr/2020 22:12:09] "POST /api/users/login HTTP/1.1" 200 -
INFO:werkzeug:192.168.100.4 - - [22/Apr/2020 22:12:09] "GET /relay/worlds/hash-seeds HTTP/1.1" 404 -
INFO:werkzeug:192.168.100.4 - - [22/Apr/2020 22:12:09] "GET /api/profiles/me HTTP/1.1" 200 -
INFO:werkzeug:192.168.100.4 - - [22/Apr/2020 22:12:10] "GET /api/profiles/1003/goals HTTP/1.1" 200 -
INFO:werkzeug:192.168.100.4 - - [22/Apr/2020 22:12:10] "GET /api/zfiles/list?folder=workouts HTTP/1.1" 200 -
INFO:werkzeug:192.168.100.4 - - [22/Apr/2020 22:12:10] "GET /api/zfiles/list?folder=customworkouts HTTP/1.1" 200 -
INFO:werkzeug:192.168.100.4 - - [22/Apr/2020 22:12:10] "GET /api/private_event/feed?organizer_only_past_events=false HTTP/1.1" 200 -
INFO:werkzeug:192.168.100.4 - - [22/Apr/2020 22:12:11] "GET /api/profiles/1003/activities HTTP/1.1" 200 -
INFO:werkzeug:192.168.100.4 - - [22/Apr/2020 22:12:11] "GET /relay/dropin HTTP/1.1" 200 -
INFO:werkzeug:192.168.100.4 - - [22/Apr/2020 22:12:11] "GET /api/profiles/1003/followees?include-follow-requests=false HTTP/1.1" 200 -
INFO:werkzeug:192.168.100.4 - - [22/Apr/2020 22:12:11] "POST /api/events/search?limit=100 HTTP/1.1" 200 -
INFO:werkzeug:192.168.100.4 - - [22/Apr/2020 22:12:11] "PUT /api/profiles/1003 HTTP/1.1" 204 -
INFO:werkzeug:192.168.100.4 - - [22/Apr/2020 22:12:12] "POST /api/zfiles HTTP/1.1" 200 -
INFO:werkzeug:192.168.100.4 - - [22/Apr/2020 22:12:12] "GET /relay/dropin HTTP/1.1" 200 -
INFO:werkzeug:192.168.100.4 - - [22/Apr/2020 22:12:13] "GET /api/telemetry/config HTTP/1.1" 404 -
INFO:werkzeug:192.168.100.4 - - [22/Apr/2020 22:12:18] "GET /api/telemetry/config HTTP/1.1" 404 -
INFO:werkzeug:192.168.100.4 - - [22/Apr/2020 22:12:19] "GET /relay/worlds/hash-seeds HTTP/1.1" 404 -
INFO:werkzeug:192.168.100.4 - - [22/Apr/2020 22:12:24] "GET /api/telemetry/config HTTP/1.1" 404 -` 

Then at the second attemp, 
I logged in as a random string ("kien")
![Screenshot_20200422-222800502](https://user-images.githubusercontent.com/54994446/80002138-7990ca80-84e9-11ea-9ea0-d7022d654962.jpg)

Then voilà, zoffline choosed 1000 as my profile
` * Debug mode: off
INFO:werkzeug: * Running on https://0.0.0.0:443/ (Press CTRL+C to quit)
INFO:werkzeug:192.168.100.4 - - [22/Apr/2020 22:27:38] "GET /api/telemetry/config HTTP/1.1" 404 -
INFO:werkzeug:192.168.100.4 - - [22/Apr/2020 22:27:44] "GET /api/telemetry/config HTTP/1.1" 404 -
INFO:werkzeug:192.168.100.4 - - [22/Apr/2020 22:27:49] "GET /api/telemetry/config HTTP/1.1" 404 -
INFO:werkzeug:192.168.100.4 - - [22/Apr/2020 22:27:54] "GET /api/telemetry/config HTTP/1.1" 404 -
INFO:werkzeug:192.168.100.4 - - [22/Apr/2020 22:27:59] "GET /api/telemetry/config HTTP/1.1" 404 -
INFO:werkzeug:192.168.100.4 - - [22/Apr/2020 22:28:03] "GET /api/auth HTTP/1.1" 200 -
WARNING:zoffline:##### username = kien
INFO:werkzeug:192.168.100.4 - - [22/Apr/2020 22:28:03] "POST /auth/realms/zwift/protocol/openid-connect/token HTTP/1.1" 200 -
INFO:werkzeug:192.168.100.4 - - [22/Apr/2020 22:28:03] "POST /api/users/login HTTP/1.1" 200 -
INFO:werkzeug:192.168.100.4 - - [22/Apr/2020 22:28:03] "GET /relay/worlds/hash-seeds HTTP/1.1" 404 -
INFO:werkzeug:192.168.100.4 - - [22/Apr/2020 22:28:03] "GET /api/profiles/me HTTP/1.1" 200 -
INFO:werkzeug:192.168.100.4 - - [22/Apr/2020 22:28:04] "GET /api/profiles/1000/goals HTTP/1.1" 200 -
INFO:werkzeug:192.168.100.4 - - [22/Apr/2020 22:28:04] "GET /api/zfiles/list?folder=workouts HTTP/1.1" 200 -
INFO:werkzeug:192.168.100.4 - - [22/Apr/2020 22:28:04] "GET /api/zfiles/list?folder=customworkouts HTTP/1.1" 200 -
INFO:werkzeug:192.168.100.4 - - [22/Apr/2020 22:28:04] "GET /api/private_event/feed?organizer_only_past_events=false HTTP/1.1" 200 -
INFO:werkzeug:192.168.100.4 - - [22/Apr/2020 22:28:04] "GET /api/profiles/1000/activities HTTP/1.1" 200 -
INFO:werkzeug:192.168.100.4 - - [22/Apr/2020 22:28:04] "GET /relay/dropin HTTP/1.1" 200 -
INFO:werkzeug:192.168.100.4 - - [22/Apr/2020 22:28:05] "GET /api/profiles/1000/followees?include-follow-requests=false HTTP/1.1" 200 -
INFO:werkzeug:192.168.100.4 - - [22/Apr/2020 22:28:05] "GET /api/telemetry/config HTTP/1.1" 404 -
INFO:werkzeug:192.168.100.4 - - [22/Apr/2020 22:28:05] "POST /api/events/search?limit=100 HTTP/1.1" 200 -
INFO:werkzeug:192.168.100.4 - - [22/Apr/2020 22:28:06] "PUT /api/profiles/1000 HTTP/1.1" 204 -
INFO:werkzeug:192.168.100.4 - - [22/Apr/2020 22:28:06] "POST /api/zfiles HTTP/1.1" 200 -`

I think you could now update version 1.0.48969 and README file also 😄 

Btw, I won't mind if you need me to test something else regarding zoffline on Andriod. So just feel free to ask ;) 
 
Cheers

**Comment by oldnapalm** [comment]
Nice, thanks!

I updated the release and README in https://github.com/oldnapalm/zwift-offline

Cheers

**Comment by oldnapalm** [comment]
Hi @kienkhuat 

If you are still using zoffline on Android and can test, please see https://github.com/zoffline/zwift-offline/issues/90#issuecomment-719012757

Thanks
