### ISSUE TITLE
get profile error

### ISSUE THREAD

**Issue by mtselection** [zoffline/zwift-offline#46]
Hi,
When try to get my profile, I receive the error:
HTTP Request failed: HTTPSConnectionPool(host='secure.zwift.com', port=443): Max retries exceeded with url: /auth/realms/zwift/tokens/access/codes (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000000004333780>: Failed to establish a new connection: [Errno 10061]

Regards

**Comment by oldnapalm** [comment]
Hello,

you need to disable zoffline before running get_profile.

https://github.com/zoffline/zwift-offline#enablingdisabling-zoffline

**Comment by mtselection** [comment]
Hello,

thank you for replay, I have now the profile.bin and I copy in the storage folder.
Reenable the zoffline and start zoffline, start the zwift with my profile, but can't logged. I try with my credential but not accept. This is a log:

 * Serving Flask app "zwift_offline" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
INFO:werkzeug: * Running on https://0.0.0.0:443/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [28/Apr/2020 15:45:30] "GET /api/auth HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [28/Apr/2020 15:45:30] "GET /launcher/realms/zwift/protocol/openid-connect/auth?client_id=Game_Launcher&redirect_uri=http:%2F%2Fzwift%2F&login=true&response_type=code HTTP/1.1" 200 -
127.0.0.1 - - [28/Apr/2020 15:45:32] "GET /gameassets/Zwift_Updates_Root/Zwift_ver_cur.xml HTTP/1.1" 200 -
127.0.0.1 - - [28/Apr/2020 15:45:32] "GET /gameassets/Zwift_Updates_Root/Launcher_ver_cur.xml HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [28/Apr/2020 15:45:38] "POST /start-zwift HTTP/1.1" 302 -
INFO:werkzeug:127.0.0.1 - - [28/Apr/2020 15:45:38] "GET /ride HTTP/1.1" 302 -
INFO:werkzeug:127.0.0.1 - - [28/Apr/2020 15:45:38] "POST /auth/realms/zwift/protocol/openid-connect/token HTTP/1.1" 200 -
127.0.0.1 - - [28/Apr/2020 15:45:38] "GET /static/web/launcher/embed.html HTTP/1.1" 200 -
127.0.0.1 - - [28/Apr/2020 15:45:40] "GET /gameassets/MapSchedule_v2.xml HTTP/1.1" 200 -
127.0.0.1 - - [28/Apr/2020 15:45:40] "GET /gameassets/Streaming/Zwift_StreamingFiles_ver_cur.xml HTTP/1.1" 200 -
127.0.0.1 - - [28/Apr/2020 15:46:38] "GET /gameassets/Zwift_Updates_Root/Zwift_ver_cur.xml HTTP/1.1" 200 -
127.0.0.1 - - [28/Apr/2020 15:46:38] "GET /gameassets/Zwift_Updates_Root/Launcher_ver_cur.xml HTTP/1.1" 200 -


Thanks

**Comment by oldnapalm** [comment]
Did it work before downloading your online profile?

Did you do the certs part in step 2?

**Comment by mtselection** [comment]
Yes, if I disable zoffline I'm logged normally.

I have a dubt, when I import ssl certificate I have generate c:\ssl directory with the files and I run under this directory certutil.exe -importpfx Root cert-zwift-com.p12 with administrator prompt.
I skip the password and finish ok, now in the cacert.pem I added line  ssl/cert-zwift-com.pem , is correct?
I try to add c:\ssl\scert-zwift-com.pem 

Thanks

**Comment by oldnapalm** [comment]
In cacert.pem you have to append the **contents** of cert-zwift-com.pem

Open cert-zwift-com.pem with Notepad, select all and copy. Then open cacert.pem and paste at the bottom.

**Comment by mtselection** [comment]
Thank you very much, now work perfect.
