### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by oldnapalm** [zoffline/zwift-offline#47]
In https://github.com/zoffline/zwift-offline/pull/41 I changed this `logging.basicConfig(level=os.environ.get("LOGLEVEL", "INFO"))` because https requests were not being logged in my Windows install.

Today I was looking for the reason your exe release is at least 1 MB smaller than mine. I was building with 64 bit Python and you do with 32 bit.

Now I changed to 32 bit and I see it works fine with `logging.basicConfig()` and with the change I did it displays `[37m` and `[0m` surrounding https requests (I'm guessing it's a color tag that Windows prompt doesn't show properly). On Mac it works no matter the basicConfig parameters, so you may want to revert my change.

**Comment by zoffline** [comment]
Odd, I'm not seeing that at least with zoffline_1.0.48969_r1.exe

**Comment by oldnapalm** [comment]
I don't see it in your release too, but in the exe I built or if I run standalone.py it happens.

![Capturar](https://user-images.githubusercontent.com/38410858/80514574-14a8fa80-8957-11ea-8dff-e098d8ef08e7.PNG)

Do you have 32 bit Windows?

Not a big deal anyway.

**Comment by zoffline** [comment]
Have 64 bit Windows. I just build 32 bit releases for compatibility. Whatever the issue is it's with Python so not much can be done and as you said it's not a big deal. Need to start supporting Python 3 anyway.

**Comment by oldnapalm** [comment]
Just to mention the fix

```
import os
import platform

if os.name == 'nt' and platform.release() == '10' and platform.version() >= '10.0.14393':
    # Fix ANSI color in Windows 10 version 10.0.14393 (Windows Anniversary Update)
    import ctypes
    kernel32 = ctypes.windll.kernel32
    kernel32.SetConsoleMode(kernel32.GetStdHandle(-11), 7)
```

https://gist.github.com/RDCH106/6562cc7136b30a5c59628501d87906f7

**Comment by zoffline** [comment]
Feel free to commit that if you'd like.

**Comment by oldnapalm** [comment]
Thanks, I think I will.

The colored log is not related to Python version or arch, it was introduced by one of these updates (when I switched from 64 to 32 bit I also reinstalled the packages)

Flask 1.0.2 -> 1.1.2
Jinja2 2.10 -> 2.11.2
Werkzeug 0.14.1 -> 1.0.1
Click 7.0 -> 7.1.2

Looking at Werkzeug changelog I'm guessing this is the cause

> Optional request log highlighting with the development server is handled by Click instead of termcolor.
