### ISSUE TITLE
Update to Zwift 1.0.49663 causes crash

### ISSUE THREAD

**Issue by zoffline** [zoffline/zwift-offline#49]
zoffline with Zwift 1.0.49663 causes Zwift to crash while logging in (or thereabouts) on Windows.

edit: same for Zwift 1.0.49751. Have traces from real servers. Will investigate later.

**Comment by oldnapalm** [comment]
Looks like it requires the TCP telemetry server in /api/users/login now.

Luckily returning 127.0.0.1 makes it work.

There's also a new request "GET /api/tcp-config".

**Comment by zoffline** [comment]
Nice, thanks!
