### ISSUE TITLE
GET /launcher HTTP/1.1 (Mac client)

### ISSUE THREAD

**Issue by oldnapalm** [zoffline/zwift-offline#5]
Mac client eventually calls "/launcher" instead of "/auth/realms/zwift/tokens/login", needed to add redirect to get past initial login window
```
# Called by Mac, but not Windows
@app.route('/launcher', methods=['GET'])
def launcher():
    return redirect("http://zwift/?code=abc", 302)
```

**Comment by zoffline** [comment]
Thanks! Pushed the fix.
