### ISSUE TITLE
Update error on Mac client (fail to download manifest)

### ISSUE THREAD

**Issue by oldnapalm** [zoffline/zwift-offline#6]
Update fails on Mac because ProxyPassMatch on cdn.zwift.com does not cover ZwiftMac_*_manifest.xml

> Patcher: ERROR #Z113, FILE "ZwiftMac_1.0.29337_manifest.xml", LINE 473: Loading local or server manifest XML file! (server manifest sucessfully downloaded)

```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /gameassets/Zwift_Updates_Root/ZwiftMac_1.0.29337_manifest.xml was not found on this server.</p>
<hr>
<address>Apache/2.4.29 (Ubuntu) Server at cdn.zwift.com Port 80</address>
</body></html>
```

Current ZwiftMac_ver_cur.xml is 1.0.29385
`<Zwift version="1.0.29385" GAME_URL="https://us-or-rly101.zwift.com" manifest="ZwiftMac_1.0.29385_manifest.xml" manifest_checksum="-1147172073" mandatory_version="0.0.0" ver_cur_checksum="-454746902"/>`

Current LauncherMac_ver_cur.xml is 1.0.7
`<Launcher version="1.0.7" URL="http://cdn.zwift.com/app/MacUpdate/"/>`

Also, clicking on "Click here to start Zwift" doesn't launch Zwift, I need auto_launch.txt in storage (no idea on this one, tried both 1.0.29337 and 1.0.29385).

**Comment by zoffline** [comment]
Thanks for the report! Appreciated. Pushed the fix.

**Comment by zoffline** [comment]
Missed the second bit. Will look into it.

**Comment by oldnapalm** [comment]
Thanks! Let me know if there's any test I can do.

**Comment by oldnapalm** [comment]
Still doesn't work.

If I change the href in embed-noauto.html to other link (local or remote) it opens the link.

Looks like it's trying to resolve http://zwift, if I add "zwift" to hosts file it opens the apache root.

**Comment by zoffline** [comment]
Should be fixed now.

**Comment by oldnapalm** [comment]
Yes, it's working now, thanks!
