### ISSUE TITLE
pyinstaller excluding import 'Tkinter'

### ISSUE THREAD

**Issue by oldnapalm** [zoffline/zwift-offline#61]
Noticed pyinstaller excludes Tkinter when building standalone with Python 2
```
7511 INFO: Excluding import 'Tkinter'
7512 INFO:   Removing import of Tkinter from module pydoc
```
Using Python 3 the module is included. Should we explicitly remove it to reduce the file size, since it's not used?
https://github.com/pyinstaller/pyinstaller/wiki/Recipe-remove-tkinter-tcl

**Comment by zoffline** [comment]
Yes, good catch. Either you can update the spec file or I can later. At the moment I can't test changes.

**Comment by oldnapalm** [comment]
Added commit https://github.com/zoffline/zwift-offline/commit/7afa77ecac80a0b6bb18bba9a5a110fb8a3ce84b
