### ISSUE TITLE
Cert issue in update 1.0.51959

### ISSUE THREAD

**Issue by oldnapalm** [zoffline/zwift-offline#62]
In 1.0.51959 cacert.pem was updated, now it uses `\r\r (0D0D)` instead of `\r\n (0D0A)` for line break on Mac and `\r\r\n (0D0D0A)` on Windows.

Edit: looks like the problem is when you open a file with `\r\r` (cacert.pem) with a text editor (tested with Notepad and Notepad++ on Windows and TextMate on Mac) and paste content with `\r\n` (cert-zwift-com.pem), all `\r\n` in the pasted content turn into just `\r`, client fails to read it and login fails.

If you use `>>` to append cert-zwift-com.pem to cacert.pem it works because `\r\n` is preserved.

On Windows: `type cert-zwift-com.pem >> cacert.pem`
On Mac: `cat cert-zwift-com.pem >> cacert.pem`

For those who prefer using a text editor I suggest using Notepad++ to replace all `\r\r\n` with `\r\n` and save cacert.pem before appending cert-zwift-com.pem contents.

![Capturar](https://user-images.githubusercontent.com/38410858/84558215-85d61e80-ad07-11ea-81c7-d79be0e70740.PNG)

**Comment by zoffline** [comment]
That's annoying. Let's wait and see if the file is updated in the next Zwift version.

**Comment by zoffline** [comment]
I updated the README with instructions to append via command line and referenced this issue. Going to leave it open for awhile as people upgrade and run into problems starting Zwift.

**Comment by oldnapalm** [comment]
Do you think it's worth mentioning Windows 7 in the README? The only difference is you have to omit the Root parameter in the certutil command.

#30 #67 

Maybe under Windows 10 instructions:

* Open Command Prompt as an admin, cd to that location and run
  * ``certutil.exe -importpfx Root cert-zwift-com.p12``
    * For Windows 7: ``certutil.exe -importpfx cert-zwift-com.p12``
  * If you're prompted for a password, just leave it blank. There is no password.

**Comment by zoffline** [comment]
Yep, added it.

**Comment by zoffline** [comment]
Closing this now. Referenced in CHANGELOG.
