### ISSUE TITLE
Expose ports 3022 and 3023 in Docker

### ISSUE THREAD

**Issue by oldnapalm** [zoffline/zwift-offline#64]
Just adding in Dockerfile is enough?

https://github.com/zoffline/zwift-offline/blob/09f8ebbddad9d9d88ad55ae4ea44739f6cf4d77a/Dockerfile#L12

Reported by @msobecki in https://github.com/zoffline/zwift-offline/issues/56#issuecomment-645849185

**Comment by zoffline** [comment]
Yes, that should be all that's needed.

**Comment by msobecki** [comment]
Hi, I'm currently out of town until monday so I cannot test it, but AFAIR default protocol for ports specified in Dockerfile is TCP, so for 3022 it should be 3022/UDP. And expose in dockerfile is only information, so it is needed to specify 3022/3023 ports mapping by -p when creating container.

BR, 
Marcin

**Comment by zoffline** [comment]
Yes, wasn't thinking when I replied, heh.
