### ISSUE TITLE
Login problem

### ISSUE THREAD

**Issue by uros76** [zoffline/zwift-offline#66]
First, thanks for this tool! 

I installed it on Windows PC and followed 1-2-3 steps as instructed. My zwift profile was obtained and stored correctly. 
However, I am getting login issues. Offline zwift doesn't let me login. 
Am I doing something wrong? 

On the screenshot below, I deleted my login email...

![image](https://user-images.githubusercontent.com/25409772/85917878-427ac480-b85e-11ea-8d8c-ab8bd84b04f0.png)

**Comment by uros76** [comment]
Actually, I obtained zwift profile before adding line to hosts file. 
Now I am trying to obtain a profile with modified hosts file and get this error: 

![image](https://user-images.githubusercontent.com/25409772/85918063-ced9b700-b85f-11ea-91e0-c4d7a5f0defd.png)

**Comment by mhewitt1978** [comment]
I have the same issue. It all installs fine I installed my user profile, such that the new launcher screen appears and I can choose my profile and world

However I just end up with the login screen as above. 

I am fairly sure that the problem stems from the modification of cacert.pem as notably with the zoffline server disabled and the hosts file entry deleted. Zwift still lands on the login screen again, however I'm deleting the appended certificates Zwift loads normally

**Comment by oldnapalm** [comment]
Please see #62, I think it may be your problem.

**Comment by uros76** [comment]
> Please see #62, I think it may be your problem.

You were right. That helped!

**Comment by m90att** [comment]
I'm seeing the same issue originally raised in this issue.  I've checked #62 and followed the instructions there but I'm still facing the same issue.  Can anyone advise please?

**Comment by oldnapalm** [comment]
@m90att what did you try from #62?

If you use Notepad++ you have to replace all `\r\r\n` in cacert.pem with `\r\n` and save the file (I would close and re-open the file to make sure) before pasting cert-zwift-com.pem contents.

The easiest way is reverting the changes in cacert.pem and running scripts\configure_client.bat

**Comment by m90att** [comment]
Yep, tried all of that, made the changes to the cert file, saved, closed
and reopened to double check. Checked hosts file, IP address.  I've checked
everything a few times but still cannot see the issue.

**Comment by oldnapalm** [comment]
If you get login error it's probably the line end issue (#62)

Try with this
[cacert.zip](https://github.com/zoffline/zwift-offline/files/4848324/cacert.zip)

**Comment by m90att** [comment]
I took your advice and reverted the cacert.pem changes and used the configure_client.bat file and voila, it works.  Thank you so much for your work on this.
