### ISSUE TITLE
Cert issue - Win 7

### ISSUE THREAD

**Issue by richlove1** [zoffline/zwift-offline#67]
Hi

Not sure if this is compatible with Win 7?

I've followed all instructions, including 'issue 62' relating to the cert, but getting an error on starting Zwift.

When Zwift Offline is running, should I see services/calls via 127.0.0.1 running in the CMD window (I saw similar on a FB screenshot)?

Here are a few shots:

![Capture2](https://user-images.githubusercontent.com/325318/86151749-0f9f2d80-baf7-11ea-87a0-be0db8d4ac52.PNG)
![Capture3](https://user-images.githubusercontent.com/325318/86151753-1037c400-baf7-11ea-9ae2-74ceb2d6cdab.PNG)
![Capture1](https://user-images.githubusercontent.com/325318/86151755-1037c400-baf7-11ea-8209-605d23adbb4c.PNG)

**Comment by richlove1** [comment]
(I tried also manually installing the cert-zwift-com.p12, as it seems from the lower screenshot, maybe it's having trouble with that.

**Comment by oldnapalm** [comment]
For Windows 7 you have to omit Root

`certutil.exe -importpfx cert-zwift-com.p12`

https://github.com/zoffline/zwift-offline/issues/30#issuecomment-558633086

**Comment by richlove1** [comment]
Great, that worked, thanks! Just trying to get Strava auth working but bit confused. If I run the strava_auth.exe helper, can I then visit localhost:8000 to authorize or do I still need to install python and do these parts:

`Install dependencies: stravalib
e.g., on Windows in command prompt: C:\Python27\Scripts\pip.exe install stravalib
Get CLIENT_ID and CLIENT_SECRET from https://www.strava.com/settings/api
Run scripts/strava_auth.py --client-id CLIENT_ID --client-secret CLIENT_SECRET` 

My assumption was that the helper was negating the need for these steps, but maybe not so...

**Comment by richlove1** [comment]
Perfect, all working. Except I followed the ghost instructions but there was no ghost file.

Will screenshot functionality/upload get added?

**Comment by oldnapalm** [comment]
> Just trying to get Strava auth working but bit confused. If I run the strava_auth.exe helper, can I then visit localhost:8000 to authorize or do I still need to install python and do these parts:

You can visit localhost:8000 and authorize, strava_token.txt will be saved, move it to your profile folder.

> I followed the ghost instructions but there was no ghost file.

Make sure you didn't create a file `enable_ghosts.txt.txt`

Only activities with more than 5 km are saved as ghosts (as well as uploaded to Strava).

> Will screenshot functionality/upload get added?

Screenshots are saved in C:\Users\user\Pictures\Zwift, you can upload to Strava website (edit activity).

I looked at the Strava API and found nothing about uploading pictures.

**Comment by richlove1** [comment]
Awesome, all sorted, thanks (I had created .txt.txt - I should know better 😄)

Thanks for your help and great tool.
