### ISSUE TITLE
Activity name encoding error - Ghost feature

### ISSUE THREAD

**Issue by MariusRumpf** [zoffline/zwift-offline#69]
When an activity is saved with ghost enabled I get an error due to the name encoding in the url. The activity name does not seem to be escaped which leads to an exception thrown for me. 

Python Version: 3.8

```
File "/usr/src/app/zwift-offline/zwift_offline.py", line 403, in api_profiles_activities_id
urllib2.urlopen("http://cdn.zwift.com/saveghost?%s" % activity.name)

File "/usr/local/lib/python3.8/http/client.py", line 1185, in _validate_path
    raise InvalidURL(f"URL can't contain control characters. {url!r} "
http.client.InvalidURL: URL can't contain control characters. '/saveghost?Zwift - Innsbruck' (found at least ' ')
```

**Comment by oldnapalm** [comment]
Thanks for reporting.

We previously used requests and in https://github.com/zoffline/zwift-offline/commit/e5e753b866f73800ddfc76a7354fab3ef784a643 it was replaced by urllib. Will take a look on how to fix it.

**Comment by zoffline** [comment]
Pulled your fix. Sorry, again.

**Comment by MariusRumpf** [comment]
Thanks, keep up the good work.
