### ISSUE TITLE
GET /auth/realms/zwift/tokens/registrations (Mac clean install)

### ISSUE THREAD

**Issue by oldnapalm** [zoffline/zwift-offline#7]
Launcher calls `/auth/realms/zwift/tokens/registrations` instead of `/auth/realms/zwift/tokens/login` or `/launcher` on Mac clean install.
Needed to add
`@app.route('/auth/realms/zwift/tokens/registrations', methods=['GET'])  # Called by Mac, but not Windows`

**Comment by zoffline** [comment]
Thanks for the report! Appreciated. Pushed the fix.
