### ISSUE TITLE
Cannot upload to strava 

### ISSUE THREAD

**Issue by megachweng** [zoffline/zwift-offline#71]
the route `/api/profiles/<int:player_id>/activities/<string:activity_id>` was not called by Zwift after I clicked `Save and Exit` button

![1](https://user-images.githubusercontent.com/18111773/87571739-1afc7680-c6fd-11ea-9fef-c55396ce7812.PNG)

**Comment by oldnapalm** [comment]
If your ride was longer than 5 km, your imported profile may be missing the attribute `is_connected_to_strava`.

You can try adding this in zwift_offline.py before line 270

```
        if profile.is_connected_to_strava != 1:
            logger.warn('Profile is not connected to Strava')
            profile.is_connected_to_strava = True
```

https://github.com/zoffline/zwift-offline/blob/91a95624f3c47958d21b334ef90ebfb758a149aa/zwift_offline.py#L270

Rides shorter than 5 km are not uploaded to Strava. You can upload the FIT file saved in `Documents\Zwift\Activities` to Strava website.

**Comment by megachweng** [comment]
Windows10 and Zwift 1.0.53342

**Comment by oldnapalm** [comment]
Are you running from source or standalone executable?

Can you do the test suggested above?

**Comment by zoffline** [comment]
As @oldnapalm's testing showed, that route is called unconditionally upon saving your activity whether or not Strava is linked. In handling that route with zoffline, an upload to Strava is attempted regardless of if the profile is linked. As long as "Save & Exit" is clicked after finishing an activity longer than 5km, I can't think of a reason the client wouldn't call that route.

**Comment by megachweng** [comment]
@oldnapalm @zoffline yeah I my test ride is less than 5km, I'll try later with a longer ride

**Comment by megachweng** [comment]
Tested. Ride must longer than 5km
