### ISSUE TITLE
Is there a way to connect Zwift Companion to Zoffline?

### ISSUE THREAD

**Issue by ErnestFlaming** [zoffline/zwift-offline#73]
Is there a way to connect Zwift Companion to Zoffline?

Sorry for the dumb question, but i wanna know if there is a way to do it.
Thanks a lot!

**Comment by oldnapalm** [comment]
I think it's possible to implement, but not sure if it's worth the effort, since most of Companion features are for social interactions. It would require a rooted Android phone (or maybe a jailbroken iPhone) to make the app use zoffline instead of Zwift server (see about configuring Android client in the README).

Which features of Companion would you like to use with zoffline?

**Comment by ErnestFlaming** [comment]
I love the watss radar on the companion, when im doing a training,
And also, i like the way it connects via bluetooth mi equipment, cause mi pc doesnt have integrated bluetooth.
Few week ago i buy a bluetooth dongle 4.0, but it seem uncompatible with windows 10. Only detects my headsets but no cadence/ velocity sensors.

**Comment by oldnapalm** [comment]
Try to unpair the sensors in your phone, then click on the gear icon in the device pair screen and select built in bluetooth.

![Captura de Tela 2020-08-14 às 17 42 56](https://user-images.githubusercontent.com/38410858/90291262-e859b100-de55-11ea-946b-9b0532363d0c.png)

**Comment by ErnestFlaming** [comment]
Thanks for the advise. It seems my bluetooth is only transmitter, not reciever. Any suggestions of what tipe of bluettoth version is needed to make it work?

Thanks a lot!

**Comment by oldnapalm** [comment]
It should work with Bluetooth 4.0 and Windows 10. Does the BT icon show "beating" in the paired devices screen?

![Capturar](https://user-images.githubusercontent.com/38410858/90312380-5e076080-deda-11ea-90bb-5d24f88100a6.PNG)

If your sensors support ANT, I would recommend you to buy an ANT adaptor, it seems much less problematic than BT for Zwift.

**Comment by ErnestFlaming** [comment]
Thanks a lot, ill try that!
