### ISSUE TITLE
Possible problems with the certificate

### ISSUE THREAD

**Issue by resolverit** [zoffline/zwift-offline#75]
Hi! Help wanted! ;) I did everything according to the instructions as written here: "zwift-offline". But for some reason when I run: "C: \ Python27 \ python.exe standalone.py" and "Zwift" it cannot login as my user. writes that: "zwift failed to login check internet connection". I wrote in the hosts file: "127.0.0.1 us-or-rly101.zwift.com secure.zwift.com cdn.zwift.com launcher.zwift.com". I connected the profile as indicated in Step 3, moved the file to storage, but does not work.
-------
Checked step 2 again. 

Downloaded the archive:
https://github.com/zoffline/zwift-offline/releases/tag/zoffline_helper

and put the files from the repository in the path:
C:\11111\zwift-offline\ssl

do in CMD Administrator
C:\11111\zwift-offline\ssl>certutil.exe -importpfx cert-zwift-com.p12
Enter
The certificate "* .zwift.com" is already in the store.
CertUtil: -importPFX - command completed successfully.

and do
C:\11111\zwift-offline\ssl>type cert-zwift-com.pem >> "C:\Program Files (x86)\Zwift\data\cacert.pem"

then edit the file "hosts"

C:\11111\zwift-offline>C:\Python27\python.exe standalone.py

![image](https://user-images.githubusercontent.com/39903986/90712497-59bdb780-e2cd-11ea-80a0-bf8f29f9fffd.png)

failed to login check internet connection

![image](https://user-images.githubusercontent.com/39903986/90712620-a86b5180-e2cd-11ea-8857-4b7eab7803df.png)

the profile has also been loaded as described in step 3

--------

 :( Please help me.

**Comment by oldnapalm** [comment]
Did you edit cacert.pem with a text editor before running the command type? If you did, you have to remove the content added with text editor, that's what causes the issue (#62).

Try to delete all added content (it's easy to identify by the text width), then run the command `type cert-zwift-com.pem >> "C:\Program Files (x86)\Zwift\data\cacert.pem"` again.

![Capturar](https://user-images.githubusercontent.com/38410858/90764373-9df58b80-e2be-11ea-9e54-bdfddb756f21.PNG)

Also notice the difference in the command certutil.exe arguments for Windows 7 and 10. Which version are you using?
