### ISSUE TITLE
Doesn't upload training to Strava

### ISSUE THREAD

**Issue by resolverit** [zoffline/zwift-offline#77]
Hello! 
Did everything as indicated in [step 4](https://github.com/zoffline/zwift-offline#step-4-optional-obtain-strava-api-token) for windows. But the workout could not be unloaded.
![image](https://user-images.githubusercontent.com/39903986/91136497-88c29780-e6d8-11ea-91ec-e343f44251ce.png)
Configured api in Strava, but data still doesn't reach
![image](https://user-images.githubusercontent.com/39903986/91139850-a93f2180-e6d9-11ea-9507-fbc8faee79a8.png)

**Comment by resolverit** [comment]
Launched the same strava_auth.exe
![image](https://user-images.githubusercontent.com/39903986/91155248-c8937a00-e6ec-11ea-826a-a89b1b7c563d.png)
I did not close it, I drove 5 km and tried to send the results to the strava. All to no avail ...
Please help me)

**Comment by oldnapalm** [comment]
When you authorize in the browser, the file `strava_token.txt` is automatically created in the script folder, just move that file to `storage/<player_id>`, do not copy/paste from browser to the txt file.

**Comment by resolverit** [comment]
Thank! It works!

**Comment by oldnapalm** [comment]
Great!

You can close the issue when it's solved.

Strava photo upload is not implemented (#28).
