### ISSUE TITLE
zoffline_1.0.55226.exe  detected as a trojan

### ISSUE THREAD

**Issue by m013** [zoffline/zwift-offline#81]
![image](https://user-images.githubusercontent.com/37451707/92772939-d6135a00-f3a4-11ea-9a61-b06877d057cc.png)

zoffline_1.0.55226.exe immediately gets detected as a virus

**Comment by oldnapalm** [comment]
It's a known pyinstaller issue https://github.com/pyinstaller/pyinstaller/issues?utf8=%E2%9C%93&q=is%3Aissue+virus

It's easy to run zoffline from source, just install latest Python 3 from https://www.python.org/downloads/, check "add to PATH" and "launcher" options in the installation, run `pip install flask protobuf protobuf3_to_dict stravalib` in Command Prompt to install the dependencies, then you can just double click `standalone.py`.

**Comment by m013** [comment]
oh

**Comment by oldnapalm** [comment]
For `zoffline_1.0.56270.exe` I built the pyinstaller bootloader (https://pyinstaller.readthedocs.io/en/stable/bootloader-building.html) so it should not be detected as a virus.

**Comment by oldnapalm** [comment]
![Capturar](https://user-images.githubusercontent.com/38410858/94862357-3bd88c00-040f-11eb-9d35-ab718964ea40.PNG)
