### ISSUE TITLE
Apple Watch Heart Rate

### ISSUE THREAD

**Issue by AlePeace** [zoffline/zwift-offline#85]
Hello, thanks for the offline mode for Zwift is awesome, but I want to know one thing, if it's possible to connect the Apple Watch like heart rate??

**Comment by oldnapalm** [comment]
I have no experience with Apple Watch, but looking at Zwift instructions I understood it requires the companion app, so I would say it's not going to work with zoffline.

https://support.zwift.com/en_us/heart-rate-monitors-Hk0MimWlS

Maybe using a 3rd party app like this

https://apps.apple.com/us/app/blueheart-bluetooth-heart-rate/id1485503543

**Comment by AlePeace** [comment]
Yeah, Zwift need a companion app to connect Apple Watch. By the way, thanks for advice with 3rd party app, I didn't think about it. Now I try thanks a lot. Cheers

**Comment by oldnapalm** [comment]
Nice, glad it worked!

Closing the issue, please reopen if you need.
