### ISSUE TITLE
zoffline.exe detected as trojan

### ISSUE THREAD

**Issue by oldnapalm** [zoffline/zwift-offline#87]
I was having problem of zoffline.exe (built with pyinstaller 4.0 and Python 3.8.5) being detected as trojan by Windows Defender ([Trojan:Win32/Fuery.C!cl](https://go.microsoft.com/fwlink/?linkid=142185&name=Trojan:Win32/Fuery.C!cl&threatid=2147718736) or [Trojan:Win32/Wacatac.DC!ml](https://go.microsoft.com/fwlink/?linkid=142185&name=Trojan:Win32/Wacatac.DC!ml&threatid=2147757791)). See #81 

According to https://github.com/pyinstaller/pyinstaller/issues/4852#issuecomment-623031031 the reason is that the bootloaders were cross-compiled for Windows, from Linux. So, as suggested, I compiled the bootloaders following instructions from https://pyinstaller.readthedocs.io/en/stable/bootloader-building.html and it's no longer being detected as trojan.

Can someone please confirm if the latest release is not detected as trojan by other anti-virus?
https://github.com/zoffline/zwift-offline/releases/tag/zoffline_1.0.56270

Thanks.

**Comment by zoffline** [comment]
Still appears to have some false positives, but overall it seems substantially better.

19/71 false positives with 1.0.56270 (https://www.virustotal.com/gui/file/3aabe0f2f8ec957b585988be995a20f437d684cc33d7baf3d480591f2713ec6c/detection)

35/71 false positives with 1.0.55600
(https://www.virustotal.com/gui/file/b080651879f2169989331b505c1e9d5ac8340dffa4e3da53deb2b094a79effa9/detection)

Also, when I downloaded them the previous release was flagged as a virus and this one wasn't.

**Comment by oldnapalm** [comment]
I found this suggestion in https://stackoverflow.com/questions/43777106/program-made-with-pyinstaller-now-seen-as-a-trojan-horse-by-avg

> Make sure everything is consistent on your machine. For Windows 64bit, install Python 64bit. Download PyInstaller 64bit for Windows. Make sure Visual Studio (VS) corresponding to your Python is installed

Since I don't have 32 bit Windows I tried using 64 bit Python and the resulting file has only one false positive

https://www.virustotal.com/gui/file/ac8618d525b6d6ece048daaba2571c280222c3d215085c8e831917eb24d84aa8/detection

Do you prefer keeping the 32 bit exe for compatibility or should I upload the 64 bit one?

**Comment by zoffline** [comment]
Nice! The 64 bit should be fine. I can't imagine many people run 32 bit Windows anymore and if they do they can always run from source. If Steam's hardware survey is at all representative, 32 bit is <.5% of installs, though I imagine that's skewed lower than the general population.

**Comment by oldnapalm** [comment]
Ok, updated the release and the scripts binaries.

**Comment by oldnapalm** [comment]
I noticed that if the file is signed (even if the certificate is self signed) it has no false positives on VirusTotal.

https://www.virustotal.com/gui/file/f63e83e13d7cb0b6814a0c7742f180a2098c4f112f592bc4d9e21afdfd276aef/detection
