### ISSUE TITLE
Update 1.0.30361

### ISSUE THREAD

**Issue by oldnapalm** [zoffline/zwift-offline#9]
Not an issue, just to let you know update 1.0.30361 is out and working fine with zoffline in my tests.

LauncherMac_ver_cur.xml
```
<Launcher version="1.0.7"
URL="http://cdn.zwift.com/app/MacUpdate/"/>
```

ZwiftMac_ver_cur.xml
```
<Zwift version="1.0.30361"
GAME_URL="https://us-or-rly101.zwift.com"
manifest="ZwiftMac_1.0.30361_manifest.xml"
manifest_checksum="-1147574144"
mandatory_version="0.0.0"
ver_cur_checksum="235030438"/>
```

**Comment by zoffline** [comment]
Thanks for the heads up and early testing. I've updated to 1.0.30362. zoffline likely doesn't support some of the running features or cloud workout sync, but I don't care about either so unless someone requests it I won't look into it.

**Comment by oldnapalm** [comment]
I don't care about those too. Any plans on looking into issue #1 ? Not a big deal, but it would be nice to see when a PR was set. I really have no clue on how to to that but I could help with testing if you want.

**Comment by zoffline** [comment]
Didn't see this till now. Unfortunately I've not been riding much lately and am fairly slammed schedule-wise so I'm not sure when I'll get a chance to investigate it. Optimistically, around Christmas. It's an annoying bug; when Zwift asks for segment results the date they were set is included so not sure why Zwift doesn't just look at that.
