### ISSUE TITLE
Updating Error

### ISSUE THREAD

**Issue by scouseman** [zoffline/zwift-offline#92]
I have zwift v 1.057840 installed on my pc.
When i don't have the IP address blocked in the host file, I can take the game through to riding.
If I block the ip address in the host file and run ZO then zwift but it keeps trying to update zwift even though it is up to date.
I tried the "auto_launch.txt" but that doesn't help.
Thanks

**Comment by oldnapalm** [comment]
When this happens you have to update zoffline (usually just copy ``C:\Program Files (x86)\Zwift\Zwift_ver_cur.xml`` to zoffline's ``cdn/gameassets/Zwift_Updates_Root/`` overwriting the existing file). If you are using the Windows exe you need to wait for zoffline to be updated (I just did it).

**Comment by scouseman** [comment]
ah sorry never realised that
Thanks again for your efforts
Cheers
