### ISSUE TITLE
Zwift API documentation

### ISSUE THREAD

**Issue by alokhan** [zoffline/zwift-offline#94]
Hi,

thanks you for this wonderful project, I am wondering would it be possible to document the Zwift API ? In order to implement a server in a different language for example.

Regards,

Alokhan

**Comment by zoffline** [comment]
Unfortunately, I doubt I will ever get around to this, sorry. However, the Zwift API implemented is fairly straightforward if you examine a network trace between Zwift and a zoffline server and look at the implemented routes.
