### ISSUE TITLE
Bundle the scripts into an android APK

### ISSUE THREAD

**Issue by igolaizola** [zoffline/zwift-offline#96]
It could be great to be able to run the python scripts from an android device. This way we could run the server and client from a single mobile device.

There are some projects that could be used for this:
 - https://kivy.org
 - https://python-for-android.readthedocs.io

This is an awesome project! Thanks for all the job you have done 👏

**Comment by oldnapalm** [comment]
Hi @igolaizola

I don't have experience on Android development to opine on this, but I would like to give you a suggestion if you don't want to run your own server. Join https://discord.com/invite/GMdn8F8 and connect your Android device to this test online server, so you can also help to check if it's working for Android (it's working for Windows and macOS). You may need to have Zwift client on Windows or Mac to create your account and upload your profile.

**Comment by igolaizola** [comment]
I have never used the projects I mentioned before, just throwing some ideas.
If I get some free time I will try to test them by myself.

**Comment by zoffline** [comment]
This may be possible, but it would seemingly required a rooted device in order to bind to ports 80 and 443 (and possibly for other reasons).
