### ISSUE TITLE
Add support for Zwift Companion App

### ISSUE THREAD

**Issue by ErnestFlaming** [zoffline/zwift-offline#99]
Pls, coud you make a compatible companion app to zoffline?
It would be great!

**Comment by rdvAndroid** [comment]
I'd also like that feature. I've tried adding an entry for a Zoffline server running on my local network in the hosts file of a rooted Android device but that didn't work.
For an extra immersive feel I run Zwift with the OSD turned off so the data that the companion app provides becomes important. Ghost rider racing moves to a whole new level when the display is not cluttered by the usual OSD.

**Comment by oldnapalm** [comment]
@ursoft is working on companion app support, please check https://github.com/ursoft/zwift-offline

**Comment by Matarile** [comment]
@oldnapalm  Do you know if the Companion App option is available yet? If so, are there any instructions to enable it? Thanks

**Comment by oldnapalm** [comment]
> @oldnapalm Do you know if the Companion App option is available yet? If so, are there any instructions to enable it? Thanks

It was not merged into the main repo yet, it's available only in @ursoft fork. I don't know if it's already functional, have not tried yet, but I suppose you need a rooted Android device (or jailbroken iOS) to be able to import the CA certificate.

**Comment by ursoft** [comment]
> It was not merged into the main repo yet, it's available only in @ursoft fork. I don't know if it's already functional, have not tried yet, but I suppose you need a rooted Android device (or jailbroken iOS) to be able to import the CA certificate.
Not 100% functional, but most of functions (GAME activity, profile editor, messaging, password change etc) are working (TODO list: Events, Activities, Goals, Followings, external connections). Instead of Android rooting I just used https://github.com/shroudedcode/apk-mitm on version v3.29.0 (hope newest version are compatible with this crack) + Hosts GO (VPN application to substitute servers)

**Comment by oldnapalm** [comment]
> Instead of Android rooting I just used https://github.com/shroudedcode/apk-mitm on version v3.29.0 (hope newest versions are compatible with this crack) + Hosts GO (VPN application to substitute servers)

Thanks! Version 3.32.0 works with apk-mitm.

I'm not the repo owner (I have write permission but @zoffline asked not to make big changes without his review, and your changes are quite big). Please open a pull request if your changes are ready to merge.

If you prefer I can open the PR from https://github.com/zoffline/zwift-offline/tree/zca

I reverted the SSL certificate, removed some unnecessary files and moved the scripts from storage to scripts folder. Not sure what to do about game_info.txt, if include it in storage, in other place, or let the user download it.

I did a quick test and it seems to work very well, awesome work!

**Comment by ursoft** [comment]
> If you prefer I can open the PR from https://github.com/zoffline/zwift-offline/tree/zca
> 
> I reverted the SSL certificate, removed some unnecessary files and moved the scripts from storage to scripts folder. Not sure what to do about game_info.txt, if include it in storage, in other place, or let the user download it.
> 
> I did a quick test and it seems to work very well, awesome work!
Thanks. My fork is too dirty to make PR from it, zwift-offline/tree/zca looks better - please open PR if you are checked changes and approved them.

**Comment by Matarile** [comment]
@ursoft  and  @oldnapalm Thank you guys!  Keep up the good work 😁

**Comment by Matarile** [comment]
I am very excited and looking forward to try this new feature 👍

**Comment by oldnapalm** [comment]
> I am very excited and looking forward to try this new feature 👍

Uploaded an exe release and the patched apk here
https://drive.google.com/drive/folders/1EnfzATowor2HYhteXx2-XW_NDm5YbICr?usp=sharing

To modify hosts you can follow instructions from "Android (non-rooted device)"
https://github.com/zoffline/zwift-offline#step-2-configure-zwift-client-to-use-zoffline

**Comment by stapa** [comment]
What version of Android is required? I tried to install it on my old 4.4.4. and got "Parse error: There was a problem parsing the package".

**Comment by oldnapalm** [comment]
> What version of Android is required? I tried to install it on my old 4.4.4. and got "Parse error: There was a problem parsing the package".

Version 5.0 or higher according to https://play.google.com/store/apps/details?id=com.zwift.android.prod

**Comment by gnostisus** [comment]
Hello

Thanks for working on this. I was hoping someone could help me get Companion working.

I was running zoffline from a directory named zoffine I followed directions for multiplayer and created an account and everything was working, I wanted to try to get Companion working so I downloaded the exe release and the patched apk from link above. renamed the old zoffline_1.0.100353.exe and put the downloaded zoffline_1.0.100353.exe in it's place launched zoffline, I followed the directions Android (non-rooted device) I installed zca-patched.apk ran Host Changer launched companion entered the email and password I created for zoffline and it said invalid email or password and in the command prompt running zoffline was the following:

INFO:zoffline:Server is running.
Traceback (most recent call last):
  File "src\\gevent\\greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "gevent\baseserver.py", line 34, in _handle_and_close_when_done
  File "gevent\server.py", line 233, in wrap_socket_and_handle
  File "gevent\_ssl3.py", line 796, in wrap_socket
  File "gevent\_ssl3.py", line 312, in __init__
  File "gevent\_ssl3.py", line 308, in __init__
  File "gevent\_ssl3.py", line 666, in do_handshake
ssl.SSLError: [SSL: SSLV3_ALERT_CERTIFICATE_UNKNOWN] sslv3 alert certificate unknown (_ssl.c:1131)
2022-02-11T23:45:55Z <Greenlet at 0x20f28a1ed00: _handle_and_close_when_done(<bound method StreamServer.wrap_socket_and_handle , <bound method StreamServer.do_close of <WSGIServer, (<gevent._socket3.socket [closed] at 0x20f29c7bc40)> failed with SSLError

Any suggestions or instructions I might of missed? I am not a programmer but I follow directions with no problem, I am running zoffline on an old first gen i7 dell that I did a fresh install of win 10 to run it on so I could reset win 10 and start from scratch if need be, I don't care about the account I just like to have sessions saved to strava for records. 

Thank You in advance

**Comment by oldnapalm** [comment]
Does the Windows client work with the new exe?

Is it possible that you already had the Companion app installed and the patched apk did not install? Try removing the app and install from the patched apk again.

**Comment by oldnapalm** [comment]
I just uploaded the latest version (3.32.2) of the patched apk. Also updated the zoffline exe, now there's an alternative to the "Host Changer" app, check updated instructions in https://github.com/zoffline/zwift-offline/tree/zca#step-7-optional-install-zwift-companion-app

https://drive.google.com/drive/folders/1EnfzATowor2HYhteXx2-XW_NDm5YbICr?usp=sharing

**Comment by gnostisus** [comment]
Thanks for the reply

sorry for the delay trying this I downloaded the new files and uninstalled companion before installing the latest apk, same results. I tried changing the dns on my phone and got the same thing. I alredady had opened ports in windows firewall that another post said to incoming/outgoing are there ports to open on  my phone?

I was thinking maybe I did something wrong with the files in the repo https://github.com/zoffline/zwift-offline/tree/zca can you walk me through where to put them and what to do with them, I installed Python 3 initially and double checked the installed dependencies at the bottom of the instructions. 

Thank You

**Comment by oldnapalm** [comment]
> I already had opened ports in windows firewall that another post said to incoming/outgoing are there ports to open on my phone?

No ports need to be open on phone. On Windows you may need to allow zoffline.exe in the Windows firewall.

> I was thinking maybe I did something wrong with the files in the repo https://github.com/zoffline/zwift-offline/tree/zca can you walk me through where to put them and what to do with them, I installed Python 3 initially and double checked the installed dependencies at the bottom of the instructions.

You don't need the files from the repo, just the exe from the gdrive link above should be enough. If you want to run from source, the steps are in https://github.com/zoffline/zwift-offline#step-1-install-zoffline (Linux, Windows, or Mac OS X (from source)).

**Comment by gnostisus** [comment]
I gave it a try running from source Windows client works and I got the same invalid email message but more in the cmd window (I replaced my username with <username>)

INFO:zoffline:Server is running.
Traceback (most recent call last):
  File "src\\gevent\\greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "C:\Users\<username>\AppData\Local\Programs\Python\Python310\lib\site-packages\gevent\baseserver.py", line 34, in _handle_and_close_when_done
    return handle(*args_tuple)
  File "C:\Users\<username>\AppData\Local\Programs\Python\Python310\lib\site-packages\gevent\server.py", line 233, in wrap_socket_and_handle
    with _closing_socket(self.wrap_socket(client_socket, **self.ssl_args)) as ssl_socket:
  File "C:\Users\<username>\AppData\Local\Programs\Python\Python310\lib\site-packages\gevent\_ssl3.py", line 796, in wrap_socket
    return SSLSocket(sock=sock, keyfile=keyfile, certfile=certfile,
  File "C:\Users\<username>\AppData\Local\Programs\Python\Python310\lib\site-packages\gevent\_ssl3.py", line 312, in __init__
    raise x
  File "C:\Users\<username>\AppData\Local\Programs\Python\Python310\lib\site-packages\gevent\_ssl3.py", line 308, in __init__
    self.do_handshake()
  File "C:\Users\<username>\AppData\Local\Programs\Python\Python310\lib\site-packages\gevent\_ssl3.py", line 666, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_CERTIFICATE_UNKNOWN] sslv3 alert certificate unknown (_ssl.c:997)
2022-02-12T22:11:22Z <Greenlet at 0x250f92ac4c0: _handle_and_close_when_done(<bound method StreamServer.wrap_socket_and_handle , <bound method StreamServer.do_close of <WSGIServer, (<gevent._socket3.socket [closed] at 0x250f921dea0)> failed with SSLError

Thanks once more

**Comment by oldnapalm** [comment]
Maybe it's something about the Android version, I tested with version 12.

Try importing https://raw.githubusercontent.com/zoffline/zwift-offline/master/ssl/cert-zwift-com.pem in the Android system. In version 12 it isn't possible but maybe in version 5 it is.

**Comment by gnostisus** [comment]
> Maybe it's something about the Android version

I was thinking that, I didn't realize it was such an early version.

where would I import it?

Continued Thanks

**Comment by oldnapalm** [comment]
You will have to try to figure it out, I have no idea.

Did you try changing the DNS in your new phone?

**Comment by gnostisus** [comment]
> Did you try changing the DNS in your new phone?

I did try that yesterday and wasn't getting a response in the cmd window, I had given up and was going to see if any friends had a newer old phone I could try, I took the lines I added to the android host file out to restore it, then was going to change the DNS back but launch companion just to and it worked.

Thanks for your patience and advice and all the work on the apps.

I'm going to do a ride in a little bit I'll let you know if all goes well.

Ride On!

**Comment by gnostisus** [comment]
I rode a session and the the map and dashboard worked and stayed connected, the action menu didn't load all the white icons, may just be my phone lineage 14.1 is based off Nougat so not very recent, they didn't seem to work with the heads up display on the windows app off I only used the u-turn and the exit, the icons to choose at turns didn't display on the map view. I was going to try the BLE pass through after riding, but forgot to. none of that really mattered later I'm going to mess around and see if the action menu buttons are working even though the icons aren't displayed by looking at the order they are in on the zwift support site.

Much Thanks

**Comment by oldnapalm** [comment]
The icons issue is because you have cdn.zwift.com in your Windows hosts file, so the fake DNS isn't able to resolve it. For the fake DNS to work better, zoffline needs to be in a different machine than the Windows client. As an alternative you can use the Host Changer app on Android (or edit /etc/hosts if the phone is rooted). Another option is using fake DNS and removing the cdn from Windows hosts (as a side effect you won't see the launcher background image and map override won't work).

**Comment by oldnapalm** [comment]
You can try this, run from source and replace fake_dns.py by this one, it will force the use of 8.8.8.8 nameserver, so the entries in Windows hosts will be ignored. Run `pip install dnspython` to install the required library.

[fake_dns.zip](https://github.com/zoffline/zwift-offline/files/8056768/fake_dns.zip)

**Comment by gnostisus** [comment]
I do have zoffline on a different machine, should the machine running zoffline have the windows host file on it need to include <zoffline ip> us-or-rly101.zwift.com secure.zwift.com cdn.zwift.com in the host file, It was modified when configure_client.bat was run, did the zwift desktop app need to be installed on the machine running zoffline if it's run from another machine? 

> You can try this, run from source and replace fake_dns.py by this one

I'll try that

If running from source and replacing fake_dns.py should DNS1 be returned to 8.8.8.8 on the phone?

thanks again

**Comment by oldnapalm** [comment]
> I do have zoffline on a different machine, should the machine running zoffline have the windows host file on it need to include us-or-rly101.zwift.com secure.zwift.com cdn.zwift.com in the host file, It was modified when configure_client.bat was run, did the zwift desktop app need to be installed on the machine running zoffline if it's run from another machine?

If zoffline is not in the same machine as the client, the machine running zoffline doesn't need the names in hosts file (and should not include cdn if you are using fake DNS). Only the machine running the client needs the hosts entries.

> If running from source and replacing fake_dns.py should DNS1 be returned to 8.8.8.8 on the phone?

No, phone DNS 1 should be the IP of the machine running zoffline. But this modified fake_dns.py is only needed if zoffline is in the same machine as the client.

**Comment by gnostisus** [comment]
I took the cdn part out of the host file on the client machine and the button icon appeared and are working, I didn't ride so not sure if the left right will show up I'll see tomorrow, as it is it was fine I keep a mini keyboard on the dresser next to the trainer where I can easily access it to change camera view, u-turn, hide heads up and turn, it's just nice to have the map and metrics on the phone and keep the display clean. 

>  (as a side effect you won't see the launcher background image and map override won't work).

when you say map override won't work that means the drop down on the launcher right, that's no big deal I ride watopia mostly, but if I did want to change is there another way to choose the map, I thought I read something about how the drop down made it easier than an older way.

Thanks for your time

**Comment by oldnapalm** [comment]
I just pushed the change to the zca branch and updated the exe in gdrive, now it should work regardless of zoffline being run on the same machine as the client and having cdn on hosts.

**Comment by gnostisus** [comment]
OK, I'll give in a try later.

Thanks

**Comment by gnostisus** [comment]
OK, gave it a try sooner,

everything seems to be working, the heads up toggle action button didn't show up last time when can wasn't in the host file, it's there now and working, I picked makuri island from dropdown and it work, even tried the BT pass through and it worked.

whatever you did great job

Ride On!

**Comment by oldnapalm** [comment]
The exe for the latest version with ZCA support can be found at https://github.com/zoffline/zwift-offline/releases/tag/zoffline_1.0.100456

Latest ZCA apk https://drive.google.com/drive/folders/1EnfzATowor2HYhteXx2-XW_NDm5YbICr?usp=sharing
